import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../../comman/Colors';
import FontsSize from '../../../comman/FontsSize';
import MarginHW from '../../../comman/MarginHW';
import fonts from '../../../comman/fonts';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  topSectionWrapper: {
    paddingBottom: MarginHW.PaddingH20,
    backgroundColor: Colors.bannerBgGreen,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW16,
    paddingTop: MarginHW.PaddingH35,
    paddingBottom: MarginHW.PaddingH8,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  backIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.textDarkGray,
  },
  logo: {
    position: 'absolute',
    left: "50%",
    top: 50,
    width: 120,
    height: 120,
    transform: [
      { translateX: -60 },
      { translateY: -60 },
    ],
  },
  securePaymentBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    top: -15,
    right: -10,
    backgroundColor: Colors.badgeGreenBg,
    paddingHorizontal: MarginHW.PaddingW10,
    // paddingVertical: MarginHW.PaddingH6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
  },
  securePaymentIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.shieldIconColor,
    marginRight: MarginHW.MarginW4,
  },
  securePaymentText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size11,
    color: Colors.shieldIconColor,
  },
  heroSection: {
    paddingHorizontal: MarginHW.PaddingW16,
    width: '70%',
  },
  heroTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size22,
    color: Colors.textDarkGreen,
    lineHeight: 28,
  },
  heroTitleGreen: {
    color: Colors.secondary_button,
  },
  heroDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textMuted,
    marginTop: MarginHW.MarginH6,
    lineHeight: 18,
  },
  trustRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: MarginHW.MarginH8,
    marginBottom: MarginHW.MarginH8,
  },
  trustItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
    borderRadius: 8,
    paddingVertical: MarginHW.PaddingH6,
    paddingHorizontal: MarginHW.PaddingW6,
    marginRight: MarginHW.MarginW6,
  },
  trustItemLast: {
    marginRight: 0,
  },
  trustIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.stateIconBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW4,
  },
  trustIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.tint,
  },
  trustTextContainer: {
    flex: 1,
  },
  trustLabel: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10,
    color: Colors.textDarkGreen,
    lineHeight: 10,
    marginBottom: MarginHW.MarginH2,
  },
  trustSublabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size9,
    color: Colors.stateLabelText,
    lineHeight: 9,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    paddingHorizontal: MarginHW.PaddingH12,
    paddingTop: MarginHW.PaddingH12,
    paddingBottom: MarginHW.PaddingH5,
    marginHorizontal: MarginHW.MarginW10,
    marginBottom: MarginHW.MarginH10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  cardTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH8,
  },
  planHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.containerBg,
    borderRadius: 12,
    padding: MarginHW.PaddingH8,
    borderWidth: 1,
    borderColor: Colors.bannerBorderGreen,
    marginBottom: MarginHW.MarginH8,
  },
  planIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    marginRight: MarginHW.MarginW12,
  },
  planTexts: {
    flex: 1,
  },
  planTitle: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.stateLabelText,
  },
  planOffset: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.tint,
    marginTop: MarginHW.MarginH1,
  },
  planSubtext: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.textMuted,
    marginTop: MarginHW.MarginH2,
  },
  detailList: {
    marginBottom: MarginHW.MarginH6,
  },
  detailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: MarginHW.PaddingH5,
    borderBottomWidth: 1,
    borderBottomColor: Colors.bannerBgGreen,
  },
  detailLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailIcon: {
    width: 12,
    height: 12,
    tintColor: Colors.tint,
    marginRight: MarginHW.MarginW6,
  },
  detailLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: Colors.textMuted,
  },
  detailVal: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size11,
    color: Colors.textDarkGreen,
  },
  alertBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.bgGreenLight,
    borderRadius: 10,
    padding: MarginHW.PaddingH8,
    marginTop: MarginHW.MarginH4,
    // marginBottom: MarginHW.MarginH8,
  },
  alertIcon: {
    width: 12,
    height: 12,
    tintColor: Colors.shieldIconColor,
    marginRight: MarginHW.MarginW6,
  },
  alertText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size10,
    color: Colors.shieldIconColor,
    flex: 1,
    lineHeight: 12,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: MarginHW.PaddingH3,
  },
  priceLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textMuted,
  },
  priceVal: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size12,
    color: Colors.textDarkGreen,
  },
  grandTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: MarginHW.PaddingH6,
    borderTopWidth: 1,
    borderTopColor: Colors.dividerGreen,
    marginTop: MarginHW.MarginH4,
  },
  grandTotalLabel: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.textDarkGreen,
  },
  grandTotalVal: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size15,
    color: Colors.tint,
  },
  paymentMethodRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: MarginHW.PaddingH12,
    borderWidth: 1,
    borderRadius: 12,
    marginVertical: MarginHW.MarginH5,
  },
  paymentMethodUnselected: {
    borderColor: Colors.borderGreenLight,
    backgroundColor: Colors.white,
  },
  paymentMethodSelected: {
    borderColor: Colors.tint,
    backgroundColor: Colors.bgGreenLight,
  },
  paymentMethodLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  paymentMethodIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: Colors.iconBgLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW12,
  },
  paymentMethodIcon: {
    width: 18,
    height: 18,
    tintColor: Colors.tint,
  },
  paymentMethodTexts: {
    flex: 1,
  },
  paymentMethodName: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.textDarkGreen,
  },
  paymentMethodSubtext: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: Colors.stateLabelText,
    marginTop: MarginHW.MarginH1,
  },
  paymentMethodRadio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: Colors.switchInactiveBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentMethodRadioSelected: {
    borderColor: Colors.tint,
  },
  paymentMethodRadioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.tint,
  },
  cardFormContainer: {
    marginTop: MarginHW.MarginH6,
    borderTopWidth: 1,
    borderTopColor: Colors.borderGreenLight,
    paddingTop: MarginHW.PaddingH12,
    paddingHorizontal: MarginHW.PaddingW4,
  },
  cardLogosRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: MarginHW.MarginH8,
  },
  cardLogo: {
    width: 24,
    height: 14,
    marginLeft: MarginHW.MarginW6,
  },
  inputLabel: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size11,
    color: Colors.textMuted,
    marginBottom: MarginHW.MarginH4,
  },
  inputField: {
    height: 40,
    borderWidth: 1,
    borderColor: Colors.switchInactiveBg,
    borderRadius: 6,
    paddingHorizontal: MarginHW.PaddingW12,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size13,
    color: Colors.textDarkGreen,
    backgroundColor: Colors.containerBg,
    marginBottom: MarginHW.MarginH10,
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardCol: {
    flex: 1,
    marginRight: MarginHW.MarginW8,
  },
  cardColLast: {
    flex: 1,
    marginRight: 0,
  },
  // UPI App Selection Styles
  upiAppsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: MarginHW.MarginH12,
    marginHorizontal: -MarginHW.MarginW4,
  },
  upiAppButton: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: 8,
    paddingVertical: MarginHW.PaddingH8,
    marginHorizontal: MarginHW.MarginW4,
    backgroundColor: Colors.white,
    elevation: 1,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
  },
  upiAppButtonSelected: {
    borderColor: Colors.tint,
    backgroundColor: Colors.bgGreenLight,
  },
  upiAppLogo: {
    width: 24,
    height: 24,
    marginBottom: MarginHW.MarginH4,
  },
  upiAppText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size10,
    color: Colors.textDarkGreen,
  },
  // Net Banking Bank Grid Styles
  banksGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: MarginHW.MarginH6,
  },
  bankButton: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: 8,
    padding: MarginHW.PaddingH8,
    marginBottom: MarginHW.MarginH8,
    backgroundColor: Colors.white,
    elevation: 1,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
  },
  bankButtonSelected: {
    borderColor: Colors.tint,
    backgroundColor: Colors.bgGreenLight,
  },
  bankLogoBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.iconBgLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
  },
  bankLogoBadgeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size9,
    color: Colors.tint,
  },
  bankText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size11,
    color: Colors.textDarkGreen,
    flex: 1,
  },
  walletLogo: {
    width: 20,
    height: 20,
    marginRight: MarginHW.MarginW8,
  },
  impactCard: {
    backgroundColor: Colors.pointsIconBgLight,
    borderRadius: 14,
    paddingVertical: MarginHW.PaddingH14,
    paddingHorizontal: MarginHW.PaddingH5,
    marginHorizontal: MarginHW.MarginW10,
    marginBottom: MarginHW.MarginH4,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
  },
  impactTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  impactLeftHand: {
    width: 44,
    height: 44,
    marginRight: MarginHW.MarginW12,
  },
  impactTexts: {
    flex: 1,
  },
  impactTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.textGreenDark,
  },
  impactDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: Colors.stateLabelText,
    marginTop: MarginHW.MarginH2,
    lineHeight: 14,
  },
  impactMiniRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: Colors.borderGrey,
    marginTop: MarginHW.MarginH10,
    paddingTop: MarginHW.PaddingH10,
  },
  impactMiniBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  impactMiniIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.textLabelGrey,
    marginRight: MarginHW.MarginW4,
  },
  impactMiniText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size12,
    color: Colors.textLabelGrey,
  },
  trustedSection: {
    marginHorizontal: MarginHW.MarginW10,
    marginBottom: MarginHW.MarginH8,
  },
  trustedRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.containerBg,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
    borderRadius: 12,
    padding: MarginHW.PaddingH12,
  },
  trustedLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  trustedShieldIcon: {
    width: 24,
    height: 24,
    tintColor: Colors.shieldIconColor,
    marginRight: MarginHW.MarginW8,
  },
  trustedTexts: {
    flex: 1,
  },
  trustedTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.textDarkGreen,
  },
  trustedDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: Colors.stateLabelText,
    lineHeight: 12,
    marginTop: MarginHW.MarginH1,
  },

  stickyFooter: {
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.borderGrey,
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: MarginHW.PaddingH12,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 10,
  },
  footerMain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerLeft: {
    justifyContent: 'center',
  },
  footerLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: Colors.stateLabelText,
  },
  footerVal: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size18,
    color: Colors.textDarkGreen,
  },
  footerDetailsLink: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH1,
  },
  footerDetailsText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size11,
    color: Colors.tint,
    marginRight: MarginHW.MarginW2,
  },
  footerDetailsArrow: {
    width: 8,
    height: 8,
    tintColor: Colors.tint,
  },
  payButton: {
    flex: 1,
    height: 44,
    backgroundColor: Colors.TextColorLightGreen,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: MarginHW.MarginW16,
  },
  payButtonIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW6,
  },
  payButtonText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.white,
    marginRight: MarginHW.MarginW4,
  },
  payButtonArrow: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size15,
    color: Colors.white,
  },
  termsText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.stateLabelText,
    textAlign: 'center',
    marginTop: MarginHW.MarginH8,
  },
  termsLink: {
    color: Colors.tint,
    fontFamily: fonts.OpenSans_SemiBold,
  },
});
