import { StyleSheet, Dimensions } from 'react-native';
import fonts from '../../../../comman/fonts';
import FontsSize from '../../../../comman/FontsSize';
import { Colors } from '../../../../comman/Colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F7FAF8',
    },
    scrollContent: {
        paddingBottom: 10,
    },
    // Hero Banner Style
    heroImageBg: {
        width: '100%',
        minHeight: 240,
    },
    heroOverlay: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        paddingBottom: 20,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: "center",
        paddingHorizontal: 16,
        marginVertical: 12,
        backgroundColor: 'transparent',
    },
    backButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#ECEFEF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    backIcon: {
        width: 16,
        height: 16,
        tintColor: '#000000',
    },
    // Progress Stepper Styles
    stepperContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 20,
        marginLeft: 16,
    },
    stepOuter: {
        alignItems: 'center',
    },
    stepCircleCompleted: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: Colors.legacyGreen,
        backgroundColor: '#0A5F35',
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepTextCompleted: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
    },
    stepCircleActive: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#0A5F35',
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepTextActive: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
    },
    stepCircleUpcoming: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: '#D1D5DB',
        backgroundColor: 'grey',
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepTextUpcoming: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#D1D5DB',
    },
    stepConnectorCompleted: {
        flex: 1,
        height: 1.5,
        backgroundColor: '#0A5F35',
        marginHorizontal: 4,
        marginTop: -16,
    },
    stepConnectorActive: {
        flex: 1,
        height: 1.5,
        backgroundColor: '#0A5F35',
        marginHorizontal: 4,
        marginTop: -16,
    },
    stepConnectorUpcoming: {
        flex: 1,
        height: 1.5,
        backgroundColor: '#D1D5DB',
        marginHorizontal: 4,
        marginTop: -16,
    },
    stepLabel: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_Regular,
        color: '#000',
        marginTop: 4,
    },
    stepLabelActive: {
        color: '#000',
        fontFamily: fonts.OpenSans_Bold,
    },
    // Banner Text
    heroTextContainer: {
        paddingHorizontal: 16,
        marginTop: 10,
    },
    heroTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    heroTitle: {
        fontSize: 20,
        fontFamily: fonts.OpenSans_Bold,
        color: Colors.legacyGreen,
    },
    heroSubtitle: {
        fontSize: 20,
        fontFamily: fonts.OpenSans_Bold,
        color: '#000',
        marginTop: -2,
    },
    heroDesc: {
        fontSize: 11.5,
        fontFamily: fonts.OpenSans_Regular,
        color: '#000',
        marginTop: 6,
        lineHeight: 16,
    },
    heroRightSpacer: {
        flex: 0.9,
    },
    // Main Container
    formContainer: {
        paddingHorizontal: 16,
        marginTop: -15, // overlapping effect
    },
    // Question Card layout
    questionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E6F0E9',
        padding: 12,
        marginBottom: 12,
        shadowColor: '#0A5F35',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 6,
        elevation: 2,
    },
    questionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    qustionView: {
        width: 40,
        height: 40,
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: '#EBF4EF',
        marginRight: 12,
    },
    questionHeaderIcon: {
        width: 25,
        height: 25,

    },
    questionHeaderTextCol: {
        flex: 1,
    },
    questionTitle: {
        fontSize: 13,
        fontFamily: fonts.OpenSans_Bold,
        color: '#1F2937',
    },
    questionSubtitle: {
        fontSize: 10.5,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7280',
        marginTop: 2,
    },
    infoButton: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 1.2,
        borderColor: '#0A5F35',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'flex-start',
    },
    infoButtonText: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    // Q1: Bill Input Slider
    billInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sliderContainer: {
        flex: 1,
        paddingLeft: 4,
        justifyContent: 'center',
    },
    sliderTrack: {
        height: 6,
        borderRadius: 3,
        backgroundColor: '#E2E8F0',
    },
    sliderSelectedTrack: {
        backgroundColor: '#0A5F35',
    },
    sliderThumb: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: '#FFFFFF',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    sliderScale: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 4,
        width: width - 190,
        paddingHorizontal: 2,
    },
    sliderScaleText: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_Regular,
        color: '#9CA3AF',
    },
    billDisplayBox: {
        paddingHorizontal: 15,
        paddingVertical: 5,
        backgroundColor: '#F3F8F5',
        borderWidth: 1.5,
        borderColor: '#E6EAE7',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    billDisplayValue: {
        fontSize: FontsSize.size14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    billDisplayLabel: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#1E293B',
        marginTop: 2,
    },
    // Q2: Source Grid Options
    sourceGridRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 4,
    },
    sourceCard: {
        width: '32%',
        backgroundColor: '#FFFFFF',
        borderWidth: 1.2,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 8,
        alignItems: 'center',
    },
    sourceCardSelected: {
        borderColor: '#0A5F35',
        backgroundColor: '#EBF4EF',
    },
    sourceCardIcon: {
        width: 20,
        height: 20,
    },
    sourceCardTextContainer: {
        flex: 1,
        marginLeft: 6,
    },
    sourceCardTitle: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#1F2937',
        textAlign: 'left',
    },
    sourceCardTitleSelected: {
        color: '#0A5F35',
    },
    sourceCardDesc: {
        fontSize: 7.5,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7280',
        textAlign: 'left',
        marginTop: 2,
        lineHeight: 10,
    },
    // Q3: Home Type Options
    homeTypeRow: {
        flexDirection: 'row',
        paddingVertical: 4,
    },
    homeTypeCard: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderWidth: 1.2,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
        alignItems: 'center',
        marginRight: 12,
    },
    homeTypeCardSelected: {
        borderColor: '#0A5F35',
        backgroundColor: '#F0FDF4',
    },
    homeTypeIcon: {
        width: 22,
        height: 22,
        marginRight: 8,
    },
    homeTypeTitle: {
        fontSize: 11.5,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#1F2937',
    },
    homeTypeTitleSelected: {
        color: '#0A5F35',
    },
    // Q4: Residents Segment
    residentsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    residentSegment: {
        width: '18%',
        height: 38,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    residentSegmentSelected: {
        borderColor: '#0A5F35',
        backgroundColor: '#F0FDF4',
    },
    residentSegmentText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#4B5563',
    },
    residentSegmentTextSelected: {
        color: '#0A5F35',
    },
    // Q5: Appliances Grid
    applianceGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    applianceCheckboxCard: {
        width: '48.5%',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        padding: 10,
        marginBottom: 10,
    },
    applianceCheckboxCardSelected: {
        borderColor: '#0A5F35',
        backgroundColor: '#F0FDF4',
    },
    checkboxContainer: {
        width: 14,
        height: 14,
        borderRadius: 7,
        borderWidth: 1,
        borderColor: '#D1D5DB',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
        backgroundColor: '#FFFFFF',
    },
    checkboxContainerChecked: {
        borderColor: '#0A5F35',
        backgroundColor: '#0A5F35',
    },
    checkIcon: {
        width: 8,
        height: 8,
        tintColor: '#FFFFFF',
    },
    applianceIconCircle: {
        width: 32,
        height: 32,
        borderRadius: 12,
        backgroundColor: '#EAF6EC',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    applianceIcon: {
        width: 18,
        height: 18,
        tintColor: '#0A5F35',
    },
    applianceLabel: {
        flex: 1,
        fontSize: 10,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#374151',
    },
    // Stats Summary Card
    statsOverviewCard: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: '#ecf3e0',

        borderRadius: 12,
        marginVertical: 5,
        paddingVertical: 10,
    },
    statItem: {
        width: '50%',
        paddingHorizontal: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    statItem1: {
        width: '50%',
        paddingHorizontal: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    statIconCircle: {
        width: 40,
        height: 40,
        borderRadius: 40 / 2,
        backgroundColor: '#EAF6EC',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    statIcon: {
        width: 20,
        height: 20,
    },
    statTextCol: {
        flex: 1,
    },
    statLabel: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
    },
    infoTextButton: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        width: 14,
        height: 14,
        borderRadius: 7,
        borderWidth: 1.2,
        borderColor: '#0A5F35',
        textAlign: 'center',
        lineHeight: 12,
    },
    statValue: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#0A5F35',
        marginTop: 2,
    },
    statUnit: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#0A5F35',
    },
    statDesc: {
        fontSize: 8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        marginTop: 2,
    },
    statsCardDivider: {
        width: 1,
        height: '80%',
        backgroundColor: '#D1E3D6',
        marginHorizontal: 5,
    },
    // Did You Know Card
    didYouKnowCard: {

        flexDirection: 'row',
        backgroundColor: '#ecf3e0',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 5,
        alignItems: 'center',
        marginVertical: 16,
    },
    didYouKnowIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#EAF6EC',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    didYouKnowIcon: {
        width: 20,
        height: 20,
        tintColor: '#0A5F35',
    },
    didYouKnowTextContainer: {
        flex: 1,
        marginRight: 10,
    },
    didYouKnowTitle: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    didYouKnowDesc: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Medium,
        color: '#374151',
        marginTop: 4,
        lineHeight: 16,
    },
    // Bottom CTAs
    ctaRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    seeCalculationButton: {
        width: '44%',
        height: 44,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#0A5F35',
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    seeCalculationIcon: {
        width: 14,
        height: 14,
        marginRight: 6,
        tintColor: '#0A5F35',
    },
    seeCalculationText: {
        fontSize: 12.5,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    saveButton: {
        width: '53%',
        height: 44,
        borderRadius: 8,
        backgroundColor: '#0A5F35',
        justifyContent: 'center',
        alignItems: 'center',
    },
    saveButtonText: {
        fontSize: 13,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
    },
});
