import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../../comman/Colors';
import FontsSize from '../../../comman/FontsSize';
import fonts from '../../../comman/fonts';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFBFB',
  },
  safeArea: {
    backgroundColor: '#FFFFFF',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F2F2',
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#ECEFEF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  backIcon: {
    width: 18,
    height: 18,
    tintColor: '#000000',
  },
  // Stepper Progress Indicators
  stepperContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: 16,
  },
  stepItem: {
    alignItems: 'center',
    flex: 1,
  },
  stepIndicator: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  stepIndicatorActive: {
    borderColor: '#0A5F35',
    backgroundColor: '#0A5F35',
  },
  stepIndicatorCompleted: {
    borderColor: '#0A5F35',
    backgroundColor: '#FFFFFF',
  },
  stepText: {
    fontSize: 11,
    fontFamily: fonts.OpenSans_Bold,
    color: '#94A3B8',
  },
  stepTextActive: {
    color: '#FFFFFF',
  },
  stepTextCompleted: {
    color: '#0A5F35',
  },
  stepLabel: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#64748B',
    marginTop: 4,
  },
  stepLabelActive: {
    color: '#0F172A',
    fontFamily: fonts.OpenSans_Bold,
  },
  stepLine: {
    position: 'absolute',
    top: 13,
    left: '12.5%',
    right: '12.5%',
    height: 1.5,
    backgroundColor: '#E2E8F0',
    zIndex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  // Hero Section
  heroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 16,
    minHeight: 160,
  },
  heroTextSection: {
    flex: 1.3,
    paddingRight: 8,
  },
  heroTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroTitle: {
    fontSize: 32,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },
  heroLeafIcon: {
    width: 24,
    height: 24,
    marginLeft: 6,
  },
  heroDesc: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Regular,
    color: '#1E293B',
    marginTop: 6,
    lineHeight: 19,
  },
  infoPillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EDF6EE',
    alignSelf: 'flex-start',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginTop: 12,
  },
  infoPillIconContainer: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#0A5F35',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },
  infoPillIconText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontFamily: fonts.OpenSans_Bold,
  },
  infoPillText: {
    fontSize: 11,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#111827',
  },
  heroImageContainer: {
    flex: 1.1,
    height: 125,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  // Main Questions Area
  questionsSection: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  sectionHeading: {
    fontSize: 13.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A1C14',
    marginBottom: 12,
  },
  // Question Card
  questionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#EEF2EF',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 3,
    elevation: 1.5,
  },
  questionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#EFF6F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  questionHeaderIcon: {
    width: 18,
    height: 18,
    tintColor: '#0D684D',
  },
  questionTextContainer: {
    flex: 1,
  },
  questionTitle: {
    fontSize: 12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A1C14',
  },
  questionSubtitle: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
    marginTop: 1.5,
  },
  questionInfoButton: {
    padding: 4,
  },
  questionInfoIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.2,
    borderColor: '#8E9A93',
    justifyContent: 'center',
    alignItems: 'center',
  },
  questionInfoIconText: {
    fontSize: 9,
    color: '#8E9A93',
    fontFamily: fonts.OpenSans_Bold,
  },
  // Multi Options Container (Row of 5 items)
  optionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  optionBox: {
    width: '18.5%',
    aspectRatio: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 2,
  },
  optionBoxSelected: {
    borderColor: '#0D684D',
    backgroundColor: '#EFF6F1',
  },
  optionIconText: {
    fontSize: 16,
    marginBottom: 4,
  },
  optionLabel: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#44554C',
    textAlign: 'center',
  },
  optionLabelSelected: {
    color: '#0D684D',
    fontFamily: fonts.OpenSans_Bold,
  },
  // Occupancy Option Box
  occupancyBox: {
    width: '18.5%',
    height: 32,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  occupancyBoxSelected: {
    borderColor: '#0D684D',
    backgroundColor: '#EFF6F1',
  },
  occupancyLabel: {
    fontSize: 11.5,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#44554C',
  },
  occupancyLabelSelected: {
    color: '#0D684D',
    fontFamily: fonts.OpenSans_Bold,
  },
  // Slider Distance Card Elements
  distanceDisplayContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 10,
    marginTop: 4,
  },
  distanceValue: {
    fontSize: 18,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0D684D',
  },
  distanceUnit: {
    fontSize: 10,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#8E9A93',
    marginLeft: 6,
  },
  sliderContainer: {
    height: 30,
    justifyContent: 'center',
    position: 'relative',
    marginVertical: 4,
  },
  sliderTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E5EBE7',
    width: '100%',
    position: 'absolute',
  },
  sliderTrackActive: {
    height: 4,
    borderRadius: 2,
    backgroundColor: '#0D684D',
    position: 'absolute',
  },
  sliderThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    borderWidth: 3.5,
    borderColor: '#0D684D',
    position: 'absolute',
    transform: [{ translateX: -9 }],
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.15,
    shadowRadius: 2.5,
    elevation: 2.5,
  },
  sliderRangeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  sliderRangeLabel: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#8E9A93',
  },
  // Estimated emissions block
  estimatedEmissionsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F9F5',
    marginHorizontal: 16,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#E2EFE6',
    marginTop: 4,
    marginBottom: 16,
  },
  co2IconContainer: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#EFF6F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#DFEAE2',
  },
  co2IconText: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0D684D',
  },
  emissionsTextContainer: {
    flex: 1.3,
  },
  emissionsHeading: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#44554C',
  },
  emissionsAmount: {
    fontSize: 17,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0D684D',
    marginTop: 2,
  },
  emissionsUnit: {
    fontSize: 10.5,
    color: '#44554C',
  },
  emissionsAmountSub: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#8E9A93',
    marginTop: 2,
  },
  seeCalculationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#0D684D',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    backgroundColor: '#FFFFFF',
  },
  seeCalculationIcon: {
    width: 11,
    height: 11,
    marginRight: 4,
    tintColor: '#0D684D',
  },
  seeCalculationText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0D684D',
  },
  // Submit Button
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#015608',
    marginHorizontal: 16,
    height: 46,
    borderRadius: 10,
    shadowColor: '#0D684D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    marginBottom: 10,
  },
  saveButtonText: {
    fontSize: 14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
    marginRight: 6,
  },
  saveButtonIcon: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: fonts.OpenSans_Bold,
  },
});
