import { StyleSheet } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';
import fonts from '../../comman/fonts';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  scrollContent: {
    paddingBottom: MarginHW.PaddingH10,
  },
  headerBackground: {
    height: 250,
    width: '100%',
  },
  headerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW10,
    marginTop: MarginHW.MarginH22,
  },
  headerTopButton: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,

  },
  headerTopButtonIcon: {
    width: 18,
    height: 18,
    tintColor: Colors.textDark,
  },
  headerRightButtons: {
    flexDirection: 'row',
    gap: MarginHW.MarginW10,
  },
  headerBottomContent: {
    paddingHorizontal: MarginHW.PaddingW20,
    paddingBottom: MarginHW.PaddingH50,
  },
  verifiedBadge: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(28, 61, 46, 0.7)',
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: MarginHW.PaddingH5,
    borderRadius: FontsSize.size16,
  },
  verifiedBadgeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size11,
    color: Colors.white,
  },
  verifiedBadgeIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW4,
  },
  headerTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size28,
    color: Colors.white,
  },
  headerLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH6,
  },
  headerLocationIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW4,
  },
  headerLocationText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size14,
    color: Colors.white,
  },
  headerDescription: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: MarginHW.MarginH10,
    lineHeight: 20,
    paddingRight: '48%',
  },
  statsOverlayCard: {
    position: 'absolute',
    bottom: 30,
    right: 10,
    backgroundColor: Colors.white,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 6,
  },
  statsCardColumn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  statsCardIcon: {
    width: 15,
    height: 15,
    tintColor: '#056213',
    marginRight: 8,
  },
  statsCardTextCol: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  statsCardValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.textDarkGreen,
  },
  statsCardLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: Colors.textLabelGrey,
    marginTop: 1,
  },
  statsCardDivider: {
    width: 1,
    height: 30,
    backgroundColor: Colors.dividerGreen,
    marginHorizontal: 2,
  },
  mainContent: {
    paddingHorizontal: MarginHW.PaddingW10,
    paddingBottom: MarginHW.MarginH10,
    marginTop: -25,
  },
  quickStatsCard: {
    backgroundColor: Colors.lightWhite,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    paddingVertical: 5,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  quickStatCol: {
    width: '23%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  quickStatIconBg: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickStatIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.TextColorLightGreen,
  },
  quickStatValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 11,
    color: Colors.textGreenDark,
    textAlign: 'center',
    alignSelf: 'stretch',
  },
  quickStatLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 9,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: 2,
    alignSelf: 'stretch',
  },
  quickStatDivider: {
    width: 1,
    height: 35,
    backgroundColor: Colors.dividerGreen,
  },
  aboutSection: {
    marginTop: MarginHW.MarginH6,
    marginHorizontal: 6,
  },
  sectionTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH4,
  },
  aboutContentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginVertical: 10,
  },
  aboutLeftTextContainer: {
    width: '63%',
  },
  aboutText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textMuted,
    lineHeight: 20,
  },
  readMoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH6,
  },
  readMoreText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: '#056213',
  },
  readMoreArrow: {
    width: 10,
    height: 10,
    tintColor: '#056213',
    marginLeft: 4,
  },
  videoCard: {
    width: '34%',
    height: HWSize.H_Height80,
    borderRadius: 10,
    overflow: 'hidden',
  },
  videoImageBg: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
  },
  playIconBg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  playIcon: {
    width: 16,
    height: 16,
    tintColor: '#056213',
    marginLeft: 2,
  },
  videoLabel: {
    position: 'absolute',
    bottom: 8,
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 10,
    color: Colors.white,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  gallerySection: {
    marginVertical: MarginHW.MarginH12,
    marginHorizontal: 6,
  },
  galleryScroll: {
    flexDirection: 'row',
    marginTop: 4,
  },
  galleryImage: {
    width: ImageSize.ImageW80,
    height: ImageSize.ImageH80,
    borderRadius: FontsSize.size8,
    marginRight: MarginHW.MarginW6,
    overflow: 'hidden',
  },
  galleryMoreOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  galleryMoreText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.white,
  },
  impactSection: {
    marginHorizontal: 6,
  },
  impactStatsCard: {
    backgroundColor: Colors.lightWhite,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    paddingVertical: 14,
    paddingHorizontal: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  impactStatCol: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  impactIconBg: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  impactIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.TextColorLightGreen,
  },
  impactValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 11,
    color: Colors.textGreenDark,
    textAlign: 'center',
    alignSelf: 'stretch',
  },
  impactLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 9,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: 2,
    alignSelf: 'stretch',
  },
  impactStatDivider: {
    width: 1,
    height: 35,
    backgroundColor: Colors.dividerGreen,
  },
  speciesSection: {
    marginTop: MarginHW.MarginH12,
    marginHorizontal: 10,
  },
  speciesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  speciesTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  speciesTitleLeaf: {
    width: 14,
    height: 14,
    tintColor: '#056213',
    marginLeft: 6,
  },
  viewAllSpeciesLink: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewAllSpeciesText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: '#056213',
  },
  viewAllSpeciesArrow: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: '#056213',
    marginLeft: MarginHW.MarginW4,
  },
  speciesSubtitle: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.textMuted,
  },
  speciesScroll: {
    flexDirection: 'row',
    paddingVertical: MarginHW.PaddingH5,
  },
  speciesCard: {
    marginTop: 5,
    width: 130,
    backgroundColor: Colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    overflow: 'hidden',
    marginRight: MarginHW.MarginW6,
    position: 'relative',
  },
  speciesCardSelected: {
    borderColor: '#056213',
    borderWidth: 1.5,
  },
  speciesImageWrapper: {
    width: '100%',
    height: 70,
    position: 'relative',
  },
  speciesImage: {
    width: '100%',
    height: '100%',
  },
  selectedCheckBadge: {
    position: 'absolute',
    bottom: -10,
    right: 10,
    width: 15,
    height: 15,
    borderRadius: 10,
    backgroundColor: '#056213',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
    zIndex: 10,
  },
  selectedCheckIcon: {
    width: 8,
    height: 8,
    tintColor: Colors.white,
  },
  speciesContent: {
    paddingHorizontal: MarginHW.PaddingH10,
    paddingVertical: 5,
  },
  speciesName: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.textGreenDark,
  },
  speciesScientific: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size11,
    color: Colors.textLabelGrey,
    fontStyle: 'italic',
    marginTop: 2,
  },
  detailsSection: {
    backgroundColor: Colors.lightWhite,
    marginHorizontal: MarginHW.MarginW10,
    marginVertical: MarginHW.MarginH10,
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: MarginHW.MarginH1,
  },
  detailsItemRow: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH8,
  },
  detailsItemCol: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: MarginHW.MarginH8,
  },
  detailsIconBg: {
    width: 20,
    height: 20,
    borderRadius: 20 / 2,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
  },
  detailsIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.legacyGreen,
  },
  detailsTextColRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailsTextColCol: {
    flex: 1,
    flexDirection: 'column',
  },
  detailsLabelRow: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.textLabelGrey,
    width: 80,
  },
  detailsValueRow: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.textDarkGreen,
    flex: 1,
  },
  detailsLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.textLabelGrey,
  },
  detailsValue: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size10,
    color: Colors.textDarkGreen,
    marginTop: 2,
  },
  bottomBanner: {
    backgroundColor: '#F7F8F3',
    borderColor: '#E7EBDC',
    borderWidth: 1,
    borderRadius: 10,
    marginHorizontal: MarginHW.MarginW10,
    paddingVertical: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bannerHandImage: {
    position: 'absolute',
    bottom: -32,
    left: -22,
    width: ImageSize.ImageW100,
    height: ImageSize.ImageH100,
    transform: [{ rotate: '-175deg' }, { scaleY: -1 }],
  },
  bannerTextContainer: {
    flex: 1,
    marginLeft: 75,
  },
  bannerTextTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size15,
    color: Colors.textDarkGreen,
  },
  bannerTextDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textMuted,
    marginTop: 2,
    lineHeight: 16,
  },
  bannerBtn: {
    backgroundColor: Colors.TextColorLightGreen,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginHorizontal: MarginHW.MarginW10,
    marginVertical: MarginHW.MarginH14,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerBtnText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.white,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
  },
  modalSafeArea: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW20,
    paddingVertical: MarginHW.PaddingH10,
  },
  modalCloseButton: {
    width: ImageSize.ImageW40,
    height: ImageSize.ImageH40,
    borderRadius: ImageSize.ImageW40 / 2,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseText: {
    color: Colors.white,
    fontSize: FontsSize.size18,
    fontFamily: fonts.OpenSans_Bold,
  },
  modalCounter: {
    color: Colors.white,
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
  },
  modalImageWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalFullImage: {
    width: '100%',
    height: '80%',
  },
  thumbnailScroll: {
    paddingVertical: MarginHW.PaddingH16,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
  },
  thumbnailContainer: {
    paddingHorizontal: MarginHW.PaddingW20,
    gap: MarginHW.MarginW10,
    alignItems: 'center',
  },
  thumbnailImage: {
    width: ImageSize.ImageW60,
    height: ImageSize.ImageH60,
    borderRadius: FontsSize.size8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  activeThumbnailImage: {
    borderColor: Colors.legacyGreen,
  },
});
