import { StyleSheet } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';
import fonts from '../../comman/fonts';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  scrollContent: {
    paddingBottom: MarginHW.PaddingH10,
  },
  headerBackground: {
    height: HWSize.H_Height350,
    width: '100%',
    justifyContent: 'space-between',
  },
  headerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW20,
    marginTop: MarginHW.MarginH35,
  },
  headerTopButton: {
    width: ImageSize.ImageW30,
    height: ImageSize.ImageH30,
    borderRadius: ImageSize.ImageW40 / 2,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,

  },
  headerTopButtonIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.textDark,
  },
  headerRightButtons: {
    flexDirection: 'row',
    gap: MarginHW.MarginW10,
  },
  headerBottomContent: {
    paddingHorizontal: MarginHW.PaddingW20,
    paddingBottom: MarginHW.PaddingH80,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: MarginHW.PaddingH5,
    borderRadius: FontsSize.size16,
    alignSelf: 'flex-start',
    marginBottom: MarginHW.MarginH10,
  },
  verifiedBadgeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size11,
    color: Colors.white,
  },
  verifiedBadgeIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW4,
  },
  headerTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size28,
    color: Colors.white,
  },
  headerLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH6,
  },
  headerLocationIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW4,
  },
  headerLocationText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size14,
    color: Colors.white,
  },
  headerDescription: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: MarginHW.MarginH10,
    lineHeight: 20,
  },
  statsOverlayCard: {
    position: 'absolute',
    bottom: -MarginHW.MarginH40,
    right: MarginHW.MarginW20,
    width: HWSize.W_Width220,
    backgroundColor: Colors.white,
    borderRadius: FontsSize.size16,
    padding: MarginHW.PaddingH16,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 6,
  },
  statsCardColumn: {
    alignItems: 'center',
    flex: 1,
  },
  statsCardIcon: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
    tintColor: Colors.legacyGreen,
  },
  statsCardValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDarkGreen,
    marginTop: MarginHW.MarginH4,
  },
  statsCardLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textLabelGrey,
    marginTop: 2,
  },
  statsCardDivider: {
    width: 1,
    height: '85%',
    backgroundColor: Colors.dividerGreen,
  },
  mainContent: {
    paddingHorizontal: MarginHW.PaddingW20,
    paddingTop: MarginHW.PaddingH50,
    paddingBottom: MarginHW.MarginH20,
  },
  quickStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: MarginHW.MarginH4,
  },
  quickStatCol: {
    width: '48%',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: FontsSize.size12,
    paddingVertical: MarginHW.PaddingH12,
    paddingHorizontal: MarginHW.PaddingW4,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    marginBottom: MarginHW.MarginH4,
  },
  quickStatIconBg: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH35,
    borderRadius: ImageSize.ImageW35 / 2,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH6,
  },
  quickStatIcon: {
    width: ImageSize.ImageW22,
    height: ImageSize.ImageH22,
    tintColor: Colors.legacyGreen,
  },
  quickStatValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.textDarkGreen,
    textAlign: 'center',
  },
  quickStatLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: 2,
  },
  aboutSection: {
    marginTop: MarginHW.MarginH6,
  },
  sectionTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size18,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH4,
  },
  aboutContentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  aboutLeftTextContainer: {
    width: '63%',
  },
  aboutText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: Colors.textMuted,
    lineHeight: 20,
  },
  readMoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH6,
  },
  readMoreText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.legacyGreen,
  },
  videoCard: {
    width: '34%',
    height: HWSize.H_Height80,
    borderRadius: FontsSize.size12,
    overflow: 'hidden',
  },
  videoImageBg: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
  },
  playIconBg: {
    width: ImageSize.ImageW30,
    height: ImageSize.ImageH30,
    borderRadius: ImageSize.ImageW30 / 2,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.legacyGreen,
    marginLeft: 2,
  },
  videoLabel: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.white,
    marginTop: MarginHW.MarginH4,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  gallerySection: {
    marginTop: MarginHW.MarginH12,
  },
  galleryScroll: {
    flexDirection: 'row',
  },
  galleryImage: {
    width: ImageSize.ImageW80,
    height: ImageSize.ImageH80,
    borderRadius: FontsSize.size12,
    marginRight: MarginHW.MarginW10,
    overflow: 'hidden',
  },
  galleryMoreOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  galleryMoreText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.white,
  },
  impactSection: {
    marginTop: MarginHW.MarginH4,
  },
  impactRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  impactCard: {
    width: '48%',
    backgroundColor: Colors.white,
    borderRadius: FontsSize.size12,
    padding: MarginHW.PaddingH12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH10,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
  },
  impactIconBg: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH35,
    borderRadius: ImageSize.ImageW35 / 2,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
  },
  impactIcon: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH20,
    tintColor: Colors.legacyGreen,
  },
  impactTextCol: {
    flex: 1,
  },
  impactValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDarkGreen,
  },
  impactLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textLabelGrey,
    marginTop: 1,
  },
  speciesSection: {
    marginTop: MarginHW.MarginH4,
  },
  speciesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  speciesTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewAllSpeciesLink: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewAllSpeciesText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.legacyGreen,
  },
  viewAllSpeciesArrow: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.legacyGreen,
    marginLeft: MarginHW.MarginW4,
  },
  speciesScroll: {
    flexDirection: 'row',
    paddingVertical: MarginHW.PaddingH5,
  },
  speciesCard: {
    width: HWSize.W_Width100,
    backgroundColor: Colors.white,
    borderRadius: FontsSize.size12,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    overflow: 'hidden',
    marginRight: MarginHW.MarginW12,
    position: 'relative',
  },
  speciesCardSelected: {
    borderColor: Colors.legacyGreen,
    borderWidth: 1.5,
  },
  speciesImage: {
    width: '100%',
    height: ImageSize.ImageH70,
  },
  speciesContent: {
    padding: MarginHW.PaddingH8,
    paddingBottom: MarginHW.PaddingH12,
  },
  speciesName: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.textDarkGreen,
  },
  speciesScientific: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size11,
    color: Colors.textLabelGrey,
    fontStyle: 'italic',
    marginTop: 2,
  },
  selectedCheckBadge: {
    position: 'absolute',
    top: MarginHW.MarginH6,
    right: MarginHW.MarginW6,
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    borderRadius: ImageSize.ImageW16 / 2,
    backgroundColor: Colors.legacyGreen,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  selectedCheckIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.white,
  },
  detailsSection: {
    marginTop: MarginHW.MarginH4,
    marginBottom: MarginHW.MarginH2,
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: MarginHW.MarginH1,
  },
  detailsItem: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: MarginHW.MarginH8,
  },
  detailsIconBg: {
    width: ImageSize.ImageW30,
    height: ImageSize.ImageH30,
    borderRadius: ImageSize.ImageW28 / 2,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
    marginTop: 2,
  },
  detailsIcon: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH20,
    tintColor: Colors.legacyGreen,
  },
  detailsTextCol: {
    flex: 1,
  },
  detailsLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: Colors.textLabelGrey,
  },
  detailsValue: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size13,
    color: Colors.textDarkGreen,
    marginTop: 2,
  },
  bottomBanner: {
    backgroundColor: '#F7F8F3',
    borderColor: '#E7EBDC',
    borderWidth: 1,
    borderRadius: FontsSize.size20,
    marginHorizontal: MarginHW.MarginW20,
    paddingVertical: MarginHW.PaddingH8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  // bannerLeftSection: {
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   flex: 1,
  //   marginRight: MarginHW.MarginW10,
  // },
  bannerHandImage: {
    position: 'absolute',
    bottom: -32,
    left: -22,
    width: ImageSize.ImageW100,
    height: ImageSize.ImageH100,
    transform: [{ rotate: '-175deg' }, { scaleY: -1 }],
  },
  bannerTextContainer: {
    flex: 1,
    marginLeft: MarginHW.MarginW80,

  },
  bannerTextTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDarkGreen,
  },
  bannerTextDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: Colors.textMuted,
    marginTop: 2,
    lineHeight: 16,
  },
  bannerBtnContainer: {
    marginHorizontal: MarginHW.MarginW20,
    paddingVertical: MarginHW.PaddingH8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bannerBtn: {
    backgroundColor: Colors.legacyGreen,
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW16,
    borderRadius: FontsSize.size12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: MarginHW.MarginH10
  },
  bannerBtnText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.white,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
  },
  modalSafeArea: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW20,
    paddingVertical: MarginHW.PaddingH10,
  },
  modalCloseButton: {
    width: ImageSize.ImageW40,
    height: ImageSize.ImageH40,
    borderRadius: ImageSize.ImageW40 / 2,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseText: {
    color: Colors.white,
    fontSize: FontsSize.size18,
    fontFamily: fonts.OpenSans_Bold,
  },
  modalCounter: {
    color: Colors.white,
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
  },
  modalImageWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalFullImage: {
    width: '100%',
    height: '80%',
  },
  thumbnailScroll: {
    paddingVertical: MarginHW.PaddingH16,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
  },
  thumbnailContainer: {
    paddingHorizontal: MarginHW.PaddingW20,
    gap: MarginHW.MarginW10,
    alignItems: 'center',
  },
  thumbnailImage: {
    width: ImageSize.ImageW60,
    height: ImageSize.ImageH60,
    borderRadius: FontsSize.size8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  activeThumbnailImage: {
    borderColor: Colors.legacyGreen,
  },
});
