import { StyleSheet } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';
import fonts from '../../comman/fonts';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFBFB',
  },
  scrollContainer: {
    paddingBottom: MarginHW.PaddingH20,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW16,
    paddingTop: MarginHW.PaddingH10,
    paddingBottom: MarginHW.PaddingH10,
    backgroundColor: '#FAFBFB',
  },
  backButton: {
    padding: MarginHW.PaddingW8,
  },
  backIcon: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH20,
    tintColor: Colors.black,
  },
  headerTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.black,
  },
  coinBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    paddingHorizontal: MarginHW.PaddingW12,
    paddingVertical: MarginHW.PaddingH5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E8EFEA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  coinIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW6,
  },
  coinIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.white,
  },
  coinTextContainer: {
    alignItems: 'flex-start',
  },
  coinAmount: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.black,
    lineHeight: 14,
  },
  coinLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 8,
    color: Colors.bannerTextDesc,
    lineHeight: 10,
  },
  stepperContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW16,
    marginVertical: MarginHW.MarginH16,
    position: 'relative',
  },
  stepperLine: {
    position: 'absolute',
    left: MarginHW.PaddingW30,
    right: MarginHW.PaddingW30,
    top: 14,
    height: 2,
    backgroundColor: '#E0E5E2',
    zIndex: 1,
  },
  stepItem: {
    alignItems: 'center',
    flex: 1,
    zIndex: 2,
  },
  stepCircle: {
    width: ImageSize.ImageH22,
    height: ImageSize.ImageH22,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH5,
  },
  stepCircleActive: {
    backgroundColor: Colors.tint,
  },
  stepCircleCompleted: {
    backgroundColor: Colors.tint,
  },
  stepCircleInactive: {
    backgroundColor: '#D1DCD6',
  },
  stepNumber: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.white,
  },
  stepCheckIcon: {
    width: 12,
    height: 12,
    tintColor: Colors.white,
  },
  stepLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    textAlign: 'center',
  },
  stepLabelActive: {
    color: Colors.tint,
    fontFamily: fonts.OpenSans_SemiBold,
  },
  stepLabelInactive: {
    color: '#8E9A93',
  },
  heroCard: {
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH8,
    overflow: 'hidden',
  },
  heroImage: {
    width: '100%',
    height: 170,
    justifyContent: 'center',
  },
  heroImageRadius: {
    width: '60%',
    left: '43%',
  },
  heroOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  heroContent: {
    flex: 1,
    paddingHorizontal: MarginHW.PaddingW20,
    justifyContent: 'center',
  },
  heroTextContainer: {
    width: '60%',
  },
  heroTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size22,
    lineHeight: 28,
    color: Colors.textDark,
  },
  heroSubtitle: {
    marginTop: MarginHW.MarginH4,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size13,
    lineHeight: 14,
    color: Colors.textMuted,
  },
  highlightGreen: {
    color: Colors.tint,
    fontFamily: fonts.OpenSans_Bold,
  },
  stateSelectorCard: {
    backgroundColor: '#F3F8F4',
    borderWidth: 1,
    borderColor: '#E2EFE5',
    borderRadius: 20,
    marginHorizontal: MarginHW.MarginW16,
    paddingVertical: MarginHW.PaddingH12,
    paddingHorizontal: MarginHW.PaddingW16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: MarginHW.MarginH20,
  },
  stateLeftSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stateIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 28,
    backgroundColor: 'rgba(161, 190, 172, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW12,
  },
  stateIcon: {
    width: 50,
    height: 50,
    marginRight: 5,

  },
  stateTextContainer: {
    justifyContent: 'center',
  },
  stateLabelText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size16,
    color: '#6B7A70',
  },
  stateValueText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.tint,
    marginTop: 1,
  },
  changeStateButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  changeStateText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size14,
    color: Colors.tint,
    marginRight: 4,
  },
  changeStatePencil: {
    width: 12,
    height: 12,
    tintColor: Colors.tint,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH12,
  },
  sectionTitleContainer: {
    flex: 1,
    paddingRight: MarginHW.PaddingW8,
  },
  sectionTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDark,
  },
  sectionSubtitle: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size13,
    color: Colors.textMuted,
    marginTop: MarginHW.MarginH1,
  },
  viewMapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: MarginHW.PaddingH3,
  },
  viewMapText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.tint,
    marginRight: MarginHW.MarginW1,
  },
  viewMapIcon: {
    width: ImageSize.ImageH16,
    height: ImageSize.ImageH16,
    tintColor: Colors.tint,
  },
  locationList: {
    paddingHorizontal: MarginHW.PaddingW16,
  },
  locationCard: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: MarginHW.PaddingW12,
    marginBottom: MarginHW.MarginH10,
    borderWidth: 1.5,
    borderColor: '#E8EFEA',
    flexDirection: 'row',
    position: 'relative',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  locationCardSelected: {
    borderColor: Colors.tint,
  },
  locationImageContainer: {
    width: 100,
    height: 100,
    borderRadius: 14,
    overflow: 'hidden',
    position: 'relative',
  },
  locationImage: {
    width: '100%',
    height: '100%',
  },
  popularBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: '#1E6B46',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  popularText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 8,
    color: Colors.white,
  },
  locationInfoContainer: {
    flex: 1,
    marginLeft: MarginHW.MarginW12,
    justifyContent: 'space-between',
  },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: 10,
  },
  cardTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size13,
    color: Colors.textDark,
    flex: 1,
    paddingRight: 6,
  },
  selectionOuterCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: '#BCCAC0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectionOuterCircleSelected: {
    borderColor: Colors.tint,
    backgroundColor: Colors.tint,
  },
  selectionInnerCheck: {
    width: 10,
    height: 10,
    tintColor: Colors.white,
  },
  locationPinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  pinIcon: {
    width: 10,
    height: 10,
    tintColor: '#5B665F',
    marginRight: 3,
  },
  pinText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size9,
    color: '#5B665F',
  },
  cardDescription: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 9,
    color: '#6B7A70',
    lineHeight: 12,
    marginTop: 4,
  },
  cardDivider: {
    height: 1,
    backgroundColor: '#EAEAEA',
    marginVertical: 6,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statCol: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 1,
  },
  statIcon: {
    width: 11,
    height: 11,
    tintColor: Colors.tint,
    marginRight: 3,
  },
  statValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 9,
    color: Colors.textDark,
  },
  statLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 7,
    color: '#8E9A93',
  },
  statDivider: {
    width: 1,
    height: 16,
    backgroundColor: '#E2EBE5',
  },
  verifiedLabel: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 9,
    color: Colors.tint,
  },
  bannerCard: {
    backgroundColor: '#EFF5F0',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2ECE5',
    marginHorizontal: MarginHW.MarginW16,
    marginTop: MarginHW.MarginH1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
    height: 76,
  },
  bannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingLeft: 14,
    paddingRight: 10,
  },
  bannerShieldContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#EFF4EF',
  },
  bannerShieldIcon: {
    width: ImageSize.ImageH20,
    height: ImageSize.ImageH20,
    tintColor: '#1A6836',
  },
  bannerText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size12,
    color: Colors.textDark,
    lineHeight: 14,
    flex: 1,
  },
  bannerRight: {
    flex: 1,
    height: 48,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  bannerHandImage: {
    width: 90,
    height: 80,
  },
  footerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW20,
    paddingBottom: MarginHW.PaddingH10,
  },
  continueButton: {
    flex: 1,
    backgroundColor: Colors.continue,
    height: 60,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    shadowColor: Colors.btnShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  continueText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size20,
    color: Colors.white,
  },
  continueArrow: {
    position: 'absolute',
    right: 20,
    width: ImageSize.ImageH20,
    height: ImageSize.ImageH20,
    tintColor: Colors.white,
  },
});
