import { StyleSheet } from 'react-native';
import { Colors } from '../../../comman/Colors';
import FontsSize from '../../../comman/FontsSize';
import MarginHW from '../../../comman/MarginHW';
import ImageSize from '../../../comman/ImageSize';
import HWSize from '../../../comman/HWSize';
import fonts from '../../../comman/fonts';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  scrollContent: {
    paddingBottom: MarginHW.PaddingH3,
  },
  headerSection: {
    height: 240,
    justifyContent: 'center',
    paddingHorizontal: MarginHW.PaddingW10,
  },
  headerTopRow: {
    position: 'absolute',
    top: 20,
    left: 10,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 20,
  },
  backButton: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  backIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.textDark,
  },
  headerContentRow: {
    flexDirection: 'row',
    marginTop: 10,

  },
  headerTextContainer: {
    flex: 1,
    justifyContent: 'center',

  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  headerSubtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  headerTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size20,
    color: Colors.textDarkGreen,
  },
  headerTitleLeaf: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    marginLeft: MarginHW.MarginW6,
  },
  headerSubtitle: {
    marginVertical: 2,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: Colors.black,
  },
  projectHighlight: {
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.legacyGreen,
  },
  gpsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.bgGreenLight,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: 4,
    borderRadius: FontsSize.size12,
    alignSelf: 'flex-start',
    marginTop: MarginHW.MarginH10,
  },
  gpsIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.legacyGreen,
    marginRight: MarginHW.MarginW4,
  },
  gpsText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.textDarkGreen,
  },
  quickStatsContainer: {
    marginHorizontal: MarginHW.MarginW10,
    marginTop: -40,
    backgroundColor: Colors.bgWhite,
    borderRadius: FontsSize.size16,
    paddingVertical: MarginHW.PaddingH12,
    paddingHorizontal: MarginHW.PaddingW10,
    borderWidth: 1,
    borderColor: '#F2F4F3',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  quickStatCol: {
    alignItems: 'center',
    flex: 1,
  },
  quickStatIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.legacyGreen,
    marginBottom: 4,
  },
  quickStatValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDarkGreen,
  },
  quickStatLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.textLabelGrey,
  },
  quickStatDivider: {
    width: 1,
    height: '60%',
    backgroundColor: '#E5E7EB',
  },
  listSection: {
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH10,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  listTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDarkGreen,
  },
  listSubtitle: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.textLabelGrey,
    marginBottom: MarginHW.MarginH8,
  },
  speciesCard: {
    backgroundColor: Colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F2F4F3',
    paddingHorizontal: 8,
    paddingVertical: 8,
    marginBottom: MarginHW.MarginH10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  speciesCardSelected: {
    borderColor: Colors.legacyGreen,
    borderWidth: 1.5,
    shadowOpacity: 0.08,
    shadowColor: Colors.legacyGreen,
  },
  cardContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  speciesInfoCol: {
    flex: 1,
    flexDirection: 'column',
  },
  speciesHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  scientificRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  speciesImage: {
    width: 85,
    height: 85,
    borderRadius: 5,
    marginRight: 12,
  },
  speciesName: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDarkGreen,
  },
  nativeBadge: {
    backgroundColor: '#EEF6F2',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 8,
  },
  nativeBadgeLeaf: {
    width: 8,
    height: 8,
    tintColor: '#1E6B46',
    marginRight: 3,
  },
  nativeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 10,
    color: '#1E6B46',
  },
  speciesScientific: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size11,
    color: Colors.textLabelGrey,
    fontStyle: 'italic',
  },
  radioButton: {
    width: 18,
    height: 18,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#C5D0C9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonSelected: {
    borderColor: '#056213',
  },
  radioDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#056213',
  },
  cardDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: MarginHW.MarginH10,
  },
  cardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5,
  },
  detailCol: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  detailDivider: {
    width: 1,
    height: 20,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 6,
  },
  detailIcon: {
    width: 16,
    height: 16,
    tintColor: '#056213',
  },
  detailLabelContainer: {
    flex: 1,
    alignItems: 'center'
  },
  detailLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 9,
    color: Colors.textLabelGrey,
  },
  detailValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 11,
    color: Colors.textDarkGreen,
    marginTop: 1,
  },
  impactSection: {
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH1,
    marginBottom: MarginHW.MarginH12,
  },
  impactCard: {
    backgroundColor: Colors.bgWhite,
    borderRadius: 10,
    padding: MarginHW.PaddingH8,
    borderWidth: 1,
    borderColor: '#DCECE3',
  },
  impactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  impactTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDarkGreen,
  },
  impactSubtitle: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: Colors.textLabelGrey,
  },
  impactGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5,
  },
  impactCol: {
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 2,
  },
  impactIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EFF5F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  impactIconBgDrop: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EBF4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  impactIcon: {
    width: 16,
    height: 16,
    tintColor: '#056213',
  },
  impactIconDrop: {
    width: 16,
    height: 16,
    tintColor: '#0066CC',
  },
  impactLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 8,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginBottom: 2,
    alignSelf: 'stretch',
  },
  impactValue: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: 10,
    color: '#056213',
    textAlign: 'center',
    alignSelf: 'stretch',
  },
  impactDivider: {
    width: 1,
    height: 35,
    backgroundColor: '#D4E8DC',
  },
  footerContainer: {
    backgroundColor: Colors.listBgLight,
    marginHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    paddingHorizontal: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 2,
    marginBottom: 20,
  },
  footerSelectedInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  footerThumbnail: {
    width: 50,
    height: 50,
    borderRadius: 5,
    marginRight: 10,
  },
  footerTextCol: {
    flex: 1,
  },
  footerLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 10,
    color: Colors.textLabelGrey,
  },
  footerName: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 14,
    color: Colors.textDarkGreen,
    marginTop: 1,
  },
  footerScientific: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: 10,
    color: Colors.textLabelGrey,
    fontStyle: 'italic',
    marginTop: 1,
  },
  footerChangeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  footerChangeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 11,
    color: '#056213',
  },
  footerChangeIcon: {
    width: 10,
    height: 10,
    tintColor: '#056213',
    marginLeft: 4,
  },
  footerDivider: {
    width: 1,
    height: 50,
    backgroundColor: '#ECEFEF',
    marginHorizontal: 12,
  },
  footerActionCol: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  proceedButton: {
    backgroundColor: '#056213',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  proceedButtonText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 14,
    color: Colors.white,
  },
  footerSecureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  footerSecureIcon: {
    width: 12,
    height: 12,
    tintColor: '#8E9A93',
    marginRight: 4,
  },
  footerSecureText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 10,
    color: '#8E9A93',
  },
});
