import { StyleSheet } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';
import fonts from '../../comman/fonts';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  bannerCard: {
    backgroundColor: Colors.bgGreenLight,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    marginHorizontal: MarginHW.MarginW16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
    paddingVertical: MarginHW.PaddingH3,
  },
  bannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingLeft: MarginHW.PaddingW14,
    paddingRight: MarginHW.PaddingW10,
  },
  bannerShieldContainer: {
    width: ImageSize.ImageW40,
    height: ImageSize.ImageH40,
    borderRadius: ImageSize.ImageW40 / 2,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW12,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
  },
  bannerShieldIcon: {
    width: ImageSize.ImageH20,
    height: ImageSize.ImageH20,
    tintColor: Colors.shieldIconColor,
  },
  bannerTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  bannerText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDark,
    lineHeight: FontsSize.size16,
    marginBottom: MarginHW.MarginH2,
  },
  bannerTextSecondary: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textDark,
    lineHeight: FontsSize.size16,
  },

  bannerHandImage: {
    width: 80,
    height: 80,
  },
  scrollContainer: {
    paddingBottom: MarginHW.PaddingH24,
  },

  heroCard: {
    marginHorizontal: 0,
    marginBottom: MarginHW.MarginH8,
    overflow: 'hidden',
  },
  heroImage: {
    width: '100%',
    height: HWSize.H_Height168,
    justifyContent: 'center',
  },
  heroImageRadius: {
    width: '100%',
    left: 30,
  },
  heroOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  heroContent: {
    flex: 1,
    paddingHorizontal: MarginHW.PaddingW20,
    justifyContent: 'center',
  },
  heroTextContainer: {
    width: '65%',
  },
  heroTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size20,
    lineHeight: FontsSize.size28,
    color: Colors.textDark,
  },
  heroSubtitle: {
    marginTop: MarginHW.MarginH4,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    lineHeight: FontsSize.size16,
    color: Colors.black,
  },
  highlightGreen: {
    color: Colors.tint,
    fontFamily: fonts.OpenSans_Bold,
  },
  sectionHeader: {
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH12,
  },

  sectionTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size18,
    color: Colors.textDark,
  },
  sectionSubtitle: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textMuted,
    marginTop: MarginHW.MarginH2,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editButtonText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size12,
    color: Colors.tint,
    marginRight: MarginHW.MarginW4,
  },
  editIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.tint,
  },
  summaryCard: {
    marginTop: -35,
    backgroundColor: Colors.listBg,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    borderRadius: 10,
    marginHorizontal: MarginHW.MarginW16,
    paddingVertical: MarginHW.PaddingH8,
    paddingBottom: MarginHW.PaddingH3,
    paddingHorizontal: MarginHW.PaddingW6,
    marginBottom: MarginHW.MarginH10,
  },
  summaryCardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH5,
    paddingHorizontal: MarginHW.PaddingW4,
  },
  summaryCardTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDarkGreen,
  },
  summaryContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  summaryRowDivider: {
    height: 1,
    backgroundColor: Colors.dividerGreen,
    marginVertical: MarginHW.MarginH4,
    marginHorizontal: MarginHW.MarginW4,
  },
  summaryItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 0.6,
  },
  summaryItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingLeft: MarginHW.PaddingW12,
  },
  summaryDivider: {
    width: 1,
    height: ImageSize.ImageH24,
    backgroundColor: Colors.dividerGreen,
    alignSelf: 'center',
  },
  summaryIconContainer: {
    width: ImageSize.ImageW38,
    height: ImageSize.ImageH38,
    borderRadius: ImageSize.ImageW38 / 2,
    backgroundColor: Colors.iconBgLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
  },
  summaryIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.tint,
  },
  summaryTextContainer: {
    flex: 1,
    flexShrink: 1,
  },
  summaryLabel: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size14,
    color: Colors.textMuted,
    flexShrink: 1,
  },
  summaryValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.tint,
    marginTop: MarginHW.MarginH2,
    lineHeight: FontsSize.size16,
    flexShrink: 1,
  },
  amountScrollView: {
    paddingHorizontal: MarginHW.PaddingW16,
    paddingBottom: MarginHW.PaddingH5,
  },
  amountCard: {
    width: HWSize.W_Width85,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderColor: Colors.bannerBorder,
    borderRadius: 8,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW10,
    position: 'relative',
  },
  amountCardSelected: {
    borderColor: Colors.tint,
    backgroundColor: Colors.white,
  },
  amountBadge: {
    position: 'absolute',
    top: MarginHW.MarginH5,
    right: MarginHW.MarginW5,
    width: 18,
    height: 18,
    borderRadius: 18 / 2,
    backgroundColor: Colors.tint,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  amountIconContainer: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    backgroundColor: Colors.borderGreenUltraLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH5,
  },
  amountCardIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.tint,
  },
  amountValueText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDark,
    lineHeight: FontsSize.size20,
  },
  amountSubtext: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size10,
    color: Colors.textGreenDark,
    marginTop: MarginHW.MarginH2,
    textAlign: 'center',
    lineHeight: FontsSize.size12,
  },
  impactBanner: {
    backgroundColor: Colors.listBgLight,
    borderRadius: 10,
    padding: MarginHW.PaddingW12,
    marginHorizontal: MarginHW.MarginW16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: MarginHW.MarginH8,
    marginTop: MarginHW.MarginH8,
    borderWidth: 1,
    borderColor: Colors.bannerBorderGreen,
  },
  impactLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.8,
  },
  impactIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 42 / 2,
    backgroundColor: Colors.badgeGreenBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
  },
  impactIcon: {
    width: 22,
    height: 22,
    tintColor: Colors.tint,
  },
  impactText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size10,
    color: Colors.textGreenDark,
    lineHeight: FontsSize.size14,
    flex: 1,
  },
  impactRight: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.1,
    borderLeftWidth: 1,
    borderLeftColor: Colors.dividerGreen,
    paddingLeft: MarginHW.PaddingW10,
    justifyContent: 'center',
  },
  impactShieldIcon: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH20,
    tintColor: Colors.tint,
    marginRight: MarginHW.MarginW16,
  },
  impactSecureText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.textGreenDark,
  },
  paymentMethodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.borderLight,
    borderRadius: 10,
    padding: MarginHW.PaddingW12,
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH8,
  },
  paymentMethodRowSelected: {
    borderColor: Colors.tint,
  },
  paymentMethodLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  methodIconWrapper: {
    width: ImageSize.ImageW40,
    height: ImageSize.ImageH40,
    borderRadius: 8,
    backgroundColor: Colors.containerBg,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW12,
  },
  methodIcon: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
  },
  methodTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDark,
  },
  methodSubtext: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.placeholderColor,
    marginLeft: MarginHW.MarginW6,
    flex: 1,
  },
  recommendedBadge: {
    backgroundColor: Colors.badgeGreenBg,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: MarginHW.PaddingH3,
    borderRadius: 6,
    marginLeft: MarginHW.MarginW8,
  },
  recommendedText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10,
    color: Colors.tint,
    textAlign: 'center',
    lineHeight: FontsSize.size12,
  },
  radioButtonOuter: {
    width: 18,
    height: 18,
    borderRadius: 18 / 2,
    borderWidth: 1.5,
    borderColor: Colors.placeholderColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonOuterSelected: {
    borderColor: Colors.tint,
  },
  radioButtonInner: {
    width: ImageSize.ImageW9,
    height: ImageSize.ImageH9,
    borderRadius: ImageSize.ImageW9 / 2,
    backgroundColor: Colors.tint,
  },
  applyPointsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.borderLight,
    borderRadius: 10,
    padding: MarginHW.PaddingW12,
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH10,
    marginTop: MarginHW.MarginH1,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  applyPointsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  pointsIconContainer: {
    width: ImageSize.ImageW38,
    height: ImageSize.ImageH38,
    borderRadius: ImageSize.ImageW38 / 2,
    backgroundColor: Colors.pointsIconBgLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW12,
  },
  pointsIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.pointsIconColor,
  },
  applyPointsTextContainer: {
    flex: 1,
  },
  applyPointsTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDark,
  },
  applyPointsSubtext: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.placeholderColor,
    marginTop: MarginHW.MarginH1,
  },
  discountValueText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.tint,
    marginRight: MarginHW.MarginW10,
  },
  customSwitchContainer: {
    width: ImageSize.ImageW50,
    height: ImageSize.ImageH26,
    borderRadius: ImageSize.ImageH26 / 2,
    padding: 2,
    justifyContent: 'center',
  },
  customSwitchKnob: {
    width: ImageSize.ImageW22,
    height: ImageSize.ImageH22,
    borderRadius: ImageSize.ImageH22 / 2,
    backgroundColor: Colors.white,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },

  footerContainer: {
    paddingHorizontal: MarginHW.PaddingW20,
    paddingBottom: MarginHW.PaddingH10,
  },
  payButton: {
    backgroundColor: Colors.continue,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.btnShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
    position: 'relative',
    paddingVertical: MarginHW.PaddingH8,
  },
  payTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  payLockIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW6,
  },
  payButtonText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.white,
  },
  payButtonSubtext: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.glassBorder,
    marginTop: MarginHW.MarginH2,
  },
  payArrow: {
    position: 'absolute',
    right: MarginHW.MarginW20,
    width: ImageSize.ImageH20,
    height: ImageSize.ImageH20,
    tintColor: Colors.white,
  },
  upiText: {
    fontFamily: fonts.OpenSans_ExtraBold,
    fontSize: FontsSize.size10,
    color: Colors.upiGreen,
    fontStyle: 'italic',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  amountBadgeCheck: {
    width: 8,
    height: 5,
    borderLeftWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: Colors.white,
    transform: [{ rotate: '-45deg' }],
    marginTop: -1,
  },
  customAmountContainer: {
    marginHorizontal: MarginHW.MarginW16,
    marginTop: MarginHW.MarginH12,
    marginBottom: MarginHW.MarginH4,
  },
  customAmountInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.tint,
    borderRadius: 14,
    backgroundColor: Colors.white,
    paddingHorizontal: MarginHW.PaddingW12,
    height: HWSize.H_Height50,
  },
  customAmountCurrency: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.tint,
    marginRight: MarginHW.MarginW6,
  },
  customAmountInput: {
    flex: 1,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size15,
    color: Colors.textDark,
    paddingVertical: 0,
  },
  methodDetails: {
    flex: 1,
  },
  methodHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  applyPointsRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});
