import { StyleSheet } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';
import fonts from '../../comman/fonts';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  bannerCard: {
    backgroundColor: '#EFF5F0',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2ECE5',
    marginHorizontal: MarginHW.MarginW16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
    position: 'relative',
    minHeight: 84,
    paddingVertical: 12,
  },
  bannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingLeft: 12,
    paddingRight: 120,
  },
  bannerShieldContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#E2ECE5',
  },
  bannerShieldIcon: {
    width: 18,
    height: 18,
    tintColor: '#056213',
  },
  bannerTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  bannerText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 13.5,
    color: '#111827',
    lineHeight: 16,
  },
  bannerTextSecondary: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 11.5,
    color: '#5B665F',
    lineHeight: 15,
    marginTop: 2,
  },
  bannerHandImage: {
    width: 130,
    height: '100%',
    position: 'absolute',
    right: 0,
    bottom: 0,
  },
  scrollContainer: {
    paddingBottom: MarginHW.PaddingH24,
  },

  heroCard: {
    marginHorizontal: 0,
    marginBottom: MarginHW.MarginH8,
    overflow: 'hidden',
  },
  heroImage: {
    width: '100%',
    height: HWSize.H_Height168,
    justifyContent: 'center',
  },
  heroImageRadius: {
    width: '100%',
    left: 60,
  },
  heroOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  heroContent: {
    flex: 1,
    paddingHorizontal: MarginHW.PaddingW20,
    justifyContent: 'center',
  },
  heroTextContainer: {
    width: '65%',
  },
  heroTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size20,
    lineHeight: FontsSize.size28,
    color: Colors.textDark,
  },
  heroSubtitle: {
    marginTop: MarginHW.MarginH4,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    lineHeight: FontsSize.size16,
    color: Colors.black,
  },
  highlightGreen: {
    color: Colors.tint,
    fontFamily: fonts.OpenSans_Bold,
  },
  sectionHeader: {
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH12,
  },

  sectionTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size18,
    color: Colors.textDark,
  },
  sectionSubtitle: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textMuted,
    marginTop: MarginHW.MarginH2,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editButtonText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size12,
    color: Colors.tint,
    marginRight: MarginHW.MarginW4,
  },
  editIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.tint,
  },
  summaryCard: {
    marginTop: -35,
    backgroundColor: Colors.listBg,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    borderRadius: 14,
    marginHorizontal: MarginHW.MarginW16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginBottom: MarginHW.MarginH10,
  },
  summaryCardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH5,
    paddingHorizontal: MarginHW.PaddingW4,
  },
  summaryCardTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDarkGreen,
  },
  summaryHorizontalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  summaryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 1,
  },
  summaryVerticalDivider: {
    width: 1,
    height: 32,
    backgroundColor: '#E0E5E2',
  },
  summaryIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#EFF5F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  summaryItemIcon: {
    width: 12,
    height: 12,
    tintColor: '#056213',
  },
  summaryItemTextCol: {
    flex: 1,
  },
  summaryItemLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 9,
    color: Colors.textMuted,
  },
  summaryItemValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 9.5,
    color: '#056213',
    marginTop: 0.5,
    lineHeight: 12,
  },
  amountScrollView: {
    paddingHorizontal: MarginHW.PaddingW16,
    paddingBottom: MarginHW.PaddingH5,
    paddingTop: 8,
  },
  amountCard: {
    width: HWSize.W_Width85,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    borderRadius: 12,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW10,
    position: 'relative',
  },
  amountCardSelected: {
    borderColor: '#056213',
    borderWidth: 1.5,
    backgroundColor: Colors.white,
  },
  amountBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#056213',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  amountIconContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#EFF5F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH5,
  },
  amountCardIcon: {
    width: 14,
    height: 14,
    tintColor: '#056213',
  },
  amountValueText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDark,
    lineHeight: FontsSize.size20,
  },
  amountSubtext: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size10,
    color: Colors.textMuted,
    marginTop: MarginHW.MarginH2,
    textAlign: 'center',
    lineHeight: FontsSize.size12,
  },
  impactBanner: {
    backgroundColor: Colors.bgGreenLight,
    borderRadius: 12,
    padding: 12,
    marginHorizontal: MarginHW.MarginW16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: MarginHW.MarginH8,
    marginTop: MarginHW.MarginH8,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
  },
  impactLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 8,
  },
  impactIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.badgeGreenBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  impactIcon: {
    width: 18,
    height: 18,
    tintColor: '#056213',
  },
  impactText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: 10.5,
    color: Colors.textDark,
    lineHeight: 14,
    flex: 1,
  },
  secureBadgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E6EFE8',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
  },
  secureBadgeIcon: {
    width: 14,
    height: 14,
    tintColor: '#056213',
    marginRight: 6,
  },
  secureBadgeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 9.5,
    color: '#056213',
    lineHeight: 12,
  },
  paymentMethodsContainer: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    borderRadius: 12,
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH10,
    overflow: 'hidden',
  },
  paymentMethodRowCustom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  paymentMethodLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  methodIconWrapperCustom: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  methodTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  methodTitleCustom: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 14,
    color: '#111827',
    marginRight: 8,
  },
  methodSubtextCustom: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 11.5,
    color: '#5B665F',
    flex: 1,
  },
  paymentMethodRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recommendedBadgeCustom: {
    backgroundColor: '#E6EFE8',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginRight: 10,
  },
  recommendedTextCustom: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 9.5,
    color: '#056213',
  },
  radioButtonOuterCustom: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: '#A1B0A6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonOuterSelectedCustom: {
    borderColor: '#056213',
  },
  radioButtonInnerCustom: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: '#056213',
  },
  paymentMethodDivider: {
    height: 1,
    backgroundColor: '#ECEFEF',
    marginHorizontal: 16,
  },
  applyPointsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    borderRadius: 12,
    padding: MarginHW.PaddingW12,
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH10,
    marginTop: MarginHW.MarginH1,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  applyPointsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  pointsIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFA751',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  pointsIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.white,
  },
  applyPointsTextContainer: {
    flex: 1,
  },
  applyPointsTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDark,
  },
  applyPointsSubtext: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.placeholderColor,
    marginTop: MarginHW.MarginH1,
  },
  discountValueText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.tint,
    marginRight: MarginHW.MarginW10,
  },
  customSwitchContainer: {
    width: ImageSize.ImageW50,
    height: ImageSize.ImageH26,
    borderRadius: ImageSize.ImageH26 / 2,
    padding: 2,
    justifyContent: 'center',
  },
  customSwitchKnob: {
    width: ImageSize.ImageW22,
    height: ImageSize.ImageH22,
    borderRadius: ImageSize.ImageH22 / 2,
    backgroundColor: Colors.white,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  secureBannerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH2,
  },
  secureBannerLockIcon: {
    width: 12,
    height: 12,
    tintColor: '#5B665F',
    marginRight: 4,
  },
  secureBannerText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: '#5B665F',
  },

  footerContainer: {
    paddingHorizontal: MarginHW.PaddingW20,
    paddingBottom: MarginHW.PaddingH10,
  },
  payButton: {
    backgroundColor: Colors.continue,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.btnShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
    position: 'relative',
    paddingVertical: MarginHW.PaddingH8,
  },
  payTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  payLockIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW6,
  },
  payButtonText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.white,
  },
  payButtonSubtext: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.glassBorder,
    marginTop: MarginHW.MarginH2,
  },
  payArrow: {
    position: 'absolute',
    right: MarginHW.MarginW20,
    width: ImageSize.ImageH20,
    height: ImageSize.ImageH20,
    tintColor: Colors.white,
  },
  upiText: {
    fontFamily: fonts.OpenSans_ExtraBold,
    fontSize: FontsSize.size10,
    color: Colors.upiGreen,
    fontStyle: 'italic',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  amountBadgeCheck: {
    width: 8,
    height: 5,
    borderLeftWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: Colors.white,
    transform: [{ rotate: '-45deg' }],
    marginTop: -1,
  },
  customAmountContainer: {
    marginHorizontal: MarginHW.MarginW16,
    marginTop: MarginHW.MarginH12,
    marginBottom: MarginHW.MarginH4,
  },
  customAmountInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.tint,
    borderRadius: 14,
    backgroundColor: Colors.white,
    paddingHorizontal: MarginHW.PaddingW12,
    height: HWSize.H_Height50,
  },
  customAmountCurrency: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.tint,
    marginRight: MarginHW.MarginW6,
  },
  customAmountInput: {
    flex: 1,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size15,
    color: Colors.textDark,
    paddingVertical: 0,
  },
  methodDetails: {
    flex: 1,
  },
  methodHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  applyPointsRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});
