import { StyleSheet, Dimensions } from 'react-native';
import fonts from '../../../comman/fonts';
import FontsSize from '../../../comman/FontsSize';
import { Colors } from '../../../comman/Colors';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FAFAFA',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginTop: 10,
        paddingTop: 16,
        paddingBottom: 10,
        backgroundColor: '#FAFAFA',
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    icon: {
        width: 18,
        height: 18,
        tintColor: '#111827',
    },
    scrollContent: {
        paddingBottom: 40,
    },
    heroSection: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    heroImageContainer: {
        width: 140,
        height: 200,
        borderRadius: 12,
        overflow: 'hidden',
        position: 'relative',
        marginRight: 16,
    },
    heroImage: {
        width: '100%',
        height: '100%',
    },
    tagBadge: {
        position: 'absolute',
        top: 8,
        left: 8,
        backgroundColor: '#0A5F35',
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 12,
    },
    tagText: {
        color: '#FFFFFF',
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
    },
    gpsBadge: {
        position: 'absolute',
        bottom: 8,
        left: 8,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 6,
        paddingVertical: 4,
        borderRadius: 4,
    },
    gpsIcon: {
        width: 12,
        height: 12,
        tintColor: '#FFFFFF',
        marginRight: 6,
    },
    gpsText: {
        color: '#FFFFFF',
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
    },
    heroInfo: {
        flex: 1,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    projectTitle: {
        flex: 1,
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginRight: 8,
    },
    featuredBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ECFDF5',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
    },
    featuredIcon: {
        width: 12,
        height: 12,
        tintColor: '#0A5F35',
        marginRight: 4,
    },
    featuredText: {
        color: '#0A5F35',
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_SemiBold,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    locationIcon: {
        width: 14,
        height: 14,
        tintColor: '#6B7280',
        marginRight: 6,
    },
    locationText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#111827',
    },
    projectDesc: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Regular,
        color: '#4B5563',
        marginBottom: 16,
        lineHeight: 18,
    },
    progressSection: {
        width: '100%',
    },
    treesHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    treesLeft: {
        flexDirection: 'row',
        alignItems: 'baseline',
    },
    treesIconMain: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
        marginRight: 6,
        alignSelf: 'center',
    },
    treesCount: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    treesGoal: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
    },
    progressPercent: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    treesLabelMain: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        marginBottom: 8,
        marginLeft: 22, // align with text
    },
    progressBarBg: {
        height: 6,
        backgroundColor: '#E5E7EB',
        borderRadius: 3,
        width: '100%',
    },
    progressBarFill: {
        height: 6,
        backgroundColor: '#0A5F35',
        borderRadius: 3,
    },
    keyStatsRow: {
        paddingHorizontal: 16,
        marginBottom: 20,
    },
    keyStatsColumnWrapper: {
        justifyContent: 'space-between',
    },
    keyStatBox: {
        width: (width - 32) / 4 - 6,
        flexDirection: 'column',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        paddingVertical: 8,
        paddingHorizontal: 2,
    },
    keyStatIconBg: {
        width: 28,
        height: 28,
        borderRadius: 8,
        backgroundColor: '#F6F7F2',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 6,
    },
    keyStatIcon: {
        width: 14,
        height: 14,
        tintColor: '#0A5F35',
    },
    keyStatTextCol: {
        alignItems: 'center',
        width: '100%',
    },
    keyStatValue: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        textAlign: 'center',
    },
    keyStatValueGreen: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        textAlign: 'center',
    },
    keyStatLabel: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7280',
        textAlign: 'center',
    },
    tabScroll: {
        marginBottom: 2,
    },
    tabItem: {
        paddingVertical: 12,
        marginRight: 24,
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    tabItemActive: {
        borderBottomColor: '#0A5F35',
    },
    tabText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#6B7280',
    },
    tabTextActive: {
        color: '#0A5F35',
    },
    tabDivider: {
        height: 1,
        backgroundColor: '#E5E7EB',
        width: '100%',
        marginBottom: 20,
    },
    sectionContainer: {
        paddingHorizontal: 16,
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 12,
    },
    aboutRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    aboutTextCol: {
        flex: 1,
        marginRight: 16,
    },
    aboutText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Regular,
        color: '#4B5563',
        lineHeight: 18,
        marginBottom: 8,
    },
    readMoreBtn: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    readMoreText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginRight: 4,
    },
    readMoreIcon: {
        width: 10,
        height: 10,
        tintColor: '#0A5F35',
    },
    quickFactsBox: {
        width: 145,
        backgroundColor: '#F6F7F2',
        borderRadius: 8,
        padding: 12,
        paddingVertical: 14,
    },
    factRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    factIcon: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
        marginRight: 8,
    },
    factLabel: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Regular,
        color: '#4B5563',
    },
    factValue: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginTop: 2,
    },
    impactCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    impactCardTitle: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 16,
    },
    impactGrid: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    impactBox: {
        alignItems: 'center',
        flex: 1,
    },
    impactIconCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F0FDF4',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    impactIcon: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
    },
    impactValue: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        textAlign: 'center',
        marginBottom: 2,
    },
    impactLabel: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7280',
        textAlign: 'center',
    },
    impactDivider: {
        width: 1,
        height: 40,
        backgroundColor: '#F3F4F6',
    },
    progressRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    gaugeContainer: {
        width: 100,
        height: 100,
        marginRight: 16,
        justifyContent: 'center',
        alignItems: 'center',
        // placeholder for actual circular gauge chart
        borderRadius: 50,
        borderWidth: 8,
        borderColor: '#0A5F35',
        borderLeftColor: '#E5E7EB', // simulated incomplete part
        transform: [{ rotate: '45deg' }],
    },
    gaugeCircle: {
        width: 84,
        height: 84,
        borderRadius: 42,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        transform: [{ rotate: '-45deg' }],
    },
    gaugeValue: {
        fontSize: 18,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    gaugeLabel: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#111827',
    },
    stepsContainer: {
        width: 190,
        marginRight: 16,
    },
    stepRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    stepIconBox: {
        width: 20,
        alignItems: 'center',
        marginRight: 8,
    },
    stepCheckIcon: {
        width: 14,
        height: 14,
        tintColor: '#0A5F35',
        marginTop: 2,
    },
    stepPendingIcon: {
        width: 14,
        height: 14,
        tintColor: '#9CA3AF',
        marginTop: 2,
    },
    stepTextCol: {
        flex: 1,
    },
    stepTitle: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 2,
    },
    stepTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    stepStatusRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    stepCheckSmall: {
        width: 12,
        height: 12,
        tintColor: '#0A5F35',
        marginRight: 4,
    },
    stepStatusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 4,
    },
    stepStatus: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#9CA3AF',
    },
    stepProgressBar: {
        flex: 1,
        height: 4,
        backgroundColor: '#E5E7EB',
        borderRadius: 2,
        marginRight: 8,
    },
    stepProgressFill: {
        height: 4,
        backgroundColor: '#0A5F35',
        borderRadius: 2,
    },
    progressStatsBox: {
        backgroundColor: '#F6F7F2',
        borderRadius: 8,
        padding: 16,
        borderWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    pStatCol: {
        flex: 1,
        alignItems: 'center',
    },
    pStatLabel: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        marginBottom: 2,
    },
    pStatValueLarge: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    pStatSub: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Regular,
        color: '#4B5563',
    },
    pStatDivider: {
        width: 1,
        height: '80%',
        backgroundColor: '#E5E7EB',
        marginHorizontal: 12,
    },
    pStatValueMedium: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    pStatRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    infoIcon: {
        width: 14,
        height: 14,
        tintColor: '#6B7280',
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    viewAllBtn: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    viewAllText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginRight: 4,
    },
    viewAllArrow: {
        fontSize: 14,
        color: '#0A5F35',
    },
    galleryScroll: {
        paddingRight: 16, // margin is handled by item
    },
    galleryCard: {
        width: 120,
        height: 80,
        borderRadius: 8,
        overflow: 'hidden',
        marginRight: 12,
        position: 'relative',
    },
    galleryImg: {
        width: '100%',
        height: '100%',
    },
    galleryLabelBg: {
        position: 'absolute',
        bottom: 6,
        left: 6,
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    galleryLabel: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    locationCard: {
        flexDirection: 'row',
        alignItems: 'stretch',
    },
    mapPlaceholder: {
        flex: 1,
        height: 'auto',
        minHeight: 120,
        borderRadius: 8,
        marginRight: 12,
    },
    locationDetailsBox: {
        flex: 1.5,
        backgroundColor: '#F6F7F2',
        borderRadius: 8,
        padding: 12,
    },
    locTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    locIconCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F0FDF4',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    locIcon: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
    },
    locTitle: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginBottom: 2,
    },
    locCoords: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Regular,
        color: '#4B5563',
    },
    locBtnsRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    locBtnOutline: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#0A5F35',
        borderRadius: 6,
        paddingVertical: 6,
        marginRight: 8,
    },
    locBtnIcon: {
        width: 12,
        height: 12,
        tintColor: '#0A5F35',
        marginRight: 4,
    },
    locBtnText: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#0A5F35',
    },
    supportCard: {
        flexDirection: 'row',
        backgroundColor: '#F6F7F2',
        marginHorizontal: 16,
        borderRadius: 10,
        padding: 16,
        marginBottom: 24,
        alignItems: 'center',
    },
    supportInfo: {
        flex: 1,
        marginRight: 16,
    },
    supportTitle: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 4,
    },
    supportDesc: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Regular,
        color: '#4B5563',
        marginBottom: 12,
    },
    supportBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#0A5F35',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 8,
        alignSelf: 'flex-start',
    },
    supportBtnIcon: {
        width: 14,
        height: 14,
        tintColor: '#FFFFFF',
        marginRight: 8,
    },
    supportBtnText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
    },
    supportImg: {
        width: 80,
        height: 80,
    },
    receiveSection: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 24,
    },
    receiveTitle: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 16,
    },
    receiveList: {
    },
    receiveRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    receiveCheckCircle: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#F0FDF4',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    receiveCheck: {
        width: 10,
        height: 10,
        tintColor: '#0A5F35',
    },
    receiveText: {
        fontSize: 13,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
    },
    trustBadgesRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 8,
        paddingVertical: 12,
        backgroundColor: '#F9FAFB',
        borderRadius: 8,
        marginHorizontal: 16,
        marginBottom: 24,
    },
    trustBadge: {
        width: '32%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 2,
    },
    trustDivider: {
        width: 1,
        height: '60%',
        backgroundColor: '#E5E7EB',
        marginHorizontal: 4,
    },
    trustIcon: {
        width: 14,
        height: 14,
        tintColor: '#0A5F35',
        marginRight: 6,
    },
    trustText: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
        flexShrink: 1,
    },
});

export default styles;
