import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import fonts from '../../comman/fonts';
import MarginHW from '../../comman/MarginHW';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFBFB',
  },
  scrollContent: {
    paddingBottom: 20,
  },
  headerHeroBg: {
    width: '100%',
    height: 240,
  },
  heroImageRadius: {
    width: '100%',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW16,
    marginVertical: 15,
    backgroundColor: 'transparent',
  },
  headerLeftCol: {
    flex: 1,
    justifyContent: 'center',

  },
  backTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 36,
    height: 36,

    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  backIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.textDark,
  },
  titleRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginLeft: 10,
  },
  headerTitle: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  headerLeafIcon: {
    width: 18,
    height: 18,
    tintColor: Colors.legacyGreen,
    marginLeft: 4,
  },
  heroSubtitle: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Regular,
    color: '#4B5563',
  },
  headerRightCol: {
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButtonCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  // Custom drawn Share and Menu dots
  shareNodeContainer: {
    width: 14,
    height: 14,
    position: 'relative',
  },
  shareNodeCircle: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: Colors.textDark,
    position: 'absolute',
  },
  shareLine: {
    position: 'absolute',
    height: 1.5,
    backgroundColor: Colors.textDark,
    transform: [{ rotate: '30deg' }],
  },
  dotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dotItem: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.textDark,
    marginHorizontal: 1.5,
  },
  heroContentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: MarginHW.PaddingW10,
  },
  heroSummaryCardContainer: {
    marginTop: 20,
    width: Dimensions.get('window').width / 1.8,
    marginRight: 10,
  },
  summaryCardInner: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 2,
  },
  heroDropletContainer: {
    flex: 0.7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroSaplingImg: {
    width: 100,
    height: 110,
    marginBottom: -10,
  },
  summaryLeftCol: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryTreeImgContainer: {

    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  summaryTreeImg: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
  },
  summaryRightCol: {
    flex: 1,
    marginLeft: 12,
  },
  summaryHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  summaryTreeName: {
    fontSize: 15,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  gpsVerifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 6,
  },
  gpsVerifiedIcon: {
    width: 12,
    height: 12,
    tintColor: '#1E6B46',
    marginRight: 3,
  },
  gpsVerifiedText: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.greenLight,
  },
  treeIdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  treeIdLabel: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#4B5563',
  },
  treeIdValue: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  copyIconContainer: {
    marginLeft: 6,
    padding: 2,
  },
  copyIcon: {
    width: 11,
    height: 11,
    tintColor: Colors.legacyGreen,
  },
  locationTextRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 5,
  },
  locationPinIcon: {
    width: 10,
    height: 10,
    tintColor: '#4B5563',
    marginRight: 4,
    marginTop: 2,
  },
  locationTextCol: {
    flexDirection: 'column',
  },
  locationText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#4B5563',
    lineHeight: 12,
  },
  scheduledPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.greenLight,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
    marginTop: 6,
  },
  scheduledPillIcon: {
    width: 10,
    height: 10,
    tintColor: '#FFFFFF',
    marginRight: 4,
  },
  scheduledPillText: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
  },
  // Section layout
  sectionContainer: {
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    marginHorizontal: MarginHW.PaddingW10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.01,
    shadowRadius: 3,
    elevation: 1,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#276328',
  },
  sectionTitleLeaf: {
    width: 12,
    height: 12,
    tintColor: Colors.legacyGreen,
    marginLeft: 4,
  },
  // Stepper timeline
  progressStepperContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 5,
  },
  progressStepperLine: {
    position: 'absolute',
    left: '6%',
    right: '6%',
    top: 20,
    height: 2,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    zIndex: 0,
  },
  progressStepperLineActive: {
    position: 'absolute',
    left: '6%',
    width: '33.3%',
    top: 20,
    height: 3,
    backgroundColor: Colors.legacyGreen,
    zIndex: 0.5,
  },
  progressStepItem: {
    alignItems: 'center',
    flex: 1,
    zIndex: 1,
  },
  progressStepOuterCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  progressStepOuterCircleCompleted: {
    borderColor: Colors.legacyGreen,
  },
  progressStepInnerCircleCompleted: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.legacyGreen,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressStepIcon: {
    width: 14,
    height: 14,
    tintColor: '#4B5563',
  },
  progressStepIconCompleted: {
    width: 11,
    height: 11,
    tintColor: '#FFFFFF',
  },
  stepCheckmarkBadge: {
    position: 'absolute',
    bottom: -3,
    right: -3,
    backgroundColor: Colors.legacyGreen,
    width: 12,
    height: 12,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  stepCheckmarkBadgeIcon: {
    width: 7,
    height: 7,
    tintColor: '#FFFFFF',
  },
  progressStepLabel: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: '#4B5563',
    marginTop: 6,
    textAlign: 'center',
    lineHeight: 9.5,
  },
  progressStepLabelActive: {
    color: Colors.legacyGreen,
  },
  progressStepDate: {
    fontSize: 7,
    fontFamily: fonts.OpenSans_Regular,
    color: '#9CA3AF',
    marginTop: 2.5,
  },
  progressStepDateCompleted: {
    color: '#6B7280',
  },
  // Two Column row
  twoColumnRow: {
    flexDirection: 'row',
    marginTop: 15,
  },
  columnLeft: {
    flex: 1,
  },
  columnRight: {
    flex: 1.3,
  },
  // Map Location Box
  mapContainer: {
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    height: 140,
    position: 'relative',
  },
  mapImage: {
    width: '100%',
    height: '100%',
  },
  mapOverlayLabel: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderWidth: 0.5,
    borderColor: '#E5E7EB',
  },
  mapOverlayLabelText: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  expandButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  expandLinesContainer: {
    width: 10,
    height: 10,
    justifyContent: 'space-between',
  },
  expandRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  expandDot: {
    width: 2,
    height: 2,
    backgroundColor: '#4B5563',
  },
  latLongRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAFBFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    paddingVertical: 8,
    marginTop: 10,
  },
  latLongCol: {
    flex: 1,
    alignItems: 'center',
  },
  latLongLabel: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#9CA3AF',
  },
  latLongValue: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    marginTop: 1,
  },
  latLongDivider: {
    width: 1,
    height: 24,
    backgroundColor: '#E5E7EB',
  },
  viewMapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.legacyGreen,
    borderRadius: 8,
    paddingVertical: 7,
    marginTop: 12,
  },
  viewMapButtonIcon: {
    width: 11,
    height: 11,
    tintColor: Colors.legacyGreen,
    marginRight: 4,
  },
  viewMapButtonText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorGreenDark,
  },
  // Growth Stages horizontal row
  growthStageScroll: {
    paddingBottom: 2,
  },
  growthStageCard: {
    width: 60,
    height: 80,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#EFF2F0',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 6,
    paddingVertical: 6,
    paddingHorizontal: 2,
  },
  growthStageCardActive: {
    borderColor: Colors.legacyGreen,
    backgroundColor: '#F4F9F6',
  },
  growthStageHeader: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#6B7280',
    textAlign: 'center',
  },
  growthStageHeaderActive: {
    color: Colors.legacyGreen,
  },
  growthStageImage: {
    width: 22,
    height: 22,
  },
  growthStageStatus: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 8,
  },
  growthStageStatusActive: {
    color: Colors.legacyGreen,
  },
  // Environmental grid
  impactScrollContent: {
    paddingBottom: 2,
    paddingTop: 4,
  },
  impactCard: {
    width: 74,
    minHeight: 70,
    backgroundColor: '#F7F9F6',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EAF0EB',
    paddingVertical: 8,
    paddingHorizontal: 4,
    marginRight: 8,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  impactIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EEF6F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  impactIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.legacyGreen,
  },
  impactIconBlueBg: {
    backgroundColor: '#EBF5FF',
  },
  impactIconBlue: {
    tintColor: '#2563EB',
  },
  impactTextCol: {
    alignItems: 'center',
  },
  impactValue: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    textAlign: 'center',
  },
  impactLabel: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
    marginTop: 1,
    textAlign: 'center',
  },
  // Timeline Updates styling
  timelineContainer: {
    flexDirection: 'column',
    position: 'relative',
  },
  timelineLine: {
    position: 'absolute',
    left: 11,
    top: 10,
    bottom: 10,
    width: 1.5,
    backgroundColor: '#EFF3F0',
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    position: 'relative',
  },
  timelineNode: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    zIndex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
  },
  timelineNodeActive: {
    borderColor: Colors.TextColorGreenDark,
    backgroundColor: Colors.TextColorGreenDark,
  },
  timelineNodeIcon: {
    width: 11,
    height: 11,
    tintColor: '#FFFFFF',
  },
  timelineContent: {
    flex: 1,
    marginLeft: 8,
    marginRight: 6,
  },
  timelineDate: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  timelineDesc: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Medium,
    color: '#4B5563',
    marginTop: 2,
    lineHeight: 10,
  },
  timelineImage: {
    width: 68,
    height: 48,
    borderRadius: 8,
  },
  viewAllUpdatesButton: {
    borderWidth: 1,
    borderColor: Colors.greenLight,
    borderRadius: 8,
    paddingVertical: 7,
    alignItems: 'center',
    marginTop: 6,
  },
  viewAllUpdatesText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorGreenDark,
  },
  // Documents
  docItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EFF2F0',
    padding: 8,
    marginBottom: 6,
  },
  docLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  docIconBg: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#EEF6F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  docIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.TextColorGreenDark,
  },
  docTextCol: {
    flex: 1,
  },
  docTitle: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  docDesc: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7280',
    marginTop: 1,
  },
  comingSoonBadge: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  comingSoonText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: '#6B7280',
  },
  downloadBadge: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: Colors.TextColorGreenDark,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  downloadText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorGreenDark,
  },
  downloadIconCustomContainer: {
    width: 10,
    height: 11,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4,
  },
  downloadIconShaft: {
    width: 1.5,
    height: 6,
    backgroundColor: Colors.TextColorGreenDark,
  },
  downloadIconArrowhead: {
    width: 5,
    height: 5,
    borderBottomWidth: 1.5,
    borderLeftWidth: 1.5,
    borderColor: Colors.TextColorGreenDark,
    transform: [{ rotate: '-45deg' }],
    marginTop: -3,
    marginBottom: 1,
  },
  downloadIconTray: {
    width: 9,
    height: 1.5,
    backgroundColor: Colors.TextColorGreenDark,
  },
  // Share
  shareRowScroll: {
    paddingBottom: 2,
    paddingTop: 4,
  },
  shareItem: {
    width: 58,
    height: 58,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  shareIcon: {
    width: 20,
    height: 20,
  },
  shareMoreDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 20,
  },
  shareLabel: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    marginTop: 4,
    textAlign: 'center',
  },
  // Bottom Sticky row
  bottomStickyContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderColor: '#E5E7EB',
  },
  stickyButtonLeft: {
    flex: 1.3,
    height: 38,
    backgroundColor: Colors.TextColorGreenDark,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
    position: 'relative',
  },
  stickyButtonLeftIcon: {
    width: 14,
    height: 14,
    tintColor: '#FFFFFF',
    marginRight: 6,
  },
  stickyButtonLeftText: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
  },
  stickyButtonLeftArrow: {
    fontSize: 12,
    color: '#FFFFFF',
    position: 'absolute',
    right: 12,
    fontWeight: 'bold',
  },
  stickyButtonRight: {
    flex: 1,
    height: 38,
    borderWidth: 1,
    borderColor: Colors.legacyGreen,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
  },
  stickyButtonRightIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.TextColorLightGreen,
    marginRight: 6,
  },
  stickyButtonRightText: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
  },
  // Tab Bar
  tabBarContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderColor: '#ECEFEF',
    paddingVertical: 6,
    height: 52,
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIcon: {
    width: 18,
    height: 18,
    tintColor: '#8E9A93',
  },
  tabIconActive: {
    tintColor: Colors.legacyGreen,
  },
  tabLabel: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#8E9A93',
    marginTop: 2,
  },
  tabLabelActive: {
    color: Colors.legacyGreen,
  },
});
