import { StyleSheet } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';
import fonts from '../../comman/fonts';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  scrollContainer: {
    paddingBottom: MarginHW.PaddingH10,
  },

  heroCard: {
    marginHorizontal: 0,
    overflow: 'hidden',
  },
  heroImage: {
    width: '100%',
    height: HWSize.H_Height168,
    justifyContent: 'center',
  },
  heroImageRadius: {
    width: '100%',
    left: 0,
  },
  heroOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  heroContent: {
    flex: 1,
    paddingHorizontal: MarginHW.PaddingW20,
    justifyContent: 'center',
  },
  heroTextContainer: {
    width: '60%',
  },
  heroTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size20,
    lineHeight: 24,
    color: Colors.textDark,
  },
  heroSubtitle: {
    marginTop: MarginHW.MarginH4,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    lineHeight: FontsSize.size16,
    color: Colors.black,
  },
  highlightGreen: {
    color: Colors.tint,
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size20,
    lineHeight: 24,
  },
  sectionHeader: {
    marginHorizontal: MarginHW.MarginW16,
    marginTop: MarginHW.MarginH8,
    marginBottom: MarginHW.MarginH12,
  },
  sectionTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDark,
  },
  summaryCard: {
    marginTop: -20,
    backgroundColor: Colors.listBg,
    borderWidth: 1,
    borderColor: Colors.bannerBorder,
    borderRadius: 10,
    marginHorizontal: MarginHW.MarginW10,
    paddingVertical: MarginHW.PaddingH8,
    paddingHorizontal: MarginHW.PaddingW10,

  },
  summaryCardTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH8,
  },
  summaryRow: {
    flexDirection: 'row',
  },
  summaryCol1: {
    flex: 0.8,
    flexDirection: 'row',
  },
  summaryCol2: {
    flex: 1,
    flexDirection: 'row',
    marginHorizontal: 2,
  },
  summaryDivider2: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: Colors.dividerGreen,
  },
  summaryRowDivider: {
    height: 1,
    backgroundColor: Colors.dividerGreen,
    marginVertical: MarginHW.MarginH8,
  },
  summaryIconContainer: {
    width: ImageSize.ImageW32,
    height: ImageSize.ImageH32,
    borderRadius: ImageSize.ImageW32 / 2,
    backgroundColor: Colors.iconBgLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
  },
  summaryIcon: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
    tintColor: Colors.tint,
  },
  summaryTextContainer: {
    flex: 1,
    flexShrink: 1,

  },
  summaryLabel: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size12,
    color: Colors.textMuted,
    flexShrink: 1,
  },
  summaryValue: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size12,
    color: Colors.tint,
    marginTop: MarginHW.MarginH2,
    lineHeight: 16,
    flexShrink: 1,
  },
  formContainer: {
    // marginTop: MarginHW.MarginH4,
  },
  inputGroup: {
    marginBottom: MarginHW.MarginH8,
  },
  inputLabel: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDark,
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH8,
  },
  stayUpdatedLabel: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDark,
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH4,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.borderLight,
    borderRadius: 10,
    backgroundColor: Colors.white,
    paddingHorizontal: MarginHW.PaddingW12,
    marginHorizontal: MarginHW.MarginW16,

  },
  inputWrapperActive: {
    borderColor: Colors.tint,
  },
  inputIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.placeholderColor,
    marginRight: MarginHW.MarginW8,
  },
  textInput: {
    flex: 1,
    height: 42,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size13,
    color: Colors.textDark,
    paddingVertical: 0,
  },
  inputSubtext: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.placeholderColor,
    marginHorizontal: MarginHW.MarginW16,
    marginTop: MarginHW.MarginH5,
  },
  textAreaWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderWidth: 1.5,
    borderColor: Colors.borderLight,
    borderRadius: 14,
    backgroundColor: Colors.white,
    paddingHorizontal: MarginHW.PaddingW12,
    paddingVertical: MarginHW.PaddingH10,
    marginHorizontal: MarginHW.MarginW16,
    height: HWSize.H_Height95,
  },
  textAreaWrapperActive: {
    borderColor: Colors.tint,
  },
  textAreaIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.placeholderColor,
    marginRight: MarginHW.MarginW8,
    marginTop: MarginHW.MarginH2,
  },
  textAreaInput: {
    flex: 1,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size13,
    color: Colors.textDark,
    height: '100%',
    textAlignVertical: 'top',
    paddingVertical: 0,
  },
  charCountText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.placeholderColor,
    alignSelf: 'flex-end',
    marginRight: MarginHW.MarginW16,
    marginTop: MarginHW.MarginH4,
  },
  stayUpdatedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.borderLight,
    borderRadius: 10,
    padding: MarginHW.PaddingW12,
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  stayUpdatedLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingRight: MarginHW.PaddingW12,
  },
  bellIconContainer: {
    width: 38,
    height: 38,
    borderRadius: 38 / 2,
    backgroundColor: Colors.badgeGreenBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW12,
  },
  bellIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.tint,
  },
  stayUpdatedText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: Colors.textMuted,
    lineHeight: FontsSize.size16,
    flex: 1,
  },
  customSwitchContainer: {
    width: ImageSize.ImageW50,
    height: ImageSize.ImageH26,
    borderRadius: ImageSize.ImageH26 / 2,
    padding: 2,
    justifyContent: 'center',
  },
  customSwitchKnob: {
    width: ImageSize.ImageW22,
    height: ImageSize.ImageH22,
    borderRadius: ImageSize.ImageH22 / 2,
    backgroundColor: Colors.white,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  bannerCard: {
    backgroundColor: Colors.bgGreenLight,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    marginHorizontal: MarginHW.MarginW16,
    marginTop: MarginHW.MarginH1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  bannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingLeft: MarginHW.PaddingW14,
    paddingRight: MarginHW.PaddingW10,
  },
  bannerShieldContainer: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW12,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
  },
  bannerShieldIcon: {
    width: ImageSize.ImageH20,
    height: ImageSize.ImageH20,
    tintColor: Colors.shieldIconColor,
  },
  bannerTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  bannerText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDark,
    lineHeight: FontsSize.size16,
    marginBottom: MarginHW.MarginH2,
  },
  bannerTextSecondary: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size12,
    color: Colors.textDark,
    lineHeight: FontsSize.size16,
  },

  bannerHandImage: {
    width: 70,
    height: 70,
  },
  footerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW20,
    paddingBottom: MarginHW.PaddingH10,
  },
  continueButton: {
    flex: 1,
    marginTop: 10,
    backgroundColor: Colors.continue,
    paddingVertical: MarginHW.PaddingH12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    shadowColor: Colors.btnShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  continueText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.white,
  },
  continueArrow: {
    position: 'absolute',
    right: MarginHW.MarginW20,
    width: ImageSize.ImageH20,
    height: ImageSize.ImageH20,
    tintColor: Colors.white,
  },
});
