import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../../../comman/Colors';
import FontsSize from '../../../../comman/FontsSize';
import fonts from '../../../../comman/fonts';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFBFB',
  },
  safeArea: {
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 32,
  },
  // Stepper Progress Indicators
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 10,
    backgroundColor: 'transparent',
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#ECEFEF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  backIcon: {
    width: 18,
    height: 18,
    tintColor: '#000000',
  },
  stepperContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: 16,
  },
  stepItem: {
    alignItems: 'center',
    flex: 1,
  },
  stepIndicator: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  stepIndicatorActive: {
    borderColor: '#0A5F35',
    backgroundColor: '#0A5F35',
  },
  stepIndicatorCompleted: {
    borderColor: '#0A5F35',
    backgroundColor: '#FFFFFF',
  },
  stepText: {
    fontSize: 11,
    fontFamily: fonts.OpenSans_Bold,
    color: '#94A3B8',
  },
  stepTextActive: {
    color: '#FFFFFF',
  },
  stepTextCompleted: {
    color: '#0A5F35',
  },
  stepLabel: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#64748B',
    marginTop: 4,
  },
  stepLabelActive: {
    color: '#0F172A',
    fontFamily: fonts.OpenSans_Bold,
  },
  stepLineLeft: {
    position: 'absolute',
    top: 13,
    left: '12.5%',
    right: '50%',
    height: 1.5,
    backgroundColor: '#0A5F35',
    zIndex: 1,
  },
  stepLineRight: {
    position: 'absolute',
    top: 13,
    left: '50%',
    right: '12.5%',
    height: 1.5,
    backgroundColor: '#E2E8F0',
    zIndex: 1,
  },
  // Hero Section
  heroImageBg: {
    width: '100%',
    minHeight: 220,
    backgroundColor: '#FFFFFF',
  },
  heroContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  heroTextSection: {
    flex: 1.25,
    paddingRight: 8,
  },
  heroTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroTitle: {
    fontSize: 32,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },
  heroLeafIcon: {
    width: 24,
    height: 24,
    marginLeft: 6,
    tintColor: '#0A5F35',
  },
  heroDescTitle: {
    fontSize: 15,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0F172A',
    marginTop: 4,
  },
  heroDesc: {
    fontSize: 11.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#000',
    marginTop: 4,
    lineHeight: 16,
  },
  infoPillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6F1',
    borderColor: '#E6F4ED',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5.5,
    alignSelf: 'flex-start',
    marginTop: 10,
  },
  infoPillIconContainer: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#0A5F35',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },
  infoPillIconText: {
    color: '#FFFFFF',
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
  },
  infoPillText: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },
  heroRightSpacer: {
    flex: 0.95,
  },
  // Main Questions Area
  questionsSection: {
    paddingHorizontal: 16,
    marginTop: -5,
  },
  // Question Card
  questionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#EEF2EF',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 3,
    elevation: 1.5,
  },
  questionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#EFF6F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  questionHeaderIcon: {
    width: 18,
    height: 18,
    tintColor: '#0A5F35',
  },
  questionTextContainer: {
    flex: 1,
  },
  questionTitle: {
    fontSize: 12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A1C14',
  },
  questionSubtitle: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
    marginTop: 1.5,
  },
  questionInfoButton: {
    padding: 4,
  },
  questionInfoIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.2,
    borderColor: '#8E9A93',
    justifyContent: 'center',
    alignItems: 'center',
  },
  questionInfoIconText: {
    fontSize: 9,
    color: '#8E9A93',
    fontFamily: fonts.OpenSans_Bold,
  },
  // 4 Option Diet Grid Row
  optionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dietOptionBox: {
    width: '23.8%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  dietOptionBoxSelected: {
    borderColor: '#0D684D',
    backgroundColor: '#EFF6F1',
  },
  dietOptionEmoji: {
    fontSize: 12,
    marginRight: 3,
  },
  dietOptionText: {
    fontSize: 8.2,
    fontFamily: fonts.OpenSans_Bold,
    color: '#44554C',
  },
  dietOptionTextSelected: {
    color: '#0D684D',
  },
  // Regular Option Row Box (Meals / Meat / Local)
  optionBox: {
    width: '23.8%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    paddingHorizontal: 2,
  },
  optionBoxSelected: {
    borderColor: '#0D684D',
    backgroundColor: '#EFF6F1',
  },
  optionBoxText: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#44554C',
    textAlign: 'center',
  },
  optionBoxTextSelected: {
    color: '#0D684D',
  },
  // Table style frequencies (Question 3)
  freqRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 6,
  },
  freqRowLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '35%',
  },
  freqRowEmoji: {
    fontSize: 14,
    marginRight: 6,
  },
  freqRowLabelText: {
    fontSize: 10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#44554C',
  },
  freqRowSegments: {
    flexDirection: 'row',
    width: '63%',
    justifyContent: 'space-between',
  },
  freqSegmentBox: {
    flex: 1,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 1.5,
  },
  freqSegmentBoxSelected: {
    borderColor: '#0D684D',
    backgroundColor: '#EFF6F1',
  },
  freqSegmentText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: '#44554C',
  },
  freqSegmentTextSelected: {
    color: '#0D684D',
  },
  // 5 option local sourcing boxes
  localOptionBox: {
    width: '18.5%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    paddingHorizontal: 2,
  },
  // Estimated Emissions Card
  emissionsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F3F9F5',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E6F4ED',
    paddingHorizontal: 12,
    paddingVertical: 14,
    marginBottom: 16,
  },
  emissionsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.25,
    marginRight: 8,
  },
  emissionsIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EFF6F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  emissionsIcon: {
    width: 16,
    height: 16,
    tintColor: '#0A5F35',
  },
  emissionsTextContainer: {
    flex: 1,
  },
  emissionsLabel: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#44554C',
  },
  emissionsValue: {
    fontSize: 16.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
    marginTop: 2,
  },
  emissionsSub: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
    marginTop: 2,
  },
  seeCalcButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#0A5F35',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
  },
  seeCalcIcon: {
    width: 12,
    height: 12,
    tintColor: '#0A5F35',
    marginRight: 5,
  },
  seeCalcText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },
  // Did you know Card
  didYouKnowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEF2EF',
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 24,
  },
  didYouKnowIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EFF6F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  didYouKnowIcon: {
    width: 16,
    height: 16,
    tintColor: '#0A5F35',
  },
  didYouKnowTextContainer: {
    flex: 1,
    marginRight: 8,
  },
  didYouKnowTitle: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0F172A',
  },
  didYouKnowDesc: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Regular,
    color: '#475569',
    marginTop: 2,
    lineHeight: 12,
  },
  didYouKnowBowlImage: {
    width: 50,
    height: 40,
  },
  // Save & Continue Button
  saveButton: {
    backgroundColor: '#0A5F35',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 8,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 14.5,
    fontFamily: fonts.OpenSans_Bold,
  },
});
