import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';
import { Colors } from '../../../comman/Colors';
import FontsSize from '../../../comman/FontsSize';
import fonts from '../../../comman/fonts';
import MarginHW from '../../../comman/MarginHW';
import ImageSize from '../../../comman/ImageSize';
import HWSize from '../../../comman/HWSize';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  scrollContent: {
    paddingBottom: MarginHW.PaddingH10,
  },

  // Header Styles
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW10,
    paddingTop: MarginHW.PaddingH8,
    paddingBottom: MarginHW.PaddingH10,
    minHeight: HWSize.H_Height64,
  },
  backButton: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH35,
    borderRadius: ImageSize.ImageW18,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
  },
  backIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.textDark,
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: MarginHW.PaddingW4,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  headerCheckIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.shieldIconColor,
    marginLeft: MarginHW.MarginW4,
  },
  headerSubtitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: MarginHW.MarginH2,
    textAlign: 'center',
  },
  headerRightSecure: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size10,
    paddingVertical: MarginHW.PaddingH5,
    paddingHorizontal: MarginHW.PaddingW8,
  },
  headerSecureIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.shieldIconColor,
    marginRight: MarginHW.MarginW6,
  },
  headerSecureTextCol: {
    justifyContent: 'center',
  },
  headerSecureTextBold: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    lineHeight: 11,
  },
  headerSecureTextDesc: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    lineHeight: 11,
  },

  // Alert Banner
  alertBanner: {
    flexDirection: 'row',
    backgroundColor: Colors.bannerBgGreen,
    borderColor: Colors.bannerBorderGreen,
    borderWidth: 1,
    borderRadius: FontsSize.size12,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH4,
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW10,
    alignItems: 'center',
  },
  alertIconContainer: {
    marginRight: MarginHW.MarginW10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  alertIcon: {
    width: ImageSize.ImageW32,
    height: ImageSize.ImageH32,
    tintColor: Colors.shieldIconColor,
  },
  alertTextContainer: {
    flex: 1,
  },
  alertTitle: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textGreenDark,
  },
  alertDesc: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.bannerBenefitLabel,
    lineHeight: 14,
  },
  floatingLeaves: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
    position: 'absolute',
    right: MarginHW.MarginW8,
    top: MarginHW.MarginH4,
    opacity: 0.7,
  },

  // Selected Project Card
  projectCard: {
    backgroundColor: Colors.white,
    borderRadius: FontsSize.size14,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH8,
    padding: MarginHW.PaddingH10,
    flexDirection: 'row',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
  },
  projectImageContainer: {
    width: ImageSize.ImageW80,
    height: ImageSize.ImageH80,
    borderRadius: FontsSize.size10,
    overflow: 'hidden',
    position: 'relative',
    marginRight: MarginHW.MarginW10,
  },
  projectImage: {
    width: '100%',
    height: '100%',
  },
  gpsBadge: {
    position: 'absolute',
    bottom: MarginHW.MarginH6,
    left: MarginHW.MarginW1,
    backgroundColor: 'rgba(10, 28, 20, 0.6)',
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW4,
    paddingVertical: MarginHW.MarginH2,
  },
  gpsIcon: {
    width: FontsSize.size11,
    height: FontsSize.size11,
    tintColor: Colors.white,
  },
  gpsText: {
    fontSize: FontsSize.size8_5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
  projectInfo: {
    flex: 1,
    justifyContent: 'space-between',
  },
  projectHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  projectName: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginRight: MarginHW.MarginW6,
  },
  badge: {
    backgroundColor: Colors.bgGreenLight,
    borderRadius: 4,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: MarginHW.MarginH2,
  },
  badgeText: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.secondary_button,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH2,
  },
  locationIcon: {
    width: ImageSize.ImageW9,
    height: ImageSize.ImageH9,
    tintColor: Colors.textLabelGrey,
    marginRight: MarginHW.MarginW4,
  },
  locationText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Medium,
    color: Colors.textLabelGrey,
  },
  projectDesc: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.bannerBenefitLabel,
    marginVertical: MarginHW.MarginH4,
    lineHeight: 14,
  },
  progressWrapper: {
    marginTop: MarginHW.MarginH4,
  },
  progressLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH4,
  },
  progressLabelText: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textGreenDark,
  },
  progressLabelNormal: {
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.bannerBenefitLabel,
  },
  progressPercentText: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textGreenDark,
  },
  progressBarTrack: {
    height: MarginHW.MarginH5,
    backgroundColor: Colors.borderGreenUltraLight,
    borderRadius: 2.5,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: Colors.upiGreen,
    borderRadius: 2.5,
  },

  // Impact Preview
  sectionHeader: {
    marginTop: MarginHW.MarginH16,
    marginHorizontal: MarginHW.MarginW10,
  },
  sectionTitle: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.legacyGreen,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH10,
    marginBottom: MarginHW.MarginH4,
  },
  impactPreviewCard: {
    backgroundColor: Colors.white,
    borderRadius: FontsSize.size14,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH8,
    paddingVertical: MarginHW.PaddingH8,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
  },
  impactRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW8,
  },
  impactColumn: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: MarginHW.MarginW2,
  },
  impactIconCircle: {
    width: ImageSize.ImageW32,
    height: ImageSize.ImageH32,
    borderRadius: ImageSize.ImageW16,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH6,
  },
  impactIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.shieldIconColor,
  },
  impactValue: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textGreenDark,
    textAlign: 'center',
  },
  impactLabel: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: MarginHW.MarginH2,
  },
  impactDivider: {
    width: 1,
    backgroundColor: Colors.borderGreenUltraLight,
    height: '75%',
    alignSelf: 'center',
  },
  impactBannerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.bannerBgGreen,
    borderRadius: FontsSize.size8,
    marginHorizontal: MarginHW.MarginW8,
    marginTop: MarginHW.MarginH12,
    paddingVertical: MarginHW.PaddingH6,
    paddingHorizontal: MarginHW.PaddingW10,
    borderWidth: 0.5,
    borderColor: Colors.borderGreenLight,
  },
  impactBannerIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.shieldIconColor,
    marginRight: MarginHW.MarginW6,
  },
  impactBannerText: {
    flex: 1,
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Medium,
    color: Colors.textGreenDark,
  },

  // Side by Side Row Layout
  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH12,
  },
  gridCol: {
    flex: 1,
  },
  gridColGap: {
    width: MarginHW.MarginW10,
  },
  columnCard: {
    backgroundColor: Colors.white,
    borderRadius: FontsSize.size14,
    padding: MarginHW.PaddingH10,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH12,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
  },
  columnTitle: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH10,
  },

  // Order Summary items
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: MarginHW.MarginH3,
  },
  summaryLabelText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    flex: 1,
  },
  summaryValueText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
    textAlign: 'right',
    flex: 1.5,
  },
  infoIcon: {
    width: ImageSize.ImageW9,
    height: ImageSize.ImageH9,
    tintColor: Colors.textLabelGrey,
    marginLeft: MarginHW.MarginW4,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.borderGreenUltraLight,
    marginVertical: MarginHW.MarginH4,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: MarginHW.MarginH2,
  },
  totalLabelText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  totalValueText: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.upiGreen,
  },
  taxBenefitCard: {
    backgroundColor: Colors.bannerBgGreen,
    borderColor: Colors.bannerBorderGreen,
    borderWidth: 1,
    borderRadius: FontsSize.size8,
    padding: MarginHW.MarginH4,
    marginTop: MarginHW.MarginH6,
    flexDirection: 'row',
  },
  taxBenefitIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.shieldIconColor,
    marginRight: MarginHW.MarginW6,
    marginTop: MarginHW.MarginH2,
  },
  taxBenefitTextCol: {
    flex: 1,
  },
  taxBenefitTextBold: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textGreenDark,
  },
  taxBenefitTextDesc: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.bannerBenefitLabel,
    marginTop: MarginHW.MarginH1,
  },
  taxBenefitLink: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.secondary_button,
    marginTop: MarginHW.MarginH4,
  },

  // Payment Methods
  paymentMethodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
    borderRadius: FontsSize.size10,
    paddingVertical: MarginHW.MarginH5,
    paddingHorizontal: MarginHW.PaddingW10,
    marginBottom: MarginHW.MarginH6,
    backgroundColor: Colors.white,
  },
  paymentMethodRowSelected: {
    borderColor: Colors.upiGreen,
    backgroundColor: Colors.bannerBgGreen,
  },
  methodInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  methodIconCircle: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
  },
  methodLogoImg: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
  },
  methodTitle: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  methodDesc: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: MarginHW.MarginH1,
  },
  radioButtonOuter: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: Colors.switchInactiveBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonOuterSelected: {
    borderColor: Colors.upiGreen,
  },
  radioButtonInner: {
    width: ImageSize.ImageW9,
    height: ImageSize.ImageH9,
    borderRadius: 4,
    backgroundColor: Colors.upiGreen,
  },

  // Pay using Card block
  cardFormCard: {
    backgroundColor: Colors.white,
    borderRadius: FontsSize.size14,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH12,
    padding: MarginHW.PaddingH10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
  },
  cardFormHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH10,
  },
  cardFormTitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  cardLogosRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardLogoIcon: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH14,
    marginLeft: MarginHW.MarginW4,
  },
  formField: {
    marginBottom: MarginHW.MarginH10,
  },
  inputLabel: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textLabelGrey,
    marginBottom: MarginHW.MarginH4,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size8,
    paddingHorizontal: MarginHW.PaddingW8,
    backgroundColor: Colors.containerBg,
    height: 38,
  },
  textInput: {
    flex: 1,
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textDark,
    padding: 0,
  },
  inputCardIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.textLabelGrey,
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  formRowCol30: {
    width: '30%',
  },
  formRowCol35: {
    width: '35%',
  },
  saveCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH6,
  },
  checkboxSquare: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: Colors.switchInactiveBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW6,
  },
  checkboxSquareChecked: {
    borderColor: Colors.upiGreen,
    backgroundColor: Colors.upiGreen,
  },
  checkboxCheckIcon: {
    width: ImageSize.ImageW9,
    height: ImageSize.ImageH9,
    tintColor: Colors.white,
  },
  checkboxLabelCol: {
    flex: 1,
  },
  checkboxLabelText: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textGreenDark,
  },
  checkboxDescText: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: MarginHW.MarginH1,
  },

  // Encryption Security Info
  encryptionCard: {
    backgroundColor: Colors.bannerBgGreen,
    borderRadius: FontsSize.size8,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH10,
    padding: MarginHW.PaddingH8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: Colors.bannerBorderGreen,
  },
  encryptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.2,
  },
  lockCircle: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
    borderRadius: 12,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW6,
  },
  lockIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.shieldIconColor,
  },
  encryptionTextCol: {
    flex: 1,
  },
  encryptionTitle: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textGreenDark,
  },
  encryptionDesc: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.footertextgray,
    marginTop: MarginHW.MarginH1,
  },
  partnerLogosRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-end',
  },
  partnerTextBadge: {
    borderWidth: 0.5,
    borderColor: Colors.switchInactiveBg,
    borderRadius: 3,
    paddingHorizontal: MarginHW.PaddingW4,
    paddingVertical: MarginHW.MarginH1,
    marginLeft: MarginHW.MarginW4,
    backgroundColor: Colors.white,
  },
  partnerTextLabel: {
    fontSize: FontsSize.size7,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textLabelGrey,
  },
  partnerLogoRazorpay: {
    fontSize: FontsSize.size7,
    fontFamily: fonts.OpenSans_ExtraBold,
    color: Colors.textGreenDark,
    fontStyle: 'italic',
    marginLeft: MarginHW.MarginW4,
  },
  bottomFloatingBar: {
    paddingVertical: MarginHW.PaddingH6,
    paddingHorizontal: MarginHW.PaddingW10,
  },
  bottomMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bottomLeftInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.2,
  },
  bottomThumbCircle: {
    width: ImageSize.ImageW32,
    height: ImageSize.ImageH32,
    borderRadius: ImageSize.ImageW16,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW6,
  },
  bottomThumbImg: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
  },
  bottomTextCol: {
    flex: 1,
  },
  bottomSupportingLabel: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  bottomProjectName: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  bottomAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH1,
  },
  bottomAmountLabel: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  bottomAmountVal: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.upiGreen,
    marginLeft: MarginHW.MarginW4,
  },
  bottomAmountQty: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginLeft: MarginHW.MarginW4,
  },
  bottomButtonBox: {
    flex: 1,
    alignItems: 'flex-end',
  },
  paySecurelyButton: {
    backgroundColor: Colors.upiGreen,
    borderRadius: FontsSize.size8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW10,
    width: '100%',
    maxWidth: HWSize.W_Width160,
  },
  payButtonLockIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.white,
  },
  payButtonText: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
  payButtonArrow: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
  bottomRedirectText: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'right',
    marginTop: MarginHW.MarginH4,
    paddingRight: MarginHW.PaddingW6,
  },
});
