import { Dimensions, StyleSheet } from 'react-native';
import { Colors } from '../../../comman/Colors';
import fonts from '../../../comman/fonts';
import FontsSize from '../../../comman/FontsSize';
import MarginHW from '../../../comman/MarginHW';
import ImageSize from '../../../comman/ImageSize';
import HWSize from '../../../comman/HWSize';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  scrollContainer: {
    paddingBottom: MarginHW.PaddingH8,
  },
  headerBackground: {
    paddingBottom: MarginHW.PaddingH35,
    width: '100%',

  },
  headerOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },

  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW16,
    marginTop: MarginHW.MarginH20,
    zIndex: 10,
  },
  backButton: {
    width: 30,
    height: 30,
    borderRadius: 30,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  backIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: '#111827',
  },
  headerTextContainer: {
    paddingHorizontal: MarginHW.PaddingW18,
    marginTop: 10,
    marginBottom: MarginHW.MarginH10,
    zIndex: 2,
  },
  headerTitle: {
    fontSize: FontsSize.size22,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.tintColorDrak,
    lineHeight: FontsSize.size28,
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowOffset: { width: 0, height: 1.5 },
    textShadowRadius: 3,
  },
  headerSubtitle: {
    fontSize: FontsSize.size15,
    fontFamily: fonts.OpenSans_Regular,
    color: '#fff',
    marginTop: MarginHW.MarginH8,
    lineHeight: FontsSize.size18,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  statsCardContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: -MarginHW.MarginH20,
    zIndex: 5,
  },
  statsCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    width: width - (MarginHW.MarginW16 * 2),
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW12,
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F2F4F3',
  },
  statColumn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  statIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EEF6F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },
  statTextCol: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: 1,
  },
  statIcon: {
    width: 20,
    height: 20,
  },
  statValue: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  statLabel: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7A70',
    marginTop: MarginHW.MarginH2,
  },
  statDivider: {
    width: 1,
    height: MarginHW.MarginH38,
    backgroundColor: '#E6ECE9',
  },
  mainContent: {
    paddingHorizontal: MarginHW.PaddingW16,
    marginTop: MarginHW.MarginH10,
  },
  sectionHeader: {
    marginBottom: MarginHW.MarginH10,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: FontsSize.size18,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  titleLeafIcon: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH20,
    marginLeft: MarginHW.MarginW6,
  },
  sectionSubtitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
  },
  projectCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    marginBottom: MarginHW.MarginH20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    overflow: 'hidden',
  },
  cardImage: {
    width: '100%',
    height: HWSize.H_Height120,
    justifyContent: 'space-between',
    padding: MarginHW.PaddingH12,
  },
  cardImageGradient: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
  },

  locationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    borderRadius: 20,
    paddingHorizontal: MarginHW.PaddingW8,
    paddingVertical: MarginHW.PaddingH5,
    alignSelf: 'flex-start',
    marginTop: 'auto',
  },
  locationBadgeIcon: {
    width: ImageSize.ImageW9,
    height: ImageSize.ImageH9,
    tintColor: '#FFFFFF',
    marginRight: MarginHW.MarginW4,
  },
  locationBadgeText: {
    color: '#FFFFFF',
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
  },
  heartButton: {
    position: 'absolute',
    top: MarginHW.MarginH12,
    right: MarginHW.MarginW12,
    width: ImageSize.ImageW32,
    height: ImageSize.ImageH32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  heartText: {
    fontSize: FontsSize.size18,
    color: '#6B7A70',
    lineHeight: FontsSize.size20,
  },
  heartTextSelected: {
    color: '#E03B3B',
  },
  cardContent: {
    padding: MarginHW.PaddingH16,
  },
  cardTitle: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  categoryTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF6F2',
    alignSelf: 'flex-start',
    borderRadius: 4,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: MarginHW.PaddingH3,
    marginTop: MarginHW.MarginH6,
  },
  categoryTagIcon: {
    width: ImageSize.ImageW9,
    height: ImageSize.ImageH9,
    tintColor: '#1E6B46',
    marginRight: MarginHW.MarginW4,
  },
  categoryTagText: {
    color: '#1E6B46',
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
  },
  cardDesc: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
    marginTop: MarginHW.MarginH10,
    lineHeight: FontsSize.size16,
  },
  specsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: MarginHW.MarginH14,
    paddingTop: MarginHW.PaddingH12,
    borderTopWidth: 1,
    borderTopColor: '#F2F4F3',
  },
  specItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  specIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    marginRight: MarginHW.MarginW4,
  },
  specText: {
    fontSize: FontsSize.size9_5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#22391f',
  },
  exploreButton: {
    backgroundColor: '#1E6B46',
    borderRadius: 8,
    paddingVertical: MarginHW.PaddingH12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: MarginHW.MarginH16,
  },
  exploreButtonText: {
    color: '#FFFFFF',
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    marginRight: MarginHW.MarginW6,
  },
  exploreButtonArrow: {
    color: '#FFFFFF',
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
  },
  horizontalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    marginBottom: MarginHW.MarginH16,
    flexDirection: 'row',
    padding: MarginHW.PaddingH10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  horizontalCardImageWrapper: {
    flex: 0.5,
    alignSelf: 'stretch',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#F3F4F6',
  },
  horizontalCardImage: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  horizontalLocationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    paddingHorizontal: MarginHW.PaddingW8,
    paddingVertical: MarginHW.PaddingH3,
    alignSelf: 'flex-start',
    marginBottom: MarginHW.MarginH6,
    marginRight: MarginHW.MarginH20,
    marginLeft: MarginHW.MarginW4
  },
  horizontalLocationBadgeIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: '#FFFFFF',
    marginRight: MarginHW.MarginW4,
  },
  horizontalLocationBadgeText: {
    color: '#FFFFFF',
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Bold,
  },
  horizontalCardContent: {
    flex: 1,
    marginLeft: MarginHW.MarginW12,
  },
  horizontalTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  horizontalCardTitle: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    flex: 1,
    marginRight: MarginHW.MarginW8,
  },
  horizontalHeartIcon: {
    width: 20,
    height: 20,
  },
  horizontalCategoryTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF5F0',
    alignSelf: 'flex-start',
    borderRadius: 6,
    paddingHorizontal: MarginHW.PaddingW8,
    paddingVertical: 1,
    marginTop: MarginHW.MarginH2,
  },
  horizontalCategoryTagIcon: {
    width: 10,
    height: 10,
    tintColor: '#056213',
    marginRight: MarginHW.MarginW4,
  },
  horizontalCategoryTagText: {
    color: '#056213',
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
  },
  horizontalCardDesc: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: '#4B5563',
    marginTop: MarginHW.MarginH6,
    lineHeight: FontsSize.size16,
  },
  horizontalDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: MarginHW.MarginH8,
  },
  horizontalSpecsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  horizontalSpecItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  horizontalSpecDivider: {
    width: 1,
    height: 18,
    backgroundColor: '#E6ECE9',
    marginHorizontal: 8,
  },
  horizontalSpecIcon: {
    width: 16,
    height: 16,
    tintColor: '#056213',
    marginRight: MarginHW.MarginW4,
  },
  horizontalSpecTextContainer: {
    flex: 1,
  },
  horizontalSpecValue: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Medium,
    color: '#111827',
    flexShrink: 1,
  },
  horizontalSpecLabel: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
    lineHeight: FontsSize.size10,
    flexShrink: 1,
  },
  horizontalExploreButton: {
    backgroundColor: '#056213',
    borderRadius: 6,
    paddingVertical: MarginHW.PaddingH3,
    paddingHorizontal: MarginHW.PaddingW12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: MarginHW.MarginH12,
  },
  horizontalExploreButtonText: {
    color: '#FFFFFF',
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    textAlign: 'center',
    flex: 1,
  },
  horizontalExploreButtonArrow: {
    color: '#FFFFFF',
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
  },
  whySection: {
    backgroundColor: '#f5f8ef',
    borderRadius: 16,
    padding: MarginHW.PaddingH10,
    borderWidth: 1,
    borderColor: '#EAEAEA',
  },
  whyHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  whyTitle: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  whyTitleLeaf: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH20,
    tintColor: Colors.tintColorDrak,
  },
  whyGrid: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginTop: MarginHW.MarginH3,
  },
  whyGridItem: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  whyDivider: {
    width: 1,
    height: 48,
    backgroundColor: '#E6ECE9',
    alignSelf: 'center',
  },
  whyIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EFF5F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH3,
  },
  whyGridIcon: {
    width: 20,
    height: 20,
    tintColor: '#056213',
  },
  whyItemTitle: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    textAlign: 'center',
  },
  whyItemDesc: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
    marginTop: MarginHW.MarginH2,
    lineHeight: FontsSize.size10,
    textAlign: 'center',
  },
  bottomBanner: {
    marginVertical: 15,
    backgroundColor: '#056213',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: MarginHW.PaddingH10,
    marginHorizontal: MarginHW.MarginW16,
    justifyContent: 'space-between',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 8,
    overflow: 'hidden',
  },
  bottomBannerIcon: {
    position: 'absolute',
    bottom: -15,
    left: -10,
    width: ImageSize.ImageW80,
    height: ImageSize.ImageH70,
    transform: [{ rotate: '-180deg' }, { scaleY: -1 }],
  },
  bottomBannerTextContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 20,
  },
  bottomBannerText: {
    color: '#FFFFFF',
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
  },
  bottomBannerButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomBannerArrow: {
    color: '#056213',
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
  },
});
