import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../comman/Colors';
import fonts from '../../comman/fonts';
import MarginHW from '../../comman/MarginHW';
import FontsSize from '../../comman/FontsSize';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFBFB',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  // Hero section styles
  heroBg: {
    width: '100%',
    height: 260,
    alignItems: 'center',
    justifyContent: 'flex-end',
    position: 'relative',
    paddingBottom: 10,
  },
  heroBgImg: {
    width: '100%',
    height: '100%',
  },
  backButton: {
    position: 'absolute',
    top: 25,
    left: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 100,
  },
  backIcon: {
    width: 16,
    height: 16,
    tintColor: '#111827',
  },
  bubbleTreeContainer: {
    position: 'relative',
    width: 180,
    height: 190,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bubbleTreeImg: {
    width: 150,
    height: 180,
  },
  checkBadge: {
    position: 'absolute',
    top: 15,
    right: 25,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.TextColorLightGreen,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  checkBadgeIcon: {
    width: 14,
    height: 14,
    tintColor: '#FFFFFF',
  },
  // Success header details
  successHeader: {
    alignItems: 'center',
    marginTop: -30,
    paddingHorizontal: 16,
    borderRadius: 25,
    backgroundColor: '#ffffff90'
  },
  successTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 30,
  },
  successTitleIcon: {
    width: 20,
    height: 20,
    marginRight: 6,
    tintColor: Colors.TextColorLightGreen,
  },
  successTitle: {
    fontSize: 20,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A1C14',
  },
  successSubtitle: {
    fontSize: 12.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#4B5563',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 17,
    paddingHorizontal: 14,
  },
  // Details quadrant card
  card: {
    backgroundColor: '#fcfcfa',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    marginHorizontal: 12,
    marginTop: 16,
    padding: 12,
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 3,
    elevation: 1,
  },
  quadrantRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  quadrantCell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  quadrantTextCol: {
    flex: 1,
    marginLeft: 10,
  },
  quadrantIcon: {
    width: 24,
    height: 24,
    marginTop: 2,
  },
  quadrantLabel: {
    fontSize: 11,
    fontFamily: fonts.OpenSans_Medium,
    color: '#4B5563',
  },
  quadrantValue: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    marginTop: 2,
    lineHeight: 17,
  },
  quadrantDividerV: {
    width: 1,
    backgroundColor: '#EFF2F0',
    marginVertical: 12,
  },
  quadrantDividerH: {
    height: 1,
    backgroundColor: '#EFF2F0',
    marginHorizontal: 12,
  },
  // Stepper journey
  journeyHeader: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    marginBottom: 10,
  },
  journeyStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginTop: 6,
  },
  stepperSegment: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepperNode: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  stepperNodeCompleted: {
    backgroundColor: Colors.TextColorLightGreen,
  },
  stepperNodeActive: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: Colors.TextColorLightGreen,
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  stepperActiveInner: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.TextColorLightGreen,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepperNodePending: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  stepperCheckIcon: {
    width: 14,
    height: 14,
    tintColor: '#FFFFFF',
  },
  stepperActiveIcon: {
    width: 16,
    height: 16,
    tintColor: '#FFFFFF',
  },
  stepperPendingIcon: {
    width: 16,
    height: 16,
    tintColor: '#9CA3AF',
  },
  stepperLine: {
    flex: 1,
    height: 3,
    marginHorizontal: -4,
    zIndex: 1,
  },
  stepperLineCompleted: {
    backgroundColor: Colors.TextColorLightGreen,
  },
  stepperLinePending: {
    backgroundColor: '#E5E7EB',
  },
  stepperLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingHorizontal: 0,
  },
  stepperLabelText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#374151',
    textAlign: 'center',
    width: 72,
    lineHeight: 12,
  },
  // Plantation ID and Date Card
  plantationIdCard: {
    backgroundColor: '#F4F7F4',
    borderRadius: 12,
    padding: 14,
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EAF1EC',
  },
  plantationIdLeft: {
    flex: 1.3,
  },
  plantationIdLabel: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#056213',
  },
  plantationIdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 10,
  },
  plantationIdVal: {
    fontSize: 15,
    fontFamily: fonts.OpenSans_Bold,
    color: '#056213',
  },
  copyBtn: {
    marginLeft: 6,
    padding: 2,
  },
  copyIcon: {
    width: 14,
    height: 14,
    tintColor: '#056213',
  },
  dateLabel: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#056213',
  },
  dateVal: {
    fontSize: 12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    marginTop: 4,
  },
  plantationIdDividerV: {
    width: 1,
    height: '80%',
    backgroundColor: '#E2EFE5',
    marginHorizontal: 12,
  },
  qrCodeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrLabel: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Medium,
    color: '#374151',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 11,
  },
  // What's Next card
  whatsNextCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#A4C6B1',
    padding: 12,
    marginTop: 8,
  },
  badgeWithinDays: {
    backgroundColor: '#E6EFE8',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  badgeWithinDaysText: {
    fontSize: 10,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
  },
  whatsNextContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  whatsNextList: {
    flex: 1,
    paddingRight: 12,
  },
  whatsNextItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  whatsNextCheckOutline: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#056213',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  whatsNextCheckIcon: {
    width: 8,
    height: 8,
    tintColor: '#056213',
  },
  whatsNextText: {
    fontSize: 11.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#374151',
  },
  whatsNextImageContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#EEF6EE',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  whatsNextImg: {
    width: '85%',
    height: '85%',
  },
  // Sections layout
  sectionContainer: {
    marginTop: 16,
    paddingHorizontal: MarginHW.PaddingW5,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    marginLeft: 4,
  },
  sectionTitleIcon: {
    width: 14,
    height: 14,
    marginRight: 6,
    tintColor: Colors.TextColorLightGreen,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
  },
  sectionHeaderInside: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 6,
  },
  sectionTitleIconInside: {
    width: 16,
    height: 16,
    marginRight: 6,
    tintColor: Colors.TextColorLightGreen,
  },
  sectionTitleInside: {
    fontSize: 14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: '#EFF2F0',
    marginVertical: 16,
  },
  // Impact preview cells
  impactPreviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    marginTop: 6,
  },
  impactPreviewCard: {
    width: '18.5%',
    height: 84,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
  },
  impactPreviewIcon: {
    width: 22,
    height: 22,
    tintColor: Colors.TextColorLightGreen,
    marginBottom: 6,
  },
  impactPreviewVal: {
    fontSize: 11,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    textAlign: 'center',
  },
  impactPreviewLabel: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 2,
  },
  // Share buttons
  shareTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  shareTitle: {
    fontSize: 14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  shareTitleIcon: {
    width: 16,
    height: 16,
    marginLeft: 6,
    tintColor: Colors.TextColorLightGreen,
  },
  shareRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    marginTop: 6,
  },
  shareBtn: {
    width: '23.5%',
    height: 72,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 4,
  },
  shareBtnIconBgWhatsApp: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#25D366',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  shareBtnIconTextWhatsApp: {
    fontSize: 11,
    color: 'white',
    fontWeight: 'bold',
  },
  shareBtnIconBgLinkedIn: {
    width: 24,
    height: 24,
    borderRadius: 4,
    backgroundColor: '#0A66C2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  shareBtnIconTextLinkedIn: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: 'white',
    marginTop: -2,
  },
  shareBtnIconBgInstagram: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: '#E1306C',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  shareBtnIconTextInstagram: {
    fontSize: 11,
    color: 'white',
  },
  shareBtnIconBgX: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  shareBtnIconTextX: {
    fontSize: 12,
    fontFamily: fonts.OpenSans_Bold,
    color: 'white',
  },
  shareBtnText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#374151',
    textAlign: 'center',
    lineHeight: 11.5,
  },
  shareDivider: {
    height: 1,
    backgroundColor: '#EFF2F0',
    marginVertical: 14,
  },
  // Buttons
  primaryBtn: {
    backgroundColor: Colors.TextColorGreenDark,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  primaryBtnText: {
    fontSize: 14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
  },
  secondaryBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: Colors.TextColorGreenDark,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 4,
  },
  secondaryBtnText: {
    fontSize: 14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorGreenDark,
  },
  // Footer banner
  footerBanner: {
    backgroundColor: '#EEF4EF',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginHorizontal: 12,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBannerText: {
    fontSize: 11.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#374151',
  },
  // Trust Badges Card
  trustCard: {
    backgroundColor: '#F7F9F6',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    marginHorizontal: 12,
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
  trustBadgeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '24.5%',
  },
  trustBadgeIcon: {
    width: 20,
    height: 20,
    tintColor: '#056213',
    marginRight: 4,
  },
  trustBadgeTextCol: {
    flex: 1,
  },
  trustBadgeTitle: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    lineHeight: 10,
  },
  trustBadgeDesc: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
    lineHeight: 9.5,
  },
});
