import { StyleSheet } from 'react-native';
import { Colors } from '../../../comman/Colors';
import FontsSize from '../../../comman/FontsSize';
import MarginHW from '../../../comman/MarginHW';
import ImageSize from '../../../comman/ImageSize';
import HWSize from '../../../comman/HWSize';
import fonts from '../../../comman/fonts';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  headerBackground: {
    paddingBottom: MarginHW.PaddingH35,
    width: '100%',
    height: 220,
  },
  heroImageRadius: {
    width: '100%',
    left: 40,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW10,
  },
  backButton: {
    width: 35,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: MarginHW.MarginH16
  },
  backIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.textDark,
  },
  decorLeaves: {
    width: ImageSize.ImageW30,
    height: ImageSize.ImageH30,
    tintColor: Colors.lightGreen,
  },
  headerTextContainer: {
    paddingHorizontal: MarginHW.PaddingW10,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  headerTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size22,
    color: Colors.textDarkGreen,
  },
  titleLeafIcon: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
    tintColor: Colors.lightGreen,
  },
  headerSubtitle: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size14,
    color: Colors.black,
    width: '50%'
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    marginLeft: MarginHW.MarginW10,
    width: '70%',
    marginTop: 10,
    paddingHorizontal: MarginHW.PaddingW16,
    paddingVertical: MarginHW.PaddingH8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 3,
  },
  searchIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.textLabelGrey,
    marginRight: MarginHW.MarginW10,
  },
  searchInput: {
    flex: 1,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: Colors.textDark,
    padding: 0,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW10,
    marginTop: MarginHW.MarginH10,
    marginBottom: MarginHW.MarginH10,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size18,
    color: Colors.textDarkGreen,
  },
  sectionTitleLeaf: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    marginLeft: MarginHW.MarginW6,
  },
  popularStatesList: {
    paddingLeft: MarginHW.PaddingW10,
    paddingRight: MarginHW.PaddingW10,
  },
  popularCard: {
    width: 145,
    backgroundColor: Colors.white,
    borderRadius: 10,
    marginRight: 10,
    marginBottom: 2,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    overflow: 'hidden',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  popularCardImage: {
    width: '100%',
    height: 95,
  },
  popularCardContent: {
    paddingHorizontal: 5,
    flex: 1,
    justifyContent: 'space-between',
  },
  popularCardName: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: 13.5,
    color: '#111827',
    marginBottom: MarginHW.MarginH2,
  },
  popularStatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 2,

    marginBottom: MarginHW.MarginH2,
  },
  popularStatIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: '#056213',
    marginRight: MarginHW.MarginW4,
  },
  popularStatText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 11,
    color: '#5B665F',
  },
  popularStatValue: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: 11,
    color: '#111827',
  },
  popularActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  popularArrowBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#056213',
    alignItems: 'center',
    justifyContent: 'center',
  },
  popularArrowIcon: {
    width: 10,
    height: 10,
    tintColor: Colors.white,
    transform: [{ rotate: '180deg' }],
  },
  allStatesList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW10,
    // paddingBottom: MarginHW.PaddingH30,
  },
  sortFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sortFilterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: MarginHW.PaddingH5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginLeft: MarginHW.MarginW8,
  },
  sortFilterIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.textDark,
    marginRight: MarginHW.MarginW4,
  },
  sortFilterText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size12,
    color: Colors.textDark,
  },
  allCard: {
    width: '48%',
    backgroundColor: Colors.white,
    borderRadius: 10,
    marginBottom: MarginHW.MarginH10,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    overflow: 'hidden',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 3,
  },
  allCardImageContainer: {
    width: '100%',
    height: ImageSize.ImageH80,
  },
  allCardImage: {
    width: '100%',
    height: '100%',
  },
  tagBadge: {
    position: 'absolute',
    top: MarginHW.MarginH5,
    left: MarginHW.MarginW8,
    backgroundColor: Colors.tint,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: MarginHW.PaddingH3,
    borderRadius: FontsSize.size10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  tagBadgeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10,
    color: Colors.white,
  },
  overlapIconContainer: {
    position: 'absolute',
    bottom: 2,
    left: 5,
    width: 28,
    height: 28,
    borderRadius: 28 / 2,
    backgroundColor: Colors.white,
    borderWidth: 2,
    borderColor: Colors.borderGreenLight,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  overlapIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.legacyGreen,
  },
  allCardContent: {
    paddingHorizontal: MarginHW.PaddingW5,
    top: 2,
    paddingBottom: MarginHW.PaddingH8,
  },
  allCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  allCardTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDarkGreen,
  },
  treeBadge: {
    backgroundColor: Colors.badgeGreenBg,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: MarginHW.PaddingH3,
    borderRadius: FontsSize.size9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  treeBadgeText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size10,
    color: Colors.legacyGreen,
  },
  treeBadgeDesc: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size10,
    color: Colors.textLabelGrey,

    textAlign: 'center',
  },
  allCardProjectsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH5,
  },
  allCardFolderIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.legacyGreen,
    marginRight: MarginHW.MarginW4,
  },
  allCardProjectsText: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.textLabelGrey,
  },
  speciesLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.textLabelGrey,
    marginTop: MarginHW.MarginH5,
  },
  speciesHighlight: {
    fontFamily: fonts.OpenSans_SemiBold,
    color: Colors.textDarkGreen,
  },
  allCardDivider: {
    height: 1,
    backgroundColor: Colors.borderGreenLight,
    marginVertical: MarginHW.MarginH8,
  },
  exploreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.borderGreenUltraLight,
    paddingVertical: MarginHW.PaddingH5,
    borderRadius: FontsSize.size10,
  },
  exploreBtnText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.legacyGreen,
    marginRight: MarginHW.MarginW4,
  },
  exploreBtnArrow: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.legacyGreen,
  },
  bottomBanner: {
    backgroundColor: '#F7F8F3',
    borderColor: '#E7EBDC',
    borderWidth: 1,
    borderRadius: FontsSize.size20,
    marginHorizontal: MarginHW.MarginW10,
    marginBottom: MarginHW.MarginH10,
    paddingRight: MarginHW.PaddingW16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: HWSize.H_Height20,
    overflow: 'hidden',
  },
  bannerLeftIcon: {
    width: ImageSize.ImageW80,
    height: ImageSize.ImageH80,
    resizeMode: 'cover',
  },
  bannerLeftCol: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  bannerTextMain: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDark,
  },
  bannerTextSub: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.legacyGreen,
    includeFontPadding: false,
  },
  bannerTextDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: Colors.textMuted,
    lineHeight: 18,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: FontsSize.size20,
    borderTopRightRadius: FontsSize.size20,
    padding: MarginHW.PaddingW20,
    minHeight: 250,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH20,
  },
  modalTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size18,
    color: Colors.textDarkGreen,
  },
  closeButton: {
    padding: MarginHW.PaddingH5,
  },
  closeButtonText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDark,
  },
  optionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: MarginHW.PaddingH14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  optionText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size16,
    color: Colors.textDark,
  },
  optionSelectedText: {
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.legacyGreen,
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonSelected: {
    borderColor: Colors.legacyGreen,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.legacyGreen,
  },
});
