import { StyleSheet, Dimensions, Platform } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import fonts from '../../comman/fonts';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },

  // Header styles
  headerHeroContainer: {
    width: '100%',
    height: 240,
    maxHeight: 1200,
    position: 'relative',
  },
  headerBgImg: {
    width: '100%',
    height: 240,
    resizeMode: 'stretch',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingTop: Platform.OS === 'ios' ? 60 : 30,
    height: Platform.OS === 'ios' ? 80 : 70,
    backgroundColor: 'transparent',
  },
  backButton: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 0.5,
    borderColor: '#EAEAEA',
  },
  backIcon: {
    width: 15,
    height: 15,
    tintColor: Colors.textDark,
  },
  headerLogo: {
    width: 250,
    height: 250,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 0.5,
    borderColor: '#EAEAEA',
    position: 'relative',
  },
  iconImg: {
    width: 15,
    height: 15,
    tintColor: '#111827',
  },
  notificationDot: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#4CAF50',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },

  // Main Scroll View
  scrollContent: {
    paddingBottom: 8,
  },

  // Hero Section
  heroSection: {
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 0,
    backgroundColor: 'transparent',
  },
  heroTextContainer: {
    width: '80%',
  },
  heroTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  heroTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size20,
    color: '#1A3E25',
  },
  heroTitleGreen: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size20,
    color: '#4b783a',
  },
  heroSubtitle: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: '#000',
    marginBottom: 8,
  },

  // Verified Metrics
  metricsGridOuter: {
    backgroundColor: '#f5f6ef',
    borderRadius: 8,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#E6EFEA',
  },
  metricsGridInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  metricChip: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  metricIconBg: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#E8F3EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  metricChipIcon: {
    width: 10,
    height: 10,
    tintColor: '#1A6836',
  },
  metricChipText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: 7.5,
    color: '#458445',
    lineHeight: 10,
  },
  metricChipTextBlack: {
    color: '#111827',
  },
  metricChipTextGreen: {
    color: '#1A6836',
  },
  metricDivider: {
    width: 1,
    height: 22,
    backgroundColor: '#D1E0D6',
    marginHorizontal: 4,
  },

  // Section styling
  sectionContainer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: '#111827',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  viewAllLink: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewAllText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size13,
    color: '#0D684D',
  },

  // Featured Projects
  featuredProjectsScroll: {
    paddingLeft: 10,
    paddingRight: 10,
  },
  projectCard: {
    width: SCREEN_WIDTH / 1.8,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    marginRight: 12,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 6,
  },
  projectImageContainer: {
    width: '100%',
    height: 100,
    backgroundColor: '#E5E7EB',
  },
  projectCardImage: {
    width: '100%',
    height: '100%',
  },
  categoryBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#1E5F20',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  categoryBadgeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size9,
    color: '#FFFFFF',
    textTransform: 'uppercase',
  },
  gpsBadge: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
  },
  gpsBadgeIcon: {
    width: 10,
    height: 10,
    tintColor: '#111827',
    marginRight: 3,
  },
  gpsBadgeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size8,
    color: '#111827',
    textTransform: 'uppercase',
  },
  projectDetails: {
    padding: 12,
  },
  projectCardTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: '#111827',
    marginBottom: 3,
  },
  projectCardLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  projectCardLocationIcon: {
    width: 12,
    height: 12,
    tintColor: '#8E9A93',
    marginRight: 4,
  },
  projectCardLocation: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size11,
    color: '#66756C',
  },
  projectCardDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: '#55665C',
    lineHeight: 16,
    marginBottom: 10,
    height: 32,
  },
  progressContainer: {
    marginBottom: 10,
  },
  progressTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  progressTextLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressTreeIcon: {
    width: 14,
    height: 14,
    tintColor: '#1A6836',
    marginRight: 6,
  },
  progressTextLabelBold: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size11,
    color: '#111827',
  },
  progressTextLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size11,
    color: '#66756C',
  },
  progressTextPercent: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size11,
    color: '#1A6836',
  },
  progressBarBg: {
    height: 6,
    backgroundColor: '#E6EFEA',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#1A6836',
    borderRadius: 3,
  },
  cardStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  cardStatBox: {
    backgroundColor: '#F6FAF7',
    borderRadius: 6,
    paddingVertical: 5,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    width: '32%',
  },
  cardStatValue: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: '#111827',
  },
  cardStatLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size8,
    color: '#55665C',
    marginTop: 2,
  },
  cardStatBoxRight: {
    flexDirection: 'row',
    backgroundColor: '#F6FAF7',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: 'center',
    width: '65%',
  },
  cardStatTextCol: {
    flex: 1,
  },
  cardStatValueRight: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10,
    color: '#111827',
  },
  cardStatLabelRight: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size8,
    color: '#55665C',
    marginTop: 2,
  },
  cardStatIcon: {
    width: 18,
    height: 18,
    tintColor: '#1A6836',
    marginRight: 8,
  },
  supportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F6FAF7',
    borderWidth: 1,
    borderColor: '#D4E8DA',
    borderRadius: 6,
    paddingVertical: 5,
  },
  supportButtonText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size12,
    color: '#1A6836',
    marginRight: 4,
  },
  supportButtonArrow: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: '#1A6836',
  },

  // How Sponsorship Works
  sponsorshipWorksContainer: {
    paddingHorizontal: 10,
  },
  sponsorshipStepsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 1,
  },
  stepItem: {
    alignItems: 'center',
    width: '21%',
  },
  stepIconContainer: {
    width: 35,
    height: 35,
    borderRadius: 35 / 2,
    backgroundColor: '#F3F7F4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E6EFEA',
  },
  stepIcon: {
    width: 15,
    height: 15,
    tintColor: '#1A6836',
  },
  stepTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10,
    color: '#111827',
    textAlign: 'center',
    marginBottom: 2,
  },
  stepSub: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size8,
    color: '#66756C',
    textAlign: 'center',
    lineHeight: 11,
  },
  stepArrowIcon: {
    fontSize: FontsSize.size14,
    color: '#8E9A93',
    top: -14,
  },

  // Choose Your Sponsorship Level
  sectionTitleUppercase: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size11,
    color: '#111827',
  },
  levelsGridScroll: {
    paddingHorizontal: 10,
  },
  levelCard: {
    width: 145,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#ECEFEF',
    borderRadius: 8,
    padding: 10,
    marginRight: 10,
    position: 'relative',
    alignItems: 'center',
  },
  levelCardSelected: {
    borderColor: '#1A6836',
    borderWidth: 1,
    backgroundColor: '#F8FBF9',
  },
  levelCardTopRight: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 1,
  },
  unselectedCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  selectedCheckmark: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#1A6836',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedCheckmarkIcon: {
    width: 10,
    height: 10,
    tintColor: '#FFFFFF',
  },
  levelIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#F5F8F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 8,
  },
  levelIcon: {
    width: 28,
    height: 28,
  },
  levelName: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10,
    color: '#111827',
    marginBottom: 4,
    textAlign: 'center',
  },
  levelAmount: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: '#1A6836',
    marginBottom: 8,
    textAlign: 'center',
  },
  levelDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size8,
    lineHeight: 12,
    color: '#55665C',
    marginBottom: 12,
    textAlign: 'center',
    height: 24,
  },
  levelBadge: {
    backgroundColor: '#F0F6F1',
    borderRadius: 6,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginBottom: 4,
  },
  levelBadgeText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size9,
    color: '#1A6836',
  },

  // What you Receive
  receiveGrid: {
    paddingHorizontal: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  receiveItemGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F7F4',
    borderWidth: 1,
    borderColor: '#E6EFEA',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
    width: '48.5%',
    marginBottom: 8,
  },
  receiveIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E6EFEA',
  },
  receiveIcon: {
    width: 14,
    height: 14,
    tintColor: '#1A6836',
  },
  receiveTitle: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size9_5,
    color: '#333333',
    lineHeight: 13,
    flex: 1,
  },

  // Bottom Checkout Bar
  bottomCheckoutBar: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#ECEFEF',
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 4,
  },
  checkoutMainRow: {
    flexDirection: 'column',
    alignItems: 'stretch',
    marginBottom: 8,
  },
  selectedDetailsBox: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7FAF3',
    borderWidth: 1,
    borderColor: '#E6EFE6',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 6,
    overflow: 'hidden',
  },
  supportingInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  supportingThumbContainer: {
    width: 46,
    height: 46,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  supportingThumb: {
    width: 70,
    height: 70,
  },
  supportingTextContainer: {
    flex: 1,
  },
  supportingLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: '#6B7A70',
    marginBottom: 1,
  },
  supportingName: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size11,
    color: '#1A6836',
  },
  supportingLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 1,
  },
  supportingLocationIcon: {
    width: 10,
    height: 10,
    tintColor: '#6B7A70',
    marginRight: 2,
  },
  supportingLocation: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size9,
    color: '#55665C',
  },
  supportingProgress: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: '#55665C',
    marginTop: 2,
  },
  boldProgressText: {
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  verticalDivider: {
    width: 1,
    height: '80%',
    backgroundColor: '#D1E0D6',
    marginHorizontal: 10,
  },
  amountInfo: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingLeft: 8,
  },
  levelLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size9,
    color: '#6B7A70',
  },
  levelValText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10,
    color: '#1A6836',
    marginBottom: 0,
  },
  amountLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size9,
    color: '#6B7A70',
  },
  amountValText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: '#1A6836',
  },
  checkoutButtonBox: {
    width: '100%',
    alignItems: 'stretch',
    justifyContent: 'center',
  },
  continueButton: {
    backgroundColor: '#0F7F1B',
    height: 45,
    marginTop: 5,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    width: '100%',
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
  },
  continueButtonArrow: {
    color: '#FFFFFF',
    fontSize: FontsSize.size14,
    marginLeft: 6,
    fontFamily: fonts.OpenSans_Bold,
  },
  securePaymentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  secureIcon: {
    width: 10,
    height: 10,
    tintColor: '#8E9A93',
    marginRight: 4,
  },
  secureText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size9_5,
    color: '#8E9A93',
  },

  // Footer visual highlights
  footerBenefitsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#FAFBFB',
    borderTopWidth: 1,
    borderTopColor: '#ECEFEF',
    marginTop: 2,
  },
  footerBenefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  footerBenefitIcon: {
    width: 11,
    height: 11,
    tintColor: '#1A6836',
    marginRight: 4,
  },
  footerBenefitText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size8_5,
    color: '#6B7A70',
  },
  footerDivider: {
    width: 1,
    height: 12,
    backgroundColor: '#D1DCD6',
    marginHorizontal: 4,
  },
});
