
const Images = {
  logo: require('../assets/images/geotree_logo.png'),
  state: require('../assets/images/state.png'),
  OnboardingWelcome: require('../assets/images/Onboarding.png'),
  OnboardingErath: require('../assets/images/OnboardingErath.png'),
  OnboardingGetstarted: require('../assets/images/OnboardingGet.png'),
  imgbottom: require('../assets/images/imgbottom.png'),
  unchecked: require('../assets/images/unchecked.png'),
  checked: require('../assets/images/checkbox.png'),
  notification: require('../assets/images/notification.png'),
  setting: require('../assets/images/setting.png'),
  IPL_img: require('../assets/images/IPL_img.png'),
  hero_image: require('../assets/images/hero_image.png'),
  history: require('../assets/images/history.png'),
  home: require('../assets/images/home.png'),
  profile: require('../assets/images/profile.png'),
  dashboard: require('../assets/images/dashboard.png'),
  carbon_offset: require('../assets/images/carbon_offset.png'),
  LeftArrow: require('../assets/images/LeftArrow.png'),
  CarbonHome: require('../assets/images/CarbonHome.png'),
  Electricity: require('../assets/images/Electricity.png'),
  Transport: require('../assets/images/Transport.png'),
  FoodLifestyles: require('../assets/images/FoodLifestyles.png'),
  Apperment: require('../assets/images/Appartment.png'),
  Car: require('../assets/images/Car.png'),
  Bus: require('../assets/images/Bus.png'),
  Bicycle: require('../assets/images/Bicycle.png'),
  Motorbike: require('../assets/images/Bike.png'),
  Train: require('../assets/images/Train.png'),
  AirTravel: require('../assets/images/airplane.png'),
  ElectricVehicle: require('../assets/images/ElectricVehicle.png'),
  Vegetarian: require('../assets/images/Vegetarian.png'),
  NonVegetarian: require('../assets/images/Non-Vegetarian.png'),
  Omnivore: require('../assets/images/Omnivore.png'),
  Vegan: require('../assets/images/Vegan.png'),
  Pancil: require('../assets/images/Pancil.png'),
  UserProfile: require('../assets/images/UserProfile.png'),
  ProfileBackground: require('../assets/images/ProfileBackground.png'),
  occasions: require('../assets/images/occasions.png'),
  back: require('../assets/images/back.png'),
  DotWelcome: require('../assets/images/DotWelcome.png'),
  treeSmall: require('../assets/images/treeSmall.png'),
  visuals: require('../assets/images/visual.png'),
  treeplant: require('../assets/images/treeplant.jpg'),
  TreePlants: require('../assets/images/TreePlants.jpg'),
  splash_full: require('../assets/images/bootsplash_logo.png'),
  backup: require('../assets/images/backup.png'),
  close: require('../assets/images/close.png'),
  carbon_img: require('../assets/images/carbon_img.png'),
  chevron_up: require('../assets/images/chevron.png'),
  arrow: require('../assets/images/arrow.png'),
  bell: require('../assets/images/bell.png'),
  calendar: require('../assets/images/calendar.png'),
  call: require('../assets/images/call.png'),
  check: require('../assets/images/check.png'),
  chevron: require('../assets/images/chevron.png'),
  cloud_out: require('../assets/images/cloud_out.png'),
  cloud: require('../assets/images/cloud.png'),
  color_tool: require('../assets/images/color-tool.png'),
  cotton_flower: require('../assets/images/cotton-flower.png'),
  cup: require('../assets/images/cup.png'),
  delete: require('../assets/images/delete.png'),
  diagram: require('../assets/images/diagram.png'),
  drop_silhouette: require('../assets/images/drop-silhouette.png'),
  exit: require('../assets/images/exit.png'),
  globe_earth: require('../assets/images/globe-earth.png'),
  globe: require('../assets/images/globe.png'),
  gps: require('../assets/images/gps.png'),
  group: require('../assets/images/group.png'),
  help: require('../assets/images/help.png'),
  hot_interface: require('../assets/images/hot_interface.png'),
  leaf_out: require('../assets/images/leaf_out.png'),
  leaf: require('../assets/images/leaf.png'),
  location: require('../assets/images/location.png'),
  next: require('../assets/images/next.png'),
  pin: require('../assets/images/pin.png'),
  planet_icon: require('../assets/images/planet-icon.png'),
  right_arrow: require('../assets/images/right-arrow.png'),
  search: require('../assets/images/search.png'),
  settings: require('../assets/images/setting.png'),
  share: require('../assets/images/share.png'),
  security: require('../assets/images/security.png'),
  speech_bubble: require('../assets/images/speech-bubble.png'),
  success: require('../assets/images/success.png'),
  up_arrows: require('../assets/images/up-arrows.png'),
  user: require('../assets/images/user.png'),
  wallet: require('../assets/images/wallet.png'),
  padlock: require('../assets/images/padlock.png'),
  check_circle: require('../assets/images/checks.png'),
  email: require('../assets/images/email.png'),



};

export type ImageKey = keyof typeof Images;
export default Images;