import { BackHandler } from "react-native";

const Images = {
  logo: require('../assets/Images/logo.png'),
  SinginGeotree: require('../assets/Images/SinginGeotree.png'),
  OtpScreenGeotree: require('../assets/Images/OtpScreen.png'),
  LoginBg: require('../assets/Images/LoginBg.png'),
  background: require('../assets/Images/NewBg.png'),
  tree: require('../assets/Images/tree.png'),
  globe: require('../assets/Images/globe.png'),
  shield: require('../assets/Images/shield.png'),
  verified: require('../assets/Images/verified.png'),
  location: require('../assets/Images/location.png'),
  leaf: require('../assets/Images/leaf.png'),
  back: require('../assets/Images/back.png'),
  chooseTree: require('../assets/Images/chooseTree.png'),
  handtree: require('../assets/Images/handtree.png'),
  earth: require('../assets/Images/earth.png'),
  bird: require('../assets/Images/bird.png'),
  co2Cloud: require('../assets/Images/co2-cloud.png'),
  gift_tree: require('../assets/Images/gift_tree.png'),
  carbon_cal: require('../assets/Images/carbon_cal.png'),
  sponsor_plant: require('../assets/Images/sponsor_plant.png'),
  project_aravalli: require('../assets/Images/project_aravalli.png'),
  project_jaipur: require('../assets/Images/project_jaipur.png'),
  project_himalayas: require('../assets/Images/project_himalayas.png'),
  HomeBg: require('../assets/Images/HomeBg.png'),
  Leaf: require('../assets/Images/leaf.png'),
  Globe: require('../assets/Images/globe.png'),
  logoGeotree: require('../assets/Images/logoGeotree.png'),
  settings: require('../assets/Images/setting.png'),
  group: require('../assets/Images/group.png'),
  neem_tree: require('../assets/Images/neem_tree.png'),
  peepal_tree: require('../assets/Images/peepal_tree.png'),
  mango_tree: require('../assets/Images/mango_tree.png'),
  gulmohar_tree: require('../assets/Images/gulmohar_tree.png'),
  apple: require('../assets/Images/apple.png'),
  flower: require('../assets/Images/flower.png'),
  setting: require('../assets/Images/settings.png'),
  profile: require('../assets/Images/user.png'),
  bell: require('../assets/Images/bell.png'),
  impact: require('../assets/Images/stats.png'),
  home: require('../assets/Images/home.png'),
  plant: require('../assets/Images/growth.png'),
  community: require('../assets/Images/friends.png'),
  location_hero_bg: require('../assets/Images/location_hero_bg.png'),
  aravali_belt: require('../assets/Images/aravali_belt.png'),
  sariska_reserve: require('../assets/Images/sariska_reserve.png'),
  thar_desert: require('../assets/Images/thar_desert.png'),
  udaipur_lakeside: require('../assets/Images/udaipur_lakeside.png'),
  bubbletree: require('../assets/Images/bubbletree.png'),
  treeIcon: require('../assets/Images/treeIcon.png'),
  Location: require('../assets/Images/location.png'),
  Emission: require('../assets/Images/emission.png'),
  rajasthan: require('../assets/Images/rajasthan.png'),
  uttarakhand: require('../assets/Images/uttarakhand.png'),
  karnataka: require('../assets/Images/karnataka.png'),
  maharashtra: require('../assets/Images/maharashtra.png'),
  tamil_nadu: require('../assets/Images/tamil_nadu.png'),
  Deshbordbg: require('../assets/Images/Deshbordbg.png'),
  geolocation: require('../assets/Images/geolocation.png'),
  edit_icon: require('../assets/Images/edit_icon.png'),
  edit: require('../assets/Images/edit.png'),
  star_badge: require('../assets/Images/star_badge.png'),
  star: require('../assets/Images/star.png'),
  StateBg: require('../assets/Images/StateBg.png'),
  nature: require('../assets/Images/nature.png'),
  ipl_banner: require('../assets/Images/ipl_banner.png'),
  detailbg: require('../assets/Images/detailbg.png'),
  calendar: require('../assets/Images/calendar.png'),
  gift: require('../assets/Images/gift.png'),
  bank: require('../assets/Images/bank.png'),
  creditcard: require('../assets/Images/credit-card.png'),
  wallet: require('../assets/Images/wallet.png'),
  // edit: require('../assets/Images/edit.png'),
  lock: require('../assets/Images/padlock.png'),
  hastag: require('../assets/Images/hastag.png'),
  leaf1: require('../assets/Images/leaf1.png'),
  check: require('../assets/Images/check.png'),

};

export type ImageKey = keyof typeof Images;
export default Images;