import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../../../comman/Colors';
import fonts from '../../../../comman/fonts';
import MarginHW from '../../../../comman/MarginHW';
import FontsSize from '../../../../comman/FontsSize';
import ImageSize from '../../../../comman/ImageSize';
import HWSize from '../../../../comman/HWSize';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  scrollContent: {
    paddingBottom: MarginHW.PaddingH8,
  },

  // Header Style
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.MarginW10,
    paddingVertical: MarginHW.PaddingH10,
    backgroundColor: 'transparent',
  },
  backButton: {
    width: ImageSize.ImageW32,
    height: ImageSize.ImageH32,
    borderRadius: ImageSize.ImageH32 / 2,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  backIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.black,
  },
  headerTitleContainer: {
    alignItems: 'center',
    flex: 1,
    marginHorizontal: MarginHW.MarginW4,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    textAlign: 'center',
  },
  headerLeafIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    marginLeft: MarginHW.MarginW4,
    tintColor: '#0A5F35',
  },
  shareButton: {
    width: ImageSize.ImageW32,
    height: ImageSize.ImageH32,
    borderRadius: ImageSize.ImageH32 / 2,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  shareIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.bannerBenefitLabel,
  },

  // Top Background Landscape Section (combines Header & Hero Stats)
  topSectionBg: {
    width: '100%',
    paddingTop: MarginHW.PaddingH20,
    paddingBottom: MarginHW.PaddingH16,
    marginBottom: 0,
  },
  heroContentContainer: {
    width: '70%',
    paddingHorizontal: MarginHW.MarginW10,
    paddingVertical: MarginHW.PaddingH10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    minHeight: 120,
  },
  heroLeftContent: {
    width: '68%',
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: MarginHW.PaddingH12,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  heroTitleLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroTitleLabel: {
    flexShrink: 1,
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_SemiBold,
    color: Colors.bannerBenefitLabel,
  },
  heroInfoIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    borderRadius: ImageSize.ImageH14 / 2,
    borderWidth: 1,
    borderColor: Colors.placeholderColor,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: MarginHW.MarginW4,
  },
  heroInfoIconText: {
    fontSize: FontsSize.size8,
    color: Colors.placeholderColor,
    fontWeight: 'bold',
  },
  heroEmissionsValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginTop: MarginHW.MarginH1,
  },
  heroEmissionsVal: {
    fontSize: FontsSize.size32,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },
  heroEmissionsUnit: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#0A5F35',
    marginLeft: MarginHW.MarginW6,
  },
  heroEquivalentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH4,
    width: '100%',
  },
  heroEquivalentIcon: {
    width: ImageSize.ImageW22,
    height: ImageSize.ImageH22,
    marginRight: MarginHW.MarginW6,
    tintColor: '#0A5F35',
  },
  heroEquivalentTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  heroEquivalentLabel: {
    fontSize: FontsSize.size8_5,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  heroEquivalentVal: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },

  // Flight Summary Segment
  summarySection: {
    marginTop: -15,
    backgroundColor: Colors.white,
    marginHorizontal: MarginHW.MarginW10,
    borderRadius: 12,
    padding: MarginHW.PaddingH10,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginBottom: MarginHW.MarginH4,
  },
  summaryTitle: {
    fontSize: FontsSize.size15,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH6,
  },
  summaryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryCol: {
    flex: 1,
    alignItems: 'center',
  },
  summaryIconWrapper: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH35,
    borderRadius: ImageSize.ImageH35 / 2,
    backgroundColor: Colors.iconBgLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH4,
  },
  summaryIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.legacyGreen,
  },
  summaryLabel: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
  },
  summaryValue: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
    marginTop: MarginHW.MarginH2,
    textAlign: 'center',
  },
  breakdownCard: {
    backgroundColor: Colors.white,
    marginHorizontal: MarginHW.MarginW10,
    borderRadius: 12,
    padding: MarginHW.PaddingH10,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginBottom: MarginHW.MarginH4,
  },
  breakdownTitle: {
    fontSize: FontsSize.size15,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH6,
  },
  breakdownGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  breakdownBox: {
    width: '48%',
    backgroundColor: Colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    padding: MarginHW.PaddingH8,
    marginBottom: MarginHW.MarginH8,
    alignItems: 'center',
  },
  breakdownBoxIcon: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH20,
    tintColor: Colors.legacyGreen,
    marginBottom: MarginHW.MarginH4,
  },
  breakdownBoxLabel: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
  },
  breakdownBoxVal: {
    fontSize: FontsSize.size15,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
    marginTop: MarginHW.MarginH2,
  },
  breakdownBoxSub: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.placeholderColor,
    marginTop: MarginHW.MarginH1,
  },
  scoreBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH2,
  },
  scoreStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.pointsIconColor,
    marginRight: MarginHW.MarginW4,
  },
  scoreStatusText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.pointsIconColor,
  },

  // Two Column Charts Layout
  chartsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: MarginHW.MarginW10,
    marginBottom: MarginHW.MarginH4,
  },
  chartHalfCard: {
    width: '49.3%',
    backgroundColor: Colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    padding: MarginHW.PaddingH8,
    justifyContent: 'space-between',
  },
  chartTitle: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH6,
  },

  // Pie chart container
  pieContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: MarginHW.MarginH6,
  },
  pieCircle: {
    width: ImageSize.ImageW70,
    height: ImageSize.ImageH70,
    borderRadius: ImageSize.ImageH70 / 2,
    borderWidth: 6,
    borderColor: '#E2E8F0', // Remaining budget color (can also be a grey border)
    borderLeftColor: '#0A5F35', // Flight emissions color
    borderTopColor: '#0A5F35', // Flight emissions color
    borderRightColor: '#3B82F6', // Offset needed color
    justifyContent: 'center',
    alignItems: 'center',
  },
  pieCircleInnerVal: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    textAlign: 'center',
  },
  pieCircleInnerUnit: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: MarginHW.MarginH1,
  },
  pieLegend: {
    marginTop: MarginHW.MarginH4,
  },
  pieLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH2,
  },
  pieLegendDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: MarginHW.MarginW6,
  },
  pieLegendLabel: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    flex: 1,
  },
  pieLegendVal: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  pieFooterBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.bannerBgGreen,
    borderRadius: 6,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: MarginHW.PaddingH3,
    marginTop: MarginHW.MarginH4,
  },
  pieFooterLeafIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: '#0A5F35',
    marginRight: MarginHW.MarginW4,
  },
  pieFooterText: {
    fontSize: FontsSize.size9_5,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.bannerBenefitLabel,
    flex: 1,
  },
  pieFooterForestImage: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH18,
    marginLeft: MarginHW.MarginW4,
  },

  // Bar Chart styling
  barChartContainer: {
    height: HWSize.H_Height70,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    marginVertical: MarginHW.MarginH6,
    paddingBottom: MarginHW.PaddingH3,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderGrey,
  },
  barCol: {
    alignItems: 'center',
    width: '40%',
  },
  barVal: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH4,
  },
  barValUnit: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  barFill: {
    width: ImageSize.ImageW24,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  barLabel: {
    width: '45%',
    fontSize: FontsSize.size9_5,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    lineHeight: 12,
  },
  barLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: MarginHW.MarginH4,
  },
  comparisonAlert: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.pointsIconBgLight,
    borderRadius: 6,
    padding: MarginHW.PaddingH3,
    marginTop: MarginHW.MarginH4,
    borderWidth: 1,
    borderColor: '#FFE8CC',
  },
  comparisonAlertIconWrapper: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    borderRadius: ImageSize.ImageH16 / 2,
    backgroundColor: Colors.pointsIconColor,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW6,
  },
  comparisonAlertIconText: {
    color: Colors.white,
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Bold,
  },
  comparisonAlertContent: {
    flex: 1,
  },
  comparisonAlertTitle: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#D97706',
  },
  comparisonAlertDesc: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: '#B45309',
    marginTop: MarginHW.MarginH1,
  },

  // GeoTree Recommendation Block
  recCard: {
    backgroundColor: Colors.whiteDivider,
    marginHorizontal: MarginHW.MarginW10,
    borderRadius: 12,
    padding: MarginHW.PaddingH10,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH4,
    overflow: 'hidden',
  },
  recIconContainer: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH35,
    borderRadius: ImageSize.ImageH35 / 2,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW12,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
  },
  recIconText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },
  recContent: {
    flex: 1,
    paddingRight: MarginHW.PaddingW85,
  },
  recHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recHeaderTitle: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },
  recText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Medium,
    color: '#44554C',
    marginTop: MarginHW.MarginH2,
    lineHeight: 16,
  },
  recClipboardGraphic: {
    width: 200,
    height: 200,
    position: 'absolute',
    right: -32,
    bottom: -40,
    opacity: 0.95,
  },
  whatMeansSection: {
    backgroundColor: Colors.white,
    marginHorizontal: MarginHW.MarginW10,
    borderRadius: 12,
    padding: MarginHW.PaddingH10,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginBottom: MarginHW.MarginH4,
  },
  whatMeansTitle: {
    fontSize: FontsSize.size15,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH6,
  },
  whatMeansItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH6,
  },
  whatMeansItemLast: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 0,
  },
  whatMeansIconWrapper: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH35,
    borderRadius: ImageSize.ImageH35 / 2,
    backgroundColor: Colors.iconBgLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW10,
  },
  whatMeansIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.legacyGreen,
  },
  whatMeansTextLabel: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  whatMeansTextVal: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginTop: MarginHW.MarginH1,
  },

  // Offset Your Flight Impact Card (Call to Action)
  offsetCard: {
    backgroundColor: Colors.white,
    marginHorizontal: MarginHW.MarginW10,
    borderRadius: 12,
    padding: MarginHW.PaddingH10,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    position: 'relative',
    marginBottom: MarginHW.MarginH4,
  },
  offsetHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: MarginHW.MarginH8,
  },
  offsetTitle: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  offsetRecommendBadge: {
    backgroundColor: Colors.badgeGreenBg,
    borderRadius: 4,
    paddingHorizontal: MarginHW.PaddingW8,
    paddingVertical: MarginHW.PaddingH3,
  },
  offsetRecommendText: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },
  offsetBodyRow: {
    flexDirection: 'row',
  },
  offsetGraphicCol: {
    alignItems: 'center',
    marginRight: MarginHW.MarginW14,
    width: HWSize.W_Width70,
  },
  offsetCircleContainer: {
    width: ImageSize.ImageW50,
    height: ImageSize.ImageH50,
    borderRadius: ImageSize.ImageH50 / 2,
    backgroundColor: Colors.iconBgLight,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    marginBottom: MarginHW.MarginH4,
  },
  offsetCircleTreeIcon: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
    tintColor: '#0A5F35',
  },
  offsetTreesText: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    textAlign: 'center',
  },
  offsetTreesSub: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
  },
  offsetInfoCol: {
    flex: 1,
    justifyContent: 'space-between',
  },
  offsetFeatureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH6,
  },
  offsetCheckIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: '#0A5F35',
    marginRight: MarginHW.MarginW6,
  },
  offsetFeatureText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: '#44554C',
  },
  offsetPricingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: MarginHW.MarginH4,
    paddingTop: MarginHW.PaddingH10,
    borderTopWidth: 1,
    borderTopColor: Colors.borderGrey,
  },
  offsetCostLabelContainer: {
    justifyContent: 'center',
  },
  offsetCostLabel: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  offsetCostValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  offsetCostVal: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A5F35',
  },
  offsetCostUnit: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginLeft: MarginHW.MarginW3,
  },
  offsetDifferenceText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Medium,
    color: Colors.bannerBenefitLabel,
    marginTop: MarginHW.MarginH4,
  },
  offsetNowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0A5F35',
    borderRadius: 6,
    paddingHorizontal: MarginHW.PaddingW12,
    paddingVertical: MarginHW.PaddingH8,
  },
  offsetNowButtonText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
    marginRight: MarginHW.MarginW6,
  },
  offsetNowButtonArrow: {
    width: ImageSize.ImageW9,
    height: ImageSize.ImageH9,
    tintColor: Colors.white,
  },

  backAssessmentBarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0A5F35',
    paddingVertical: MarginHW.PaddingH12,
    marginHorizontal: MarginHW.MarginW10,
    marginBottom: MarginHW.MarginH6,
    borderRadius: 10
  },
  backAssessmentArrow: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW8,
  },
  backAssessmentText: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
});
