import { StyleSheet, Platform } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';
import fonts from '../../comman/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  scrollContainer: {
    paddingBottom: MarginHW.PaddingH3,
  },
  heroImageBackground: {
    width: '100%',
    paddingBottom: MarginHW.PaddingH20,
  },
  heroContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW16,
    marginTop: MarginHW.MarginH10,

    position: 'relative',
  },
  heroLeft: {
    width: '62%',
    justifyContent: 'flex-start',
  },
  heroTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size22,
    lineHeight: 28,
    color: Colors.textDarkGreen,
  },
  highlightGreen: {
    color: Colors.tint,
    fontFamily: fonts.OpenSans_Bold,
  },
  heroSubtitle: {
    marginTop: MarginHW.MarginH10,
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    lineHeight: 18,
    color: Colors.textMuted,
  },
  heroLocationContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    // backgroundColor: 'rgba(30, 107, 70, 0.06)',
    paddingVertical: MarginHW.PaddingH8,
    paddingRight: MarginHW.PaddingW10,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  heroLocationIcon: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH20,
    tintColor: Colors.tint,
    // marginRight: MarginHW.MarginW6,
    marginTop: MarginHW.MarginH2,
  },
  heroLocationText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12,
    color: Colors.tint,
    lineHeight: 18,
    left: 5,
  },
  bubbleTreeContainer: {
    position: 'absolute',
    right: 0,
    top: -15,
    width: HWSize.W_Width140,
    height: HWSize.H_Height200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bubbleTreeImage: {
    width: HWSize.W_Width130,
    height: HWSize.H_Height190,
  },
  card: {

    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.bannerBorder,
    borderRadius: 10,

    marginHorizontal: MarginHW.MarginW16,
    paddingVertical: MarginHW.PaddingH6,
    paddingHorizontal: MarginHW.PaddingW14,
    marginBottom: MarginHW.MarginH10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH12,
    paddingHorizontal: MarginHW.PaddingW4,
  },
  cardHeaderIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.tint,
    marginRight: MarginHW.MarginW8,
  },
  cardHeaderTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDarkGreen,
  },
  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  gridCol: {
    width: '24%',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  gridIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 28 / 2,
    backgroundColor: Colors.iconBgLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  gridIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.tint,
  },
  gridLabel: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size11,
    color: Colors.textLabelGrey,
    textAlign: 'center',
  },
  gridValue: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size12,
    color: Colors.tint,
    textAlign: 'center',
    lineHeight: 16,
  },
  gridDivider: {
    width: 1.2,
    alignSelf: 'stretch',
    backgroundColor: Colors.dividerGreen,
    marginVertical: 2,
  },
  gridCol2: {
    width: '47%',
    alignItems: 'center',
  },
  gridRowDivider: {
    height: 1.2,
    backgroundColor: Colors.dividerGreen,
    marginVertical: MarginHW.MarginH14,
    marginHorizontal: MarginHW.MarginW12,
  },
  gridDivider2: {
    width: 1.2,
    height: 48,
    backgroundColor: Colors.dividerGreen,
    alignSelf: 'center',
  },
  checkIconValue: {
    width: 16,
    height: 16,
    tintColor: Colors.tint,
    marginTop: MarginHW.MarginH6,
    alignSelf: 'center',
  },
  certificateSplit: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
  },
  certificateLeft: {
    flex: 1.4,
    paddingRight: MarginHW.PaddingW10,
  },
  certificateIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: Colors.tint,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  certificateIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.white,
  },
  certificateTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.textDarkGreen,
  },
  certificateSubtext: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14,
    color: Colors.textLabelGrey,
    marginTop: MarginHW.MarginH4,
    lineHeight: 18,
  },
  certificateBtn: {
    borderWidth: 1.2,
    borderColor: Colors.tint,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 5,
    alignSelf: 'flex-start',
    marginTop: 10,
  },
  certificateBtnText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10,
    color: Colors.tint,
  },
  certificateRight: {
    flex: 0.9,
    height: HWSize.H_Height85,
    borderWidth: 1.5,
    borderColor: Colors.borderLight,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: Colors.containerBg,
    padding: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  certificateImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
  },
  timelineSplit: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timelineContainer: {
    flex: 1.3,
    paddingRight: MarginHW.PaddingW10,
  },
  timelineRight: {
    flex: 0.9,
    backgroundColor: Colors.bgGreenLight,
    borderRadius: 10,
    padding: 10,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    borderWidth: 1.2,
    borderColor: Colors.borderGreenLight,

  },
  timelineRightImage: {
    width: '100%',
    height: HWSize.H_Height80,
    borderRadius: 8,
  },
  timelineRightText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: 9.5,
    color: Colors.textGreenDark,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 13,
  },
  timelineStep: {
    flexDirection: 'row',

  },
  timelineIndicatorContainer: {
    alignItems: 'center',
    marginRight: MarginHW.MarginW10,
    width: 18,
  },
  timelineLine: {
    width: 1.5,
    flex: 1,
    backgroundColor: Colors.dividerGreen,
  },
  timelineNodeCompleted: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.tint,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timelineNodeActiveBorder: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: Colors.tint,
    backgroundColor: '#FFFFFF',
  },
  timelineNodeInactive: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: Colors.borderLight,
    backgroundColor: '#FFFFFF',
  },
  timelineCheckIcon: {
    width: 8,
    height: 8,
    tintColor: Colors.white,
  },
  timelineContent: {
    flex: 1,
    paddingBottom: 12,
  },
  timelineTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 11.5,
    color: Colors.textDark,
  },
  timelineTitleCompleted: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 11.5,
    color: Colors.tint,
  },
  timelineDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 9.5,
    color: Colors.textMuted,
    marginTop: 2,
    lineHeight: 12,
  },
  impactBanner: {
    backgroundColor: Colors.bannerBgGreen,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginHorizontal: MarginHW.MarginW16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: MarginHW.MarginH8,
    marginTop: MarginHW.MarginH4,
    borderWidth: 1,
    borderColor: Colors.bannerBorderGreen,
  },
  impactLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.8,
  },
  impactIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.badgeGreenBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
  },
  impactIcon: {
    width: 18,
    height: 18,
    tintColor: Colors.tint,
  },
  impactText: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: 10,
    color: Colors.textGreenDark,
    lineHeight: 13,
    flex: 1,
  },
  impactRight: {
    flex: 0.9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  impactRightImage: {
    width: 75,
    height: 48,
  },
  bannerCard: {
    backgroundColor: Colors.bgGreenLight,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    marginHorizontal: MarginHW.MarginW16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
    paddingVertical: MarginHW.PaddingH8,
  },
  bannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingLeft: MarginHW.PaddingW14,
    paddingRight: MarginHW.PaddingW10,
  },
  bannerShieldContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
  },
  bannerShieldIcon: {
    width: ImageSize.ImageH20,
    height: ImageSize.ImageH20,
    tintColor: Colors.shieldIconColor,
  },
  bannerTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  bannerText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size14,
    color: Colors.textDark,
    lineHeight: 16,
    marginBottom: MarginHW.MarginH2,
  },
  bannerTextSecondary: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.textDark,
    lineHeight: 15,
  },
  bannerRight: {
    flex: 1,
    height: 48,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  bannerHandImage: {
    width: 70,
    height: 70,
  },
  footerContainer: {
    paddingHorizontal: MarginHW.PaddingW20,
    paddingBottom: MarginHW.PaddingH10,
    paddingTop: MarginHW.PaddingH12,
  },
  trackButton: {
    backgroundColor: Colors.continue,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.btnShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
    position: 'relative',
  },
  trackButtonText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 15,
    color: Colors.white,
  },
  trackArrow: {
    position: 'absolute',
    right: 20,
    width: 16,
    height: 16,
    tintColor: Colors.white,
  },
  plantAnotherButton: {
    height: 50,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.tint,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  plantAnotherText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 14,
    color: Colors.tint,
  },
  plantAnotherIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.tint,
    marginRight: 6,
  },
});
