import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import fonts from '../../comman/fonts';
import MarginHW from '../../comman/MarginHW';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFBFB',
    paddingTop: MarginHW.PaddingW16,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  // Header and Hero ImageBackground wrapper
  headerHeroBg: {
    width: '100%',
    height: 190

  },
  heroImageRadius: {
    width: '100%',
    left: 35,
  },
  // Top Header Row (transparent)
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW16,
    paddingVertical: 10,
    backgroundColor: 'transparent'
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    // Premium soft shadow for floating look
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  backIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.textDark,
  },
  // Stepper Indicator
  stepperContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginLeft: 10,
    position: 'relative',
    height: 40,
  },
  stepperLine: {
    position: 'absolute',
    left: '10%',
    right: '10%',
    top: 13,
    height: 2,
    backgroundColor: '#E5E7EB',
    zIndex: 0,
  },
  stepperLineActive: {
    position: 'absolute',
    left: '10%',
    width: '55%', // spans up to Step 4 (Dedication)
    top: 13,
    height: 2,
    backgroundColor: Colors.legacyGreen,
    zIndex: 0.5,
  },
  stepItem: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  stepCircleContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: Colors.listBgLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleActive: {
    borderColor: Colors.legacyGreen,
    backgroundColor: Colors.listBgLight,
  },
  stepCircleCompleted: {
    borderColor: '#E6EFEA',
    backgroundColor: '#E6EFEA',
  },
  stepIcon: {
    width: 12,
    height: 12,
    tintColor: '#9CA3AF',
  },
  stepIconActive: {
    tintColor: '#FFFFFF',
  },
  stepIconCompleted: {
    width: 12,
    height: 12,
    tintColor: Colors.legacyGreen,
  },
  checkmarkBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: Colors.legacyGreen,
    width: 12,
    height: 12,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  checkmarkBadgeIcon: {
    width: 6,
    height: 6,
    tintColor: '#FFFFFF',
  },
  stepLabel: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Bold,
    color: '#9CA3AF',
    marginTop: 4,
  },
  stepLabelActive: {
    color: Colors.legacyGreen,
  },
  // Hero Section
  heroSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW16,
    height: '100%',
  },
  heroLeft: {
    flex: 0.9,
  },
  heroTitle: {
    fontSize: FontsSize.size20,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  heroTitleLeaf: {
    width: 22,
    height: 22,
    tintColor: Colors.legacyGreen,
    marginLeft: 6,
  },
  heroSubtitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: '#4B5563',
    marginTop: 6,
  },
  heroRight: {
    flex: 0.6,
    alignItems: 'flex-end',
    marginTop: 55,
  },
  heroRightContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    width: 120,
    height: 110,
  },
  heroSaplingImg: {
    width: 90,
    height: 100,
  },
  secureBadge: {
    position: 'absolute',
    bottom: 5,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2ECE5',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 3,
  },
  secureBadgeIcon: {
    width: 14,
    height: 14,
    tintColor: '#1E6B46',
    marginRight: 4,
  },
  secureBadgeTextCol: {
    flexDirection: 'column',
  },
  secureBadgeText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Medium,
    color: '#111827',
    lineHeight: 10,
  },
  // Selected Summary Card
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 10,
    marginTop: -14,
    marginHorizontal: MarginHW.PaddingW10,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 1,
  },
  summaryLeftCol: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryTreeImgContainer: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#EFF5F1',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  summaryTreeImg: {
    width: 70,
    height: 70,
    borderRadius: 70 / 2
  },
  summaryRightCol: {
    flex: 1,
    marginLeft: 14,
  },
  summaryHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryTreeName: {
    fontSize: 16,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  gpsVerifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
  },
  gpsVerifiedIcon: {
    width: 12,
    height: 12,
    tintColor: '#1E6B46',
    marginRight: 4,
  },
  gpsVerifiedText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1E6B46',
  },
  summaryStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryStatCol: {
    flex: 1,
  },
  summaryStatLabel: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
    marginBottom: 4,
  },
  summaryStatValGreen: {
    fontSize: 12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.legacyGreen,
  },
  summaryStatVal: {
    fontSize: 11,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    lineHeight: 14,
  },
  summaryStatDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 8,
  },
  co2Row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoIcon: {
    fontSize: 11,
    color: Colors.legacyGreen,
    marginLeft: 4,
  },
  // Section Headers & Containers
  sectionContainer: {
    marginTop: 15,
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
  },
  sectionTitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    marginBottom: 10,
  },
  // Dedication type
  typeList: {
    paddingTop: 10,
    paddingBottom: 8,
    paddingHorizontal: 4,
  },
  typeCard: {
    width: 70,
    height: 80,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    paddingHorizontal: 4,
    position: 'relative',
    overflow: 'visible',
  },
  typeCardActive: {
    borderColor: Colors.legacyGreen,
    backgroundColor: Colors.listBgLight,
  },
  checkmarkBadgeSelection: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.legacyGreen,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1.5,
    elevation: 2,
    zIndex: 10,
  },
  checkmarkBadgeSelectionIcon: {
    width: 8,
    height: 8,
    tintColor: '#FFFFFF',
  },
  typeIcon: {
    width: 26,
    height: 26,
    tintColor: '#4B5563',
  },
  typeIconActive: {
    tintColor: Colors.legacyGreen,
  },
  typeTitle: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#4B5563',
    marginTop: 8,
    textAlign: 'center',
    lineHeight: 12,
  },
  typeTitleActive: {
    color: Colors.legacyGreen,
  },
  // Allocation
  allocationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  allocationCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    paddingHorizontal: 6,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 4,
    position: 'relative',
    minHeight: 80,
  },
  allocationCardActive: {
    borderColor: Colors.listBgLight,
    backgroundColor: Colors.listBgLight,
  },
  allocationIcon: {
    width: 24,
    height: 24,
    tintColor: '#1E6B46',
    marginRight: 6,
  },
  allocationTextCol: {
    flex: 1,
    justifyContent: 'center',
  },
  allocationTitle: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    lineHeight: 12,
  },
  allocationSubtitle: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#4B5563',
    marginTop: 2,
    lineHeight: 10,
  },
  allocationCheck: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  allocationCheckActive: {
    borderColor: '#1E6B46',
    backgroundColor: '#1E6B46',
  },
  checkmarkText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: 'bold',
  },
  // Split Example Container Badges
  exampleContainer: {
    backgroundColor: Colors.listBgLight,
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
  },
  exampleTitle: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1E6B46',
    marginBottom: 10,
  },
  exampleScrollList: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  exampleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  exampleBadgeIconBg: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#EEF6F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  exampleBadgeIcon: {
    width: 12,
    height: 12,
    tintColor: '#1E6B46',
  },
  exampleBadgeTextCol: {
    flexDirection: 'column',
    justifyContent: 'center',
  },
  exampleBadgeName: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  exampleBadgeQty: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1E6B46',
    marginTop: 1,
  },
  exampleAddBadge: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#1E6B46',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    height: 38,
  },
  exampleAddText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1E6B46',
  },
  // Recipient input fields
  recipientHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  thisIsMeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  thisIsMeLabel: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#6B7280',
    marginRight: 6,
  },
  inputsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inputGroupCol: {
    flex: 1,
    marginHorizontal: 3,
  },
  inputLabel: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#4B5563',
    marginBottom: 4,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 6,
    paddingHorizontal: 6,
    height: 36,
    backgroundColor: '#FFFFFF',
  },
  inputWrapperActive: {
    borderColor: Colors.legacyGreen,
  },
  inputIcon: {
    width: 12,
    height: 12,
    tintColor: '#9CA3AF',
    marginRight: 6,
  },
  textInput: {
    flex: 1,
    fontSize: 11,
    fontFamily: fonts.OpenSans_Medium,
    color: '#111827',
    padding: 0,
  },
  // Split columns
  twoColumnRow: {
    flexDirection: 'row',
    paddingHorizontal: MarginHW.PaddingW16,
    marginTop: 15,
  },
  leftColumn: {
    flex: 1,
    marginRight: 10,
  },
  rightColumn: {
    flex: 0.7,
  },
  innerSectionContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  messageCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    padding: 12,
    alignItems: 'stretch',
    height: 90,
  },
  messageCardActive: {
    borderColor: Colors.legacyGreen,
  },
  messageInputCol: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  messageTextInput: {
    fontSize: 11,
    fontFamily: fonts.OpenSans_Medium,
    color: '#111827',
    textAlignVertical: 'top',
    padding: 0,
    height: '100%',
  },
  messageGraphicCol: {
    width: 60,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 8,
  },
  messageGraphic: {
    width: 50,
    height: 48,
  },
  messageCharCount: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 2,
  },
  // Updates horizontal scroll lists
  updatesList: {
    paddingBottom: 4,
  },
  updateToggleCard: {
    width: 120,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 8,
    backgroundColor: '#FFFFFF',
    marginRight: 6,
    justifyContent: 'space-between',

  },
  updateIconBg: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#EEF6F2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  updateIcon: {
    width: 12,
    height: 12,
    tintColor: Colors.legacyGreen,
  },
  updateTitle: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    marginTop: 4,
  },
  updateDesc: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7280',
    marginTop: 1,
    lineHeight: 10,
  },
  updateSwitchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  // Sidebar Impact Preview
  previewCard: {
    backgroundColor: '#F4F9F6',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2ECE5',
    padding: 10,
    height: Dimensions.get('window').height / 2.9,
  },
  previewTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  previewTitleText: {
    fontSize: 10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  previewTitleLeaf: {
    width: 12,
    height: 12,
    marginLeft: 4,
  },
  previewItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  previewIcon: {
    width: 14,
    height: 14,
    marginRight: 6,
  },
  previewTextWrapper: {
    flexDirection: 'column',
    flex: 1,
  },
  previewVal: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1E6B46',
  },
  previewLabel: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#4B5563',
    marginTop: 1,
  },
  // Trust Banner
  trustBanner: {
    flexDirection: 'row',
    backgroundColor: '#F4F9F6',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2ECE5',
    paddingVertical: 12,
    paddingHorizontal: 6,
    marginHorizontal: MarginHW.PaddingW16,
    marginTop: 15,
    justifyContent: 'space-between',
  },
  trustCol: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  trustDivider: {
    width: 1,
    height: '60%',
    backgroundColor: '#E2ECE5',
    alignSelf: 'center',
  },
  trustIconBg: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#EEF6F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  trustIcon: {
    width: 10,
    height: 10,
    tintColor: Colors.legacyGreen,
  },
  trustTextCol: {
    flex: 1,
  },
  trustTitleText: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
  },
  trustDescText: {
    fontSize: 6.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#4B5563',
    marginTop: 1,
  },
  // Footer / CTA
  footerContainer: {
    marginTop: 20,
    paddingHorizontal: MarginHW.PaddingW16,
    alignItems: 'center',
  },
  actionButton: {
    width: '100%',
    height: 44,
    borderRadius: 10,
    overflow: 'hidden',
  },
  gradientBtn: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  btnSaplingImg: {
    position: 'absolute',
    left: 14,
    width: 60,
    height: 40,
  },
  actionBtnText: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
  },
  actionBtnArrow: {
    position: 'absolute',
    right: 14,
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  secureTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  secureIcon: {
    fontSize: 10,
    color: '#6B7280',
    marginRight: 4,
  },
  secureText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
  },
});
