import { StyleSheet, Dimensions } from 'react-native';
import fonts from '../../../comman/fonts';
import FontsSize from '../../../comman/FontsSize';
import { Colors } from '../../../comman/Colors';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FAFAFA',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 16,
        marginVertical: 20,
        backgroundColor: '#FAFAFA',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    backIcon: {
        width: 16,
        height: 16,
        tintColor: '#111827',
    },
    headerTitleContainer: {
        flex: 1,
        alignItems: 'center',
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    titleLeafIcon: {
        width: 16,
        height: 16,
        marginLeft: 6,
    },
    headerSubtitle: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        marginTop: 2,
    },
    filterButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    filterIcon: {
        width: 18,
        height: 18,
        tintColor: '#111827',
    },
    scrollContent: {
        paddingBottom: 50,
    },
    statsBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#f6f7f2',
        borderRadius: 8,
        marginHorizontal: 16,
        paddingVertical: 12,
        paddingHorizontal: 8,
        marginBottom: 16,
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
        justifyContent: 'center',
    },
    statIconCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#e3e6d1',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 6,
    },
    statIcon: {
        width: 14,
        height: 14,
        tintColor: '#0A5F35',
    },
    statTextCol: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 5
    },
    statValue: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    statLabel: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#111827',
    },
    statDivider: {
        width: 1,
        height: 24,
        backgroundColor: '#D1D5DB',
        marginHorizontal: 4,
    },
    categoriesScroll: {
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    categoryChip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        marginRight: 10,
    },
    categoryChipActive: {
        backgroundColor: '#0A5F35',
        borderColor: '#0A5F35',
    },
    categoryIcon: {
        width: 14,
        height: 14,
        marginRight: 6,
        tintColor: '#0A5F35',
    },
    categoryText: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
    },
    categoryTextActive: {
        color: '#FFFFFF',
    },
    projectListContent: {
        paddingHorizontal: 16,
    },
    projectCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        marginBottom: 16,
        overflow: 'hidden',
    },
    imageContainer: {
        width: '100%',
        height: 140,
        position: 'relative',
    },
    projectImage: {
        width: '100%',
        height: '100%',
    },
    tagBadge: {
        position: 'absolute',
        top: 12,
        left: 12,
        backgroundColor: '#0A5F35',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    tagText: {
        color: '#FFFFFF',
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Bold,
    },
    gpsBadge: {
        position: 'absolute',
        bottom: 12,
        left: 12,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    gpsIcon: {
        width: 10,
        height: 10,
        tintColor: '#FFFFFF',
        marginRight: 4,
    },
    gpsText: {
        color: '#FFFFFF',
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Bold,
    },
    projectInfo: {
        padding: 16,
    },
    projectHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    titleLocationCol: {
        flex: 1,
        marginRight: 12,
    },
    projectTitle: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 4,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    locationIcon: {
        width: 12,
        height: 12,
        tintColor: '#6B7280',
        marginRight: 4,
    },
    locationText: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#111827',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ECFDF5',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 5,
    },
    statusIcon: {
        width: 10,
        height: 10,
        tintColor: '#0A5F35',
        marginRight: 4,
    },
    statusText: {
        color: '#4b783a',
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_SemiBold,
    },
    projectDesc: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Regular,
        color: '#4B5563',
        marginBottom: 16,
        lineHeight: 16,
    },
    statsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    treesCol: {
        flex: 1,
    },
    treesLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    treesIcon: {
        width: 12,
        height: 12,
        tintColor: '#0A5F35',
        marginRight: 4,
    },
    treesValue: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    treesLabel: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        marginBottom: 6,
    },
    progressBarBg: {
        height: 4,
        backgroundColor: '#E5E7EB',
        borderRadius: 2,
        width: '100%',
    },
    progressBarFill: {
        height: 4,
        backgroundColor: '#0A5F35',
        borderRadius: 2,
    },
    progressText: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginLeft: 12,
    },
    verticalDivider: {
        width: 1,
        height: 30,
        backgroundColor: '#E5E7EB',
        marginHorizontal: 16,
    },
    daysCol: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    daysIcon: {
        width: 16,
        height: 16,
        tintColor: '#6B7280',
        marginRight: 8,
    },
    daysValue: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    daysLabel: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
    },
    footerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        paddingTop: 12,
    },
    ngoInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    ngoIcon: {
        width: 20,
        height: 20,
        tintColor: '#0A5F35',
        marginRight: 8,
    },
    ngoName: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
    },
    ngoLabel: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
    },
    verifiedInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 16,
    },
    verifiedIcon: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
        marginRight: 6,
    },
    verifiedValue: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
    },
    verifiedLabel: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
    },
    viewDetailsBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    viewDetailsText: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#0A5F35',

        marginRight: 4,
    },
    viewDetailsArrow: {
        fontSize: 12,
        color: '#111827',
    },
    bottomBarContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#f6f7f2',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    bottomBarLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 12,
    },
    bottomBarIconCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#e3e6d1',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    bottomBarIcon: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
    },
    bottomBarTextCol: {
        flex: 1,
    },
    bottomBarTitle: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 2,
    },
    bottomBarSub: {
        fontSize: FontsSize.size7,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
    },
    howItWorksBtn: {
        backgroundColor: '#0A5F35',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 6,
    },
    howItWorksText: {
        color: '#FFFFFF',
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_SemiBold,
    },
});

export default styles;
