import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import fonts from '../../comman/fonts';
import MarginHW from '../../comman/MarginHW';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFBFB',
  },
  scrollContent: {
    paddingBottom: 2,
  },
  headerBg: {
    width: '100%',
    height: 250,
    position: 'relative',
  },
  headerBgImg: {
    width: '100%',
    height: '100%',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW16,
    paddingTop: 20, // Accommodate Status bar spacing
    paddingBottom: 10,
    backgroundColor: 'transparent',
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  backIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.textDark,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButtonCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  actionIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.textDark,
  },
  notificationDot: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#39B89A',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  heroContentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: MarginHW.PaddingW16,
    marginTop: 10,
    position: 'relative',
  },
  heroLeftCol: {
    flex: 1.3,
    paddingBottom: 10,
  },
  heroTitle: {
    fontSize: 22,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    lineHeight: 28,
  },
  heroTitleGreen: {
    color: Colors.TextColorGreenDark,
  },
  heroSubtitle: {
    fontSize: 10,
    fontFamily: fonts.OpenSans_Regular,
    color: '#4B5563',
    marginTop: 6,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3FAF6',
    borderWidth: 1,
    borderColor: '#D1FAE5',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    marginTop: 10,
  },
  heroBadgeText: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0D684D',
  },
  heroRightCol: {
    flex: 0.8,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    position: 'relative',
  },
  heroSaplingImg: {
    width: 90,
    height: 130,
    marginBottom: -10,
  },
  // Sections layout
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW16,
    marginTop: 10,
    marginBottom: 10,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 13.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.black,
  },
  sectionTitleLeaf: {
    width: 12,
    height: 12,
    tintColor: Colors.legacyGreen,
    marginLeft: 4,
  },
  viewAllRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewAllText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
    marginRight: 2,
  },
  // States list horizontal
  statesScroll: {
    paddingLeft: MarginHW.PaddingW16,
    paddingRight: 8,
  },
  stateCard: {
    width: 72,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#EFF2F0',
    padding: 5,
    alignItems: 'center',
    marginRight: 10,
    position: 'relative',
  },
  stateCardActive: {
    borderColor: Colors.TextColorLightGreen,
    backgroundColor: '#F4F9F6',
  },
  stateImg: {
    width: 58,
    height: 52,
    borderRadius: 6,
  },
  stateName: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#4B5563',
    marginTop: 4,
    textAlign: 'center',
  },
  stateNameActive: {
    color: Colors.TextColorLightGreen,
  },
  stateCheckBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: Colors.TextColorLightGreen,
    width: 14,
    height: 14,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  stateCheckIcon: {
    width: 8,
    height: 8,
    tintColor: '#FFFFFF',
  },
  // Projects list horizontal
  projectsScroll: {
    paddingLeft: MarginHW.PaddingW16,
    paddingRight: 8,
  },
  projectCard: {
    width: 160,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginRight: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 2,
  },
  projectImgContainer: {
    width: '100%',
    height: 95,
    position: 'relative',
  },
  projectImg: {
    width: '100%',
    height: '100%',
  },
  projectBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: '#354826',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  projectBadgeText: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
  },
  projectInfo: {
    padding: 8,
  },
  projectTitle: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  projectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  projectIcon: {
    width: 9,
    height: 9,
    tintColor: '#6B7280',
    marginRight: 4,
  },
  projectIconGreen: {
    tintColor: Colors.TextColorLightGreen,
  },
  projectText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
  },
  projectTextGreen: {
    color: Colors.TextColorLightGreen,
    fontFamily: fonts.OpenSans_Bold,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
  },
  paginationDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#D1D5DB',
    marginHorizontal: 3,
  },
  paginationDotActive: {
    backgroundColor: Colors.TextColorLightGreen,
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  // Categories horizontal
  categoriesScroll: {
    paddingLeft: MarginHW.PaddingW16,
    paddingRight: 8,
  },
  categoryCard: {
    width: 94,
    height: 125,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#EFF2F0',
    padding: 8,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryIconBg: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#F3FAF6',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  categoryIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  categoryTitle: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    textAlign: 'center',
    marginTop: 4,
  },
  categoryDesc: {
    fontSize: 7,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 1.5,
    lineHeight: 8.5,
  },
  categoryFooter: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
    marginTop: 4,
  },
  // Trust Badges Grid
  trustRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFF2F0',
    borderRadius: 10,
    marginHorizontal: MarginHW.PaddingW16,
    paddingVertical: 12,
    paddingHorizontal: 4,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.01,
    shadowRadius: 4,
    elevation: 1,
  },
  trustCol: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  trustIconBg: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#EEF6F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  trustIcon: {
    width: 12,
    height: 12,
    tintColor: Colors.TextColorLightGreen,
  },
  trustTitle: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    textAlign: 'center',
  },
  trustDesc: {
    fontSize: 6.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 1.5,
    lineHeight: 8,
  },
  // Tab Bar
  tabBarContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderColor: '#ECEFEF',
    paddingVertical: 6,
    height: 52,
    marginTop: 20,
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIcon: {
    width: 18,
    height: 18,
    tintColor: '#8E9A93',
  },
  tabIconActive: {
    tintColor: Colors.TextColorLightGreen,
  },
  tabLabel: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#8E9A93',
    marginTop: 2,
  },
  tabLabelActive: {
    color: Colors.TextColorLightGreen,
  },
});
