import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import fonts from '../../comman/fonts';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  // Top Header navigation row
  headerRow: {

    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW16,
    paddingTop: 10,
    backgroundColor: 'transparent',

  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.textDark,
  },
  stepperContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginLeft: 10,
    paddingVertical: 10,
    position: 'relative',
  },
  stepperLine: {
    position: 'absolute',
    left: 20,
    right: 20,
    top: 22,
    height: 1,
    backgroundColor: '#E2ECE5',
    zIndex: 1,
  },
  stepperLineActive: {
    position: 'absolute',
    left: 20,
    right: '50%',
    top: 22,
    height: 1,
    backgroundColor: Colors.legacyGreen,
    zIndex: 1.5,
  },
  stepItem: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  stepCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleActive: {
    borderColor: Colors.legacyGreen,
    backgroundColor: Colors.legacyGreen,
  },
  stepCircleCompleted: {
    borderColor: '#E6EFEA',
    backgroundColor: '#E6EFEA',
  },
  stepIcon: {
    width: 12,
    height: 12,
    tintColor: '#9CA3AF',
  },
  stepIconActive: {
    tintColor: '#FFFFFF',
  },
  stepIconCompleted: {
    width: 10,
    height: 10,
    tintColor: Colors.legacyGreen,
  },
  stepLabel: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: '#9CA3AF',
    marginTop: 2,
  },
  stepLabelActive: {
    color: Colors.legacyGreen,
  },
  // Hero section banner
  heroSection: {
    width: '100%',
    height: 240,
    overflow: 'hidden',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFill,

    paddingHorizontal: MarginHW.PaddingW16,
    paddingTop: 50,
    justifyContent: 'space-between',
  },
  heroTextContainer: {
    marginTop: 20,
  },
  heroTitle: {
    fontSize: FontsSize.size20,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.black,
  },
  heroName: {
    fontSize: FontsSize.size22,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
    marginTop: 4,
  },
  heroSubtitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.black,
    marginTop: 4,
    width: '75%',
  },
  heroPillsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  attributesCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 8,
    flex: 1,
    marginRight: 10,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
  },
  attributeItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pillIcon: {
    width: 16,
    height: 16,
    marginRight: 6,
    tintColor: Colors.legacyGreen,
  },
  attributeTextWrapper: {
    flexDirection: 'column',
  },
  attributeLabelText: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#6B7280',
    lineHeight: 9,
  },
  attributeValText: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
    lineHeight: 11,
    marginTop: 1,
  },
  verticalDivider: {
    width: 1,
    height: '60%',
    backgroundColor: '#E5E7EB',
  },
  gpsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
  },
  gpsIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.legacyGreen,
    marginRight: 6,
  },
  gpsTextWrapper: {
    flexDirection: 'column',
  },
  gpsText: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.legacyGreen,
    lineHeight: 9,
  },
  // Section Headers
  sectionContainer: {
    paddingHorizontal: MarginHW.PaddingW10,
    paddingVertical: 10,
    backgroundColor: '#fff',
    marginHorizontal: 5,
    borderRadius: 10,

  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  viewAllLink: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.legacyGreen,
  },
  // Quantity Selection Cards
  quantityList: {
    paddingBottom: 8,
  },
  quantityCard: {
    width: (width) / 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    padding: 8,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'space-between', shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  quantityCardActive: {
    borderColor: Colors.legacyGreen,
    backgroundColor: '#F4F9F6',
  },
  checkmarkBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: Colors.legacyGreen,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmarkText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: 'bold',
  },
  quantityIcon: {
    width: 44,
    height: 44,
    marginTop: 4,
  },
  customIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3FBF7',
    borderWidth: 1.5,
    borderColor: '#E6EFEA',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
  },
  customEditIcon: {
    width: 18,
    height: 18,
  },
  quantityTitle: {
    fontSize: 10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#374151',
    marginTop: 4,
  },
  quantityTitleActive: {
    color: Colors.legacyGreen,
  },
  priceText: {
    fontSize: 12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    marginTop: 2,
  },
  discountBadge: {
    backgroundColor: '#FFEBEA',
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginTop: 2,
  },
  discountBadgeActive: {
    backgroundColor: '#E6EFEA',
  },
  discountText: {
    fontSize: 7,
    fontFamily: fonts.OpenSans_Bold,
    color: '#D32F2F',
  },
  discountTextActive: {
    color: Colors.legacyGreen,
  },
  co2Text: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Medium,
    color: '#9CA3AF',
    marginTop: 6,
    textAlign: 'center',
  },
  co2TextActive: {
    color: Colors.legacyGreen,
  },
  customInputContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingVertical: 6,
  },
  customTextInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 6,
    width: '90%',
    height: 28,
    textAlign: 'center',
    fontSize: 11,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    padding: 0,
  },
  customChooseBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: Colors.legacyGreen,
    borderRadius: 6,
    paddingVertical: 3,
    paddingHorizontal: 8,
    marginTop: 4,
  },
  customChooseBtnText: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.legacyGreen,
  },
  // Info banner strip
  infoStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#edf5e5',
    borderRadius: 8,
    padding: 10,
    marginTop: 12,
  },
  infoStripIcon: {
    width: 14,
    height: 14,
    marginRight: 8,
  },
  infoStripText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#1E6B46',
    flex: 1,
  },
  // Project Cards
  projectsList: {
    paddingBottom: 8,
  },
  projectCard: {
    width: width / 2,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginRight: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  projectCardActive: {
    borderColor: Colors.legacyGreen,
    borderWidth: 1.5,
  },
  projectImageContainer: {
    width: '100%',
    height: 100,
  },
  projectImage: {
    width: '100%',
    height: '100%',
  },
  projectTag: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: Colors.legacyGreen,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
  },
  projectTagText: {
    color: '#FFFFFF',
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
  },
  projectSelector: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  projectSelectorSelected: {
    backgroundColor: Colors.legacyGreen,
    borderColor: Colors.legacyGreen,
  },
  projectContent: {
    padding: 12,
    minHeight: 110,
  },
  projectTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  projectTitle: {
    fontSize: 11.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  projectLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  projectLocIcon: {
    width: 10,
    height: 10,
    tintColor: Colors.legacyGreen,
    marginRight: 4,
  },
  projectLocation: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
  },
  projectDesc: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#4B5563',
    marginTop: 6,
    lineHeight: 14,
  },
  projectFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  plantedCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  plantedIcon: {
    width: 10,
    height: 10,
    tintColor: Colors.legacyGreen,
    marginRight: 4,
  },
  plantedText: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.legacyGreen,
  },
  // Impact summary cards grid
  impactCardContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F4F9F6',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2ECE5',
    paddingVertical: 14,
    paddingHorizontal: 8,
    marginTop: 10,
    justifyContent: 'space-between',
  },
  impactCol: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  impactIcon: {
    width: 22,
    height: 22,
    tintColor: Colors.legacyGreen,
    marginBottom: 6,
  },
  impactValue: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    textAlign: 'center',
  },
  impactLabel: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
    marginTop: 2,
    textAlign: 'center',
  },
  impactDivider: {
    width: 1,
    height: '60%',
    backgroundColor: '#E2ECE5',
  },
  // Trust banner
  trustBanner: {
    flexDirection: 'row',
    backgroundColor: '#F4F9F6',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2ECE5',
    paddingVertical: 14,
    paddingHorizontal: 8,
    justifyContent: 'space-between',
  },
  trustCol: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  trustDivider: {
    width: 1,
    height: '60%',
    backgroundColor: '#E2ECE5',
    alignSelf: 'center',
  },
  trustIconBg: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#EEF6F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  trustIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.legacyGreen,
  },
  trustTextCol: {
    flex: 1,
  },
  trustTitle: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
  },
  trustDesc: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#4B5563',
    marginTop: 2,
    lineHeight: 10,
  },
  // Main Action CTA & Footer lock info
  footerContainer: {
    marginTop: 30,
    paddingHorizontal: MarginHW.PaddingW16,
    alignItems: 'center',
  },
  actionButton: {
    width: '100%',
    height: 45,
    borderRadius: 10,
    overflow: 'hidden',
  },
  gradientBtn: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionBtnText: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
    marginRight: 8,
  },
  actionBtnArrow: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  secureTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  secureIcon: {
    fontSize: 10,
    color: '#6B7280',
    marginRight: 4,
  },
  secureText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
  },
});
