import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../../comman/Colors';
import fonts from '../../../comman/fonts';
import MarginHW from '../../../comman/MarginHW';
import FontsSize from '../../../comman/FontsSize';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFBFB',
  },
  scrollContent: {
    paddingBottom: 110, // space for sticky footer
  },
  // Hero section styles
  heroBg: {
    width: '100%',
    height: 260,
    position: 'relative',
  },
  heroBgImg: {
    width: '100%',
    height: '100%',
  },
  heroTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW16,
    paddingTop: 25,
    paddingBottom: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  backIcon: {
    width: 16,
    height: 16,
    tintColor: Colors.textDark,
  },
  howItWorksBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 6,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  howItWorksIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.TextColorLightGreen,
    marginRight: 6,
  },
  howItWorksText: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
  },
  heroContent: {
    paddingHorizontal: MarginHW.PaddingW16,
    marginTop: 1,
  },
  heroTitle: {
    fontSize: FontsSize.size20,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
    lineHeight: 25,
  },
  heroTitleGreen: {
    fontSize: FontsSize.size20,
    color: Colors.TextColorLightGreen,
  },
  heroTitleLeaf: {
    width: 18,
    height: 18,
    tintColor: Colors.TextColorLightGreen,
    marginLeft: 4,
  },
  heroSubtitle: {
    fontSize: 11.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#000',
    marginTop: 6,
    maxWidth: '65%',
    lineHeight: 16,
  },
  // Stepper styles
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    alignSelf: 'flex-start',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 2,
  },
  stepCircle: {
    width: 15,
    height: 15,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2ECE5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleActive: {
    backgroundColor: Colors.TextColorLightGreen,
    borderColor: Colors.TextColorLightGreen,
  },
  stepCirclePending: {
    borderColor: '#A4C6B1',
  },
  stepCircleText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#374151',
  },
  stepCircleTextActive: {
    color: '#FFFFFF',
  },
  stepCheckIcon: {
    width: 9,
    height: 9,
    tintColor: '#374151',
  },
  stepperLine: {
    width: 32,
    height: 1,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#D1DCD6',
    marginHorizontal: 4,
  },
  stepperLineActive: {
    borderColor: Colors.TextColorLightGreen,
  },
  stepperLineSplit: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  stepperLineHalf: {
    width: 16,
    height: 1,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#D1DCD6',
  },
  // Section general styles
  sectionContainer: {
    marginTop: 18,
    paddingHorizontal: MarginHW.PaddingW5,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    marginLeft: 4,
  },
  sectionTitleIcon: {
    width: 14,
    height: 14,
    marginRight: 6,
    tintColor: Colors.TextColorLightGreen,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
  },
  // Option Card Grid/Row
  optionsScroll: {
    paddingLeft: 4,
    paddingRight: 12,
    paddingTop: 6,
    paddingBottom: 4,
  },
  optionCard: {
    width: 70,
    height: 85,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    padding: 6,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 2,
    elevation: 1,
  },
  optionCardSelected: {
    borderColor: Colors.TextColorLightGreen,
    backgroundColor: '#FFFFFF',
  },
  optionIconWrapper: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  optionIconWrapperSelected: {
    // No background needed to match the mockup
  },
  optionIcon: {
    width: 18,
    height: 18,
    tintColor: Colors.TextColorLightGreen,
  },
  optionLabel: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#222222',
    textAlign: 'center',
    lineHeight: 12,
  },
  optionLabelSelected: {
    color: Colors.TextColorLightGreen,
  },
  optionCheckBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: Colors.TextColorLightGreen,
    width: 14,
    height: 14,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
  },
  optionCheckIconMini: {
    width: 8,
    height: 8,
    tintColor: '#FFFFFF',
  },
  // Section 2 horizontal priorities cards
  priorityCard: {
    width: 100,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    paddingHorizontal: 8,
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 2,
    elevation: 1,
  },
  priorityCardSelected: {
    borderColor: Colors.TextColorLightGreen,
    backgroundColor: '#FFFFFF',
  },
  priorityIcon: {
    width: 24,
    height: 24,
    marginRight: 6,
    tintColor: Colors.TextColorLightGreen,
  },
  priorityLabel: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#222222',
    textAlign: 'left',
    lineHeight: 12,
    flex: 1,
  },
  priorityLabelSelected: {
    color: Colors.TextColorLightGreen,
  },
  // Preferred Location styles
  locationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  locationCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    padding: 12,
    marginRight: 8,
  },
  locationPinIcon: {
    width: 22,
    height: 22,
    tintColor: Colors.TextColorLightGreen,
    marginRight: 8,
  },
  locationCardTextCol: {
    flex: 1,
  },
  locationStateName: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
  },
  locationChangeLink: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
    marginTop: 2,
  },
  locationInfoCard: {
    flex: 1.3,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F4F7F4',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 12,
  },
  locationInfoIcon: {
    width: 28,
    height: 28,
    tintColor: Colors.TextColorLightGreen,
    marginRight: 8,
  },
  locationInfoText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#4B5563',
    lineHeight: 13,
    flex: 1,
  },
  // Top Recommendations list
  recommendationsScroll: {
    paddingLeft: 4,
    paddingRight: 12,
  },
  bestMatchCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E6EFE8',
    padding: 12,
    width: 250,
    marginRight: 10,
    position: 'relative',
  },
  bestMatchTag: {
    position: 'absolute',
    top: 4,
    left: 4,
    backgroundColor: Colors.TextColorGreenDark,
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
    zIndex: 2,
  },
  bestMatchTagText: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
  },
  bestMatchTopRow: {
    flexDirection: 'row',
    marginTop: 4,
  },
  bestMatchImgContainer: {
    position: 'relative',
    width: 80,
    height: 85,
    borderRadius: 6,
    overflow: 'hidden',
  },
  bestMatchImg: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F3FAF6',
  },
  bestMatchDetails: {
    flex: 1,
    marginLeft: 10,
  },
  bestMatchTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  bestMatchTitle: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
    marginRight: 4,
  },
  gpsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E6EFE8',
    borderRadius: 3,
    paddingHorizontal: 4,
    paddingVertical: 1.5,
    marginTop: 2,
  },
  gpsBadgeIcon: {
    width: 7,
    height: 7,
    tintColor: Colors.TextColorLightGreen,
  },
  gpsBadgeText: {
    fontSize: 6.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
    marginLeft: 2,
  },
  matchRateBadge: {
    backgroundColor: '#E6F4EA',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2.5,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  matchRateText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
  },
  bestMatchBullets: {
    marginTop: 8,
  },
  bulletItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  bulletIcon: {
    width: 8,
    height: 8,
    tintColor: Colors.TextColorLightGreen,
    marginRight: 6,
  },
  bulletText: {
    fontSize: 8.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#4B5563',
  },
  bestMatchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.TextColorGreenDark,
    borderRadius: 6,
    paddingVertical: 8,
    marginTop: 10,
  },
  bestMatchBtnIcon: {
    width: 10,
    height: 10,
    tintColor: '#FFFFFF',
    marginRight: 6,
  },
  bestMatchBtnText: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
  },
  // Small Recommendation Card
  smallRecCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EFF2F0',
    padding: 10,
    width: 124,
    marginRight: 10,
    alignItems: 'center',
  },
  smallRecImgContainer: {
    position: 'relative',
    width: 60,
    height: 60,
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 8,
  },
  smallRecImg: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F3FAF6',
  },
  smallRecTitle: {
    fontSize: 11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
    textAlign: 'center',
  },
  smallRecMatchBadge: {
    position: 'absolute',
    top: 4,
    left: 4,
    backgroundColor: '#E6F4EA',
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1.5,
    zIndex: 2,
  },
  smallRecMatchText: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
  },
  smallRecBullets: {
    marginTop: 6,
    width: '100%',
  },
  smallRecBulletItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 3,
  },
  smallRecBulletIcon: {
    width: 6,
    height: 6,
    tintColor: Colors.TextColorLightGreen,
    marginRight: 4,
    marginTop: 2,
  },
  smallRecBulletText: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#6B7280',
    lineHeight: 10,
    flex: 1,
  },
  smallRecLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#EFF2F0',
    width: '100%',
    paddingTop: 6,
  },
  smallRecLinkText: {
    fontSize: 9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
  },
  // Comparison Table styles
  tableContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EFF2F0',
    overflow: 'hidden',
    marginTop: 8,
    marginHorizontal: 4,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#F4F7F4',
    borderBottomWidth: 1,
    borderBottomColor: '#EFF2F0',
    paddingVertical: 8,
  },
  tableHeaderCell: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
    textAlign: 'center',
    paddingHorizontal: 2,
  },
  tableDataRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#EFF2F0',
    paddingVertical: 8,
    alignItems: 'center',
  },
  tableCell: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Medium,
    color: Colors.textDark,
    textAlign: 'center',
    paddingHorizontal: 2,
  },
  treeCellContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 6,
  },
  treeCellIcon: {
    width: 12,
    height: 12,
    marginRight: 4,
  },
  treeCellText: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
  },
  dropIcon: {
    width: 6,
    height: 8,
    tintColor: '#3B82F6',
    marginRight: 2,
  },
  checkCircleIcon: {
    width: 10,
    height: 10,
    tintColor: Colors.TextColorLightGreen,
    alignSelf: 'center',
  },
  // Bottom summary banner
  bottomBanner: {
    backgroundColor: '#FAFBF9',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EFF2F0',
    padding: 12,
    marginHorizontal: MarginHW.PaddingW10,
    marginTop: 16,
  },
  bottomBannerTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  bottomBannerLeaf: {
    width: 16,
    height: 16,
    tintColor: Colors.TextColorLightGreen,
    marginRight: 8,
    marginTop: 2,
  },
  bottomBannerText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#4B5563',
    lineHeight: 13,
    flex: 1,
  },
  bottomBannerDivider: {
    height: 1,
    backgroundColor: '#EFF2F0',
    marginVertical: 4,
  },
  bottomBannerBadgesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  bottomBannerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  bottomBannerBadgeIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.TextColorLightGreen,
    marginRight: 4,
  },
  bottomBannerBadgeLabel: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
    lineHeight: 10,
    flex: 1,
  },
  bottomBannerBadgeDivider: {
    width: 1,
    height: 20,
    backgroundColor: '#E2ECE5',
    alignSelf: 'center',
  },
  // Sticky bottom footer
  stickyFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderColor: '#ECEFEF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    paddingBottom: 16,
  },
  primaryStickyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.TextColorGreenDark,
    borderRadius: 10,
    paddingVertical: 12,
  },
  primaryStickyBtnText: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
    marginRight: 6,
  },
  primaryStickyBtnArrow: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
  },
});
