import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../../comman/Colors';
import FontsSize from '../../../comman/FontsSize';
import fonts from '../../../comman/fonts';
import MarginHW from '../../../comman/MarginHW';
import ImageSize from '../../../comman/ImageSize';
import HWSize from '../../../comman/HWSize';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  scrollContent: {
    paddingBottom: 0,
  },

  // Header Styles
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW10,
    paddingTop: MarginHW.PaddingH8,
    paddingBottom: MarginHW.PaddingH10,
  },
  backButton: {
    width: 35,
    height: 35,
    borderRadius: 35 / 2,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
  },
  backIcon: {
    width: 18,
    height: 18,
    tintColor: Colors.textDark,
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: MarginHW.PaddingW4,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  headerCheckIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.shieldIconColor,
    marginLeft: MarginHW.MarginW4,
  },
  headerSubtitle: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: MarginHW.MarginH2,
    textAlign: 'center',
  },
  headerRightSecure: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size10,
    paddingVertical: MarginHW.PaddingH5,
    paddingHorizontal: MarginHW.PaddingW8,
  },
  headerSecureIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.shieldIconColor,
    marginRight: MarginHW.MarginW6,
  },
  headerSecureTextCol: {
    justifyContent: 'center',
  },
  headerSecureTextBold: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    lineHeight: 10,
  },
  headerSecureTextDesc: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    lineHeight: 10,
  },

  // Main Project Card
  projectCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH4,
    height: 120,
    overflow: 'hidden',
  },
  projectImageContainer: {
    width: '38%',
    height: '100%',
    position: 'relative',
  },
  projectImage: {
    width: '100%',
    height: '100%',
  },
  gpsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(21, 48, 25, 0.8)',
    borderRadius: 6,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: 4,
    position: 'absolute',
    bottom: 8,
    left: 8,
  },
  gpsIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW4,
  },
  gpsText: {
    fontSize: FontsSize.size8_5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
  projectInfo: {
    flex: 1,
    padding: 10,
    justifyContent: 'center',
  },
  projectHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  projectName: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    flex: 1,
    marginRight: MarginHW.MarginW4,
  },
  categoryBadge: {
    backgroundColor: '#EAF4EC',
    borderRadius: 3,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  categoryBadgeText: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#1E6B46',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  locationIcon: {
    width: 10,
    height: 10,
    tintColor: '#111827',
    marginRight: MarginHW.MarginW4,
  },
  locationText: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#111827',
  },
  projectDesc: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Medium,
    color: '#55665C',
    lineHeight: 12,
  },
  progressWrapper: {
    marginTop: MarginHW.MarginH8,
  },
  progressLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH4,
  },
  progressTreeIcon: {
    width: 12,
    height: 12,
    tintColor: '#1E6B46',
    marginRight: 4,
  },
  progressLabelText: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  progressLabelNormal: {
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
    fontSize: FontsSize.size10,
  },
  progressPercentText: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1E6B46',
    marginLeft: 'auto',
  },
  progressBarTrack: {
    height: 4,
    backgroundColor: '#E2EFE5',
    borderRadius: 2,
    overflow: 'hidden',
    bottom: 2,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#1E6B46',
    borderRadius: 2,
  },

  // Stats Grid Section
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH8,
  },
  statChip: {
    flex: 1,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
    borderRadius: FontsSize.size8,
    paddingVertical: MarginHW.PaddingH8,
    paddingHorizontal: MarginHW.PaddingW4,
    alignItems: 'center',
    marginHorizontal: MarginHW.MarginW3,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 1.5,
    elevation: 1,
  },
  statIconContainer: {
    width: ImageSize.ImageW28,
    height: ImageSize.ImageH28,
    borderRadius: ImageSize.ImageW14,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH4,
  },
  statIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.TextColorLightGreen,
  },
  statVal: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    textAlign: 'center',
  },
  statLabel: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: 1,
  },

  // Section Headers
  sectionTitle: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: '#55665C',
    marginBottom: 16,
  },

  // Impact Preview Card
  impactPreviewCard: {
    backgroundColor: '#F7FAF3',
    borderWidth: 1,
    borderColor: '#E6EFE6',
    borderRadius: 10,
    marginHorizontal: MarginHW.MarginW10,
    padding: 10,
    marginVertical: 15,
  },
  impactRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  impactColumn: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  impactIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#ECF2ED',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: MarginHW.MarginH6,
  },
  impactIcon: {
    width: 18,
    height: 18,
    tintColor: '#1A6836',
  },
  impactValue: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1A6836',
    textAlign: 'center',
    marginBottom: 2,
  },
  impactLabel: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Medium,
    color: '#55665C',
    textAlign: 'center',
    lineHeight: 12,
  },
  impactDivider: {
    width: 1,
    height: '70%',
    backgroundColor: Colors.borderGreenUltraLight,
    alignSelf: 'center',
  },

  // Review Selection Card
  reviewCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F0F0F0',
    borderRadius: 8,
    marginHorizontal: MarginHW.MarginW10,
    marginBottom: MarginHW.MarginH8,
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  reviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  reviewDivider: {
    height: 1,
    backgroundColor: '#F0F0F0',
    width: '100%',
  },
  selectionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  selectionThumbContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F6F9F7',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    overflow: 'hidden',
  },
  selectionThumb: {
    width: 24,
    height: 24,
  },
  selectionTextContainer: {
    flex: 1,
  },
  selectionLabel: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: '#55665C',
    marginBottom: 2,
  },
  selectionValue: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1A6836',
    marginBottom: 2,
  },
  selectionDesc: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: '#55665C',
  },
  changeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F9F6',
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  changeButtonIcon: {
    width: 10,
    height: 10,
    tintColor: '#1A6836',
    marginRight: 4,
  },
  changeButtonText: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#1A6836',
  },

  // Choose Contribution Amount
  amountGridScroll: {
    paddingHorizontal: MarginHW.MarginW10,
    paddingBottom: 10,
    paddingTop: 10,
  },
  amountCard: {
    width: 80,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    position: 'relative',
  },
  amountCardSelected: {
    borderColor: '#1A6836',
    borderWidth: 1,
    backgroundColor: '#F7FCF8',
  },
  amountCardValue: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  amountCardSelectedText: {
    color: '#1A6836',
  },
  amountCardTrees: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: '#55665C',
    marginTop: 4,
  },
  amountCardSelectedTrees: {
    color: '#1A6836',
    fontFamily: fonts.OpenSans_Medium,
  },
  tickBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#1A6836',
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tickIcon: {
    width: 10,
    height: 10,
    tintColor: Colors.white,
  },
  otherAmountContainer: {
    width: '100%',
    paddingHorizontal: MarginHW.MarginW10,
    marginBottom: MarginHW.MarginH8,
  },
  otherAmountWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    borderRadius: FontsSize.size8,
    paddingHorizontal: MarginHW.PaddingW10,
    height: 44,
  },
  otherAmountWrapperSelected: {
    borderColor: Colors.TextColorLightGreen,
    borderWidth: 1.5,
  },
  otherAmountCurrency: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginRight: 4,
  },
  otherAmountInput: {
    flex: 1,
    height: '100%',
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    padding: 0,
  },
  // Alert Banner
  alertGreenBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F7F4',
    borderRadius: 8,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: 4,
    marginBottom: MarginHW.MarginH10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  alertGreenIcon: {
    width: 16,
    height: 16,
    tintColor: '#1A6836',
    marginRight: 8,
  },
  alertGreenText: {
    flex: 1,
    fontSize: FontsSize.size9_5,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#1A6836',
  },

  // Grid for details & payment methods (stacked on mobile but styled neatly)
  formContainer: {
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH4,
  },
  detailsCard: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size12,
    padding: MarginHW.PaddingW12,
    marginBottom: MarginHW.MarginH8,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2.5,
    elevation: 2,
  },
  formTitle: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH10,
  },
  formField: {
    marginBottom: MarginHW.MarginH10,
  },
  inputLabel: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_SemiBold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH4,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    borderRadius: 8,
    paddingHorizontal: MarginHW.PaddingW10,
    height: 44,
  },
  inputWrapperActive: {
    borderColor: Colors.TextColorLightGreen,
    borderWidth: 1.2,
  },
  textInput: {
    flex: 1,
    height: '100%',
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textDark,
    padding: 0,
  },
  phonePrefixBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
    borderRightWidth: 1,
    borderRightColor: Colors.borderGrey,
    paddingRight: MarginHW.PaddingW8,
    height: '60%',
  },
  flagIcon: {
    width: 18,
    height: 12,
    borderRadius: 1,
    marginRight: 4,
  },
  phonePrefixText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_SemiBold,
    color: Colors.textDark,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: MarginHW.MarginH6,
    paddingRight: MarginHW.PaddingW8,
  },
  checkboxSquare: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: Colors.TextColorLightGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: MarginHW.MarginW8,
    marginTop: 2,
  },
  checkboxSquareChecked: {
    backgroundColor: Colors.TextColorLightGreen,
  },
  checkboxCheckIcon: {
    width: 10,
    height: 10,
    tintColor: Colors.white,
  },
  checkboxLabelCol: {
    flex: 1,
  },
  checkboxLabelText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_SemiBold,
    color: Colors.textDark,
    lineHeight: 14,
  },
  checkboxDescText: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: 1,
  },

  // Payment Methods
  paymentMethodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW8,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    borderRadius: 8,
    marginBottom: MarginHW.MarginH8,
    backgroundColor: Colors.white,
  },
  paymentMethodRowSelected: {
    borderColor: Colors.TextColorLightGreen,
    backgroundColor: Colors.bgGreenLight,
  },
  methodInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  methodIconCircle: {
    width: ImageSize.ImageW28,
    height: ImageSize.ImageH28,
    borderRadius: ImageSize.ImageW14,
    backgroundColor: Colors.lightgray,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: MarginHW.MarginW8,
  },
  methodLogoImg: {
    width: '65%',
    height: '65%',
  },
  methodTitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  methodDesc: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: 1,
  },
  radioButtonOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: Colors.switchInactiveBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonOuterSelected: {
    borderColor: Colors.TextColorLightGreen,
  },
  radioButtonInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.TextColorLightGreen,
  },

  // Security logos card
  securityLogosCard: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size12,
    marginHorizontal: MarginHW.MarginW10,
    padding: MarginHW.PaddingW12,
    alignItems: 'center',
    marginBottom: MarginHW.MarginH1,
  },
  securityTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  securityTextIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.TextColorLightGreen,
    marginRight: MarginHW.MarginW6,
  },
  securityTextTitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorGreenDark,
  },
  securityTextDesc: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
  },
  partnerBadgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: MarginHW.MarginH5,
    width: '100%',
  },
  partnerTextBadge: {
    borderWidth: 0.5,
    borderColor: Colors.borderGreenLight,
    borderRadius: 3,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: 2,
    backgroundColor: Colors.lightgray,
    marginHorizontal: 6,
  },
  partnerTextLabel: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorGreenDark,
  },
  partnerTextLabelRazor: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_ExtraBold,
    color: '#0052FF',
    fontStyle: 'italic',
  },

  // Sticky Bottom Footer Bar
  bottomFloatingBar: {
    backgroundColor: Colors.white,
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW10,
    shadowColor: Colors.black,

  },
  bottomSummaryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F0F0F0',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  bottomThumbImg: {
    width: 70,
    height: 50,
    marginRight: 12,
  },
  bottomTextCol: {
    flex: 1,
    justifyContent: 'center',
  },
  bottomSupportingLabel: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: '#55665C',
    marginBottom: 2,
  },
  bottomProjectName: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1A6836',
  },
  bottomDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#F0F0F0',
    marginHorizontal: 12,
  },
  bottomAmountCol: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingRight: 4,
  },
  bottomAmountLabel: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: '#55665C',
    marginBottom: 2,
  },
  bottomAmountVal: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: '#1A6836',
  },
  bottomAmountQty: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: '#55665C',
    marginTop: 2,
  },
  bottomButtonBox: {
    width: '100%',
  },

  paySecurelyButton: {
    backgroundColor: Colors.TextColorLightGreen,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW10,
    width: '100%',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  payButtonText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
  payButtonArrow: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
  bottomRedirectText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Medium,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: MarginHW.MarginH1,
    alignSelf: 'center',
  },
  bottomRedirectIcon: {
    width: ImageSize.ImageH12,
    height: ImageSize.ImageH12,
    tintColor: Colors.textLabelGrey,
    marginRight: MarginHW.MarginH2,
  },
});
