import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../../comman/Colors';
import FontsSize from '../../../comman/FontsSize';
import fonts from '../../../comman/fonts';
import MarginHW from '../../../comman/MarginHW';
import ImageSize from '../../../comman/ImageSize';
import HWSize from '../../../comman/HWSize';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg,
  },
  scrollContent: {
    paddingBottom: 0,
  },

  // Header Styles
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW10,
    paddingTop: MarginHW.PaddingH8,
    paddingBottom: MarginHW.PaddingH10,
    minHeight: HWSize.H_Height64,
  },
  backButton: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH35,
    borderRadius: ImageSize.ImageW18,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
  },
  backIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.textDark,
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: MarginHW.PaddingW4,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: FontsSize.size16,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  headerCheckIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.shieldIconColor,
    marginLeft: MarginHW.MarginW4,
  },
  headerSubtitle: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: MarginHW.MarginH2,
    textAlign: 'center',
  },
  headerRightSecure: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size10,
    paddingVertical: MarginHW.PaddingH5,
    paddingHorizontal: MarginHW.PaddingW8,
  },
  headerSecureIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.shieldIconColor,
    marginRight: MarginHW.MarginW6,
  },
  headerSecureTextCol: {
    justifyContent: 'center',
  },
  headerSecureTextBold: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    lineHeight: 10,
  },
  headerSecureTextDesc: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    lineHeight: 10,
  },

  // Main Project Card
  projectCard: {
    backgroundColor: Colors.white,
    borderRadius: FontsSize.size12,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH4,
    padding: MarginHW.PaddingW10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  projectImageContainer: {
    width: '100%',
    height: 160,
    minHeight: 150,
    borderRadius: FontsSize.size10,
    overflow: 'hidden',
    position: 'relative',
  },
  projectImage: {
    width: '100%',
    height: '100%',
  },
  gpsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 4,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: MarginHW.PaddingH3,
    position: 'absolute',
    bottom: MarginHW.MarginH6,
    left: MarginHW.MarginW6,
  },
  gpsIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.white,
    marginRight: MarginHW.MarginW4,
  },
  gpsText: {
    fontSize: FontsSize.size8_5,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
  projectInfo: {
    marginTop: MarginHW.MarginH10,
  },
  projectHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  projectName: {
    fontSize: FontsSize.size15,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    flex: 1,
    marginRight: MarginHW.MarginW8,
  },
  categoryBadge: {
    backgroundColor: Colors.badgeGreenBg,
    borderRadius: 4,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: MarginHW.PaddingH3,
  },
  categoryBadgeText: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: MarginHW.MarginH4,
  },
  locationIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.textLabelGrey,
    marginRight: MarginHW.MarginW4,
  },
  locationText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Medium,
    color: Colors.textLabelGrey,
  },
  projectDesc: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.bannerBenefitLabel,
    marginTop: MarginHW.MarginH6,
    lineHeight: 16,
  },
  progressWrapper: {
    marginTop: MarginHW.MarginH12,
  },
  progressLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: MarginHW.MarginH4,
  },
  progressLabelText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  progressLabelNormal: {
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  progressPercentText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: Colors.borderGreenLight,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: Colors.TextColorLightGreen,
    borderRadius: 3,
  },

  // Stats Grid Section
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH8,
  },
  statChip: {
    flex: 1,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenUltraLight,
    borderRadius: FontsSize.size8,
    paddingVertical: MarginHW.PaddingH8,
    paddingHorizontal: MarginHW.PaddingW4,
    alignItems: 'center',
    marginHorizontal: MarginHW.MarginW3,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 1.5,
    elevation: 1,
  },
  statIconContainer: {
    width: ImageSize.ImageW28,
    height: ImageSize.ImageH28,
    borderRadius: ImageSize.ImageW14,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MarginHW.MarginH4,
  },
  statIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.TextColorLightGreen,
  },
  statVal: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    textAlign: 'center',
  },
  statLabel: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: 1,
  },

  // Section Headers
  sectionTitle: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH1,
    marginBottom: MarginHW.MarginH4,
  },
  sectionSubtitle: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginHorizontal: MarginHW.MarginW10,
    marginBottom: MarginHW.MarginH8,
  },

  // Impact Preview Card
  impactPreviewCard: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size12,
    marginHorizontal: MarginHW.MarginW10,
    padding: MarginHW.PaddingW12,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  impactRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  impactColumn: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  impactIconCircle: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH35,
    borderRadius: ImageSize.ImageW18,
    backgroundColor: Colors.bgGreenLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: MarginHW.MarginH6,
  },
  impactIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.TextColorLightGreen,
  },
  impactValue: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
    textAlign: 'center',
  },
  impactLabel: {
    fontSize: FontsSize.size8_5,
    fontFamily: fonts.OpenSans_Medium,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: 2,
    lineHeight: 11,
  },
  impactDivider: {
    width: 1,
    height: '70%',
    backgroundColor: Colors.borderGreenUltraLight,
    alignSelf: 'center',
  },

  // Review Selection Card
  selectionCard: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size10,
    marginHorizontal: MarginHW.MarginW10,
    padding: MarginHW.PaddingW10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: MarginHW.MarginH8,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  selectionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  selectionThumbContainer: {
    width: ImageSize.ImageW40,
    height: ImageSize.ImageH40,
    borderRadius: 8,
    backgroundColor: Colors.bgGreenLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: MarginHW.MarginW8,
    overflow: 'hidden',
  },
  selectionThumb: {
    width: '80%',
    height: '80%',
  },
  selectionTextContainer: {
    flex: 1,
  },
  selectionLabel: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  selectionValue: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginTop: 1,
  },
  selectionDesc: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.bannerBenefitLabel,
    marginTop: 1,
  },
  changeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.lightgray,
    borderWidth: 0.8,
    borderColor: Colors.borderGrey,
    borderRadius: 6,
    paddingVertical: MarginHW.PaddingH5,
    paddingHorizontal: MarginHW.PaddingW8,
  },
  changeButtonIcon: {
    width: ImageSize.ImageW12,
    height: ImageSize.ImageH12,
    tintColor: Colors.textDark,
    marginRight: 4,
  },
  changeButtonText: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDark,
  },

  // Choose Contribution Amount
  amountGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginHorizontal: MarginHW.MarginW10,
  },
  amountCard: {
    width: '31%',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    borderRadius: FontsSize.size8,
    paddingVertical: MarginHW.PaddingH10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: MarginHW.MarginH8,
    position: 'relative',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 1.5,
    elevation: 1,
  },
  amountCardSelected: {
    borderColor: Colors.TextColorLightGreen,
    borderWidth: 1.5,
    backgroundColor: Colors.bgGreenLight,
  },
  amountCardValue: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  amountCardSelectedText: {
    color: Colors.TextColorLightGreen,
  },
  amountCardTrees: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: 2,
  },
  amountCardSelectedTrees: {
    color: Colors.TextColorLightGreen,
    fontFamily: fonts.OpenSans_Bold,
  },
  tickBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: Colors.TextColorLightGreen,
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tickIcon: {
    width: 9,
    height: 9,
    tintColor: Colors.white,
  },
  otherAmountContainer: {
    width: '100%',
    marginTop: MarginHW.MarginH4,
    marginBottom: MarginHW.MarginH8,
  },
  otherAmountWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    borderRadius: FontsSize.size8,
    paddingHorizontal: MarginHW.PaddingW10,
    height: 44,
  },
  otherAmountWrapperSelected: {
    borderColor: Colors.TextColorLightGreen,
    borderWidth: 1.5,
  },
  otherAmountCurrency: {
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginRight: 4,
  },
  otherAmountInput: {
    flex: 1,
    height: '100%',
    fontSize: FontsSize.size14,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    padding: 0,
  },
  alertGreenBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.bannerBgGreen,
    borderColor: Colors.bannerBorderGreen,
    borderWidth: 1,
    borderRadius: FontsSize.size8,
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH4,
    paddingVertical: MarginHW.PaddingH8,
    paddingHorizontal: MarginHW.PaddingW10,
  },
  alertGreenIcon: {
    width: ImageSize.ImageW14,
    height: ImageSize.ImageH14,
    tintColor: Colors.TextColorLightGreen,
    marginRight: MarginHW.MarginW8,
  },
  alertGreenText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Medium,
    color: Colors.TextColorGreenDark,
    flex: 1,
  },

  // Grid for details & payment methods (stacked on mobile but styled neatly)
  formContainer: {
    marginHorizontal: MarginHW.MarginW10,
    marginTop: MarginHW.MarginH4,
  },
  detailsCard: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size12,
    padding: MarginHW.PaddingW12,
    marginBottom: MarginHW.MarginH8,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2.5,
    elevation: 2,
  },
  formTitle: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH10,
  },
  formField: {
    marginBottom: MarginHW.MarginH10,
  },
  inputLabel: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_SemiBold,
    color: Colors.textDarkGreen,
    marginBottom: MarginHW.MarginH4,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    borderRadius: 8,
    paddingHorizontal: MarginHW.PaddingW10,
    height: 44,
  },
  inputWrapperActive: {
    borderColor: Colors.TextColorLightGreen,
    borderWidth: 1.2,
  },
  textInput: {
    flex: 1,
    height: '100%',
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textDark,
    padding: 0,
  },
  phonePrefixBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: MarginHW.MarginW8,
    borderRightWidth: 1,
    borderRightColor: Colors.borderGrey,
    paddingRight: MarginHW.PaddingW8,
    height: '60%',
  },
  flagIcon: {
    width: 18,
    height: 12,
    borderRadius: 1,
    marginRight: 4,
  },
  phonePrefixText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_SemiBold,
    color: Colors.textDark,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: MarginHW.MarginH6,
    paddingRight: MarginHW.PaddingW8,
  },
  checkboxSquare: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: Colors.TextColorLightGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: MarginHW.MarginW8,
    marginTop: 2,
  },
  checkboxSquareChecked: {
    backgroundColor: Colors.TextColorLightGreen,
  },
  checkboxCheckIcon: {
    width: 10,
    height: 10,
    tintColor: Colors.white,
  },
  checkboxLabelCol: {
    flex: 1,
  },
  checkboxLabelText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_SemiBold,
    color: Colors.textDark,
    lineHeight: 14,
  },
  checkboxDescText: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: 1,
  },

  // Payment Methods
  paymentMethodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW8,
    borderWidth: 1,
    borderColor: Colors.borderGrey,
    borderRadius: 8,
    marginBottom: MarginHW.MarginH8,
    backgroundColor: Colors.white,
  },
  paymentMethodRowSelected: {
    borderColor: Colors.TextColorLightGreen,
    backgroundColor: Colors.bgGreenLight,
  },
  methodInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  methodIconCircle: {
    width: ImageSize.ImageW28,
    height: ImageSize.ImageH28,
    borderRadius: ImageSize.ImageW14,
    backgroundColor: Colors.lightgray,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: MarginHW.MarginW8,
  },
  methodLogoImg: {
    width: '65%',
    height: '65%',
  },
  methodTitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  methodDesc: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginTop: 1,
  },
  radioButtonOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: Colors.switchInactiveBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonOuterSelected: {
    borderColor: Colors.TextColorLightGreen,
  },
  radioButtonInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.TextColorLightGreen,
  },

  // Security logos card
  securityLogosCard: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderGreenLight,
    borderRadius: FontsSize.size12,
    marginHorizontal: MarginHW.MarginW10,
    padding: MarginHW.PaddingW12,
    alignItems: 'center',
    marginBottom: MarginHW.MarginH1,
  },
  securityTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  securityTextIcon: {
    width: ImageSize.ImageW18,
    height: ImageSize.ImageH18,
    tintColor: Colors.TextColorLightGreen,
    marginRight: MarginHW.MarginW6,
  },
  securityTextTitle: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorGreenDark,
  },
  securityTextDesc: {
    fontSize: FontsSize.size10,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    textAlign: 'center',
  },
  partnerBadgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: MarginHW.MarginH5,
    width: '100%',
  },
  partnerTextBadge: {
    borderWidth: 0.5,
    borderColor: Colors.borderGreenLight,
    borderRadius: 3,
    paddingHorizontal: MarginHW.PaddingW6,
    paddingVertical: 2,
    backgroundColor: Colors.lightgray,
    marginHorizontal: 6,
  },
  partnerTextLabel: {
    fontSize: FontsSize.size9,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorGreenDark,
  },
  partnerTextLabelRazor: {
    fontSize: FontsSize.size8,
    fontFamily: fonts.OpenSans_ExtraBold,
    color: '#0052FF',
    fontStyle: 'italic',
  },

  // Sticky Bottom Footer Bar
  bottomFloatingBar: {
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.borderGreenLight,
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 10,
  },
  bottomMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bottomLeftInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.1,
    marginRight: MarginHW.MarginW8,
  },
  bottomThumbCircle: {
    width: ImageSize.ImageW35,
    height: ImageSize.ImageH35,
    borderRadius: ImageSize.ImageW18,
    backgroundColor: Colors.bgGreenLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW6,
  },
  bottomThumbImg: {
    width: '90%',
    height: '90%',
  },
  bottomTextCol: {
    flex: 1,
  },
  bottomSupportingLabel: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  bottomProjectName: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.textDarkGreen,
  },
  bottomAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 1,
  },
  bottomAmountLabel: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
  },
  bottomAmountVal: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.TextColorLightGreen,
    marginLeft: 3,
  },
  bottomAmountQty: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Regular,
    color: Colors.textLabelGrey,
    marginLeft: 4,
  },
  bottomButtonBox: {
    flex: 0.9,
    alignItems: 'flex-end',
  },
  paySecurelyButton: {
    backgroundColor: Colors.TextColorLightGreen,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: MarginHW.PaddingH10,
    paddingHorizontal: MarginHW.PaddingW10,
    width: '100%',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  payButtonText: {
    fontSize: FontsSize.size12,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
  payButtonArrow: {
    fontSize: FontsSize.size13,
    fontFamily: fonts.OpenSans_Bold,
    color: Colors.white,
  },
  bottomRedirectText: {
    fontSize: FontsSize.size11,
    fontFamily: fonts.OpenSans_Medium,
    color: Colors.textLabelGrey,
    textAlign: 'center',
    marginTop: MarginHW.MarginH1,
    alignSelf: 'center',
  },
  bottomRedirectIcon: {
    width: ImageSize.ImageH12,
    height: ImageSize.ImageH12,
    tintColor: Colors.textLabelGrey,
    marginRight: MarginHW.MarginH2,
  },
});
