import { Dimensions, StyleSheet } from 'react-native';
import fonts from '../../../../comman/fonts';
import FontsSize from '../../../../comman/FontsSize';
import { Colors } from '../../../../comman/Colors';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    container: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 40,
    },
    headerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        marginTop: 30,
        backgroundColor: '#F9FAFB',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerLogo: {
        width: 32,
        height: 32,
        marginRight: 12,
    },
    headerTextCol: {
        justifyContent: 'center',
    },
    greetingTitle: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 2,
    },
    greetingSubtitle: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    notificationBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    notificationIcon: {
        width: 18,
        height: 18,
        tintColor: '#4B5563',
    },
    profileBtn: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    profileImg: {
        width: 40,
        height: 40,
        borderRadius: 20,
        marginRight: 8,
    },
    profileTextCol: {
        justifyContent: 'center',
    },
    profileName: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    profileRole: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#0A5F35',
    },
    topStatsScrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    topStatsCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 8,
        marginHorizontal: 12,
        marginVertical: 15,
        flexDirection: 'row',
        flexWrap: 'nowrap',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    statCol: {
        alignItems: 'center',
    },
    statIconCircle: {
        width: 32,
        height: 32,
        borderRadius: 32 / 2,
        backgroundColor: Colors.listBg,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 6,
    },
    statIcon: {
        width: 16,
        height: 16,
        tintColor: Colors.legacyGreen,
    },
    statValue: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 2,
    },
    statLabel: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
        textAlign: 'center',
    },
    statSubLabel: {
        fontSize: 7,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        textAlign: 'center',
        marginTop: 2,
    },
    statDivider: {
        width: 1,
        height: '60%',
        backgroundColor: '#E5E7EB',
        marginHorizontal: 2,
        alignSelf: 'center',
    },
    carbonRingContainer: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: 3,
        borderColor: Colors.legacyGreen,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 6,
    },
    carbonRingValue: {
        fontSize: 8,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    statLabelNeutral: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_Bold,
        color: Colors.legacyGreen,
        textAlign: 'center',
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginHorizontal: 20,
        marginBottom: 12,
        marginTop: 8,
    },
    sectionTitle: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    sectionLink: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    contributionCard: {
        marginHorizontal: 20,
        marginBottom: 24,
        borderRadius: 10,
        overflow: 'hidden',
        height: 320,
    },
    contributionBg: {
        width: '100%',
        height: '100%',
    },
    contributionOverlay: {
        flex: 1,
        backgroundColor: 'transparent',
        paddingTop: 24,
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    contributionTitle: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    contributionStatsBox: {
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        paddingVertical: 20,
        paddingHorizontal: 16,
        width: '55%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
        alignSelf: 'flex-end',
        marginTop: 'auto',
    },
    contribStatItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    contribStatIconCircle: {
        width: 32,
        height: 32,
        borderRadius: 32 / 2,
        backgroundColor: Colors.listBg,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    contribStatIcon: {
        width: 16,
        height: 16,
        tintColor: Colors.greenthem,
    },
    contribStatValue: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: Colors.greenthem,
        marginBottom: 2,
    },
    contribStatLabel: {
        fontSize: 8,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#4B5563',
    },
    plantationCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    plantationRow: {
        flexDirection: 'row',
        marginBottom: 16,
    },
    plantationImg: {
        width: 80,
        height: 80,
        borderRadius: 8,
        marginRight: 16,
    },
    plantationInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    plantationTitle: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 4,
    },
    plantationLocation: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        marginBottom: 8,
    },
    statusTagComplete: {
        backgroundColor: '#F0FDF4',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        alignSelf: 'flex-start',
    },
    statusTagTextComplete: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    statusTagMonitoring: {
        backgroundColor: '#FFFBEB',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        alignSelf: 'flex-start',
    },
    statusTagTextMonitoring: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#F59E0B',
    },
    progressRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    progressBarContainer: {
        flex: 1,
        height: 6,
        backgroundColor: '#F3F4F6',
        borderRadius: 3,
        marginRight: 12,
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#0A5F35',
        borderRadius: 3,
    },
    progressText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        width: 32,
        textAlign: 'right',
    },
    trackBtn: {
        width: '100%',
        paddingVertical: 10,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        alignItems: 'center',
    },
    trackBtnText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    horizontalScrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    growthUpdatesContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 24,
    },
    growthUpdatesHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    growthUpdateCard: {
        width: Dimensions.get('screen').width / 3 - 30,
        height: 120,
        borderRadius: 8,
        overflow: 'hidden',
        position: 'relative',
    },
    growthUpdateImg: {
        width: Dimensions.get('screen').width / 3 - 20,
        height: '100%',
    },
    growthUpdateTag: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        backgroundColor: Colors.legacyGreen,
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderTopRightRadius: 8,
        borderBottomLeftRadius: 12,
    },
    growthUpdateTagText: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
    },
    growthUpdatesFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 16,
    },
    footerIcon: {
        width: 18,
        height: 18,
        tintColor: Colors.legacyGreen,
        marginRight: 8,
    },
    footerText: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#4B5563',
    },
    growthUpdateFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 20,
        marginBottom: 24,
    },

    certificatesContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 24,
    },
    certificateItemCard: {
        width: Dimensions.get('screen').width / 3 - 32,
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        padding: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        alignItems: 'center',
    },
    certIcon: {
        width: 32,
        height: 32,
        marginBottom: 8,
    },
    certTitle: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        textAlign: 'center',
        marginBottom: 16,
    },
    certDownloadBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: Colors.greenthem,
        width: '100%',
    },
    certDownloadText: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: Colors.greenthem,
        marginRight: 4,
    },
    certDownloadIcon: {
        width: 10,
        height: 10,
        tintColor: Colors.greenthem,
    },
    infoIcon: {
        width: 16,
        height: 16,
        tintColor: '#6B7280',
    },
    journeyCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    journeyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    journeyRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    journeyLeftCol: {
        alignItems: 'center',
        marginRight: 24,
    },
    journeyRingContainer: {
        width: 120,
        height: 120,
        borderRadius: 70,
        borderWidth: 10,
        borderColor: Colors.greenthem,
        borderTopColor: '#d1fae5',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    journeyInnerImg: {
        width: 50,
        height: 50,
        tintColor: Colors.greenthem
    },
    journeyInfo: {
        flex: 1,
    },
    journeyLabel: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#4B5563',
        marginBottom: 2,
    },
    journeyValue: {
        fontSize: 20,
        fontFamily: fonts.OpenSans_Bold,
        color: Colors.greenthem,
        marginBottom: 2,
    },
    journeyUnit: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#4B5563',
    },
    journeyDivider: {
        height: 1,
        backgroundColor: '#E5E7EB',
        width: '100%',
        marginVertical: 8,
    },
    journeyStatusBox: {
        backgroundColor: '#F0FDF4',
        padding: 12,
        borderRadius: 8,
        marginTop: 8,
    },
    journeyStatusLabel: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 4,
    },
    journeyStatusValue: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: Colors.greenthem,
        marginBottom: 4,
    },
    journeyStatusSub: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
    },
    journeyFooterText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: Colors.greenthem,
    },
    quickActionsContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    quickActionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    quickActionBtn: {
        width: '48%',
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        alignItems: 'center',
    },
    quickActionIcon: {
        width: 32,
        height: 32,
        marginBottom: 12,
    },
    quickActionTitle: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        textAlign: 'center',
        marginBottom: 4,
    },
    quickActionDesc: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        textAlign: 'center',
    },
    feedHeader: {
        marginBottom: 20,
    },
    feedCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    feedItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 20
    },
    feedIconCircleGreen: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: Colors.greenthem,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    feedIconCircleGray: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F0FDF4',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    feedIconWhite: {
        width: 14,
        height: 14,
        tintColor: '#FFFFFF',
    },
    feedIconGray: {
        width: 14,
        height: 14,
        tintColor: Colors.greenthem,
    },
    feedInfo: {
        flex: 1,
    },
    feedDate: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        marginBottom: 2,
    },
    feedText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
    },
    feedLine: {
        width: 2,
        height: 24,
        backgroundColor: '#E5E7EB',
        marginLeft: 15,
        marginVertical: 4,
    },
    feedViewAllBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 16,
        paddingVertical: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: Colors.greenthem,
    },
    feedViewAllText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: Colors.greenthem,
    },
    cardHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    mapCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    mapRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    mapImg: {
        width: 140,
        height: 160,
        marginRight: 16,
        borderRadius: 8,
    },
    statesList: {
        flex: 1,
    },
    stateItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    stateIconCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F0FDF4',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    stateIcon: {
        width: 16,
        height: 16,
        tintColor: Colors.greenthem,
    },
    stateTitle: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    stateSub: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
    },
    stateValue: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    achievementsContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    achievementCard: {
        width: '31%',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    achievementRing: {
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 1,
        borderColor: Colors.greenthem,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    achievementIcon: {
        width: 48,
        height: 48,
        borderRadius: 48 / 2
    },
    achievementTitle: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        textAlign: 'center',
        marginBottom: 4,
    },
    achievementDesc: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 8,
    },
    achievementStatus: {
        backgroundColor: '#F0FDF4',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    achievementStatusText: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    bottomBannerCard: {
        backgroundColor: '#F4FBF6',
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 24,
        marginHorizontal: 20,
        marginBottom: 24,
        borderRadius: 12,
    },
    bottomBannerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    bottomBannerImg: {
        width: 80,
        height: 80,
        marginRight: 12,
    },
    bottomBannerInfo: {
        flex: 1,
    },
    bottomBannerText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#0A5F35',
        lineHeight: 18,
    },
    bottomBannerStatsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#D1D5DB',
    },
    verticalDivider: {
        width: 1,
        height: 30,
        backgroundColor: '#D1D5DB',
    },
    bottomBannerStatItem: {
        alignItems: 'center',
    },
    bottomBannerStatValue: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    bottomBannerStatUnit: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
    },
    bottomBannerStatLabel: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
        marginTop: 2,
    },
    continueBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#0A5F35',
        marginHorizontal: 20,
        marginBottom: 10,
        paddingVertical: 16,
        borderRadius: 8,
    },
    continueBtnIconLeft: {
        width: 18,
        height: 18,
        tintColor: '#FFFFFF',
        marginRight: 8,
    },
    continueBtnText: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
        marginRight: 8,
    },
    continueBtnArrow: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
    },
});
