
import { getLanguage } from './i18n';

const translations: Record<'en' | 'hi', Record<string, string>> = {
	en: {
		AppName: 'Store Pedia',
		MobileNumber: 'Mobile number',
		LoginButton: 'Log in',
		LogOut: 'Log Out',
		NotAvailable: 'N/A',
		NoRecord: "No Record Found",
		PlantNameLabel: 'Plant Name',
		ScientificNameLabel: 'Scientific Name',
		CO2AbsorptionLabel: 'CO₂ Absorption',
		MaturityLabel: 'Maturity',
		TreeHeightLabel: 'Tree Height',
		RateLabel: 'Rate',
		Close: 'Close',
		Cancel: 'Cancel',
		Loading: 'Loading...',
		Preferences: "Preferences",
		PrivacyPolicy: "Privacy Policy",
		PushNotifications: "Push Notifications",
		Delete: "Delete",
		Logout: "Logout",
		logout_sure: 'Are you sure you want to logout?',

		AppOpening_PlantTitle: 'PLANT.',
		AppOpening_TrackTitle: 'TRACK.',
		AppOpening_ImpactTitle: 'IMPACT',
		AppOpening_Subtitle1: 'Plant verified trees.',
		AppOpening_Subtitle2: 'Track growth.',
		AppOpening_Subtitle3: 'Leave a ',
		AppOpening_SubtitleLegacy: 'legacy',
		AppOpening_GetStarted: 'Get Started',
		AppOpening_AlreadyHaveAccount: 'Already have an account? ',
		AppOpening_SignIn: 'Sign In',
		AppOpening_VerifiedPlantations: 'VERIFIED\nPLANTATIONS',
		AppOpening_GPSTracked: 'GPS\nTRACKED',
		AppOpening_RealImpact: 'REAL\nIMPACT',
		AppOpening_TreesPlanted: 'TREES PLANTED',
		AppOpening_CO2Offset: 'CO₂ OFFSET',
		AppOpening_SurvivalRate: 'SURVIVAL RATE',
		SignIn_Subtitle: 'Enter your mobile number to continue.',
		SignIn_Title: 'Sign In',
		SignIn_MobilePlaceholder: 'Enter mobile number',
		SignIn_SendOTP: 'Send OTP',
		Otp_LogoSubtitle: 'Plant. Track. Impact.',
		Otp_VerifyTitle: 'Verify OTP',
		Otp_EnterCodeSent: 'Enter the 6-digit verification code sent to',
		Otp_SecureVerification: 'Secure mobile verification',
		Otp_ExpiresIn: 'Code expires in',
		Otp_DidNotReceive: "Didn't receive OTP? ",
		Otp_Resend: 'Resend OTP',
		Otp_AgreeTo: 'By continuing, you agree to our ',
		Otp_TermsAndConditions: 'Terms & Conditions',
		Otp_PrivacyPolicy: 'Privacy Policy',
		Home_HeroTitleLeft: 'A GREENER',
		Home_HeroTitleHighlight: 'FUTURE',
		Home_HeroTitleRight: 'STARTS HERE',
		Home_HeroSubtitleLeft: 'Plant a tree today and be a part of ',
		Home_HeroSubtitleHighlight: 'real change',
		Home_HeroSubtitleRight: ' for our planet.',
		Home_BtnPlantFirstTree: 'PLANT YOUR FIRST TREE',
		Home_BtnCarbonCalculator: 'CARBON CALCULATOR',
		Home_BtnCarbonCalculatorSub: 'Calculate your impact',
		Home_StatsTreesVal: '1.2M+',
		Home_StatsTreesLabel: 'Trees Planted',
		Home_StatsCO2Val: '12.5K',
		Home_StatsCO2Label: 'Tons CO₂ Offset',
		Home_StatsUsersVal: '52K+',
		Home_StatsUsersLabel: 'Active Users',
		Home_StatsStatesVal: '28',
		Home_StatsStatesLabel: 'States Covered',
		Home_QuickPlantTitle: 'PLANT\nA TREE',
		Home_QuickPlantSubtitle: 'Plant for yourself',
		Home_QuickGiftTitle: 'GIFT\nA TREE',
		Home_QuickGiftSubtitle: 'Gift for someone',
		Home_QuickCarbonTitle: 'CARBON\nCALCULATOR',
		Home_QuickCarbonSubtitle: 'Calculate your impact',
		Home_QuickSponsorTitle: 'SPONSOR\nPLANTATION',
		Home_QuickSponsorSubtitle: 'Support communities',
		Home_SectionTitle: 'Featured Projects',
		Home_ViewAll: 'View All',
		Home_ProjAravalliTitle: 'Aravalli Restoration',
		Home_ProjBadgeRestoration: 'Restoration',
		Home_ProjRajasthan: 'Rajasthan',
		Home_ProjJaipurTitle: 'Urban Forest Jaipur',
		Home_ProjBadgeUrban: 'Urban',
		Home_ProjHimalayasTitle: 'Himalayan Plantation',
		Home_ProjBadgeHimalayan: 'Himalayan',
		Home_ProjUttarakhand: 'Uttarakhand',
		Home_ProjKarnataka: 'Karnataka',
		Home_ProjMaharashtra: 'Maharashtra',
		Home_ProjTamilNadu: 'Tamil Nadu',
		Home_BannerSubtitle: 'YOUR SMALL ACTION',
		Home_BannerTitleLeft: 'CREATES A ',
		Home_BannerTitleHighlight: 'BIG IMPACT',
		Home_BannerTitleRight: '',
		Home_BannerItemAir: 'Cleaner Air',
		Home_BannerItemPlanet: 'Healthier Planet',
		Home_BannerItemTomorrow: 'Better Tomorrow',
		Home_SelectStateTitle: 'SELECT YOUR STATE',
		HomeCatgroyTitle: 'Categories',
		Home_ViewAllStates: 'View All',
		State_TitlePart1: 'First, choose a state\nto ',
		State_TitlePart2: 'Plant your first tree',
		State_Subtitle: 'Our plantations are state-specific. Choose a state to see trees and projects available near you.',
		State_WhySelectTitle: 'Why select a state?',
		State_WhySelectDesc: 'It helps us show you the right trees, projects and locations where your impact is needed the most.',
		State_SelectYourState: 'Select Your State',
		State_ExploreAcrossIndia: 'Explore plantation projects across India',
		State_Popular: 'Popular',
		State_TreesPlantedSuffix: 'Trees Planted',
		State_ActiveProjectsSuffix: 'Active Projects',
		State_BottomInfo: 'Once you select a state, you\'ll be able to choose trees and locations specific to that region.',
		State_Continue: 'Continue',
		Dashboard_YourGreenImpact: 'YOUR GREEN IMPACT',
		Dashboard_ContinueYourJourney: 'CONTINUE YOUR JOURNEY',
		Dashboard_MyTrees: 'MY TREES',
		Dashboard_SelectState: 'SELECT STATE',
		Dashboard_CommunityImpact: 'COMMUNITY IMPACT',
		Dashboard_JuneChallenge: 'June Challenge',
		Dashboard_ViewAllTrees: 'View All',
		Dashboard_StatTreesLabel: 'Trees Planted',
		Dashboard_StatTreesSubtext: '↑ 4 This Month',
		Dashboard_StatCO2Label: 'CO₂ Offset',
		Dashboard_StatCO2Subtext: '↑ 36 kg This Month',
		Dashboard_StatLocLabel: 'Locations',
		Dashboard_StatLocSubtext: 'Across India',
		Dashboard_StatPointsLabel: 'Green Points',
		Dashboard_StatPointsSubtext: 'View Rewards >',
		Dashboard_JourneyPlantTitle: 'Plant More\nTrees',
		Dashboard_JourneyPlantSub: 'Grow more green',
		Dashboard_JourneyCarbonTitle: 'Offset\nCarbon',
		Dashboard_JourneyCarbonSub: 'Reduce your\ncarbon footprint',
		Dashboard_JourneyGiftTitle: 'Gift\nTrees',
		Dashboard_JourneyGiftSub: 'Give the gift of a\ngreener future',
		Dashboard_JourneySponsorTitle: 'Sponsor\nPlantation',
		Dashboard_JourneySponsorSub: 'Support large scale\ngreen initiatives',
		Dashboard_TreesSuffix: 'Trees',
		Dashboard_Selected: 'Selected',
		Dashboard_CommTrees: 'Trees Planted',
		Dashboard_CommCO2: 'Tons CO₂ Offset',
		Dashboard_CommUsers: 'Active Users',
		Dashboard_CommStates: 'States Covered',
		Dashboard_GreetingSub: 'Good Morning, Aarav! 🌿',
		Dashboard_GreetingMain: 'Every Action\nCreates Impact',
		Dashboard_GreetingDescPart1: 'Keep going, a ',
		Dashboard_GreetingDescPart2: 'greener',
		Dashboard_GreetingDescPart3: ' tomorrow\nis in your hands.',
		Dashboard_Live: 'Live',
		Dashboard_TreeLabel: 'Tree',
		Dashboard_JaipurRajasthan: 'Jaipur, Rajasthan',
		Dashboard_Healthy: 'Healthy',
		Dashboard_GPSVerified: 'GPS Verified',
		Dashboard_Height: 'Height',
		Dashboard_PlantedOn: 'Planted On',
		Dashboard_LastUpdated: 'Last Updated',
		Dashboard_ThreeDaysAgo: '3 Days Ago',
		Dashboard_MockPlantedDate: '12 May 2025',
		Dashboard_BannerDesc: 'Explore verified plantation projects\nacross Rajasthan.',
		Dashboard_ExploreProjects: 'Explore Projects',
		Dashboard_ChallengeSubtitle: 'Plant 3 Trees this month and earn 200 Green Coins!',
		Dashboard_Progress: 'Progress',
		Dashboard_GreenCoins: 'Green Coins',
		ChooseTree_TreeNeemName: 'Neem',
		ChooseTree_BannerTitle: 'Once you choose a tree,',
		ChooseTree_BannerDesc: "you'll be able to select the best location for plantation in Rajasthan.",
		ChooseTree_BenefitReduces: 'Reduces',
		ChooseTree_BenefitCarbon: 'Carbon',
		ChooseTree_BenefitSupports: 'Supports',
		ChooseTree_BenefitSupportsSub: 'Biodiversity',
		ChooseTree_BenefitCreates: 'Creates a',
		ChooseTree_BenefitGreenerFuture: 'Greener Future',
		ChooseTree_BenefitGPSTracked: 'GPS',
		ChooseTree_BenefitVerified: 'Tracked',
		ChooseTree_FooterText: 'All trees are verified and planted in partnership with local communities.',
		ChooseTree_Continue: 'Continue',
		UserProfile: 'User Profile',
		AccountDetails: 'Account Details',
		AccountStatus: 'Account Status',
		Verified: 'Verified',
		Unverified: 'Unverified',
		GreenWalletAmount: 'Green Wallet Amount',
		SupportLegal: 'Support & Legal',
		NotAvailableText: 'Not Available',
		Splash_Tagline: 'Sow a Seed, Save a Life',
		ExploreStates_Title: 'Explore Plantation \nStates',
		ExploreStates_Subtitle: 'Choose a state and discover verified plantation projects.',
		ExploreStates_SearchPlaceholder: 'Search State',
		ExploreStates_PopularStates: 'Popular States',
		ExploreStates_AllStates: 'All States',
		ExploreStates_Sort: 'Sort',
		ExploreStates_Filter: 'Filter',
		ExploreStates_ProjectsAvailable: 'Projects Available',
		ExploreStates_SpeciesLabel: 'Species:',
		ExploreStates_Explore: 'Explore',
		ExploreStates_BannerTextMain: 'Every state. Every tree.',
		ExploreStates_BannerTextSub: 'Every action counts.',
		ExploreStates_BannerTextDesc: 'Your small step today creates a \n greener tomorrow.',
		PlantationJourney_AlertNoNotifications: 'No new notifications.',
		PlantationJourney_AlertProjectsRedirect: 'Redirecting to all verified projects...',
		PlantationJourney_AlertCategoryGuide: 'Showing recommendation engine guide...',
		PlantationJourney_TitleStart: 'Start Your',
		PlantationJourney_TitleHighlight: 'Plantation Journey',
		PlantationJourney_Subtitle: 'Plant a tree today and create a greener tomorrow.',
		PlantationJourney_HeroBadge: '✓ 100% Verified • GPS Tracked • Impactful',
		PlantationJourney_ChooseState: 'Choose a State',
		PlantationJourney_ViewAllStates: 'View All States',
		PlantationJourney_ExploreProjects: 'Explore Verified Projects',
		PlantationJourney_ViewAllProjects: 'View All Projects',
		PlantationJourney_ChooseCategory: 'Choose a Tree Category',
		PlantationJourney_WhichTreeGuide: 'Which tree should I plant?',
		PlantationJourney_BadgeFeatured: 'FEATURED',
		PlantationJourney_BadgeTrending: 'TRENDING',
		PlantationJourney_BadgeNew: 'NEW',
		PlantationJourney_TreesPlantedCount: '{{count}}+ Trees Planted',
		PlantationJourney_NativeTreesDesc: 'Best for local\nenvironment',
		PlantationJourney_FruitTreesDesc: 'Nourish nature\n& communities',
		PlantationJourney_MedicinalTreesTitle: 'Medicinal Trees',
		PlantationJourney_MedicinalTreesDesc: 'Support health\n& well-being',
		PlantationJourney_FloweringTreesDesc: 'Beautify nature\n& surroundings',
		PlantationJourney_SpeciesCount: '{{count}}+ Species',
		PlantationJourney_TrustGPSDesc: 'Every tree is\nGPS tagged',
		PlantationJourney_TrustSurvivalTitle: 'High Survival',
		PlantationJourney_TrustSurvivalDesc: 'Carefully planted\n& monitored',
		PlantationJourney_TrustTranspTitle: 'Transparent',
		PlantationJourney_TrustTranspDesc: 'Real time updates\n& tracking',
		PlantationJourney_TrustTrustedTitle: 'Trusted 50K+',
		PlantationJourney_TrustTrustedDesc: 'Join thousands of\ngreen partners',
		Alert_NotificationsTitle: 'Notifications',
		Alert_ProjectsTitle: 'Projects',
		Alert_CategoryGuideTitle: 'Category Guide',

		Statewise_Title: '{{state}} Plantation \nProjects',
		Statewise_LocationsCovered: 'Locations Covered',
		Statewise_AvailableLocations: 'Available Plantation Locations',
		Statewise_ChooseVerified: 'Choose a verified project location to plant your tree.',
		Statewise_SurvivalRate: 'Tree Survival Rate',
		Statewise_ExploreProject: 'Explore Project',
		Statewise_WhyChoose: 'Why Choose Our Plantation Projects?',
		Statewise_SelectProjectToPlant: 'Select a Project to Plant Your Tree',
		Statewise_GPSTracked: 'GPS Tracked',
		Statewise_GPSDesc: 'Real-time location tracking',
		Statewise_VerifiedPlantation: 'Verified Plantation',
		Statewise_VerifiedDesc: '100% verified & authenticated',
		Statewise_CarbonOffset: 'Carbon Offset',
		Statewise_CarbonDesc: 'Measurable carbon impact',
		Statewise_DigitalCertificate: 'Digital Certificate',
		Statewise_CertificateDesc: 'Get a certificate for your contribution',

		ProjectSelect_ProjectFocus: 'Project Focus',
		ProjectSelect_AreaCovered: 'Area Covered',
		ProjectSelect_ProjectSince: 'Project Since',
		ProjectSelect_TrustedPartner: 'Trusted Partner',
		ProjectSelect_NgoPartner: 'NGO Partner',
		ProjectSelect_ProjectPartner: 'Project Partner',
		ProjectSelect_AboutProject: 'About This Project',
		ProjectSelect_ReadLess: 'Read Less',
		ProjectSelect_ReadMore: 'Read More',
		ProjectSelect_ProjectVideo: 'Project Video',
		ProjectSelect_ProjectGallery: 'Project Gallery',
		ProjectSelect_MoreImages: '+{{count}} More',
		ProjectSelect_ProjectImpact: 'Project Impact',
		ProjectSelect_Co2OffsetEst: 'CO₂ Offset (Est.)',
		ProjectSelect_NativeSpecies: 'Native Species',
		ProjectSelect_WaterSaved: 'Water Saved/Year',
		ProjectSelect_AvailableSpecies: 'Available Tree Species',
		ProjectSelect_ChooseNative: 'Choose from native species suitable for this location.',
		ProjectSelect_ProjectDetails: 'Project Details',
		ProjectSelect_SoilType: 'Soil Type',
		ProjectSelect_PlantationMethod: 'Plantation Method',
		ProjectSelect_Rainfall: 'Rainfall',
		ProjectSelect_Maintenance: 'Maintenance',
		ProjectSelect_ReadyImpact: 'Ready to make an impact?',
		ProjectSelect_ChooseTreeJourney: 'Choose a tree and continue your plantation journey.',
		ProjectSelect_ChooseTreeSpecies: 'Choose Tree Species',

		ChooseLocation_TitleLeft: 'Choose a Location \nin ',
		ChooseLocation_Subtitle: 'Select the best location for your tree. All our plantations are verified and managed by local partners.',
		ChooseLocation_VerifiedLocations: 'Verified Plantation Locations',
		ChooseLocation_ChooseSpecific: 'Choose a specific location for your tree plantation.',
		ChooseLocation_ActiveProjects: 'Active Projects',
		ChooseLocation_ByGeoTree: 'by GeoTree',
		ChooseLocation_AllLocationsVerified: 'All locations are verified and trees are planted in partnership with local communities.',

		ChooseTree_HeroTitleLeft: 'Choose a Tree to\nPlant in ',
		ChooseTree_HeroTitleHighlight: 'Rajasthan   ',
		ChooseTree_HeroSubtitleLeft: 'Every tree you plant contributes to a ',
		ChooseTree_HeroSubtitleHighlight: ' greener',
		ChooseTree_HeroSubtitleRight: ' and healthier Rajasthan ',
		ChooseTree_ChangeState: 'Change State ',
		ChooseTree_TabAll: 'All Trees',
		ChooseTree_TabNative: 'Native Trees',
		ChooseTree_TabFruit: 'Fruit Trees',
		ChooseTree_TabFlowering: 'Flowering Trees',
		ChooseTree_NeemName: 'Neem',
		ChooseTree_NeemDesc: 'A hardy native tree known for its medicinal properties and air purifying qualities.',
		ChooseTree_PeepalName: 'Peepal',
		ChooseTree_PeepalDesc: 'A sacred tree that produces oxygen even at night and supports biodiversity.',
		ChooseTree_MangoName: 'Mango',
		ChooseTree_MangoDesc: 'A popular fruit tree that provides shade and delicious fruits.',
		ChooseTree_GulmoharName: 'Gulmohar',
		ChooseTree_GulmoharDesc: 'A beautiful flowering tree that adds vibrant colors to the environment.',
		ChooseTree_GrowthRate: 'Growth Rate',
		ChooseTree_Maintenance: 'Maintenance',
		ChooseTree_GreenPointsLabel: 'Green Points',
		ChooseTree_GrowthMedium: 'Medium',
		ChooseTree_GrowthFast: 'Fast',
		ChooseTree_MaintenanceLow: 'Low',
		ChooseTree_MaintenanceMedium: 'Medium',
		ChooseTree_CategoryNative: 'Native',
		ChooseTree_CategoryFruit: 'Fruit',
		ChooseTree_CategoryFlowering: 'Flowering',

		ChooseSpecies_Title: 'Choose a Tree Species',
		ChooseSpecies_Subtitle: 'Select a native tree species to plant at',
		ChooseSpecies_GpsVerified: 'GPS Verified Project',
		ChooseSpecies_AcresCovered: 'Acres Covered',
		ChooseSpecies_AvailableTitle: 'Available Tree Species',
		ChooseSpecies_AvailableSubtitle: 'Choose a species that you want to plant.',
		ChooseSpecies_NativeTag: 'Native',
		ChooseSpecies_Lifespan: 'Lifespan',
		ChooseSpecies_WaterNeed: 'Water Need',
		ChooseSpecies_WaterLow: 'Low',
		ChooseSpecies_WaterVeryLow: 'Very Low',
		ChooseSpecies_WaterMedium: 'Medium',
		ChooseSpecies_ImpactTitle: 'Your Impact with This Tree',
		ChooseSpecies_ImpactSubtitle: 'See the positive change your tree will create.',
		ChooseSpecies_OxygenGenerated: 'Oxygen Generated',
		ChooseSpecies_WaterSaved: 'Water Saved',
		ChooseSpecies_SupportsBiodiversity: 'Supports Biodiversity',
		ChooseSpecies_SelectedLabel: 'Selected Species',
		ChooseSpecies_ChangeBtn: 'Change',
		ChooseSpecies_ProceedBtn: 'Proceed to Dedication',
		ChooseSpecies_NeemName: 'Neem',
		ChooseSpecies_KhejriName: 'Khejri',
		ChooseSpecies_RohidaName: 'Rohida',
		ChooseSpecies_AmlaName: 'Amla',
		ChooseSpecies_BabulName: 'Babul',
		ChooseSpecies_OxygenVal: '{{count}} Kg/Year',
		ChooseSpecies_WaterSavedVal: '{{count}} Liters/Year',
		ChooseSpecies_BioHigh: 'High',
		ChooseSpecies_BioVeryHigh: 'Very High',
		ChooseSpecies_LifespanVal: '{{count}} Years',

		ChoiceTree_HeroTitle: 'Great Choice! 🍃',
		ChoiceTree_HeroSubtitle: "You're about to plant a native tree that creates a real impact.",
		ChoiceTree_NativeTo: 'Native to',
		ChoiceTree_HighCO2: 'High CO₂',
		ChoiceTree_Absorption: 'Absorption',
		ChoiceTree_Drought: 'Drought',
		ChoiceTree_Resistant: 'Resistant',
		ChoiceTree_Long: 'Long',
		ChoiceTree_Lifespan: 'Lifespan',
		ChoiceTree_QtyTitle: 'How many trees would you like to plant?',
		ChoiceTree_Custom: 'Custom',
		ChoiceTree_PlantMore: 'Plant more trees',
		ChoiceTree_Choose: 'Choose',
		ChoiceTree_EnterQty: 'Enter Qty',
		ChoiceTree_Co2Year: '{{count}} KG CO₂ / Year',
		ChoiceTree_MoreImpact: 'More trees, bigger impact! Plant in bulk and contribute to a greener tomorrow.',
		ChoiceTree_WherePlant: 'Where would you like to plant?',
		ChoiceTree_ViewAllProjects: 'View All Projects',
		ChoiceTree_Planted: '{{count}} Trees Planted',
		ChoiceTree_YourImpact: 'Your Impact for This Planting',
		ChoiceTree_YouArePlanting: 'You are planting',
		ChoiceTree_Co2OffsetYear: 'CO₂ offset / year',
		ChoiceTree_WaterSoil: 'Water & Soil',
		ChoiceTree_Conservation: 'Conservation',
		ChoiceTree_Supports: 'Supports',
		ChoiceTree_Biodiversity: 'Biodiversity',
		ChoiceTree_MonitoringVal: '3 Years',
		ChoiceTree_Monitoring: 'Monitoring',
		ChoiceTree_VerifiedTransparent: '100% Verified & Transparent',
		ChoiceTree_VerifiedDesc: 'Every tree is GPS tagged, monitored for 3 years and you get regular updates.',
		ChoiceTree_SecurePayment: 'Secure Payment',
		ChoiceTree_SecureDesc: 'Your payment is safe & encrypted',
		ChoiceTree_TrustedBy: 'Trusted by 50K+',
		ChoiceTree_PlantersAcross: 'Planters across India',
		ChoiceTree_ProceedBtn: 'Proceed to Dedication',
		ChoiceTree_SecureNote: 'Secure • Transparent • Trusted by 50K+ Planters',

		WhichTree_HowItWorks: 'How it works?',
		WhichTree_HowItWorksDesc: 'Our algorithms evaluate your planting purpose (e.g. Carbon Offset, gifting) and environmental priorities (e.g. water requirement, local biodiversity) to recommend native trees best suited for your selected state.',
		WhichTree_GotIt: 'Got it!',
		WhichTree_SelectLocation: 'Select Location',
		WhichTree_ChooseState: 'Choose a state for plantation:',
		WhichTree_Cancel: 'Cancel',
		WhichTree_FindPerfect: 'Find the Perfect Tree For Your Purpose',
		WhichTree_AnswerFew: "Answer a few questions and we'll recommend the best tree for you.",
		WhichTree_WhyPlanting: '1. Why are you planting? ',
		WhichTree_PurposeCarbon: 'Carbon\nOffset',
		WhichTree_PurposeGift: 'Gift a\nTree',
		WhichTree_PurposeMemory: 'In\nMemory',
		WhichTree_PurposeEnv: 'Environmental\nImpact',
		WhichTree_PurposeCsr: 'CSR /\nCorporate',
		WhichTree_PurposePersonal: 'Personal\nPlantation',
		WhichTree_WhatMatters: '2. What matters most to you? ',
		WhichTree_PriorityCo2: 'Highest CO₂\nabsorption',
		WhichTree_PriorityGrowth: 'Fast\ngrowth',
		WhichTree_PriorityNative: 'Native\nspecies',
		WhichTree_PriorityMedicinal: 'Medicinal\nvalue',
		WhichTree_PriorityWildlife: 'Wildlife\nsupport',
		WhichTree_PriorityLifespan: 'Long\nlifespan',
		WhichTree_PreferredLocation: '3. Preferred Location ',
		WhichTree_ChangeState: 'Change state ∨',
		WhichTree_LocationInfo: 'All recommended trees are native and suitable for your selected location.',
		WhichTree_TopRecommendations: 'Your Top Tree Recommendations ',
		WhichTree_BestMatch: 'BEST MATCH',
		WhichTree_GpsVerified: 'GPS VERIFIED',
		WhichTree_PlantTree: 'Plant {{name}} →',
		WhichTree_PlantNow: 'Plant Now  →',
		WhichTree_ImpactComparison: 'Impact Comparison ',
		WhichTree_TableTree: 'Tree',
		WhichTree_TableCo2: 'CO₂ Absorption\n(Per Year)',
		WhichTree_TableLifespan: 'Lifespan',
		WhichTree_TableWater: 'Water Need',
		WhichTree_TableNative: 'Native to\n{{state}}',
		WhichTree_TableSurvival: 'Survival\nRate',
		WhichTree_BottomBanner: 'Every tree you plant is GPS tagged, monitored for 3 years & contributes to a greener tomorrow.',

		DedicateTree_Title: 'Dedicate Your Tree',
		DedicateTree_Subtitle: 'Make this plantation meaningful \nby dedicating it to someone special.',
		DedicateTree_WhoForTitle: 'Who is this tree for?',
		DedicateTree_DedicationDetails: 'Dedication Details',
		DedicateTree_RecipientName: 'Recipient Name',
		DedicateTree_EnterName: 'Enter name',
		DedicateTree_Occasion: 'Occasion',
		DedicateTree_SelectOccasion: 'Select Occasion',
		DedicateTree_OccasionDate: 'Occasion Date',
		DedicateTree_EmailOptional: 'Email (Optional)',
		DedicateTree_EnterEmail: 'Enter email address',
		DedicateTree_PersonalMessage: 'Personal Message',
		DedicateTree_WriteMessage: 'Write a message...',
		DedicateTree_SpecialOptions: 'Special Options',
		DedicateTree_SendCertificate: 'Send Digital Certificate',
		DedicateTree_SendCertificateDesc: 'We will email the certificate to recipient',
		DedicateTree_NotifyRecipient: 'Notify Recipient via Email',
		DedicateTree_NotifyRecipientDesc: 'Recipient will be notified about this dedication',
		DedicateTree_ReceiveUpdates: 'Receive Growth Updates',
		DedicateTree_ReceiveUpdatesDesc: "Get updates about your tree's growth",
		DedicateTree_AddToPortfolio: 'Add Tree to My Impact Portfolio',
		DedicateTree_AddToPortfolioDesc: 'Track and showcase your green impact',
		DedicateTree_ImpactSummary: 'Impact Summary',
		DedicateTree_Trees: 'Trees',
		DedicateTree_TreeVal: '{{count}} Tree',
		DedicateTree_TreesVal: '{{count}} Trees',
		DedicateTree_Location: 'Location',
		DedicateTree_Certificate: 'Certificate',
		DedicateTree_CertIncluded: 'Digital Certificate Included',
		DedicateTree_CertNotRequested: 'No Certificate Requested',
		DedicateTree_MakingRealImpact: 'You are making a real impact!',
		DedicateTree_GreenerTomorrow: 'Thank you for contributing to a greener tomorrow.',
		DedicateTree_NumberTrees: 'Number of Trees',
		DedicateTree_ContinuePayment: 'Continue to Payment',
		DedicateTree_SecurePaymentNote: 'Secure Payment  •  SSL Encrypted  •  Trusted by Thousands',
		DedicateTree_Done: 'Done',
		DedicateTree_Confirm: 'Confirm',
		DedicateTree_Day: 'Day',
		DedicateTree_Month: 'Month',
		DedicateTree_Year: 'Year',
		DedicateTree_OptionMyselfTitle: 'Myself',
		DedicateTree_OptionMyselfSub: 'Plant for your own impact',
		DedicateTree_OptionBirthdayTitle: 'Birthday',
		DedicateTree_OptionBirthdaySub: 'Celebrate a birthday',
		DedicateTree_OptionAnniversaryTitle: 'Anniversary',
		DedicateTree_OptionAnniversarySub: 'Celebrate a special milestone',
		DedicateTree_OptionLovedOneTitle: 'Loved One',
		DedicateTree_OptionLovedOneSub: 'Gift a tree to someone special',
		DedicateTree_OptionMemoryTitle: 'In Memory Of',
		DedicateTree_OptionMemorySub: 'Create a lasting tribute',
		DedicateTree_OptionCorporateTitle: 'Corporate / CSR',
		DedicateTree_OptionCorporateSub: 'Plant on behalf of an organization',

		Review_Title: 'Review Your\nPlantation',
		Review_Subtitle: 'Confirm your impact before completing your plantation.',
		Review_GpsVerified: 'GPS VERIFIED',
		Review_EstCo2: 'Estimated CO₂ Impact',
		Review_DedicationSummary: 'Dedication Summary',
		Review_DedicatedTo: 'Dedicated To',
		Review_Message: 'Message',
		Review_TreeAllocation: 'Tree Allocation',
		Review_ViewDetails: 'View Details  →',
		Review_EnvImpact: 'Your Environmental Impact',
		Review_CostBreakdown: 'Cost Breakdown',
		Review_GPSTracking: 'GPS Tracking',
		Review_Included: 'Included',
		Review_GrowthMonitoring: 'Growth Monitoring (3 Years)',
		Review_DigitalCertificate: 'Digital Certificate',
		Review_TotalAmount: 'Total Amount',
		Review_InclusiveTaxes: 'Inclusive of all taxes',
		Review_ChoosePayment: 'Choose a Payment Method',
		Review_SecurePayments: '100% Secure Payments',
		Review_UpiRecommended: 'UPI (Recommended)',
		Review_DebitCredit: 'Debit / Credit Cards',
		Review_NetBanking: 'Net Banking',
		Review_AllBanksSupported: 'All major banks supported',
		Review_Wallets: 'Wallets',
		Review_WalletsSupported: 'Paytm, Amazon Pay, Mobikwik & more',
		Review_SSLTitle: '100% Secure Payment',
		Review_SSLDesc: 'SSL Encrypted',
		Review_VerifiedPlantation: 'Verified Plantation',
		Review_VerifiedDesc: 'Real Trees, Real Impact',
		Review_RefundProtection: 'Refund Protection',
		Review_RefundDesc: 'Easy & Hassle-Free',
		Review_TrustedBy: 'Trusted by 50K+',
		Review_PlantersAcross: 'Planters Across India',
		Review_PromiseTitle: 'Your Impact. Our Promise.',
		Review_PromiseDesc: 'Every tree is GPS tracked & verified.',
		Review_PaySecurely: 'Pay ₹{{amount}} Securely',
		Review_SecureGateway: 'Secure Payment Gateway • SSL Encrypted • Your Data is Safe',
		Review_AlertTitle: 'Confirm Payment',
		Review_AlertMsg: 'Process ₹1,990 securely via {{method}}?',
		Review_AlertCancel: 'Cancel',
		Review_AlertPayNow: 'Pay Now',

		Payment_AlmostThere: 'Almost There',
		Payment_Subtitle: 'Review your plantation\ndetails before proceeding.',
		Payment_Summary: 'Plantation Summary',
		Payment_TreeSpecies: 'Tree Species',
		Payment_GPSStatus: 'GPS Status',
		Payment_GPSVerified: 'GPS Verified',
		Payment_PreviewTitle: 'Your Impact Preview',
		Payment_WaterConservation: 'Water\nConservation\nContribution',
		Payment_DonationBreakdown: 'Donation Breakdown',
		Payment_SecureTitle: '256-bit SSL Encrypted',
		Payment_SecureDesc: 'Your payment information is safe with us',
		Payment_NoStoreCard: 'We do not store your card details',
		Payment_PaySecurelyBtn: 'Pay ₹{{amount}} Securely →',
		Payment_AgreeTerms: 'By proceeding, you agree to our ',
		Payment_TermsConditions: 'Terms & Conditions',

		Details_Title: 'Tell us a little about\nyour tree',
		Details_Subtitle: 'Add a personal touch! This helps us dedicate your tree and keep you updated on its growth.',
		Details_SummaryTitle: 'Your Selection Summary',
		Details_PlantedBy: 'Planted By',
		Details_PlantedByYou: 'You',
		Details_AddDetails: 'Add Your Details',
		Details_YourName: 'Your Name',
		Details_EnterNamePlaceholder: 'Enter your full name',
		Details_DedicateOptional: 'Dedicate Your Tree (Optional)',
		Details_DedicatePlaceholder: 'E.g. In memory of someone / For a loved one',
		Details_CertificateNote: 'This will appear on your tree certificate.',
		Details_MessageOptional: 'Add a Message (Optional)',
		Details_MessagePlaceholder: 'E.g., For a greener tomorrow',
		Details_StayUpdated: 'Stay Updated',
		Details_StayUpdatedDesc: "We'll keep you updated with your tree's growth and impact.",
		Details_SafeHands: 'Your tree is in safe hands!',
		Details_SafeHandsDesc: 'All plantations are verified and monitored by our local partners.',
		Details_ContinuePayment: 'Continue to Payment',

		Confirmed_Title: 'Plantation Confirmed!',
		Confirmed_Subtitle: 'Your {{qty}} {{name}} Trees have been successfully reserved for plantation.',
		Confirmed_TreesReserved: 'Trees Reserved',
		Confirmed_EstimatedImpact: 'Estimated CO₂ Impact',
		Confirmed_JourneyHeader: 'Plantation Journey',
		Confirmed_PaymentComplete: 'Payment\nComplete',
		Confirmed_PlantationReserved: 'Plantation\nReserved',
		Confirmed_PlantationScheduled: 'Plantation\nScheduled',
		Confirmed_GpsVerification: 'GPS\nVerification',
		Confirmed_GrowthUpdates: 'Growth\nUpdates',
		Confirmed_PlantationIdLabel: 'Your Plantation ID',
		Confirmed_DateLabel: 'Date',
		Confirmed_ScanToView: 'Scan to view\nyour plantation',
		Confirmed_WhatsNext: "What's Next?",
		Confirmed_WithinDays: 'Within 7-15 Days',
		Confirmed_NextPlantComplete: 'Plantation will be completed',
		Confirmed_NextGpsAssign: 'GPS coordinates will be assigned',
		Confirmed_NextPhotosUpload: 'Geo-tagged photos will be uploaded',
		Confirmed_NextCertIssued: 'Digital certificate will be issued',
		Confirmed_ShareImpact: 'Share Your Impact',
		Confirmed_InspireOthers: 'Inspire others to make a difference',
		Confirmed_TrackMyTrees: 'Track My Trees',
		Confirmed_DownloadReceipt: 'Download Receipt',
		Confirmed_AlertReceiptTitle: 'Receipt Download',
		Confirmed_AlertReceiptMsg: 'Your payment receipt is being downloaded as a PDF...',
		Confirmed_AlertIdTitle: 'ID Copied',
		Confirmed_AlertIdMsg: 'Plantation ID copied successfully to clipboard.',
		Confirmed_AlertShareTitle: 'Share Impact',
		Confirmed_AlertShareMsg: 'Opening share dialog for {{channel}}...',

		ThankYou_Title: 'Tree Successfully\nReserved!',
		ThankYou_Subtitle: 'Thank you for taking a step towards a greener tomorrow. Your tree plantation request has been confirmed.',
		ThankYou_PlantedAt: 'Your tree will be planted at\n',
		ThankYou_DetailsTitle: 'Your Tree Details',
		ThankYou_TreeId: 'Tree ID',
		ThankYou_PlantedBy: 'Planted By',
		ThankYou_ImpactGlance: 'Your Impact at a Glance',
		ThankYou_ExpectedAnnual: 'Expected Annual\nCO₂ Absorption',
		ThankYou_ExpectedLifetime: 'Expected Lifetime\nImpact',
		ThankYou_ExpectedLifetimeVal: '{{count}}+ KG CO₂',
		ThankYou_SupportsBiodiversity: 'Supports\nBiodiversity',
		ThankYou_GpsEnabled: 'GPS Tracking\nEnabled',
		ThankYou_CertTitle: 'Digital Tree Certificate',
		ThankYou_CertAvailable: 'Available after plantation verification.',
		ThankYou_CertPreviewBtn: 'View Certificate Preview',
		ThankYou_NextTitle: 'What Happens Next?',
		ThankYou_TrackMyTree: 'Track My Tree',
		ThankYou_PlantAnother: 'Plant Another Tree',
		ThankYou_MakingImpact: 'Thank you for making an impact!',
		ThankYou_MovementDesc: 'You are now a part of the movement towards a cleaner, greener planet.',

		Portfolio_Title: 'My Plantation Portfolio',
		Portfolio_Subtitle: 'Track your trees. See your impact. Inspire the world.',
		Portfolio_ActiveTrees: 'Active Trees',
		Portfolio_TotalCo2: 'Total CO₂ Impact',
		Portfolio_ActiveProjects: 'Active Projects',
		Portfolio_Status: 'Status',
		Portfolio_ExpectedDate: 'Expected Date',
		Portfolio_Progress: 'Progress',
		Portfolio_ViewJourney: 'View Tree Journey',
		Portfolio_ViewOnMap: 'View on Map',
		Portfolio_ProjectDetails: 'Project Details',
		Portfolio_ShareProject: 'Share Project',
		Portfolio_MyTreesStatus: 'My Trees Status',
		Portfolio_ViewAll: 'View All >',
		Portfolio_ViewAllTrees: 'View All Trees >',
		Portfolio_TreeDetails: 'Tree Details',
		Portfolio_LatestUpdates: 'Latest Updates',
		Portfolio_NoUpdatesYet: 'No updates yet. We will notify you once plantation is completed and photos are uploaded.',
		Portfolio_DifferenceTitle: "You're Making a Real Difference! 🌏",
		Portfolio_DifferenceDesc: 'Thank you for helping build a greener planet.',
		Portfolio_TimelinePayment: 'Payment Completed',
		Portfolio_TimelineReserved: 'Plantation Reserved',
		Portfolio_TimelineScheduled: 'Plantation Scheduled',
		Portfolio_TimelineGps: 'GPS Verification',
		Portfolio_TimelineUpdates: 'Growth Updates',
		Portfolio_TimelineExpectedDays: 'Expected in 7-15 days',
		Portfolio_TimelinePending: 'Pending',
		Portfolio_AlertCopied: 'Copied',
		Portfolio_AlertBatchId: 'Batch ID copied successfully to clipboard.',

		Journey_Title: 'My Tree Journey',
		Journey_Subtitle: 'Track your tree. See your impact. Inspire the world.',
		Journey_TreeIdLabel: 'Tree ID: ',
		Journey_StepPayment: 'Payment\nComplete',
		Journey_StepReserved: 'Tree\nReserved',
		Journey_StepScheduled: 'Plantation\nScheduled',
		Journey_StepPlanted: 'Tree\nPlanted',
		Journey_StepGps: 'GPS\nVerified',
		Journey_StepUpdates: 'Growth\nUpdates',
		Journey_StepCert: 'Certificate\nIssued',
		Journey_StageBefore: 'Before\nPlantation',
		Journey_StageMonth: 'Month {{count}}',
		Journey_StageAwaiting: 'Awaiting\nPlantation',
		Journey_StageComing: 'Coming\nSoon',
		Journey_ImpactWater: 'Water Saved',
		Journey_ImpactHabitat: 'Habitat for',
		Journey_ImpactWildlife: 'Birds & Wildlife',
		Journey_TimelineTitle: 'Project Updates',
		Journey_DocsTitle: 'Documents & Certificates',
		Journey_Download: 'Download',
		Journey_ComingSoon: 'Coming Soon',
		Journey_Invoice: 'Invoice / Receipt',
		Journey_InvoiceDesc: 'Payment of ₹1,990',
		Journey_PlantationPhotos: 'Plantation Photos',
		Journey_PhotosDesc: 'Geo-tagged photos from the site',
		Journey_ReportDesc: 'Environmental impact report',
		Journey_ViewPhotosBtn: 'View Plantation Photos',
		Journey_ShareImpactBtn: 'Share My Impact',
		Journey_AlertCopiedTitle: 'Success',
		Journey_AlertCopiedMsg: 'Tree ID: GT-2026-10245 copied to clipboard!',

		ChoiceTree_StepState: 'State',
		ChoiceTree_StepProject: 'Project',
		ChoiceTree_StepTree: 'Tree',
		ChoiceTree_StepDedication: 'Dedication',
		ChoiceTree_StepPayment: 'Payment',
	},
	hi: {

		AppName: 'स्टोर पीडिया',
		MobileNumber: 'मोबाइल नंबर',
		LoginButton: 'लॉग इन',
		NoRecord: "कोई रिकॉर्ड नहीं मिला",


		LogOut: 'लॉग आउट',
		NotAvailable: 'उपलब्ध नहीं',

		PlantNameLabel: 'पौधे का नाम',
		ScientificNameLabel: 'वैज्ञानिक नाम',
		CO2AbsorptionLabel: 'CO₂ अवशोषण',
		MaturityLabel: 'परिपक्वता',
		TreeHeightLabel: 'पेड़ की ऊंचाई',
		RateLabel: 'दर',
		Close: 'बंद करें',
		Cancel: 'रद्द करें',
		Loading: 'लोड हो रहा है...',
		Preferences: "प्राथमिकताएँ",
		PrivacyPolicy: "गोपनीयता नीति",
		PushNotifications: "तुरंत सूचनाएं",
		Delete: "हटाएं",
		Logout: "लॉग आउट",
		logout_sure: "क्या आप वाकई लॉग आउट करना चाहते हैं?",
		AppOpening_PlantTitle: 'पौधा लगाएं.',
		AppOpening_TrackTitle: 'ट्रैक करें.',
		AppOpening_ImpactTitle: 'प्रभाव.',
		AppOpening_Subtitle1: 'सत्यापित पेड़ लगाएं.',
		AppOpening_Subtitle2: 'विकास को ट्रैक करें.',
		AppOpening_Subtitle3: 'एक विरासत ',
		AppOpening_SubtitleLegacy: 'छोड़ें',
		AppOpening_GetStarted: 'शुरू करें',
		AppOpening_AlreadyHaveAccount: 'पहले से ही एक खाता है? ',
		AppOpening_SignIn: 'साइन इन करें',
		AppOpening_VerifiedPlantations: 'सत्यापित\nवृक्षारोपण',
		AppOpening_GPSTracked: 'जीपीएस\nट्रैक्ड',
		AppOpening_RealImpact: 'वास्तविक\nप्रभाव',
		AppOpening_TreesPlanted: 'लगाए गए पेड़',
		AppOpening_CO2Offset: 'CO₂ ऑफ़सेट',
		AppOpening_SurvivalRate: 'जीवित रहने की दर',
		SignIn_Subtitle: 'आगे बढ़ने के लिए अपना मोबाइल नंबर दर्ज करें।',
		SignIn_Title: 'साइन इन',
		SignIn_MobilePlaceholder: 'मोबाइल नंबर दर्ज करें',
		SignIn_SendOTP: 'ओटीपी भेजें',
		Otp_LogoSubtitle: 'पौधा लगाएं. ट्रैक करें. प्रभाव.',
		Otp_VerifyTitle: 'ओटीपी सत्यापित करें',
		Otp_EnterCodeSent: 'भेजे गए 6-अंकीय सत्यापन कोड को दर्ज करें',
		Otp_SecureVerification: 'सुरक्षित मोबाइल सत्यापन',
		Otp_ExpiresIn: 'कोड की समय सीमा समाप्त होने में',
		Otp_DidNotReceive: 'ओटीपी प्राप्त नहीं हुआ? ',
		Otp_Resend: 'ओटीपी पुनः भेजें',
		Otp_AgreeTo: 'आगे बढ़कर, आप हमारे ',
		Otp_TermsAndConditions: 'नियम और शर्तों',
		Otp_PrivacyPolicy: 'गोपनीयता नीति से सहमत हैं',
		Home_HeroTitleLeft: 'एक हरा-भरा',
		Home_HeroTitleHighlight: 'भविष्य',
		Home_HeroTitleRight: 'यहाँ से शुरू होता है',
		Home_HeroSubtitleLeft: 'आज ही एक पेड़ लगाएं और हमारे ग्रह के लिए ',
		Home_HeroSubtitleHighlight: 'वास्तविक बदलाव',
		Home_HeroSubtitleRight: ' का हिस्सा बनें।',
		Home_BtnPlantFirstTree: 'अपना पहला पेड़ लगाएं',
		Home_BtnCarbonCalculator: 'कार्बन कैलकुलेटर',
		Home_BtnCarbonCalculatorSub: 'अपने प्रभाव की गणना करें',
		Home_StatsTreesVal: '1.2M+',
		Home_StatsTreesLabel: 'लगाए गए पेड़',
		Home_StatsCO2Val: '12.5K',
		Home_StatsCO2Label: 'टन CO₂ ऑफसेट',
		Home_StatsUsersVal: '52K+',
		Home_StatsUsersLabel: 'सक्रिय उपयोगकर्ता',
		Home_StatsStatesVal: '28',
		Home_StatsStatesLabel: 'कवर किए गए राज्य',
		Home_QuickPlantTitle: 'पेड़\nलगाएं',
		Home_QuickPlantSubtitle: 'स्वयं के लिए लगाएं',
		Home_QuickGiftTitle: 'पेड़\nउपहार दें',
		Home_QuickGiftSubtitle: 'किसी के लिए उपहार',
		Home_QuickCarbonTitle: 'कार्बन\nकैलकुलेटर',
		Home_QuickCarbonSubtitle: 'अपने प्रभाव की गणना करें',
		Home_QuickSponsorTitle: 'वृक्षारोपण\nप्रायोजित करें',
		Home_QuickSponsorSubtitle: 'समुदायों का समर्थन करें',
		Home_SectionTitle: 'विशेष परियोजनाएं',
		Home_ViewAll: 'सभी देखें >',
		Home_ProjAravalliTitle: 'अरावली पुनरुद्धार',
		Home_ProjBadgeRestoration: 'पुनरुद्धार',
		Home_ProjRajasthan: 'राजस्थान',
		Home_ProjJaipurTitle: 'शहरी वन जयपुर',
		Home_ProjBadgeUrban: 'शहरी',
		Home_ProjHimalayasTitle: 'हिमालयी वृक्षारोपण',
		Home_ProjBadgeHimalayan: 'हिमालयी',
		Home_ProjUttarakhand: 'उत्तराखंड',
		Home_ProjKarnataka: 'कर्नाटक',
		Home_ProjMaharashtra: 'महाराष्ट्र',
		Home_ProjTamilNadu: 'तमिलनाडु',
		Home_BannerSubtitle: 'आपका छोटा सा कदम',
		Home_BannerTitleLeft: '',
		Home_BannerTitleHighlight: 'बड़ा बदलाव',
		Home_BannerTitleRight: ' लाता है',
		Home_BannerItemAir: 'स्वच्छ हवा',
		Home_BannerItemPlanet: 'स्वस्थ ग्रह',
		Home_BannerItemTomorrow: 'बेहतर कल',
		Home_SelectStateTitle: 'अपना राज्य चुनें',
		Home_ViewAllStates: 'सभी राज्य देखें',
		State_TitlePart1: 'पहले, अपना पहला पेड़ लगाने के लिए\n',
		State_TitlePart2: 'एक राज्य चुनें',
		State_Subtitle: 'हमारे वृक्षारोपण राज्य-विशिष्ट हैं। अपने आस-पास उपलब्ध पेड़ों और परियोजनाओं को देखने के लिए एक राज्य चुनें।',
		State_WhySelectTitle: 'राज्य क्यों चुनें?',
		State_WhySelectDesc: 'यह हमें आपको सही पेड़, परियोजनाएं और स्थान दिखाने में मदद करता है जहां आपके प्रभाव की सबसे अधिक आवश्यकता है।',
		State_SelectYourState: 'अपना राज्य चुनें',
		State_ExploreAcrossIndia: 'पूरे भारत में वृक्षारोपण परियोजनाओं का पता लगाएं',
		State_Popular: 'लोकप्रिय',
		State_TreesPlantedSuffix: 'पेड़ लगाए गए',
		State_ActiveProjectsSuffix: 'सक्रिय परियोजनाएं',
		State_BottomInfo: 'एक बार जब आप एक राज्य चुन लेते हैं, तो आप उस क्षेत्र के विशिष्ट पेड़ों और स्थानों को चुन सकेंगे।',
		State_Continue: 'जारी रखें',
		Dashboard_YourGreenImpact: 'आपका हरित प्रभाव',
		Dashboard_ContinueYourJourney: 'अपनी यात्रा जारी रखें',
		Dashboard_MyTrees: 'मेरे पेड़',
		Dashboard_SelectState: 'राज्य चुनें',
		Dashboard_CommunityImpact: 'सामुदायिक प्रभाव',
		Dashboard_JuneChallenge: 'जून की चुनौती',
		Dashboard_ViewAllTrees: 'सभी पेड़ देखें',
		Dashboard_StatTreesLabel: 'पेड़ लगाए गए',
		Dashboard_StatTreesSubtext: '↑ 4 इस महीने',
		Dashboard_StatCO2Label: 'CO₂ ऑफसेट',
		Dashboard_StatCO2Subtext: '↑ 36 किग्रा इस महीने',
		Dashboard_StatLocLabel: 'स्थान',
		Dashboard_StatLocSubtext: 'पूरे भारत में',
		Dashboard_StatPointsLabel: 'ग्रीन पॉइंट्स',
		Dashboard_StatPointsSubtext: 'पुरस्कार देखें >',
		Dashboard_JourneyPlantTitle: 'और पेड़\nलगाएं',
		Dashboard_JourneyPlantSub: 'अधिक हरियाली बढ़ाएं',
		Dashboard_JourneyCarbonTitle: 'कार्बन\nकम करें',
		Dashboard_JourneyCarbonSub: 'कार्बन पदचिह्न घटाएं',
		Dashboard_JourneyGiftTitle: 'पेड़\nउपहार दें',
		Dashboard_JourneyGiftSub: 'हरे-भरे भविष्य का उपहार',
		Dashboard_JourneySponsorTitle: 'वृक्षारोपण\nप्रायोजित करें',
		Dashboard_JourneySponsorSub: 'बड़े पैमाने पर सहयोग करें',
		Dashboard_TreesSuffix: 'पेड़',
		Dashboard_Selected: 'चयनित',
		Dashboard_CommTrees: 'पेड़ लगाए गए',
		Dashboard_CommCO2: 'टन CO₂ ऑफसेट',
		Dashboard_CommUsers: 'सक्रिय उपयोगकर्ता',
		Dashboard_CommStates: 'कवर किए गए राज्य',
		Dashboard_GreetingSub: 'शुभ प्रभात, आरव! 🌿',
		Dashboard_GreetingMain: 'हर कदम\nप्रभाव लाता है',
		Dashboard_GreetingDescPart1: 'जारी रखें, एक ',
		Dashboard_GreetingDescPart2: 'हरित',
		Dashboard_GreetingDescPart3: ' कल\nआपके हाथों में है।',
		Dashboard_Live: 'लाइव',
		Dashboard_TreeLabel: 'पेड़',
		Dashboard_JaipurRajasthan: 'जयपुर, राजस्थान',
		Dashboard_Healthy: 'स्वस्थ',
		Dashboard_GPSVerified: 'जीपीएस सत्यापित',
		Dashboard_Height: 'ऊंचाई',
		Dashboard_PlantedOn: 'रोपा गया',
		Dashboard_LastUpdated: 'अंतिम बार अपडेट किया गया',
		Dashboard_ThreeDaysAgo: '3 दिन पहले',
		Dashboard_MockPlantedDate: '12 मई 2025',
		Dashboard_BannerDesc: 'राजस्थान भर में सत्यापित वृक्षारोपण\nपरियोजनाओं का पता लगाएं।',
		Dashboard_ExploreProjects: 'परियोजनाओं का पता लगाएं',
		Dashboard_ChallengeSubtitle: 'इस महीने 3 पेड़ लगाएं और 200 ग्रीन कॉइन्स कमाएं!',
		Dashboard_Progress: 'प्रगति',
		Dashboard_GreenCoins: 'ग्रीन कॉइन्स',
		ChooseTree_TreeNeemName: 'नीम',
		ChooseTree_BannerTitle: 'एक बार जब आप पेड़ चुन लेते हैं,',
		ChooseTree_BannerDesc: 'तो आप राजस्थान में वृक्षारोपण के लिए सबसे अच्छे स्थान का चयन कर सकेंगे।',
		ChooseTree_BenefitReduces: 'कम करता है',
		ChooseTree_BenefitCarbon: 'कार्बन',
		ChooseTree_BenefitSupports: 'समर्थन करता है',
		ChooseTree_BenefitSupportsSub: 'जैव विविधता',
		ChooseTree_BenefitCreates: 'बनाता है',
		ChooseTree_BenefitGreenerFuture: 'हरा-भरा भविष्य',
		ChooseTree_BenefitGPSTracked: 'जीपीएस',
		ChooseTree_BenefitVerified: 'ट्रैकिंग',
		ChooseTree_FooterText: 'सभी पेड़ सत्यापित हैं और स्थानीय समुदायों के साथ साझेदारी में लगाए गए हैं।',
		ChooseTree_Continue: 'जारी रखें',
		UserProfile: 'उपयोगकर्ता प्रोफ़ाइल',
		AccountDetails: 'खाता विवरण',
		AccountStatus: 'खाते की स्थिति',
		Verified: 'सत्यापित',
		Unverified: 'अपुष्ट',
		GreenWalletAmount: 'ग्रीन वॉलेट राशि',
		SupportLegal: 'सहायता और कानूनी',
		NotAvailableText: 'उपलब्ध नहीं है',
		Splash_Tagline: 'एक बीज बोएं, एक जीवन बचाएं',
		ExploreStates_Title: 'वृक्षारोपण राज्य खोजें',
		ExploreStates_Subtitle: 'एक राज्य चुनें और सत्यापित वृक्षारोपण परियोजनाओं की खोज करें।',
		ExploreStates_SearchPlaceholder: 'राज्य खोजें',
		ExploreStates_PopularStates: 'लोकप्रिय राज्य',
		ExploreStates_AllStates: 'सभी राज्य',
		ExploreStates_Sort: 'क्रमबद्ध करें',
		ExploreStates_Filter: 'फ़िल्टर',
		ExploreStates_ProjectsAvailable: 'परियोजनाएं उपलब्ध',
		ExploreStates_SpeciesLabel: 'प्रजातियां:',
		ExploreStates_Explore: 'अन्वेषण करें',
		ExploreStates_BannerTextMain: 'हर राज्य। हर पेड़।',
		ExploreStates_BannerTextSub: 'हर क्रिया मायने रखती है।',
		ExploreStates_BannerTextDesc: 'आज आपका छोटा कदम कल एक \n हरित कल का निर्माण करता है।',
		PlantationJourney_AlertNoNotifications: 'कोई नया नोटिफिकेशन नहीं है।',
		PlantationJourney_AlertProjectsRedirect: 'सभी सत्यापित परियोजनाओं पर पुनर्निर्देशित किया जा रहा है...',
		PlantationJourney_AlertCategoryGuide: 'सिफारिश इंजन गाइड दिखा रहा है...',
		PlantationJourney_TitleStart: 'अपनी',
		PlantationJourney_TitleHighlight: 'वृक्षारोपण यात्रा शुरू करें',
		PlantationJourney_Subtitle: 'आज ही एक पेड़ लगाएं और हरा-भरा कल बनाएं।',
		PlantationJourney_HeroBadge: '✓ 100% सत्यापित • जीपीएस ट्रैक्ड • प्रभावशाली',
		PlantationJourney_ChooseState: 'एक राज्य चुनें',
		PlantationJourney_ViewAllStates: 'सभी राज्य देखें',
		PlantationJourney_ExploreProjects: 'सत्यापित परियोजनाओं का अन्वेषण करें',
		PlantationJourney_ViewAllProjects: 'सभी परियोजनाएं देखें',
		PlantationJourney_ChooseCategory: 'पेड़ की श्रेणी चुनें',
		PlantationJourney_WhichTreeGuide: 'मुझे कौन सा पेड़ लगाना चाहिए?',
		PlantationJourney_BadgeFeatured: 'विशेष रुप से प्रदर्शित',
		PlantationJourney_BadgeTrending: 'ट्रेंडिंग',
		PlantationJourney_BadgeNew: 'नया',
		PlantationJourney_TreesPlantedCount: '{{count}}+ पेड़ लगाए गए',
		PlantationJourney_NativeTreesDesc: 'स्थानीय पर्यावरण के लिए सर्वश्रेष्ठ',
		PlantationJourney_FruitTreesDesc: 'प्रकृति और समुदायों का पोषण करें',
		PlantationJourney_MedicinalTreesTitle: 'औषधीय पेड़',
		PlantationJourney_MedicinalTreesDesc: 'स्वास्थ्य और कल्याण का समर्थन करें',
		PlantationJourney_FloweringTreesDesc: 'प्रकृति और परिवेश को सुंदर बनाएं',
		PlantationJourney_SpeciesCount: '{{count}}+ प्रजातियां',
		PlantationJourney_TrustGPSDesc: 'हर पेड़ पर जीपीएस टैग है',
		PlantationJourney_TrustSurvivalTitle: 'उच्च उत्तरजीविता',
		PlantationJourney_TrustSurvivalDesc: 'सावधानीपूर्वक रोपण और निगरानी',
		PlantationJourney_TrustTranspTitle: 'पारदर्शी',
		PlantationJourney_TrustTranspDesc: 'वास्तविक समय अपडेट और ट्रैकिंग',
		PlantationJourney_TrustTrustedTitle: 'विश्वसनीय 50K+',
		PlantationJourney_TrustTrustedDesc: 'हजारों हरित भागीदारों से जुड़ें',
		Alert_NotificationsTitle: 'सूचनाएं',
		Alert_ProjectsTitle: 'परियोजनाएं',
		Alert_CategoryGuideTitle: 'श्रेणी गाइड',

		Statewise_Title: '{{state}} वृक्षारोपण \nपरियोजनाएं',
		Statewise_LocationsCovered: 'कवर किए गए स्थान',
		Statewise_AvailableLocations: 'उपलब्ध वृक्षारोपण स्थान',
		Statewise_ChooseVerified: 'अपना पेड़ लगाने के लिए एक सत्यापित परियोजना स्थान चुनें।',
		Statewise_SurvivalRate: 'पेड़ के जीवित रहने की दर',
		Statewise_ExploreProject: 'परियोजना का अन्वेषण करें',
		Statewise_WhyChoose: 'हमारी वृक्षारोपण परियोजनाओं को क्यों चुनें?',
		Statewise_SelectProjectToPlant: 'अपना पेड़ लगाने के लिए एक परियोजना चुनें',
		Statewise_GPSTracked: 'जीपीएस ट्रैक किया गया',
		Statewise_GPSDesc: 'वास्तविक समय स्थान ट्रैकिंग',
		Statewise_VerifiedPlantation: 'सत्यापित वृक्षारोपण',
		Statewise_VerifiedDesc: '100% सत्यापित और प्रमाणित',
		Statewise_CarbonOffset: 'कार्बन ऑफ़सेट',
		Statewise_CarbonDesc: 'मापने योग्य कार्बन प्रभाव',
		Statewise_DigitalCertificate: 'डिजिटल प्रमाणपत्र',
		Statewise_CertificateDesc: 'अपने योगदान के लिए प्रमाणपत्र प्राप्त करें',

		ProjectSelect_ProjectFocus: 'परियोजना फोकस',
		ProjectSelect_AreaCovered: 'कवर किया गया क्षेत्र',
		ProjectSelect_ProjectSince: 'परियोजना शुरू',
		ProjectSelect_TrustedPartner: 'विश्वसनीय भागीदार',
		ProjectSelect_NgoPartner: 'एनजीओ भागीदार',
		ProjectSelect_ProjectPartner: 'परियोजना भागीदार',
		ProjectSelect_AboutProject: 'इस परियोजना के बारे में',
		ProjectSelect_ReadLess: 'कम पढ़ें',
		ProjectSelect_ReadMore: 'और पढ़ें',
		ProjectSelect_ProjectVideo: 'परियोजना वीडियो',
		ProjectSelect_ProjectGallery: 'परियोजना गैलरी',
		ProjectSelect_MoreImages: '+{{count}} और',
		ProjectSelect_ProjectImpact: 'परियोजना प्रभाव',
		ProjectSelect_Co2OffsetEst: 'CO₂ ऑफसेट (अनुमानित)',
		ProjectSelect_NativeSpecies: 'स्थानीय प्रजातियां',
		ProjectSelect_WaterSaved: 'बचाया गया पानी/वर्ष',
		ProjectSelect_AvailableSpecies: 'उपलब्ध पेड़ों की प्रजातियां',
		ProjectSelect_ChooseNative: 'इस स्थान के लिए उपयुक्त स्थानीय प्रजातियों में से चुनें।',
		ProjectSelect_ProjectDetails: 'परियोजना विवरण',
		ProjectSelect_SoilType: 'मिट्टी का प्रकार',
		ProjectSelect_PlantationMethod: 'वृक्षारोपण विधि',
		ProjectSelect_Rainfall: 'वर्षा',
		ProjectSelect_Maintenance: 'रखरखाव',
		ProjectSelect_ReadyImpact: 'क्या आप प्रभाव डालने के लिए तैयार हैं?',
		ProjectSelect_ChooseTreeJourney: 'एक पेड़ चुनें और अपनी वृक्षारोपण यात्रा जारी रखें।',
		ProjectSelect_ChooseTreeSpecies: 'पेड़ की प्रजाति चुनें',

		ChooseLocation_TitleLeft: 'स्थान चुनें \nमें ',
		ChooseLocation_Subtitle: 'अपने पेड़ के लिए सर्वोत्तम स्थान चुनें। हमारे सभी वृक्षारोपण स्थानीय भागीदारों द्वारा सत्यापित और प्रबंधित हैं।',
		ChooseLocation_VerifiedLocations: 'सत्यापित वृक्षारोपण स्थान',
		ChooseLocation_ChooseSpecific: 'अपने वृक्षारोपण के लिए एक विशिष्ट स्थान चुनें।',
		ChooseLocation_ActiveProjects: 'सक्रिय परियोजनाएं',
		ChooseLocation_ByGeoTree: 'जियोट्री द्वारा',
		ChooseLocation_AllLocationsVerified: 'सभी स्थान सत्यापित हैं और स्थानीय समुदायों के साथ साझेदारी में पेड़ लगाए जाते हैं।',

		ChooseTree_HeroTitleLeft: 'वृक्षारोपण के लिए एक पेड़ चुनें\n',
		ChooseTree_HeroTitleHighlight: 'राजस्थान   ',
		ChooseTree_HeroSubtitleLeft: 'आपके द्वारा लगाया गया हर पेड़ एक ',
		ChooseTree_HeroSubtitleHighlight: ' हरित',
		ChooseTree_HeroSubtitleRight: ' और स्वस्थ राजस्थान में योगदान देता है',
		ChooseTree_ChangeState: 'राज्य बदलें ',
		ChooseTree_TabAll: 'सभी पेड़',
		ChooseTree_TabNative: 'स्वदेशी पेड़',
		ChooseTree_TabFruit: 'फलदार पेड़',
		ChooseTree_TabFlowering: 'फूलों वाले पेड़',
		ChooseTree_NeemName: 'नीम',
		ChooseTree_NeemDesc: 'एक मजबूत स्वदेशी पेड़ जो अपने औषधीय गुणों और वायु शुद्धिकरण गुणों के लिए जाना जाता है।',
		ChooseTree_PeepalName: 'पीपल',
		ChooseTree_PeepalDesc: 'एक पवित्र पेड़ जो रात में भी ऑक्सीजन पैदा करता है और जैव विविधता का समर्थन करता है।',
		ChooseTree_MangoName: 'आम',
		ChooseTree_MangoDesc: 'एक लोकप्रिय फलदार पेड़ जो छाया और स्वादिष्ट फल प्रदान करता है।',
		ChooseTree_GulmoharName: 'गुलमोहर',
		ChooseTree_GulmoharDesc: 'एक सुंदर फूलों वाला पेड़ जो पर्यावरण में जीवंत रंग जोड़ता है।',
		ChooseTree_GrowthRate: 'विकास दर',
		ChooseTree_Maintenance: 'रखरखाव',
		ChooseTree_GreenPointsLabel: 'ग्रीन पॉइंट्स',
		ChooseTree_GrowthMedium: 'मध्यम',
		ChooseTree_GrowthFast: 'तेज़',
		ChooseTree_MaintenanceLow: 'कम',
		ChooseTree_MaintenanceMedium: 'मध्यम',
		ChooseTree_CategoryNative: 'स्वदेशी',
		ChooseTree_CategoryFruit: 'फल',
		ChooseTree_CategoryFlowering: 'फूलों वाला',

		ChooseSpecies_Title: 'पेड़ की प्रजाति चुनें',
		ChooseSpecies_Subtitle: 'लगाने के लिए एक स्वदेशी पेड़ की प्रजाति चुनें',
		ChooseSpecies_GpsVerified: 'जीपीएस सत्यापित परियोजना',
		ChooseSpecies_AcresCovered: 'एकड़ क्षेत्र',
		ChooseSpecies_AvailableTitle: 'उपलब्ध पेड़ की प्रजातियां',
		ChooseSpecies_AvailableSubtitle: 'वह प्रजाति चुनें जिसे आप लगाना चाहते हैं।',
		ChooseSpecies_NativeTag: 'स्वदेशी',
		ChooseSpecies_Lifespan: 'जीवनकाल',
		ChooseSpecies_WaterNeed: 'पानी की आवश्यकता',
		ChooseSpecies_WaterLow: 'कम',
		ChooseSpecies_WaterVeryLow: 'बहुत कम',
		ChooseSpecies_WaterMedium: 'मध्यम',
		ChooseSpecies_ImpactTitle: 'इस पेड़ के साथ आपका प्रभाव',
		ChooseSpecies_ImpactSubtitle: 'देखें कि आपका पेड़ क्या सकारात्मक बदलाव लाएगा।',
		ChooseSpecies_OxygenGenerated: 'उत्पादित ऑक्सीजन',
		ChooseSpecies_WaterSaved: 'बचाया गया पानी',
		ChooseSpecies_SupportsBiodiversity: 'जैव विविधता का समर्थन',
		ChooseSpecies_SelectedLabel: 'चयनित प्रजाति',
		ChooseSpecies_ChangeBtn: 'बदलें',
		ChooseSpecies_ProceedBtn: 'समर्पण के लिए आगे बढ़ें',
		ChooseSpecies_NeemName: 'नीम',
		ChooseSpecies_KhejriName: 'खेजड़ी',
		ChooseSpecies_RohidaName: 'रोहिड़ा',
		ChooseSpecies_AmlaName: 'आँवला',
		ChooseSpecies_BabulName: 'बबूल',
		ChooseSpecies_OxygenVal: '{{count}} किग्रा/वर्ष',
		ChooseSpecies_WaterSavedVal: '{{count}} लीटर/वर्ष',
		ChooseSpecies_BioHigh: 'उच्च',
		ChooseSpecies_BioVeryHigh: 'बहुत उच्च',
		ChooseSpecies_LifespanVal: '{{count}} वर्ष',

		ChoiceTree_HeroTitle: 'शानदार विकल्प! 🍃',
		ChoiceTree_HeroSubtitle: 'आप एक स्वदेशी पेड़ लगाने वाले हैं जो वास्तविक प्रभाव डालता है।',
		ChoiceTree_NativeTo: 'मूल निवासी',
		ChoiceTree_HighCO2: 'उच्च CO₂',
		ChoiceTree_Absorption: 'अवषण',
		ChoiceTree_Drought: 'सूखा',
		ChoiceTree_Resistant: 'प्रतिरोधी',
		ChoiceTree_Long: 'लंबा',
		ChoiceTree_Lifespan: 'जीवनकाल',
		ChoiceTree_QtyTitle: 'आप कितने पेड़ लगाना चाहेंगे?',
		ChoiceTree_Custom: 'कस्टम',
		ChoiceTree_PlantMore: 'अधिक पेड़ लगाएं',
		ChoiceTree_Choose: 'चुनें',
		ChoiceTree_EnterQty: 'मात्रा दर्ज करें',
		ChoiceTree_Co2Year: '{{count}} किग्रा CO₂ / वर्ष',
		ChoiceTree_MoreImpact: 'अधिक पेड़, बड़ा प्रभाव! थोक में रोपण करें और एक हरित कल में योगदान दें।',
		ChoiceTree_WherePlant: 'आप कहाँ रोपण करना चाहेंगे?',
		ChoiceTree_ViewAllProjects: 'सभी परियोजनाएं देखें',
		ChoiceTree_Planted: '{{count}} पेड़ लगाए गए',
		ChoiceTree_YourImpact: 'इस रोपण के लिए आपका प्रभाव',
		ChoiceTree_YouArePlanting: 'आप लगा रहे हैं',
		ChoiceTree_Co2OffsetYear: 'CO₂ ऑफ़सेट / वर्ष',
		ChoiceTree_WaterSoil: 'जल और मृदा',
		ChoiceTree_Conservation: 'संरक्षण',
		ChoiceTree_Supports: 'समर्थन करता है',
		ChoiceTree_Biodiversity: 'जैव विविधता',
		ChoiceTree_MonitoringVal: '3 वर्ष',
		ChoiceTree_Monitoring: 'निगरानी',
		ChoiceTree_VerifiedTransparent: '100% सत्यापित और पारदर्शी',
		ChoiceTree_VerifiedDesc: 'हर पेड़ जीपीएस टैग किया गया है, 3 साल तक निगरानी की जाती है और आपको नियमित अपडेट मिलते हैं।',
		ChoiceTree_SecurePayment: 'सुरक्षित भुगतान',
		ChoiceTree_SecureDesc: 'आपका भुगतान सुरक्षित और एन्क्रिप्टेड है',
		ChoiceTree_TrustedBy: '50K+ द्वारा विश्वसनीय',
		ChoiceTree_PlantersAcross: 'पूरे भारत में रोपणकर्ता',
		ChoiceTree_ProceedBtn: 'समर्पण के लिए आगे बढ़ें',
		ChoiceTree_SecureNote: 'सुरक्षित • पारदर्शी • 50K+ रोपणकर्ताओं द्वारा विश्वसनीय',

		WhichTree_HowItWorks: 'यह कैसे काम करता है?',
		WhichTree_HowItWorksDesc: 'हमारे एल्गोरिदम आपके रोपण उद्देश्य (जैसे कार्बन ऑफ़सेट, उपहार देना) और पर्यावरणीय प्राथमिकताओं (जैसे पानी की आवश्यकता, स्थानीय जैव विविधता) का मूल्यांकन करके आपके चुने हुए राज्य के लिए सबसे उपयुक्त स्वदेशी पेड़ों की सिफारिश करते हैं।',
		WhichTree_GotIt: 'समझ गया!',
		WhichTree_SelectLocation: 'स्थान चुनें',
		WhichTree_ChooseState: 'वृक्षारोपण के लिए एक राज्य चुनें:',
		WhichTree_Cancel: 'रद्द करें',
		WhichTree_FindPerfect: 'अपने उद्देश्य के लिए सही पेड़ खोजें',
		WhichTree_AnswerFew: 'कुछ सवालों के जवाब दें और हम आपके लिए सबसे अच्छे पेड़ की सिफारिश करेंगे।',
		WhichTree_WhyPlanting: '1. आप वृक्षारोपण क्यों कर रहे हैं? ',
		WhichTree_PurposeCarbon: 'कार्बन\nऑफ़सेट',
		WhichTree_PurposeGift: 'पेड़\nउपहार दें',
		WhichTree_PurposeMemory: 'याद\nमें',
		WhichTree_PurposeEnv: 'पर्यावरणीय\nप्रभाव',
		WhichTree_PurposeCsr: 'सीएसआर /\nकॉर्पोरेट',
		WhichTree_PurposePersonal: 'व्यक्तिगत\nवृक्षारोपण',
		WhichTree_WhatMatters: '2. आपके लिए सबसे ज्यादा क्या मायने रखता है? ',
		WhichTree_PriorityCo2: 'उच्चतम CO₂\nअवशोषण',
		WhichTree_PriorityGrowth: 'तेज़\nविकास',
		WhichTree_PriorityNative: 'स्वदेशी\nप्रजाति',
		WhichTree_PriorityMedicinal: 'औषधीय\nमूल्य',
		WhichTree_PriorityWildlife: 'वन्यजीव\nसमर्थन',
		WhichTree_PriorityLifespan: 'लंबा\nजीवनकाल',
		WhichTree_PreferredLocation: '3. पसंदीदा स्थान ',
		WhichTree_ChangeState: 'राज्य बदलें ∨',
		WhichTree_LocationInfo: 'सभी अनुशंसित पेड़ स्वदेशी हैं और आपके चयनित स्थान के लिए उपयुक्त हैं।',
		WhichTree_TopRecommendations: 'आपकी शीर्ष पेड़ सिफारिशें ',
		WhichTree_BestMatch: 'सर्वोत्तम मिलान',
		WhichTree_GpsVerified: 'जीपीएस सत्यापित',
		WhichTree_PlantTree: '{{name}} लगाएं →',
		WhichTree_PlantNow: 'अभी लगाएं →',
		WhichTree_ImpactComparison: 'प्रभाव तुलना ',
		WhichTree_TableTree: 'पेड़',
		WhichTree_TableCo2: 'CO₂ अवशोषण\n(प्रति वर्ष)',
		WhichTree_TableLifespan: 'जीवनकाल',
		WhichTree_TableWater: 'पानी की आवश्यकता',
		WhichTree_TableNative: '{{state}} के\nस्वदेशी',
		WhichTree_TableSurvival: 'जीवित रहने की\nदर',
		WhichTree_BottomBanner: 'आपके द्वारा लगाया गया प्रत्येक पेड़ जीपीएस टैग किया गया है, 3 वर्षों तक उसकी निगरानी की जाती है और वह एक हरित कल में योगदान देता है।',

		DedicateTree_Title: 'अपना पेड़ समर्पित करें',
		DedicateTree_Subtitle: 'किसी विशेष व्यक्ति को समर्पित करके इस वृक्षारोपण को सार्थक बनाएं।',
		DedicateTree_WhoForTitle: 'यह पेड़ किसके लिए है?',
		DedicateTree_DedicationDetails: 'समर्पण विवरण',
		DedicateTree_RecipientName: 'प्राप्तकर्ता का नाम',
		DedicateTree_EnterName: 'नाम दर्ज करें',
		DedicateTree_Occasion: 'अवसर',
		DedicateTree_SelectOccasion: 'अवसर चुनें',
		DedicateTree_OccasionDate: 'अवसर की तिथि',
		DedicateTree_EmailOptional: 'ईमेल (वैकल्पिक)',
		DedicateTree_EnterEmail: 'ईमेल पता दर्ज करें',
		DedicateTree_PersonalMessage: 'व्यक्तिगत संदेश',
		DedicateTree_WriteMessage: 'एक संदेश लिखें...',
		DedicateTree_SpecialOptions: 'विशेष विकल्प',
		DedicateTree_SendCertificate: 'डिजिटल प्रमाणपत्र भेजें',
		DedicateTree_SendCertificateDesc: 'हम प्राप्तकर्ता को ईमेल द्वारा प्रमाणपत्र भेजेंगे',
		DedicateTree_NotifyRecipient: 'ईमेल के माध्यम से प्राप्तकर्ता को सूचित करें',
		DedicateTree_NotifyRecipientDesc: 'प्राप्तकर्ता को इस समर्पण के बारे में सूचित किया जाएगा',
		DedicateTree_ReceiveUpdates: 'विकास अपडेट प्राप्त करें',
		DedicateTree_ReceiveUpdatesDesc: 'अपने पेड़ के विकास के बारे में अपडेट प्राप्त करें',
		DedicateTree_AddToPortfolio: 'पेड़ को मेरे प्रभाव पोर्टफोलियो में जोड़ें',
		DedicateTree_AddToPortfolioDesc: 'अपने हरित प्रभाव को ट्रैक और प्रदर्शित करें',
		DedicateTree_ImpactSummary: 'प्रभाव सारांश',
		DedicateTree_Trees: 'पेड़',
		DedicateTree_TreeVal: '{{count}} पेड़',
		DedicateTree_TreesVal: '{{count}} पेड़',
		DedicateTree_Location: 'स्थान',
		DedicateTree_Certificate: 'प्रमाणपत्र',
		DedicateTree_CertIncluded: 'डिजिटल प्रमाणपत्र शामिल है',
		DedicateTree_CertNotRequested: 'कोई प्रमाणपत्र अनुरोध नहीं किया गया',
		DedicateTree_MakingRealImpact: 'आप वास्तविक प्रभाव डाल रहे हैं!',
		DedicateTree_GreenerTomorrow: 'एक हरित कल में योगदान देने के लिए धन्यवाद।',
		DedicateTree_NumberTrees: 'पेड़ों की संख्या',
		DedicateTree_ContinuePayment: 'भुगतान के लिए आगे बढ़ें',
		DedicateTree_SecurePaymentNote: 'सुरक्षित भुगतान  •  एसएसएल एन्क्रिप्टेड  •  हजारों लोगों द्वारा विश्वसनीय',
		DedicateTree_Done: 'पूर्ण',
		DedicateTree_Confirm: 'पुष्टि करें',
		DedicateTree_Day: 'दिन',
		DedicateTree_Month: 'महीना',
		DedicateTree_Year: 'वर्ष',
		DedicateTree_OptionMyselfTitle: 'स्वयं',
		DedicateTree_OptionMyselfSub: 'अपने खुद के प्रभाव के लिए रोपण करें',
		DedicateTree_OptionBirthdayTitle: 'जन्मदिन',
		DedicateTree_OptionBirthdaySub: 'जन्मदिन मनाएं',
		DedicateTree_OptionAnniversaryTitle: 'वर्षगांठ',
		DedicateTree_OptionAnniversarySub: 'एक विशेष मील के पत्थर का जश्न मनाएं',
		DedicateTree_OptionLovedOneTitle: 'प्रियजन',
		DedicateTree_OptionLovedOneSub: 'किसी विशेष व्यक्ति को एक पेड़ उपहार में दें',
		DedicateTree_OptionMemoryTitle: 'याद में',
		DedicateTree_OptionMemorySub: 'एक स्थायी श्रद्धांजलि बनाएं',
		DedicateTree_OptionCorporateTitle: 'कॉर्पोरेट / सीएसआर',
		DedicateTree_OptionCorporateSub: 'किसी संगठन की ओर से रोपण करें',

		Review_Title: 'अपने वृक्षारोपण\nकी समीक्षा करें',
		Review_Subtitle: 'अपने वृक्षारोपण को पूरा करने से पहले अपने प्रभाव की पुष्टि करें।',
		Review_GpsVerified: 'जीपीएस सत्यापित',
		Review_EstCo2: 'अनुमानित CO₂ प्रभाव',
		Review_DedicationSummary: 'समर्पण सारांश',
		Review_DedicatedTo: 'समर्पित',
		Review_Message: 'संदेश',
		Review_TreeAllocation: 'पेड़ आवंटन',
		Review_ViewDetails: 'विवरण देखें  →',
		Review_EnvImpact: 'आपका पर्यावरणीय प्रभाव',
		Review_CostBreakdown: 'लागत विवरण',
		Review_GPSTracking: 'जीपीएस ट्रैकिंग',
		Review_Included: 'शामिल',
		Review_GrowthMonitoring: 'विकास निगरानी (3 वर्ष)',
		Review_DigitalCertificate: 'डिजिटल प्रमाणपत्र',
		Review_TotalAmount: 'कुल राशि',
		Review_InclusiveTaxes: 'सभी करों सहित',
		Review_ChoosePayment: 'भुगतान विधि चुनें',
		Review_SecurePayments: '100% सुरक्षित भुगतान',
		Review_UpiRecommended: 'यूपीआई (अनुशंसित)',
		Review_DebitCredit: 'डेबिट / क्रेडिट कार्ड',
		Review_NetBanking: 'नेट बैंकिंग',
		Review_AllBanksSupported: 'सभी प्रमुख बैंक समर्थित',
		Review_Wallets: 'वॉलेट',
		Review_WalletsSupported: 'Paytm, Amazon Pay, Mobikwik और अधिक',
		Review_SSLTitle: '100% सुरक्षित भुगतान',
		Review_SSLDesc: 'एसएसएल एन्क्रिप्टेड',
		Review_VerifiedPlantation: 'सत्यापित वृक्षारोपण',
		Review_VerifiedDesc: 'वास्तविक पेड़, वास्तविक प्रभाव',
		Review_RefundProtection: 'धनवापसी सुरक्षा',
		Review_RefundDesc: 'आसान और परेशानी मुक्त',
		Review_TrustedBy: '50K+ द्वारा विश्वसनीय',
		Review_PlantersAcross: 'पूरे भारत में रोपणकर्ता',
		Review_PromiseTitle: 'आपका प्रभाव। हमारा वादा।',
		Review_PromiseDesc: 'हर पेड़ जीपीएस ट्रैक और सत्यापित है।',
		Review_PaySecurely: '₹{{amount}} सुरक्षित रूप से भुगतान करें',
		Review_SecureGateway: 'सुरक्षित भुगतान गेटवे • एसएसएल एन्क्रिप्टेड • आपका डेटा सुरक्षित है',
		Review_AlertTitle: 'भुगतान की पुष्टि करें',
		Review_AlertMsg: '₹1,990 {{method}} के माध्यम से सुरक्षित रूप से प्रोसेस करें?',
		Review_AlertCancel: 'रद्द करें',
		Review_AlertPayNow: 'अभी भुगतान करें',

		Payment_AlmostThere: 'बस पहुँच गए',
		Payment_Subtitle: 'आगे बढ़ने से पहले अपने वृक्षारोपण विवरण की समीक्षा करें।',
		Payment_Summary: 'वृक्षारोपण सारांश',
		Payment_TreeSpecies: 'पेड़ की प्रजाति',
		Payment_GPSStatus: 'जीपीएस स्थिति',
		Payment_GPSVerified: 'जीपीएस सत्यापित',
		Payment_PreviewTitle: 'आपका प्रभाव पूर्वावलोकन',
		Payment_WaterConservation: 'जल\nसंरक्षण\nयोगदान',
		Payment_DonationBreakdown: 'दान का विवरण',
		Payment_SecureTitle: '256-बिट एसएसएल एन्क्रिप्टेड',
		Payment_SecureDesc: 'आपकी भुगतान जानकारी हमारे पास सुरक्षित है',
		Payment_NoStoreCard: 'हम आपके कार्ड का विवरण संग्रहीत नहीं करते हैं',
		Payment_PaySecurelyBtn: '₹{{amount}} सुरक्षित रूप से भुगतान करें →',
		Payment_AgreeTerms: 'आगे बढ़कर, आप हमारे ',
		Payment_TermsConditions: 'नियम और शर्तों से सहमत हैं',

		Details_Title: 'अपने पेड़ के बारे में\nथोड़ा बताएं',
		Details_Subtitle: 'एक व्यक्तिगत स्पर्श जोड़ें! यह हमें आपका पेड़ समर्पित करने और इसके विकास के बारे में आपको अपडेट रखने में मदद करता है।',
		Details_SummaryTitle: 'आपका चयन सारांश',
		Details_PlantedBy: 'द्वारा रोपित',
		Details_PlantedByYou: 'आप',
		Details_AddDetails: 'अपने विवरण जोड़ें',
		Details_YourName: 'आपका नाम',
		Details_EnterNamePlaceholder: 'अपना पूरा नाम दर्ज करें',
		Details_DedicateOptional: 'अपना पेड़ समर्पित करें (वैकल्पिक)',
		Details_DedicatePlaceholder: 'उदा. किसी की याद में / किसी प्रियजन के लिए',
		Details_CertificateNote: 'यह आपके पेड़ के प्रमाणपत्र पर दिखाई देगा।',
		Details_MessageOptional: 'एक संदेश जोड़ें (वैकल्पिक)',
		Details_MessagePlaceholder: 'उदा., एक हरे-भरे कल के लिए',
		Details_StayUpdated: 'अपडेट रहें',
		Details_StayUpdatedDesc: 'हम आपको आपके पेड़ के विकास और प्रभाव के बारे में अपडेट रखेंगे।',
		Details_SafeHands: 'आपका पेड़ सुरक्षित हाथों में है!',
		Details_SafeHandsDesc: 'सभी वृक्षारोपण हमारे स्थानीय भागीदारों द्वारा सत्यापित और निगरानी किए जाते हैं।',
		Details_ContinuePayment: 'भुगतान के लिए आगे बढ़ें',

		Confirmed_Title: 'वृक्षारोपण की पुष्टि!',
		Confirmed_Subtitle: 'आपके {{qty}} {{name}} पेड़ वृक्षारोपण के लिए सफलतापूर्वक आरक्षित कर लिए गए हैं।',
		Confirmed_TreesReserved: 'पेड़ आरक्षित',
		Confirmed_EstimatedImpact: 'अनुमानित CO₂ प्रभाव',
		Confirmed_JourneyHeader: 'वृक्षारोपण यात्रा',
		Confirmed_PaymentComplete: 'भुगतान\nपूरा हुआ',
		Confirmed_PlantationReserved: 'वृक्षारोपण\nआरक्षित',
		Confirmed_PlantationScheduled: 'वृक्षारोपण\nनिर्धारित',
		Confirmed_GpsVerification: 'जीपीएस\nसत्यापन',
		Confirmed_GrowthUpdates: 'विकास\nअपडेट',
		Confirmed_PlantationIdLabel: 'आपकी वृक्षारोपण आईडी',
		Confirmed_DateLabel: 'तिथि',
		Confirmed_ScanToView: 'अपना वृक्षारोपण देखने\nके लिए स्कैन करें',
		Confirmed_WhatsNext: 'आगे क्या होगा?',
		Confirmed_WithinDays: '7-15 दिनों के भीतर',
		Confirmed_NextPlantComplete: 'वृक्षारोपण पूरा किया जाएगा',
		Confirmed_NextGpsAssign: 'जीपीएस निर्देशांक आवंटित किए जाएंगे',
		Confirmed_NextPhotosUpload: 'जियो-टैग की गई तस्वीरें अपलोड की जाएंगी',
		Confirmed_NextCertIssued: 'डिजिटल प्रमाणपत्र जारी किया जाएगा',
		Confirmed_ShareImpact: 'अपना प्रभाव साझा करें',
		Confirmed_InspireOthers: 'दूसरों को बदलाव लाने के लिए प्रेरित करें',
		Confirmed_TrackMyTrees: 'मेरे पेड़ों को ट्रैक करें',
		Confirmed_DownloadReceipt: 'रसीद डाउनलोड करें',
		Confirmed_AlertReceiptTitle: 'रसीद डाउनलोड',
		Confirmed_AlertReceiptMsg: 'आपकी भुगतान रसीद पीडीएफ के रूप में डाउनलोड की जा रही है...',
		Confirmed_AlertIdTitle: 'आईडी कॉपी की गई',
		Confirmed_AlertIdMsg: 'वृक्षारोपण आईडी सफलतापूर्वक क्लिपबोर्ड पर कॉपी की गई।',
		Confirmed_AlertShareTitle: 'प्रभाव साझा करें',
		Confirmed_AlertShareMsg: '{{channel}} के लिए साझाकरण संवाद खोला जा रहा है...',

		ThankYou_Title: 'पेड़ सफलतापूर्वक\nआरक्षित!',
		ThankYou_Subtitle: 'हरे-भरे कल की दिशा में कदम उठाने के लिए धन्यवाद। आपका पेड़ लगाने का अनुरोध सत्यापित हो गया है।',
		ThankYou_PlantedAt: 'आपका पेड़ यहाँ लगाया जाएगा\n',
		ThankYou_DetailsTitle: 'आपके पेड़ का विवरण',
		ThankYou_TreeId: 'पेड़ की आईडी',
		ThankYou_PlantedBy: 'द्वारा रोपित',
		ThankYou_ImpactGlance: 'एक नज़र में आपका प्रभाव',
		ThankYou_ExpectedAnnual: 'अनुमानित वार्षिक\nCO₂ अवशोषण',
		ThankYou_ExpectedLifetime: 'अनुमानित जीवनकाल\nप्रभाव',
		ThankYou_ExpectedLifetimeVal: '{{count}}+ किग्रा CO₂',
		ThankYou_SupportsBiodiversity: 'जैव विविधता\nका समर्थन',
		ThankYou_GpsEnabled: 'जीपीएस ट्रैकिंग\nसक्रिय',
		ThankYou_CertTitle: 'डिजिटल पेड़ प्रमाणपत्र',
		ThankYou_CertAvailable: 'वृक्षारोपण सत्यापन के बाद उपलब्ध।',
		ThankYou_CertPreviewBtn: 'प्रमाणपत्र पूर्वावलोकन देखें',
		ThankYou_NextTitle: 'आगे क्या होता है?',
		ThankYou_TrackMyTree: 'मेरे पेड़ को ट्रैक करें',
		ThankYou_PlantAnother: 'एक और पेड़ लगाएं',
		ThankYou_MakingImpact: 'प्रभाव डालने के लिए धन्यवाद!',
		ThankYou_MovementDesc: 'अब आप स्वच्छ, हरित ग्रह की दिशा में आंदोलन का हिस्सा हैं।',

		Portfolio_Title: 'मेरा वृक्षारोपण पोर्टफोलियो',
		Portfolio_Subtitle: 'अपने पेड़ों को ट्रैक करें। अपना प्रभाव देखें। दुनिया को प्रेरित करें।',
		Portfolio_ActiveTrees: 'सक्रिय पेड़',
		Portfolio_TotalCo2: 'कुल CO₂ प्रभाव',
		Portfolio_ActiveProjects: 'सक्रिय परियोजनाएं',
		Portfolio_Status: 'स्थिति',
		Portfolio_ExpectedDate: 'अनुमानित तिथि',
		Portfolio_Progress: 'प्रगति',
		Portfolio_ViewJourney: 'पेड़ की यात्रा देखें',
		Portfolio_ViewOnMap: 'मानचित्र पर देखें',
		Portfolio_ProjectDetails: 'परियोजना विवरण',
		Portfolio_ShareProject: 'परियोजना साझा करें',
		Portfolio_MyTreesStatus: 'मेरे पेड़ों की स्थिति',
		Portfolio_ViewAll: 'सभी देखें >',
		Portfolio_ViewAllTrees: 'सभी पेड़ देखें >',
		Portfolio_TreeDetails: 'पेड़ का विवरण',
		Portfolio_LatestUpdates: 'नवीनतम अपडेट',
		Portfolio_NoUpdatesYet: 'अभी तक कोई अपडेट नहीं। वृक्षारोपण पूरा होने और तस्वीरें अपलोड होने के बाद हम आपको सूचित करेंगे।',
		Portfolio_DifferenceTitle: 'आप वास्तव में बदलाव ला रहे हैं! 🌏',
		Portfolio_DifferenceDesc: 'हरे-भरे ग्रह के निर्माण में मदद करने के लिए धन्यवाद।',
		Portfolio_TimelinePayment: 'भुगतान पूर्ण हुआ',
		Portfolio_TimelineReserved: 'वृक्षारोपण आरक्षित',
		Portfolio_TimelineScheduled: 'वृक्षारोपण निर्धारित',
		Portfolio_TimelineGps: 'जीपीएस सत्यापन',
		Portfolio_TimelineUpdates: 'विकास अपडेट',
		Portfolio_TimelineExpectedDays: '7-15 दिनों में अनुमानित',
		Portfolio_TimelinePending: 'लंबित',
		Portfolio_AlertCopied: 'कॉपी किया गया',
		Portfolio_AlertBatchId: 'बैच आईडी सफलतापूर्वक क्लिपबोर्ड पर कॉपी की गई।',

		Journey_Title: 'मेरी पेड़ यात्रा',
		Journey_Subtitle: 'अपने पेड़ को ट्रैक करें। अपना प्रभाव देखें। दुनिया को प्रेरित करें।',
		Journey_TreeIdLabel: 'पेड़ की आईडी: ',
		Journey_StepPayment: 'भुगतान\nपूर्ण',
		Journey_StepReserved: 'पेड़\nआरक्षित',
		Journey_StepScheduled: 'वृक्षारोपण\nनिर्धारित',
		Journey_StepPlanted: 'पेड़\nरोपा गया',
		Journey_StepGps: 'जीपीएस\nसत्यापित',
		Journey_StepUpdates: 'विकास\nअपडेट',
		Journey_StepCert: 'प्रमाणपत्र\nजारी',
		Journey_StageBefore: 'वृक्षारोपण\nसे पहले',
		Journey_StageMonth: 'महीना {{count}}',
		Journey_StageAwaiting: 'वृक्षारोपण की\nप्रतीक्षा',
		Journey_StageComing: 'जल्द\nआ रहा है',
		Journey_ImpactWater: 'बचाया गया पानी',
		Journey_ImpactHabitat: 'आवास स्थान',
		Journey_ImpactWildlife: 'पक्षी और वन्यजीव',
		Journey_TimelineTitle: 'परियोजना अपडेट',
		Journey_DocsTitle: 'दस्तावेज़ और प्रमाणपत्र',
		Journey_Download: 'डाउनलोड',
		Journey_ComingSoon: 'जल्द आ रहा है',
		Journey_Invoice: 'चालान / रसीद',
		Journey_InvoiceDesc: '₹1,990 का भुगतान',
		Journey_PlantationPhotos: 'वृक्षारोपण तस्वीरें',
		Journey_PhotosDesc: 'साइट से जियो-टैग की गई तस्वीरें',
		Journey_ReportDesc: 'पर्यावरण प्रभाव रिपोर्ट',
		Journey_ViewPhotosBtn: 'वृक्षारोपण तस्वीरें देखें',
		Journey_ShareImpactBtn: 'मेरा प्रभाव साझा करें',
		Journey_AlertCopiedTitle: 'सफलता',
		Journey_AlertCopiedMsg: 'पेड़ आईडी: GT-2026-10245 क्लिपबोर्ड पर कॉपी की गई!',

		ChoiceTree_StepState: 'राज्य',
		ChoiceTree_StepProject: 'परियोजना',
		ChoiceTree_StepTree: 'पेड़',
		ChoiceTree_StepDedication: 'समर्पण',
		ChoiceTree_StepPayment: 'भुगतान',
	},
};

const String = new Proxy(
	{} as Record<string, string>,
	{
		get: (_, prop: string) => {
			const lang = getLanguage();
			return translations[lang]?.[prop] ?? translations.en[prop] ?? prop;
		},
	}
);

export default String;
