
import { getLanguage } from './i18n';

const translations: Record<'en' | 'hi', Record<string, string>> = {
	en: {
		AppName: 'Store Pedia',
		Getstarted: 'Get started',
		I_have_planted_a_Tree: 'I have planted a Tree',
		Login_Signup: 'Login/Sign up',
		SignIn: 'Sign In',
		SendOTP: 'Send OTP',
		Continue: 'Continue',
		WelcomeBack: 'Welcome back',
		MobileNumber: 'Mobile number',
		OtpVerify: 'OTP Verification',
		NumberPlaceholder: 'Enter your Number',
		PasswordLabel: 'Password',
		PasswordPlaceholder: 'Enter your password',
		ForgotPassword: 'Forgot password?',
		LoginButton: 'Log in',
		NoAccount: "Don't have an account?",
		IndividualType: 'Individual',
		GovernmentType: 'Government',
		ForgotTitle: 'Reset Password',
		NewPassword: 'New password',
		NewPasswordPlaceholder: 'Enter new password',
		ConfirmPassword: 'Confirm password',
		ConfirmPasswordPlaceholder: 'Repeat new password',
		ResetButton: 'Reset password',
		Carbon_WelcomeTitle: 'What’s your carbon footprint?',
		Carbon_WelcomeSubtitle: 'See how your lifestyle affects the environment',
		Carbon_CalculateButton: 'Calculate my Footprint',
		Carbon_Household_Header: 'Household',
		Carbon_Household_PeopleLabel: 'How many people live in your household?',
		Carbon_Household_PeoplePlaceholder: 'e.g. 3',
		Carbon_Household_PincodeLabel: 'What is your pincode?',
		Carbon_Household_PincodePlaceholder: 'e.g. 380015',
		Carbon_Household_Next: 'Continue to Energy',
		Carbon_Energy_Header: 'Energy',
		Carbon_Energy_ElectricityPlaceholder: 'Electricity (₹ / month)',
		Carbon_Energy_GasPlaceholder: 'Natural Gas (₹ / month)',
		Carbon_Energy_FuelOilPlaceholder: 'Fuel Oil (₹ / month)',
		Carbon_Energy_PropanePlaceholder: 'Propane (₹ / month)',
		Carbon_Energy_Next: 'Continue to Transportation',
		Carbon_Transport_Header: 'Transportation',
		Carbon_Transport_VehiclesLabel: 'How many vehicles does your household use?',
		Carbon_Transport_VehiclesPlaceholder: 'Number of vehicles',
		Carbon_Transport_DistanceLabel: 'How many miles do you drive per year?',
		Carbon_Transport_DistancePlaceholder: 'Distance per year (km)',
		Carbon_Transport_MileageLabel: 'What is the average mileage of your vehicle?',
		Carbon_Transport_MileagePlaceholder: 'Average mileage (km/l)',
		Carbon_Transport_Next: 'Continue to Waste',
		Carbon_Waste_Header: 'Waste',
		Carbon_Waste_Plastic: '☑ Plastic',
		Carbon_Waste_Glass: '☑ Glass',
		Carbon_Waste_Paper: '☑ Paper',
		Carbon_Waste_Metal: '☑ Metal',
		Carbon_Waste_Next: 'See My Results',
		Carbon_Result_Title: 'My Carbon Footprint',
		Carbon_Result_Subtitle: 'Annual estimated CO₂ emissions',
		Carbon_Result_EmailPlaceholder: 'Enter email to get report',
		Carbon_Result_Button: 'Get My Report',
		Carbon_Back: 'Back',
		Small: 'Small actions today',
		greener: '🌱 A greener tomorrow',
		Climate_change: 'Climate change',
		startswithus: 'starts with us',
		Our_daily_choices: 'Our daily choices create carbon emissions—often without us noticing.',
		Understand_your_impact: 'Understand your impact',
		Measure_your_footprint: 'Measure your carbon footprint and discover simple ways to reduce it.',
		Offset_you: 'Offset what you',
		avoid: 'can’t avoid',
		Support_verified: 'Support verified climate projects and make a real difference.',
		Plant_a_tree: 'Plant a tree and help us to ',
		Cure_our_planet: 'cure our planet',
		Enterdigit: 'Enter the 6-digit code sent to you at',
		NotRecevice: 'If you not receive OPT? ',
		Resend_Now: 'Re-send',
		agree_with: 'By clicking Continue, you agree with our',
		Privacy_Policy: 'Privacy Policy',
		Hey_User: 'Hey ',
		Celebrate: 'Let’s Celebrate your Occasion',
		Mother_Earth: 'Help Us To Save Our Mother Earth',
		Explore_plantations: 'Explore plantations across India, from heritage lands to green fields',
		IPLDotBall: 'IPL Dot Ball',
		Every_dot_ball_counts: 'Explore plantations across India, from heritage lands to green fields. Every dot ball counts—transform cricket moments into real tree plantations.',
		Dot_Ball: '1 Dot Ball = 1 Tree',
		States_of_India: 'States of India',
		Discover_GeoTree: 'Discover how GeoTree connects plantations across India, blending nature with culture. Explore each state’s green journey alongside its iconic heritage.',
		Add_your_tate: 'Add your state',
		Join_Plant: ' Join us. Plant a tree to add your state in the list.',
		Start_your: 'Know your',
		footprint_journey: 'Carbon Footprint',
		See_how_add_up: 'See how your daily choices add up',
		Calculate: 'Calculate Carbon Footprint',
		Next: 'Next',
		footprint_track: 'Let’s track your carbon !',
		Which_type: 'Content Home Type',
		vehicle_type: 'What is your vehicle type?',
		electricity_used: 'How is your electricity you used?',
		TreesPlantedImpact: 'Trees Planted',
		CO2OffsetImpact: 'CO2 Offset',
		StartPlanting: 'Start Planting',
		ChooseNextTree: 'Choose your next tree to plant and track its growth.',
		HelloUserImpact: 'Hello ',
		GrowGreenerPlanet: 'Let\'s grow a greener planet today',
		TotalCO2OffsetImpact: 'Total CO2 Offset',
		KgUnitOut: ' kg',
		OffsetProgressYears: 'Offset Progress (Years)',
		FindProjectsBtn: 'Find Projects',
		GlobalRanking: 'GLOBAL RANKING',
		ContributorsLabel: 'CONTRIBUTORS',
		LocationsLabel: 'LOCATIONS',
		TreesUnit: ' Trees',
		TonsCO2Unit: ' Tons CO₂',
		UsersUnit: ' Users',
		AreasUnit: ' Areas',
		Top5PercentPlanters: 'Top 5% of Planters',
		RankedGlobally1402: 'Ranked #1,402 globally',
		MilestonesLabel: 'Milestones',
		ViewAllBtn: 'View All',
		CO2Saved100kg: '100kg CO2 Saved',
		TreesPlanted10: '10 Trees Planted',
		WaterGuardian: 'Water Guardian',
		CommunityProjectsLabel: 'Community Projects',
		AmazonReforestation: 'Amazon Reforestation',
		GoalReached85Percent: '85% of goal reached',
		ScandinavianTaiga: 'Scandinavian Taiga',
		GoalReached42Percent: '42% of goal reached',
		TreeSpeciesBreakdownLabel: 'Tree Species Breakdown',
		OakTrees: 'Oak Trees',
		Mangroves: 'Mangroves',
		PineTrees: 'Pine Trees',
		describes_your_diet: 'What best describes your diet?',
		Result: 'Result',
		carbon_footprint: 'Your carbon account',
		Based_on_your_answers: 'Based on your answers',
		AnnualCO2Emissions: 'Annual CO2 Emissions',
		Offsetmyfootprint: 'Offset my account',
		See_reduce: 'See how to reduce',
		meaningful: 'Turn your special moments into a meaningful impact',
		SelectOccasion_Type: 'Select Event Type',
		PLANTATIONDETAILS: 'PLANTATION DETAILS',
		Choose_Number_Trees: 'Choose Number of Trees *',
		Distribute_Plants: ' Distribute n plants by species',
		Add_Species: '+ Add Species',
		Plantname: 'Plant name',
		Quantity: 'Quantity',
		Remove: 'Remove',
		Name: 'Name *',
		Date: 'Date *',
		Message_optional: 'Message',
		BIRTHDAY_Message_optional: 'Birthday Message',
		height: 'Height (cm) *',
		Price: 'Price (₹) *',
		Choose_Location: 'Select a State',
		Choose_Location_for_your_plant: 'Select Project for Plantation',
		Choose_location: 'Choose location',
		SUBMIT: 'SUBMIT',
		Trees_PlantedSuccessfully: 'Trees Planted Successfully!',
		Certificate_of_TreePlantation: 'Certificate of Tree Plantation',
		This_certifies_that: 'This certifies that',
		welcomeSmall: 'WELCOME TO',
		headline: ' Dot Ball Tree Plantation',
		helpText: 'Help make cricket greener by supporting dot balls',
		perTeam: 'Per Team',
		perMatch: 'Per Match',
		wholeTournament: 'Whole Tournament',
		IPL_Dot_Ball_Tree_Plantation: ' Dot Ball Tree Plantation',
		Team: 'Team',
		Match: 'Match',
		perTeamSmall: 'Every dot ball helps plant a tree',
		Select_Team: 'Select Team',
		PerTeamSelected: 'Per Team Selected',
		PerMatchSelected: 'Per Match Selected',
		Select_treesfor: 'Select trees for ',
		trees: 'trees',
		dots: 'dots ball',
		WholeTournamentSelected: 'Whole Tournament Selected',
		Select_Team_1: 'Select Team 1',
		Select_Team_2: 'Select Team 2',
		Select_Team_3: 'Select Team 3',
		tree_planted_on: '1 dot ball = 1 tree planted',
		dot_balls: 'dot balls',
		Donate: 'Donate :',
		Estimate: 'Estimate Dot Balls  : ',
		Update: 'Update',
		Submit: 'Submit',
		TrackingDashboard: 'Tracking Dashboard',
		TrackingOverview: 'Plantation Overview',
		TrackingLiveLocation: 'Live Location',
		TrackingGrowthTimeline: 'Growth Timeline',
		TrackingImpactSummary: 'Impact Summary',
		TrackingViewFullMap: 'View on Full Map',
		TrackingDatePlanted: 'Date Planted',
		TrackingEstimatedCO2: 'Estimated CO₂ Absorbed',
		TrackingOxygenGenerated: 'Oxygen Generated',
		TrackingDistanceLabel: 'Distance from you',
		TrackingLongitudeLabel: 'Longitude',
		TrackingLatitudeLabel: 'Latitude',
		TrackingOrderPlantationId: 'Order ID / Plantation ID',
		TrackingOrderPlantationValue: 'PTN-876552110',
		TrackingInitiativeTitle: 'Green Future Initiative',
		TrackingTreesPlanted: 'Trees Planted',
		TrackingPlanted: 'Planted',
		TrackingGrowing: 'Growing',
		TrackingTimelineSapling: 'Sapling',
		TrackingTimelineYoungTree: 'Young Tree',
		TrackingTimelineMatureTree: 'Mature Tree',
		TrackingTimelineHealthy: 'Healthy',
		TrackingTimelineInProgress: 'In Progress',
		TrackingTimelineScheduled: 'Scheduled',
		TrackingTimelineDate1: '15 Aug 2025',
		TrackingTimelineDate2: '14 Nov 2025',
		TrackingTimelineDate3: '15 Feb 2026',
		TrackingDatePlantedValue: '15 Aug 2025',
		TrackingEstimatedCO2Value: ' Tons',
		TrackingEstimatedCO2Note: 'Reduced carbon footprint ',
		TrackingOxygenGeneratedValue: ' kg',
		TrackingOxygenGeneratedNote: ' kg of fresh oxygen',
		LanguageSelectTitle: 'Choose Language',
		LanguageSelectSubtitle: 'Select your preferred language',
		LanguageEnglish: 'English',
		LanguageHindi: 'हिंदी',
		ChangeLanguage: 'Change Language',
		ProfileTitle: 'Profile',
		LogOut: 'Log Out',
		PaymentHistory: 'Payment History',
		Certificates: 'Certificates',
		Notifications: 'Notifications',
		FaqSupport: 'FAQs & Support',
		SearchHelp: 'Search for help',
		LiveChat: 'Live Chat',
		EmailUs: 'Email',
		CallUs: 'Call Us',
		FAQsTitle: 'Frequently Asked Questions',
		StillNeedHelp: 'Still need help?',
		SupportTeamAvailable: 'Our support team is available 24/7 to assist you with any questions.',
		ContactSupport: 'Contact Support',
		History: 'History',
		PlantationHistory: 'Plantation History',
		Language: 'Language',
		ImpactSummaryCards: 'Impact Summary Cards',
		TotalTreesPlanted: 'Total Trees Planted',
		TotalCO2Emissions: 'Total CO₂ Emissions',
		TreeCountLabel: 'Tree Count',
		PlantationHistoryTitle: 'Plantation History',
		TonUnit: 't',
		PlantTreesTitle: 'Plant Trees',
		PlantTreesSubtitle: 'for Special Events',
		PlantTreesDescription: 'Celebrate birthdays, anniversaries,\n& memories with trees.',
		Start: 'Start',
		CategoryHome: 'Home',
		CategoryTransport: 'Transport',
		CategoryFood: 'Food',
		YourCarbonAccount: 'Your carbon account',
		Energy: 'Energy',
		Waste: 'Waste',
		Breakdown: 'Breakdown',
		OffsetRecommendation: 'Offset recommendation',
		CarbonKgPerYear: 'kg CO₂/year',
		CarbonTonsPerYear: 'tons CO₂/year',
		SelectState: 'Select State',
		ExploreMore: 'Explore more',
		EnterNamePlaceholder: 'Enter name',
		ChooseStatePlaceholder: 'Choose State',
		ChooseProjectPlaceholder: 'Choose Project',
		SelectPlantPlaceholder: 'Select plant',
		SelectQuantityPlaceholder: 'Select quantity',
		HeightPlaceholder: 'Height',
		PricePlaceholder: 'Price',
		MessagePlaceholder: 'Write a message',
		CarbonFootprint: 'Carbon Footprint',
		DotBallLabel: 'Dot Ball',
		CarbonOffsetLabel: 'Carbon Offset',
		DateLabel: 'Date',
		TeamLabel: 'Team',
		CarbonResultLabel: 'Carbon result',
		TypeLabel: 'Type',
		TotalCO2Label: 'Total CO₂',
		TreesSupportedLabel: 'Trees supported',
		TreesLabel: 'trees',
		AmountLabel: 'Amount',
		LocationLabel: 'Location',
		NotAvailable: 'N/A',
		NoRecord: "No Record Found",
		HistoryInstruction: 'Choose your type of plantation.',
		TonUnitLabel: 'tons',
		TurnedDotBallsIntoTrees: 'Turned dot balls into trees',
		JoinCricketGreener: 'Join to make cricket greener',
		DownloadCertificate: 'Download certificate',
		ShareOnWhatsApp: 'Share on WhatsApp',
		ShareOnInstagram: 'Share on Instagram',
		TeamChallengeTitle: 'Team Challenge',
		TeamChallengeSubtitle: 'Support your team with trees',
		FansLabel: 'Fans',
		Support: 'Support',
		CustomizeTrees: 'Customize Trees:',
		CustomizeDotBalls: 'Customize Dot Balls:',
		PricePerTree: '₹10 per tree',
		Confirm: 'Confirm',
		ErrorTitle: 'Error',
		ErrorEnterValidDotBalls: 'Please enter a valid number of dot balls',
		ErrorEnterValidTrees: 'Please enter a valid number of trees',
		ErrorLargerThanAvailableDotBalls: 'Larger than available dot balls',
		ErrorLargerThanAvailableTeamDotBalls: 'Value is larger than available team dot balls',
		ErrorLargerThanSelectedTeamBalls: 'Value is larger than selected team balls',
		ErrorLargerThanAvailableMatchDots: 'Value is larger than available match dots',
		ErrorTeamIdMissing: 'Team ID is missing',
		ErrorSelectTeam: 'Please select a team.',
		SupportSubmittedSuccess: 'Support submitted successfully',
		ErrorSomethingWentWrong: 'Something went wrong',
		ErrorUnableToReachServer: 'Unable to reach server',
		DotBallsEqualsTreesPlanted: 'Dot balls = Trees planted',
		TreesFundedLabel: 'Trees funded:',
		SupportWithTrees: 'Support with Trees',
		TabToday: 'Today',
		TabPrevious: 'Previous',
		TabUpcoming: 'Upcoming',
		TableHeaderDate: 'Date',
		TableHeaderMatches: 'Matches',
		TableHeaderPrePlantation: 'Pre-plantation',
		TableHeaderDotBalls: 'Dot balls',
		SelectTeamToSupport: 'Select Team to Support:',
		Match_H: 'Match',
		MatchLabel: 'Match Details',
		Team1Label: 'Team 1',
		Team2Label: 'Team 2',
		PlantNameLabel: 'Plant Name',
		ScientificNameLabel: 'Scientific Name',
		CO2AbsorptionLabel: 'CO₂ Absorption',
		MaturityLabel: 'Maturity',
		TreeHeightLabel: 'Tree Height',
		RateLabel: 'Rate',
		Close: 'Close',
		ErrorSelectHouseType: 'Please select house type',
		ErrorSelectTransportType: 'Please select transport type',
		ErrorSelectFoodType: 'Please select food type',
		ThankYouTitle: 'Thank You for Your Green Contribution! 🌱',
		ThankYouMessage: 'Your tree has been successfully planted.',
		ThankYouPlanting: 'Together, we’re restoring nature and fighting climate change—one tree at a time.',
		GoToHome: 'Go to Home',
		Skip: 'Skip',
		HOUSE_TYPE: "Please select house type",
		TRANSPORT_TYPE: "Please select transport type",
		DITE_TYPE: "Please select food type",
		NO_DATA_FOUND: "No data found",
		RELATION_WITH_PERSON: "Select relation with person",
		AGE: "Age",
		AGE_Placeholder: "Enter age",
		DEATH_ANNIVERSY_YEAR: "Death Anniversary Year",
		DEATH_ANNIVERSY_YEAR_PLACEHOLDER: "Enter death anniversary year",
		EART_DAY_THEAM: "Earth Day Theme",
		EVENT_DATE: "Event Date",
		PLANTATION_PURPOSE: "Purpose of Plantation",
		HOUSE_OWNER_NAME: "House Owner",
		City_Area: "City / Area",
		City_Area_Placeholder: "Enter city or area",
		HOUSE_WARMING_DATE: "House Warming Date",
		RETIRED_PERSON_NAME: "Retired Person Name",
		RETIRED_PERSON_NAME_PLACEHOLDER: "Enter retired person name",
		Organization_Department: "Organization/Department",
		Organization_Department_Placeholder: "Enter organization or department",
		Years_of_Service: "Years of Service",
		Years_of_Service_Placeholder: "Enter years of service",
		A_new_beginning_with_nature: "A new beginning with nature",
		Share_Instagram: "Share on Instagram",
		Share_WhatsApp: "Share on WhatsApp",
		Download_Certificate: "Download Certificate",
		Scan_verify: "Scan to verify plantation record",
		Certificate_Text: "has celebrated by planting trees",
		supportTitle: "Support Dot-Ball Tree Plantation",
		supportSubtitle: "Fund trees for dot balls bowled!",
		paymentMethodTitle: "Select Payment Method",
		Location_Label: "Location:",
		Tree_Type_Label: "Tree Type: Native, climate-suitable species",
		CO2_Label: "CO₂ Offset:",
		Date_Label: "Date:",
		Occasion_Title: 'Occasion Title',
		Occasion_Title_Placeholder: 'Enter occasion title',
		Occasion_Description: 'Occasion Description',
		Occasion_Description_Placeholder: 'Enter occasion description',
		Occasion_Date: 'Occasion Date',
		Honoured_Person_Name: 'Honoured Person(s) Name',
		Honoured_Person_Name_Placeholder: 'Enter honoured person(s) name',
		Teacher_Name: 'Teacher’s Name',
		Teacher_Name_Placeholder: 'Enter teacher’s name',
		School_College_Name: 'School/College Name',
		School_College_Name_Placeholder: 'Enter school or college name',
		Subject_Role: 'Subject / Role',
		Subject_Role_Placeholder: 'Enter subject or role',
		Teacher_Day_Date: 'Teacher’s Day Date',
		Plantation_Drive_Type: 'Plantation Drive Type',
		Plantation_Drive_Type_Placeholder: 'Select plantation drive type',
		Number_of_Participants: 'Number of Participants',
		Number_of_Participants_Placeholder: 'Enter number of participants',
		School_NGO_Organization_Name: 'School / NGO / Organization Name',
		School_NGO_Organization_Name_Placeholder: 'Enter school, NGO or organization name',
		Couple_Name: 'Couple Name *',
		Couple_name_placeholder: 'Enter couple name',
		Anniversary_Year: 'Anniversary Year',
		Anniversary_Year_Placeholder: 'Enter anniversary year',
		Relationship_Message: 'Relationship Message',
		Relationship_Message_Placeholder: 'Enter relationship message',
		Death_Anniversary_message: 'Death Anniversary Message',
		Death_Anniversary_message_Placeholder: 'Enter death anniversary message',
		Invalid_Mobile_Number: 'Phone Number should consist of 10 digits',
		Please_enter_phone_number: 'Please enter your phone number',
		Please_enter_name: 'Please enter a name.',
		Please_select_project: 'Please select a project.',
		Please_add_at_least_one_species: 'Please add at least one species.',
		Please_complete_species_details: 'Please complete all species details (plant, height, quantity, rate).',
		Unable_to_submit: 'Unable to submit.',
		Unable_to_submit_try_again: 'Unable to submit. Please try again.',
		completed: 'completed',
		occasionText: "On the occasion of {{name}}",
		Relation_Self: 'Self',
		Relation_Father: 'Father',
		Relation_Mother: 'Mother',
		Relation_Friend: 'Friend',
		Relation_Other: 'Other',
		EarthDay_ClimateAction: 'Climate Action',
		EarthDay_PlasticFreeEarth: 'Plastic Free Earth',
		EarthDay_SaveBiodiversity: 'Save Biodiversity',
		Purpose_Vastu: 'Vastu',
		Purpose_HomeGarden: 'Home Garden',
		Purpose_Environment: 'Environment',
		VanMahotsav_MassPlantation: 'Mass Plantation',
		VanMahotsav_IndividualContribution: 'Individual Contribution',
		Gift_Plantation: 'Gift Plantation',
		Gratitude_Message_Optional: 'Gratitude message (optional)',
		Message_Of_Gratitude: 'Message of gratitude',
		Select_Relation: 'Select Relation',
		Select_EarthDay_Theme: 'Select Earth Day Theme',
		Select_Purpose: 'Select Purpose',
		In_Loving_Memory: 'In loving memory',
		Edit_Profile: 'Edit Profile',
		Profile_Details: 'Profile Details',
		Profile_update_failed: 'Profile update failed',
		An_error_occurred: 'An error occurred',
		Update_Profile_Photo: 'Update Profile Photo',
		Choose_an_option: 'Choose an option',
		Camera: 'Camera',
		Gallery: 'Gallery',
		Cancel: 'Cancel',
		Email: 'Email',
		Enter_email: 'Enter email',
		Phone: 'Phone',
		Enter_phone: 'Enter phone',
		Support_Tree_Plantation: 'Support Tree Plantation',
		Fund_trees_for_Plantation: 'Fund trees for Plantation!',
		UPI_UPI_Apps: 'UPI / UPI Apps',
		UPI_Sub: 'PhonePe, Paytm, Google Pay, etc',
		Credit_Debit_Card: 'Credit / Debit Card',
		Card_Sub: 'Visa, Mastercard',
		Net_Banking: 'Net Banking',
		Bank_Sub: '100+ Banks',
		Pay: 'Pay',
		User_not_available: 'User not available',
		TonsCO2Year: 'tons CO2/year',
		Loading: 'Loading...',
		WaitText: 'Please wait',
		Too_many_requests: 'Too many requests from this IP, please try again after 15 minutes',
		Enter_valid_otp: 'Please enter a valid 6-digit OTP',
		Select_privacy_policy: 'Please select privacy policy',
		Verification_failed: 'Verification failed',
		Waiting_for_otp: 'Waiting for OTP…',
		Time: 'Time',
		Venue: 'Venue',
		ContributorDetails: "Contributor Details",
		ContributionImpact: "Your contribution directly helps in planting and nurturing {{trees}} trees, offsetting approximately {{carbon}} kg of CO₂ per year.",
		Contributor: "Contributor",
		ProjectType: "Project Type",
		Project: "Project",
		ProjectIn: "Project in {{state}}",
		PlantSpecies: "Plant Species",
		TotalQuantity: "Total Quantity",
		TotalAmount: "Total Amount",
		PayAmount: "Pay ₹{{amount}}",
		PaymentHistoryTitle: "Payment History",
		NoProjectsFoundForState: "No projects available for this state.",
		TreePlantingMilestones: "Tree Planting Milestones",
		CarbonImpactAchievements: "Carbon Impact Achievements",
		Account: "Account",
		Settings: "Settings",
		Preferences: "Preferences",
		Activity: "Activity",
		HelpCenter: "Help Center",
		PrivacyPolicy: "Privacy Policy",
		Terms: "Terms of Service",
		TreeActivitySharing: "Tree Activity Sharing",
		PushNotifications: "Push Notifications",
		MarkAllAsRead: "Mark all read",
		ShareProgressWithFriends: "Allow friends to see your progress",
		OlderNotifications: "OLDER NOTIFICATIONS",
		Milestone_Tree_1_Title: "Seed Starter",
		Milestone_Tree_1_Subtitle: "Plant your first tree 🌱",
		Milestone_Tree_2_Title: "Green Beginner",
		Milestone_Tree_2_Subtitle: "5 Trees planted",
		Milestone_Tree_3_Title: "Nature Supporter",
		Milestone_Tree_3_Subtitle: "10 Trees planted",
		Milestone_Tree_4_Title: "Eco Grower",
		Milestone_Tree_4_Subtitle: "20 Trees planted",
		Milestone_Tree_5_Title: "Forest Builder",
		Milestone_Tree_5_Subtitle: "50 Trees planted",
		Milestone_Tree_6_Title: "Green Champion",
		Milestone_Tree_6_Subtitle: "100 Trees planted",
		Milestone_Tree_7_Title: "Earth Protector",
		Milestone_Tree_7_Subtitle: "250 Trees planted",
		Milestone_Tree_8_Title: "Forest Creator",
		Milestone_Tree_8_Subtitle: "500 Trees planted",
		Milestone_Carbon_1_Title: "Carbon Beginner",
		Milestone_Carbon_1_Subtitle: "Offset 50 kg CO₂",
		Milestone_Carbon_2_Title: "Clean Air Contributor",
		Milestone_Carbon_2_Subtitle: "Offset 100 kg CO₂",
		Milestone_Carbon_3_Title: "Climate Helper",
		Milestone_Carbon_3_Subtitle: "Offset 250 kg CO₂",
		Milestone_Carbon_4_Title: "Eco Saver",
		Milestone_Carbon_4_Subtitle: "Offset 500 kg CO₂",
		Milestone_Carbon_5_Title: "Carbon Warrior",
		Milestone_Carbon_5_Subtitle: "Offset 1 Ton CO₂",
		Milestone_Carbon_6_Title: "Climate Guardian",
		Milestone_Carbon_6_Subtitle: "Offset 3 Tons CO₂",
		Milestone_Carbon_7_Title: "Planet Defender",
		Milestone_Carbon_7_Subtitle: "Offset 5 Tons CO₂",
		Delete_Species: "Delete Species",
		Delete_Species_Sure: 'Are you sure you want to delete this species?',
		Delete: "Delete",
		Logout: "Logout",
		logout_sure: 'Are you sure you want to logout?',
		Dates: "Date",
		OrderId: "Order Id",
		Amount: "Amount",
		Status: "Status",
		GoBack: "Change Number ",

		AppOpening_PlantTitle: 'PLANT.',
		AppOpening_TrackTitle: 'TRACK.',
		AppOpening_ImpactTitle: 'IMPACT',
		AppOpening_Subtitle1: 'Plant verified trees.',
		AppOpening_Subtitle2: 'Track growth.',
		AppOpening_Subtitle3: 'Leave a ',
		AppOpening_SubtitleLegacy: 'legacy',
		AppOpening_GetStarted: 'Get Started',
		AppOpening_AlreadyHaveAccount: 'Already have an account? ',
		AppOpening_SignIn: 'Sign In',
		AppOpening_VerifiedPlantations: 'VERIFIED\nPLANTATIONS',
		AppOpening_GPSTracked: 'GPS\nTRACKED',
		AppOpening_RealImpact: 'REAL\nIMPACT',
		AppOpening_TreesPlanted: 'TREES PLANTED',
		AppOpening_CO2Offset: 'CO₂ OFFSET',
		AppOpening_SurvivalRate: 'SURVIVAL RATE',
	},
	hi: {
		AppName: 'स्टोर पीडिया',
		Getstarted: 'शुरू करें',
		I_have_planted_a_Tree: 'मैंने एक पेड़ लगाया है',
		Login_Signup: 'लॉगिन/साइन अप',
		SignIn: 'साइन इन',
		SendOTP: 'ओटीपी भेजें',
		Continue: 'जारी रखें',
		WelcomeBack: 'वापसी पर स्वागत है',
		MobileNumber: 'मोबाइल नंबर',
		OtpVerify: 'ओटीपी सत्यापन',
		NumberPlaceholder: 'अपना नंबर दर्ज करें',
		PasswordLabel: 'पासवर्ड',
		PasswordPlaceholder: 'अपना पासवर्ड दर्ज करें',
		ForgotPassword: 'पासवर्ड भूल गए?',
		LoginButton: 'लॉग इन',
		NoAccount: 'खाता नहीं है?',
		IndividualType: 'व्यक्तिगत',
		GovernmentType: 'सरकारी',
		ForgotTitle: 'पासवर्ड रीसेट करें',
		NewPassword: 'नया पासवर्ड',
		NewPasswordPlaceholder: 'नया पासवर्ड दर्ज करें',
		ConfirmPassword: 'पासवर्ड की पुष्टि करें',
		ConfirmPasswordPlaceholder: 'नया पासवर्ड दोहराएं',
		ResetButton: 'पासवर्ड रीसेट करें',
		Carbon_WelcomeTitle: 'आपका कार्बन फुटप्रिंट कितना है?',
		Carbon_WelcomeSubtitle: 'देखें आपकी जीवनशैली पर्यावरण को कैसे प्रभावित करती है',
		Carbon_CalculateButton: 'मेरा फुटप्रिंट कैलकुलेट करें',
		Carbon_Household_Header: 'घर',
		Carbon_Household_PeopleLabel: 'आपके घर में कितने लोग रहते हैं?',
		Carbon_Household_PeoplePlaceholder: 'उदा. 3',
		Carbon_Household_PincodeLabel: 'आपका पिनकोड क्या है?',
		Carbon_Household_PincodePlaceholder: 'उदा. 380015',
		Carbon_Household_Next: 'ऊर्जा पर जाएं',
		Carbon_Energy_Header: 'ऊर्जा',
		Carbon_Energy_ElectricityPlaceholder: 'बिजली (₹ / माह)',
		Carbon_Energy_GasPlaceholder: 'प्राकृतिक गैस (₹ / माह)',
		Carbon_Energy_FuelOilPlaceholder: 'फ्यूल ऑयल (₹ / माह)',
		Carbon_Energy_PropanePlaceholder: 'प्रोपेन (₹ / माह)',
		Carbon_Energy_Next: 'परिवहन पर जाएं',
		Carbon_Transport_Header: 'परिवहन',
		Carbon_Transport_VehiclesLabel: 'आपके घर में कितने वाहन हैं?',
		Carbon_Transport_VehiclesPlaceholder: 'वाहनों की संख्या',
		Carbon_Transport_DistanceLabel: 'आप साल में कितने किमी ड्राइव करते हैं?',
		Carbon_Transport_DistancePlaceholder: 'सालाना दूरी (किमी)',
		Carbon_Transport_MileageLabel: 'आपके वाहन की औसत माइलेज क्या है?',
		Carbon_Transport_MileagePlaceholder: 'औसत माइलेज (किमी/ली)',
		Carbon_Transport_Next: 'कचरे पर जाएं',
		Carbon_Waste_Header: 'कचरा',
		Carbon_Waste_Plastic: '☑ प्लास्टिक',
		Carbon_Waste_Glass: '☑ कांच',
		Carbon_Waste_Paper: '☑ कागज',
		Carbon_Waste_Metal: '☑ धातु',
		Carbon_Waste_Next: 'परिणाम देखें',
		Carbon_Result_Title: 'मेरा कार्बन फुटप्रिंट',
		Carbon_Result_Subtitle: 'वार्षिक अनुमानित CO₂ उत्सर्जन',
		Carbon_Result_EmailPlaceholder: 'रिपोर्ट पाने के लिए ईमेल दर्ज करें',
		Carbon_Result_Button: 'रिपोर्ट प्राप्त करें',
		Carbon_Back: 'वापस',
		Small: 'आज छोटे कदम',
		greener: '🌱 कल हरियाली',
		NoRecord: "कोई रिकॉर्ड नहीं मिला",

		Climate_change: 'जलवायु परिवर्तन',
		startswithus: 'हमसे शुरू होता है',
		Our_daily_choices: 'हमारी रोज़ की पसंदें अक्सर बिना जाने कार्बन उत्सर्जन बढ़ाती हैं।',
		Understand_your_impact: 'अपने प्रभाव को समझें',
		Measure_your_footprint: 'अपना कार्बन फुटप्रिंट मापें और कम करने के आसान तरीके जानें।',
		Offset_you: 'जो टाल नहीं सकते',
		avoid: 'उसे ऑफ़सेट करें',
		Support_verified: 'सत्यापित जलवायु परियोजनाओं का समर्थन करें और बदलाव लाएं।',
		Plant_a_tree: 'एक पेड़ लगाएं और हमारी मदद करें ',
		Cure_our_planet: 'धरती को ठीक करने में',
		Enterdigit: 'आपको भेजा गया 6-अंकों का कोड दर्ज करें',
		NotRecevice: 'ओटीपी नहीं मिला? ',
		Resend_Now: 'फिर से भेजें',
		agree_with: 'जारी रखते हुए, आप सहमत हैं',
		Privacy_Policy: 'गोपनीयता नीति से',
		Hey_User: 'नमस्ते ',
		Celebrate: 'अपने अवसर का जश्न मनाएं',
		Mother_Earth: 'हमारी धरती माता को बचाने में मदद करें',
		Explore_plantations: 'भारत भर में वृक्षारोपण खोजें, विरासत भूमि से हरे खेतों तक',
		IPLDotBall: 'आईपीएल डॉट बॉल',
		Every_dot_ball_counts: 'हर डॉट बॉल मायने रखती है—क्रिकेट के पलों को पेड़ों में बदलें।',
		Dot_Ball: '1 डॉट बॉल = 1 पेड़',
		States_of_India: 'भारत के राज्य',
		Discover_GeoTree: 'GeoTree कैसे प्रकृति और संस्कृति को जोड़ता है, जानें।',
		Add_your_tate: 'अपने राज्य को जोड़ें',
		Join_Plant: 'हमसे जुड़ें, अपने राज्य को सूची में जोड़ने के लिए पेड़ लगाएं।',
		Start_your: 'जानिए अपना',
		footprint_journey: 'कार्बन फुटप्रिंट',
		See_how_add_up: 'देखें आपकी रोज़मर्रा की आदतें कैसे जुड़ती हैं',
		Calculate: 'कार्बन फुटप्रिंट कैलकुलेट करें',
		Next: 'आगे',
		footprint_track: 'आइए आपके कार्बन को ट्रैक करें!',
		Which_type: 'घर का प्रकार चुनें',
		vehicle_type: 'आपका वाहन प्रकार क्या है?',
		electricity_used: 'आप कितनी बिजली उपयोग करते हैं?',
		describes_your_diet: 'आपका आहार कैसा है?',
		TreesPlantedImpact: 'लगाए गए पेड़',
		CO2OffsetImpact: 'CO2 ऑफसेट',
		StartPlanting: 'वृक्षारोपण शुरू करें',
		ChooseNextTree: 'लगाने के लिए अपना अगला पेड़ चुनें और उसके बढ़ने पर नज़र रखें।',
		HelloUserImpact: 'नमस्ते ',
		GrowGreenerPlanet: 'आइए आज एक हरा-भरा ग्रह बनाएं',
		TotalCO2OffsetImpact: 'कुल CO2 ऑफ़सेट',
		KgUnitOut: ' किग्रा',
		OffsetProgressYears: 'ऑफ़सेट प्रगति (वर्ष)',
		FindProjectsBtn: 'परियोजनाएं खोजें',
		GlobalRanking: 'वैश्विक रैंकिंग',
		ContributorsLabel: 'योगदानकर्ता',
		LocationsLabel: 'स्थान',
		TreesUnit: ' पेड़',
		TonsCO2Unit: ' टन CO₂',
		UsersUnit: ' उपयोगकर्ता',
		AreasUnit: ' क्षेत्र',
		Top5PercentPlanters: 'शीर्ष 5% प्लांटर्स',
		RankedGlobally1402: 'विश्व स्तर पर #1,402 रैंक',
		MilestonesLabel: 'मील के पत्थर',
		ViewAllBtn: 'सभी देखें',
		CO2Saved100kg: '100kg CO2 बचाया',
		TreesPlanted10: '10 पेड़ लगाए गए',
		WaterGuardian: 'जल रक्षक',
		CommunityProjectsLabel: 'सामुदायिक परियोजनाएं',
		AmazonReforestation: 'अमेज़ॅन पुनर्वनीकरण',
		GoalReached85Percent: 'लक्ष्य का 85% पूरा हुआ',
		ScandinavianTaiga: 'स्कैंडिनेवियाई टैगा',
		GoalReached42Percent: 'लक्ष्य का 42% पूरा हुआ',
		TreeSpeciesBreakdownLabel: 'पेड़ों की प्रजातियों का विवरण',
		OakTrees: 'ओक के पेड़',
		Mangroves: 'मैंग्रोव',
		PineTrees: 'पाइन के पेड़',
		Result: 'परिणाम',
		carbon_footprint: 'आपका कार्बन खाता',
		Based_on_your_answers: 'आपके जवाबों के आधार पर',
		AnnualCO2Emissions: 'वार्षिक CO₂ उत्सर्जन',
		Offsetmyfootprint: 'मेरा फुटप्रिंट ऑफ़सेट करें',
		See_reduce: 'कम कैसे करें देखें',
		meaningful: 'अपने खास पलों को अर्थपूर्ण बनाएं',
		SelectOccasion_Type: 'कार्यक्रम प्रकार चुनें',
		PLANTATIONDETAILS: 'रोपण विवरण',
		Choose_Number_Trees: 'पेड़ों की संख्या चुनें *',
		Distribute_Plants: 'प्रजाति के अनुसार पौधे बांटें',
		Add_Species: '+ प्रजाति जोड़ें',
		Plantname: 'पौधे का नाम',
		Quantity: 'मात्रा',
		Remove: 'हटाएं',
		Name: 'नाम *',
		Date: 'तारीख *',
		Message_optional: 'संदेश',
		BIRTHDAY_Message_optional: 'जन्मदिन संदेश',
		height: 'ऊंचाई (सेमी) *',
		Price: 'कीमत (₹) *',
		Choose_Location: 'राज्य चुनें',
		Choose_Location_for_your_plant: 'रोपण के लिए परियोजना चुनें',
		Choose_location: 'स्थान चुनें',
		SUBMIT: 'सबमिट',
		Trees_PlantedSuccessfully: 'पेड़ सफलतापूर्वक लगाए गए!',
		Certificate_of_TreePlantation: 'वृक्षारोपण प्रमाणपत्र',
		This_certifies_that: 'यह प्रमाणित करता है कि',
		welcomeSmall: 'स्वागत है',
		headline: ' डॉट बॉल वृक्षारोपण',
		helpText: 'डॉट बॉल के जरिए हरियाली बढ़ाने में मदद करें',
		perTeam: 'प्रति टीम',
		perMatch: 'प्रति मैच',
		wholeTournament: 'पूरा टूर्नामेंट',
		IPL_Dot_Ball_Tree_Plantation: ' डॉट बॉल वृक्षारोपण',
		Team: 'टीम',
		Match: 'मैच',
		perTeamSmall: 'हर डॉट बॉल एक पेड़ लगाती है',
		Select_Team: 'टीम चुनें',
		PerTeamSelected: 'प्रति टीम चुना गया',
		PerMatchSelected: 'प्रति मैच चुना गया',
		Select_treesfor: 'पेड़ चुनें ',
		Match_H: 'मैच',
		trees: 'पेड़',
		dots: 'डॉट बॉल',
		WholeTournamentSelected: 'पूरा टूर्नामेंट चुना गया',
		Select_Team_1: 'टीम 1 चुनें',
		Select_Team_2: 'टीम 2 चुनें',
		Select_Team_3: 'टीम 3 चुनें',
		tree_planted_on: '1 डॉट बॉल = 1 पेड़ लगाया गया',
		dot_balls: 'डॉट बॉल',
		Donate: 'दान :',
		Estimate: 'अनुमानित डॉट बॉल : ',
		Update: 'अपडेट',
		Submit: 'सबमिट',
		TrackingDashboard: 'ट्रैकिंग डैशबोर्ड',
		TrackingOverview: 'रोपण अवलोकन',
		TrackingLiveLocation: 'लाइव लोकेशन',
		TrackingGrowthTimeline: 'विकास समयरेखा',
		TrackingImpactSummary: 'प्रभाव सारांश',
		TrackingViewFullMap: 'पूरा नक्शा देखें',
		TrackingDatePlanted: 'रोपण तिथि',
		TrackingEstimatedCO2: 'अनुमानित CO₂ अवशोषण',
		TrackingOxygenGenerated: 'ऑक्सीजन उत्पादन',
		TrackingDistanceLabel: 'आपसे दूरी',
		TrackingLongitudeLabel: 'देशांतर',
		TrackingLatitudeLabel: 'अक्षांश',
		TrackingOrderPlantationId: 'ऑर्डर ID / रोपण ID',
		TrackingOrderPlantationValue: 'PTN-876552110',
		TrackingInitiativeTitle: 'ग्रीन फ्यूचर पहल',
		TrackingTreesPlanted: 'पेड़ लगाए',
		TrackingPlanted: 'लगाए गए',
		TrackingGrowing: 'बढ़ रहे',
		TrackingTimelineSapling: 'पौधा',
		TrackingTimelineYoungTree: 'युवा पेड़',
		TrackingTimelineMatureTree: 'परिपक्व पेड़',
		TrackingTimelineHealthy: 'स्वस्थ',
		TrackingTimelineInProgress: 'प्रगति पर',
		TrackingTimelineScheduled: 'निर्धारित',
		TrackingTimelineDate1: '15 अगस्त 2025',
		TrackingTimelineDate2: '14 नवंबर 2025',
		TrackingTimelineDate3: '15 फरवरी 2026',
		TrackingDatePlantedValue: '15 अगस्त 2025',
		TrackingEstimatedCO2Value: ' टन',
		TrackingEstimatedCO2Note: ' टन कम किया',

		TrackingOxygenGeneratedValue: ' किग्रा',
		TrackingOxygenGeneratedNote: ' किग्रा ताज़ा ऑक्सीजन ',
		LanguageSelectTitle: 'भाषा चुनें',
		LanguageSelectSubtitle: 'अपनी पसंदीदा भाषा चुनें',
		LanguageEnglish: 'English',
		LanguageHindi: 'हिंदी',
		ChangeLanguage: 'भाषा बदलें',
		ProfileTitle: 'प्रोफ़ाइल',
		LogOut: 'लॉग आउट',
		PaymentHistory: 'भुगतान इतिहास',
		Certificates: 'प्रमाणपत्र',
		Notifications: 'सूचनाएं',
		FaqSupport: 'FAQs और सहायता',
		SearchHelp: 'सहायता के लिए खोजें',
		LiveChat: 'लाइव चैट',
		EmailUs: 'ईमेल',
		CallUs: 'हमें कॉल करें',
		FAQsTitle: 'अक्सर पूछे जाने वाले प्रश्न',
		StillNeedHelp: 'अभी भी मदद चाहिए?',
		SupportTeamAvailable: 'हमारी सहायता टीम आपकी किसी भी प्रश्न में सहायता के लिए 24/7 उपलब्ध है।',
		ContactSupport: 'सहायता से संपर्क करें',
		History: 'इतिहास',
		PlantationHistory: 'रोपण इतिहास',
		Language: 'भाषा',
		ImpactSummaryCards: 'प्रभाव सारांश कार्ड',
		TotalTreesPlanted: 'कुल लगाए गए पेड़',
		TotalCO2Emissions: 'कुल CO₂ उत्सर्जन',
		TreeCountLabel: 'पेड़ों की संख्या',
		PlantationHistoryTitle: 'रोपण इतिहास',
		TonUnit: 'टन',
		PlantTreesTitle: 'पेड़ लगाएं',
		PlantTreesSubtitle: 'खास अवसरों के लिए',
		PlantTreesDescription: 'जन्मदिन, वर्षगांठ,\nऔर यादों को पेड़ों के साथ मनाएं।',
		Start: 'शुरू करें',
		CategoryHome: 'घर',
		CategoryTransport: 'परिवहन',
		CategoryFood: 'भोजन',
		YourCarbonAccount: 'आपका कार्बन खाता',
		Energy: 'ऊर्जा',
		Waste: 'कचरा',
		Breakdown: 'विभाजन',
		OffsetRecommendation: 'ऑफसेट सुझाव',
		CarbonKgPerYear: 'किग्रा CO₂/वर्ष',
		CarbonTonsPerYear: 'टन CO₂/वर्ष',
		SelectState: 'राज्य चुनें',
		ExploreMore: 'और देखें',
		EnterNamePlaceholder: 'नाम दर्ज करें',
		ChooseStatePlaceholder: 'राज्य चुनें',
		ChooseProjectPlaceholder: 'परियोजना चुनें',
		SelectPlantPlaceholder: 'पौधा चुनें',
		SelectQuantityPlaceholder: 'मात्रा चुनें',
		HeightPlaceholder: 'ऊंचाई',
		PricePlaceholder: 'कीमत',
		MessagePlaceholder: 'संदेश लिखें',
		CarbonFootprint: 'कार्बन फुटप्रिंट',
		DotBallLabel: 'डॉट बॉल',
		CarbonOffsetLabel: 'कार्बन ऑफ़सेट',
		DateLabel: 'तारीख',
		TeamLabel: 'टीम',
		CarbonResultLabel: 'कार्बन परिणाम',
		TypeLabel: 'प्रकार',
		TotalCO2Label: 'कुल CO₂',
		TreesSupportedLabel: 'समर्थित पेड़',
		TreesLabel: 'पेड़',
		AmountLabel: 'राशि',
		LocationLabel: 'स्थान',
		NotAvailable: 'उपलब्ध नहीं',
		HistoryInstruction: 'अपने वृक्षारोपण का प्रकार चुनें।',
		TonUnitLabel: 'टन',
		TurnedDotBallsIntoTrees: 'डॉट बॉल को पेड़ों में बदला',
		JoinCricketGreener: 'क्रिकेट को और हरित बनाने में जुड़ें',
		DownloadCertificate: 'प्रमाणपत्र डाउनलोड करें',
		ShareOnWhatsApp: 'व्हाट्सऐप पर साझा करें',
		ShareOnInstagram: 'इंस्टाग्राम पर साझा करें',
		TeamChallengeTitle: 'टीम चैलेंज',
		TeamChallengeSubtitle: 'पेड़ों के लिए अपनी टीम का समर्थन करें',
		FansLabel: 'फैंस',
		CustomizeTrees: 'पेड़ कस्टमाइज़ करें:',
		CustomizeDotBalls: 'डॉट बॉल्स कस्टमाइज़ करें:',
		PricePerTree: '₹10 प्रति पेड़',
		Confirm: 'कन्फर्म',
		ErrorTitle: 'त्रुटि',
		ErrorEnterValidDotBalls: 'कृपया डॉट बॉल की सही संख्या दर्ज करें',
		ErrorEnterValidTrees: 'कृपया पेड़ों की सही संख्या दर्ज करें',
		ErrorLargerThanAvailableDotBalls: 'उपलब्ध डॉट बॉल से अधिक है',
		Milestone_Tree_1_Title: "सीड स्टार्टर",
		Milestone_Tree_1_Subtitle: "अपना पहला पेड़ लगाएं 🌱",
		Milestone_Tree_2_Title: "ग्रीन बिगिनर",
		Milestone_Tree_2_Subtitle: "5 पेड़ लगाए गए",
		Milestone_Tree_3_Title: "प्रकृति समर्थक",
		Milestone_Tree_3_Subtitle: "10 पेड़ लगाए गए",
		Milestone_Tree_4_Title: "इको ग्रोअर",
		Milestone_Tree_4_Subtitle: "20 पेड़ लगाए गए",
		Milestone_Tree_5_Title: "वन निर्माता",
		Milestone_Tree_5_Subtitle: "50 पेड़ लगाए गए",
		Milestone_Tree_6_Title: "ग्रीन चैंपियन",
		Milestone_Tree_6_Subtitle: "100 पेड़ लगाए गए",
		Milestone_Tree_7_Title: "धरती रक्षक",
		Milestone_Tree_7_Subtitle: "250 पेड़ लगाए गए",
		Milestone_Tree_8_Title: "वन सर्जक",
		Milestone_Tree_8_Subtitle: "500 पेड़ लगाए गए",
		Milestone_Carbon_1_Title: "कार्बन शुरुआती",
		Milestone_Carbon_1_Subtitle: "50 किग्रा CO₂ ऑफ़सेट करें",
		Milestone_Carbon_2_Title: "स्वच्छ हवा योगदानकर्ता",
		Milestone_Carbon_2_Subtitle: "100 किग्रा CO₂ ऑफ़सेट करें",
		Milestone_Carbon_3_Title: "जलवायु सहायक",
		Milestone_Carbon_3_Subtitle: "250 किग्रा CO₂ ऑफ़सेट करें",
		Milestone_Carbon_4_Title: "इको सेवर",
		Milestone_Carbon_4_Subtitle: "500 किग्रा CO₂ ऑफ़सेट करें",
		Milestone_Carbon_5_Title: "कार्बन योद्धा",
		Milestone_Carbon_5_Subtitle: "1 टन CO₂ ऑफ़सेट करें",
		Milestone_Carbon_6_Title: "जलवायु संरक्षक",
		Milestone_Carbon_6_Subtitle: "3 टन CO₂ ऑफ़सेट करें",
		Milestone_Carbon_7_Title: "ग्रह रक्षक",
		Milestone_Carbon_7_Subtitle: "5 टन CO₂ ऑफ़सेट करें",
		ErrorLargerThanAvailableTeamDotBalls: 'उपलब्ध टीम डॉट बॉल्स से अधिक है',
		ErrorLargerThanSelectedTeamBalls: 'चुनी गई टीम की बॉल्स से अधिक है',
		ErrorLargerThanAvailableMatchDots: 'उपलब्ध मैच डॉट्स से अधिक है',
		ErrorTeamIdMissing: 'टीम ID नहीं मिली',
		ErrorSelectTeam: 'कृपया एक टीम चुनें।',
		SupportSubmittedSuccess: 'सपोर्ट सफलतापूर्वक सबमिट हो गया',
		ErrorSomethingWentWrong: 'कुछ गलत हो गया',
		ErrorUnableToReachServer: 'सर्वर से संपर्क नहीं हो पाया',
		DotBallsEqualsTreesPlanted: 'डॉट बॉल = लगाए गए पेड़',
		TreesFundedLabel: 'पेड़ फंड किए:',
		SupportWithTrees: 'पेड़ों से सपोर्ट करें',
		TabToday: 'आज',
		TabPrevious: 'पिछला',
		TabUpcoming: 'आगामी',
		TableHeaderDate: 'तारीख',
		TableHeaderMatches: 'मैच',
		TableHeaderPrePlantation: 'प्री-प्लांटेशन',
		TableHeaderDotBalls: 'डॉट बॉल',
		SelectTeamToSupport: 'सपोर्ट के लिए टीम चुनें:',
		MatchLabel: 'मैच विवरण',

		Team1Label: 'टीम 1',
		Team2Label: 'टीम 2',
		PlantNameLabel: 'पौधे का नाम',
		ScientificNameLabel: 'वैज्ञानिक नाम',
		CO2AbsorptionLabel: 'CO₂ अवशोषण',
		MaturityLabel: 'परिपक्वता',
		TreeHeightLabel: 'पेड़ की ऊंचाई',
		RateLabel: 'दर',
		Close: 'बंद करें',
		ErrorSelectHouseType: 'कृपया घर का प्रकार चुनें',
		ErrorSelectTransportType: 'कृपया परिवहन प्रकार चुनें',
		ErrorSelectFoodType: 'कृपया भोजन प्रकार चुनें',
		ThankYouTitle: 'आपके हरित योगदान के लिए धन्यवाद! 🌱',
		ThankYouMessage: 'आपका पेड़ सफलतापूर्वक लगाया गया है।',
		ThankYouPlanting: 'मिलकर, हम प्रकृति को पुनर्स्थापित कर रहे हैं और जलवायु परिवर्तन से लड़ रहे हैं—एक पेड़ करके।',
		GoToHome: 'होम पर जाएं',
		Skip: 'छोड़ें',
		HOUSE_TYPE: "कृपया घर का प्रकार चुनें",
		TRANSPORT_TYPE: "कृपया परिवहन का प्रकार चुनें",
		DIET_TYPE: "कृपया आहार का प्रकार चुनें",
		NO_DATA_FOUND: "कोई जानकारी उपलब्ध नहीं है",
		RELATION_WITH_PERSON: "व्यक्ति के साथ संबंध चुनें",
		AGE: "उम्र",
		AGE_Placeholder: "उम्र दर्ज करें",
		DEATH_ANNIVERSY_YEAR: "मृत्यु वार्षिकी वर्ष",
		DEATH_ANNIVERSY_YEAR_PLACEHOLDER: "मृत्यु वार्षिकी वर्ष दर्ज करें",
		EART_DAY_THEAM: "अर्थ दिवस थीम",
		EVENT_DATE: "कार्यक्रम की तारीख",
		PLANTATION_PURPOSE: "रोपण का उद्देश्य",
		HOUSE_OWNER_NAME: "घर के मालिक ",
		City_Area: "शहर / क्षेत्र",
		City_Area_Placeholder: "शहर या क्षेत्र दर्ज करें",
		HOUSE_WARMING_DATE: "हाउस वार्मिंग की तारीख",
		RETIRED_PERSON_NAME: "सेवानिवृत्त व्यक्ति का नाम",
		RETIRED_PERSON_NAME_PLACEHOLDER: "सेवानिवृत्त व्यक्ति का नाम दर्ज करें",
		Organization_Department: "संगठन / विभाग",
		Organization_Department_Placeholder: "संगठन या विभाग दर्ज करें",
		Years_of_Service: "सेवा के वर्ष",
		Years_of_Service_Placeholder: "सेवा के वर्ष दर्ज करें",
		A_new_beginning_with_nature: "प्रकृति के साथ एक नया आरंभ",
		Share_Instagram: "इंस्टाग्राम पर साझा करें",
		Share_WhatsApp: "व्हाट्सऐप पर साझा करें",
		Download_Certificate: "प्रमाणपत्र डाउनलोड करें",
		Scan_verify: "पौधारोपण रिकॉर्ड सत्यापित करने के लिए स्कैन करें",
		Certificate_Text: "पेड़ लगाकर मनाया है",
		Location_Label: "स्थान:",
		Tree_Type_Label: "वृक्ष का प्रकार: स्थानीय, जलवायु के अनुकूल प्रजातियाँ",
		CO2_Label: "CO₂ अवशोषण:",
		Date_Label: "तिथि:",
		supportTitle: "डॉट-बॉल वृक्षारोपण का समर्थन करें",
		supportSubtitle: "फेंकी गई डॉट बॉल्स के लिए पेड़ों का सहयोग करें!",
		paymentMethodTitle: "भुगतान विधि चुनें",
		Occasion_Title: 'अवसर का शीर्षक',
		Occasion_Title_Placeholder: 'अवसर का शीर्षक दर्ज करें',
		Occasion_Description: 'अवसर विवरण',
		Occasion_Description_Placeholder: 'अवसर विवरण दर्ज करें',
		Occasion_Date: 'अवसर की तारीख',
		Honoured_Person_Name: 'सम्मानित व्यक्ति का नाम',
		Honoured_Person_Name_Placeholder: 'सम्मानित व्यक्ति का नाम दर्ज करें',
		Teacher_Name: 'शिक्षक का नाम',
		Teacher_Name_Placeholder: 'शिक्षक का नाम दर्ज करें',
		School_College_Name: 'स्कूल / कॉलेज का नाम',
		School_College_Name_Placeholder: 'स्कूल या कॉलेज का नाम दर्ज करें',
		Subject_Role: 'विषय / भूमिका',
		Subject_Role_Placeholder: 'विषय या भूमिका दर्ज करें',
		Teacher_Day_Date: 'शिक्षक दिवस की तारीख',
		Plantation_Drive_Type: 'पौधारोपण अभियान का प्रकार',
		Plantation_Drive_Type_Placeholder: 'पौधारोपण अभियान का प्रकार चुनें',
		Number_of_Participants: 'प्रतिभागियों की संख्या',
		Number_of_Participants_Placeholder: 'प्रतिभागियों की संख्या दर्ज करें',
		School_NGO_Organization_Name: 'स्कूल / NGO / संगठन का नाम',
		School_NGO_Organization_Name_Placeholder: 'स्कूल, NGO या संगठन का नाम दर्ज करें',
		Couple_Name: 'जोड़े का नाम *',
		Couple_name_placeholder: 'जोड़े का नाम दर्ज करें',
		Anniversary_Year: 'वर्षगांठ वर्ष',
		Anniversary_Year_Placeholder: 'वर्षगांठ वर्ष दर्ज करें',
		Relationship_Message: 'संबंध संदेश',
		Relationship_Message_Placeholder: 'संबंध संदेश दर्ज करें',
		Death_Anniversary_message: 'मृत्यु वार्षिकी संदेश',
		Death_Anniversary_message_Placeholder: 'मृत्यु वार्षिकी संदेश दर्ज करें',
		Invalid_Mobile_Number: 'मोबाइल नंबर केवल 10 अंकों का होना चाहिए।',
		Please_enter_phone_number: 'कृपया अपना फ़ोन नंबर दर्ज करें',
		Please_enter_name: 'कृपया नाम दर्ज करें।',
		Please_select_project: 'कृपया एक परियोजना चुनें।',
		Please_add_at_least_one_species: 'कृपया कम से कम एक प्रजाति जोड़ें।',
		Please_complete_species_details: 'कृपया सभी प्रजाति विवरण पूरे करें (पौधा, ऊँचाई, मात्रा, दर)।',
		Unable_to_submit: 'जमा करने में असमर्थ।',
		Unable_to_submit_try_again: 'जमा करने में असमर्थ। कृपया पुनः प्रयास करें।',
		completed: 'सफलतापूर्वक',
		occasionText: "{{name}} के अवसर पर",
		Relation_Self: 'स्वयं',
		Relation_Father: 'पिता',
		Relation_Mother: 'माता',
		Relation_Friend: 'मित्र',
		Relation_Other: 'अन्य',
		EarthDay_ClimateAction: 'जलवायु कार्रवाई',
		EarthDay_PlasticFreeEarth: 'प्लास्टिक मुक्त पृथ्वी',
		EarthDay_SaveBiodiversity: 'जैव विविधता बचाएं',
		Purpose_Vastu: 'वास्तु',
		Purpose_HomeGarden: 'घरेलू बगीचा',
		Purpose_Environment: 'पर्यावरण',
		VanMahotsav_MassPlantation: 'सामूहिक वृक्षारोपण',
		VanMahotsav_IndividualContribution: 'व्यक्तिगत योगदान',
		Gift_Plantation: 'उपहार स्वरूप वृक्षारोपण',
		Gratitude_Message_Optional: 'आभार संदेश (वैकल्पिक)',
		Message_Of_Gratitude: 'आभार संदेश',
		Select_Relation: 'संबंध चुनें',
		Select_EarthDay_Theme: 'अर्थ डे थीम चुनें',
		Select_Purpose: 'उद्देश्य चुनें',
		In_Loving_Memory: 'प्यारी स्मृति में',
		Edit_Profile: 'प्रोफ़ाइल संपादित करें',
		Profile_Details: 'प्रोफ़ाइल विवरण',
		Profile_update_failed: 'प्रोफ़ाइल अपडेट विफल',
		An_error_occurred: 'एक त्रुटि हुई',
		Update_Profile_Photo: 'प्रोफ़ाइल फोटो अपडेट करें',
		Choose_an_option: 'एक विकल्प चुनें',
		Camera: 'कैमरा',
		Gallery: 'गैलरी',
		Cancel: 'रद्द करें',
		Email: 'ईमेल',
		Enter_email: 'ईमेल दर्ज करें',
		Phone: 'फोन',
		Enter_phone: 'फोन दर्ज करें',
		Support_Tree_Plantation: 'वृक्षारोपण का समर्थन करें',
		Fund_trees_for_Plantation: 'वृक्षारोपण के लिए पेड़ों का सहयोग करें!',
		UPI_UPI_Apps: 'यूपीआई / यूपीआई ऐप्स',
		UPI_Sub: 'फोनपे, पेटीएम, गूगल पे, इत्यादि',
		Credit_Debit_Card: 'क्रेडिट / डेबिट कार्ड',
		Card_Sub: 'वीजा, मास्टरकार्ड',
		Net_Banking: 'नेट बैंकिंग',
		Bank_Sub: '100+ बैंक',
		Pay: 'भुगतान करें',
		User_not_available: 'उपयोगकर्ता उपलब्ध नहीं है',
		TonsCO2Year: 'टन CO2/वर्ष',
		Loading: 'लोड हो रहा है...',
		WaitText: 'कृपया प्रतीक्षा करें',
		Too_many_requests: 'इस आईपी से बहुत अधिक अनुरोध, कृपया 15 मिनट के बाद पुनः प्रयास करें',
		Enter_valid_otp: 'कृपया एक वैध 6-अंकीय ओटीपी दर्ज करें',
		Select_privacy_policy: 'कृपया गोपनीयता नीति चुनें',
		Verification_failed: 'सत्यापन विफल रहा',
		Waiting_for_otp: 'ओटीपी की प्रतीक्षा की जा रही है...',
		Time: 'समय',
		Venue: 'स्थान',
		ContributorDetails: "योगदानकर्ता विवरण",
		ContributionImpact: "आपका योगदान सीधे {{trees}} पेड़ लगाने और उनका पोषण करने में मदद करता है, जिससे हर वर्ष लगभग {{carbon}} किलोग्राम CO₂ का संतुलन होता है।",
		Contributor: "योगदानकर्ता",
		ProjectType: "परियोजना प्रकार",
		Project: "परियोजना",
		ProjectIn: "{{state}} में परियोजना",
		PlantSpecies: "पौधों की प्रजाति",
		TotalQuantity: "कुल मात्रा",
		TotalAmount: "कुल राशि",
		PayAmount: "₹{{amount}} का भुगतान करें",
		PaymentHistoryTitle: "भुगतान इतिहास",
		NoProjectsFoundForState: "इस राज्य के लिए कोई परियोजना उपलब्ध नहीं है।",
		TreePlantingMilestones: "वृक्षारोपण माइलस्टोन",
		CarbonImpactAchievements: "कार्बन प्रभाव उपलब्धियाँ",
		Account: "खाता",
		Settings: "सेटिंग्स",
		Preferences: "प्राथमिकताएँ",
		Activity: "गतिविधि",
		Support: "सहायता",
		HelpCenter: "सहायता केंद्र",
		PrivacyPolicy: "गोपनीयता नीति",
		Terms: "सेवा की शर्तें",
		TreeActivitySharing: "पेड़ गतिविधि साझा करना",
		PushNotifications: "तुरंत सूचनाएं",
		MarkAllAsRead: "सभी को पढ़ा हुआ मानें",
		ShareProgressWithFriends: "दोस्तों को आपकी प्रगति देखने की अनुमति दें",
		OlderNotifications: "पुराने नोटिफिकेशन",
		Delete_Species: "प्रजाति हटाएं",
		Delete_Species_Sure: "क्या आप वाकई इस प्रजाति को हटाना चाहते हैं?",
		Delete: "हटाएं",
		Logout: "लॉग आउट",
		logout_sure: "क्या आप वाकई लॉग आउट करना चाहते हैं?",
		Dates: "तारीख",
		OrderId: "ऑर्डर आईडी",
		Amount: "राशि",
		Status: "स्थिति",
		GoBack: "नंबर बदलें",
		AppOpening_PlantTitle: 'पौधा लगाएं.',
		AppOpening_TrackTitle: 'ट्रैक करें.',
		AppOpening_ImpactTitle: 'प्रभाव.',
		AppOpening_Subtitle1: 'सत्यापित पेड़ लगाएं.',
		AppOpening_Subtitle2: 'विकास को ट्रैक करें.',
		AppOpening_Subtitle3: 'एक विरासत ',
		AppOpening_SubtitleLegacy: 'छोड़ें',
		AppOpening_GetStarted: 'शुरू करें',
		AppOpening_AlreadyHaveAccount: 'पहले से ही एक खाता है? ',
		AppOpening_SignIn: 'साइन इन करें',
		AppOpening_VerifiedPlantations: 'सत्यापित\nवृक्षारोपण',
		AppOpening_GPSTracked: 'जीपीएस\nट्रैक्ड',
		AppOpening_RealImpact: 'वास्तविक\nप्रभाव',
		AppOpening_TreesPlanted: 'लगाए गए पेड़',
		AppOpening_CO2Offset: 'CO₂ ऑफ़सेट',
		AppOpening_SurvivalRate: 'जीवित रहने की दर',
	},
};

const String = new Proxy(
	{} as Record<string, string>,
	{
		get: (_, prop: string) => {
			const lang = getLanguage();
			return translations[lang]?.[prop] ?? translations.en[prop] ?? prop;
		},
	}
);

export default String;
