import { Dimensions, StyleSheet } from 'react-native';
import fonts from '../../../comman/fonts';
import FontsSize from '../../../comman/FontsSize';
import { Colors } from '../../../comman/Colors';

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    container: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingTop: 16,
        paddingBottom: 24,
    },
    backBtn: {
        width: 40,
        height: 40,
        borderRadius: 40 / 2,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    backIcon: {
        width: 15,
        height: 15,
        tintColor: '#111827',
    },
    headerTitleContainer: {
        flex: 1,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: FontsSize.size14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    titleLeafIcon: {
        width: 16,
        height: 16,
        marginLeft: 8,
    },
    headerSubtitle: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        marginTop: 4,
    },
    badgeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    badgeIcon: {
        width: 16,
        height: 16,
        marginRight: 6,
        tintColor: '#0A5F35',
    },
    badgeText: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    topBanner: {
        backgroundColor: '#F9FDF5',
        marginHorizontal: 16,
        borderRadius: 6,
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 5,
        paddingHorizontal: 16,
        marginBottom: 10,
    },
    topBannerImgContainer: {
        marginRight: 16,
    },
    topBannerImg: {
        width: 60,
        height: 60,
    },
    topBannerTextContainer: {
        flex: 1,
    },
    topBannerText: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
    },
    sectionContainer: {
        marginVertical: 10,
    },
    sectionContainerGray: {
        backgroundColor: '#f6f7f2',
        paddingVertical: 15,
        paddingHorizontal: 10,
        marginHorizontal: 16,
        borderRadius: 10,
        marginBottom: 6,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginBottom: 10,
    },
    sectionTitle: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    sectionLeafIcon: {
        width: 16,
        height: 16,
        marginLeft: 8,
    },
    stepsScrollContent: {
        paddingHorizontal: 10,
        paddingVertical: 10,
        marginHorizontal: 16,
        marginVertical: 8,
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
    },
    stepItemContainer: {
        alignItems: 'center',
        width: Dimensions.get('window').width / 5 - 10,
        position: 'relative',
        marginTop: 8
    },
    stepIconCircle: {
        width: 40,
        height: 40,
        borderRadius: 40 / 2,
        backgroundColor: '#f4f6f0',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: -12,
        zIndex: 1,
    },
    stepIcon: {
        width: 15,
        height: 15,
        tintColor: '#0A5F35',
    },
    stepNumberCircle: {
        width: 20,
        height: 20,
        borderRadius: 20 / 2,
        backgroundColor: '#0A5F35',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#FFFFFF',
        zIndex: 2,
        marginBottom: 16,
    },
    stepNumberText: {
        color: '#FFFFFF',
        fontSize: 8,
        fontFamily: fonts.OpenSans_Bold,
    },
    stepConnector: {
        position: 'absolute',
        top: 20,
        left: 55,
        width: 110,
        height: 1,
        backgroundColor: '#D1D5DB',
        zIndex: 0,
    },
    stepTitle: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#111827',
        textAlign: 'center',
        paddingBottom: 5,
    },
    stepDesc: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 14,
    },
    whatYouGetScrollContent: {
        paddingHorizontal: 2,
        paddingVertical: 5
    },
    whatYouGetItem: {
        alignItems: 'center',
        marginRight: 10,
        width: Dimensions.get('window').width / 6 - 10,


    },
    whatYouGetIconCircle: {
        width: 40,
        height: 40,
        borderRadius: 40 / 2,
        backgroundColor: '#e3e6d1',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,

    },
    whatYouGetIcon: {
        width: 15,
        height: 15,
        tintColor: '#0A5F35',
    },
    whatYouGetTitle: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Medium,
        color: '#111827',
        textAlign: 'center',
    },
    assuranceScrollContent: {
        paddingHorizontal: 16,
    },
    assuranceCard: {
        width: Dimensions.get('window').width / 4 - 12,
        padding: 5,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        marginRight: 8,
        alignItems: 'center',
    },
    assuranceIconCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#f6f7f2',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    assuranceIcon: {
        width: 15,
        height: 15,
        tintColor: '#0A5F35',
    },
    assuranceTitle: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        textAlign: 'center',
        marginBottom: 4,
    },
    assuranceDesc: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 10,
    },
    journeyScrollContent: {
        paddingHorizontal: 10,
    },
    journeySectionWrapper: {
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        marginHorizontal: 16,
        paddingVertical: 15,
        borderColor: '#E5E7EB',
        borderWidth: 1,
    },
    journeyItemContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    journeyItem: {
        alignItems: 'center',
        width: Dimensions.get('window').width / 4 - 16,
    },
    journeyImage: {
        width: '90%',
        height: 70,
        borderRadius: 8,
        marginBottom: 8,
    },
    journeyTitle: {
        fontSize: FontsSize.size7,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
        textAlign: 'center',
    },
    journeyArrow: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginHorizontal: 4,
        marginBottom: 20,
    },
    footerBanner: {
        backgroundColor: '#f6f7f2',
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        marginHorizontal: 16,
        borderRadius: 10,
        marginBottom: 16,
    },
    footerBannerImg: {
        width: 50,
        height: 50,
        marginRight: 10,
    },
    footerBannerInfo: {
        flex: 1,
    },
    footerBannerTitle: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 2,
    },
    footerBannerSub: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
    },
    exploreBtn: {
        backgroundColor: '#0A5F35',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 6,
        marginLeft: 8,
    },
    exploreBtnText: {
        color: '#FFFFFF',
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_SemiBold,
        marginRight: 4,
    },
    exploreBtnArrow: {
        color: '#FFFFFF',
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_SemiBold,
    },
    taxFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f6f7f2',
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginHorizontal: 16,
        borderRadius: 10,
    },
    taxShieldIcon: {
        width: 14,
        height: 14,
        marginRight: 6,
        tintColor: '#0A5F35',
    },
    taxFooterText: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
        flex: 1,
    },
    taxFooterBold: {
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    taxFooterLink: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#0A5F35',
    },
});

export default styles;
