import { StyleSheet } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';
import fonts from '../../comman/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFBFB',
  },
  safeArea: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: MarginHW.PaddingW20 || 20,
    paddingTop: MarginHW.PaddingH10 || 10,
    paddingBottom: MarginHW.PaddingH5 || 5,
    backgroundColor: '#FAFBFB',
  },
  backButton: {
    padding: 6,
    borderRadius: 8,
  },
  backIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.black,
  },
  headerTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16 || 16,
    color: '#000',
  },
  pointsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FEF3C7',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  pointsIcon: {
    width: 14,
    height: 14,
    marginRight: 4,
  },
  pointsText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10 || 10,
    color: '#D97706',
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: MarginHW.MarginH16 || 16,
    paddingHorizontal: MarginHW.PaddingW20 || 20,
  },
  stepWrapper: {
    alignItems: 'center',
    flex: 1,
    position: 'relative',
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    zIndex: 2,
  },
  stepCircleActive: {
    backgroundColor: Colors.tint,
    borderColor: Colors.tint,
  },
  stepCircleInactive: {
    backgroundColor: '#E5E7EB',
    borderColor: '#E5E7EB',
  },
  stepTextActive: {
    color: Colors.white,
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12 || 12,
  },
  stepTextInactive: {
    color: '#9CA3AF',
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12 || 12,
  },
  stepLabelActive: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size10 || 10,
    color: Colors.tint,
    marginTop: 6,
    textAlign: 'center',
  },
  stepLabelInactive: {
    fontFamily: fonts.OpenSans_Medium,
    fontSize: FontsSize.size10 || 10,
    color: '#9CA3AF',
    marginTop: 6,
    textAlign: 'center',
  },
  stepLine: {
    height: 2,
    position: 'absolute',
    top: 14,
    left: '50%',
    right: '-50%',
    backgroundColor: '#E5E7EB',
    zIndex: 1,
  },
  stepLineActive: {
    backgroundColor: Colors.tint,
  },
  selectedStateCard: {
    marginHorizontal: MarginHW.MarginW20 || 20,
    borderRadius: 20,
    backgroundColor: '#F5FAF7',
    borderWidth: 1,
    borderColor: '#E1EFEA',
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
    height: 125,
  },
  stateTextContainer: {
    flex: 1,
    zIndex: 2,
    justifyContent: 'center',
  },
  stateIconContainer: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  stateIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.tint,
  },
  stateLabel: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size10 || 10,
    color: '#66756C',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  stateName: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size24 || 24,
    color: Colors.tint,
    marginTop: 2,
  },
  changeStateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  changeStateText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size12 || 12,
    color: Colors.tint,
    textDecorationLine: 'underline',
    marginRight: 4,
  },
  pencilIcon: {
    width: 10,
    height: 10,
    tintColor: Colors.tint,
  },
  stateGraphicContainer: {
    position: 'absolute',
    right: -10,
    bottom: -15,
    width: 160,
    height: 150,
    zIndex: 1,
  },
  stateGraphic: {
    width: '100%',
    height: '100%',
  },
  mainTitleContainer: {
    paddingHorizontal: MarginHW.PaddingW20 || 20,
    marginTop: MarginHW.MarginH24 || 24,
    marginBottom: MarginHW.MarginH16 || 16,
  },
  mainTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size24 || 24,
    color: '#1A2E22',
    lineHeight: 32,
  },
  mainTitleHighlight: {
    color: Colors.tint,
  },
  mainSubtitle: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size14 || 14,
    color: '#55665C',
    marginTop: 6,
    lineHeight: 20,
  },
  mainSubtitleHighlight: {
    color: Colors.tint,
    fontFamily: fonts.OpenSans_SemiBold,
  },
  categoriesContainer: {
    paddingLeft: MarginHW.PaddingW20 || 20,
    marginBottom: MarginHW.MarginH16 || 16,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E6EAE8',
    marginRight: 8,
    backgroundColor: Colors.white,
  },
  categoryButtonActive: {
    backgroundColor: Colors.tint,
    borderColor: Colors.tint,
  },
  categoryIcon: {
    width: 14,
    height: 14,
    marginRight: 6,
    tintColor: '#55665C',
  },
  categoryIconActive: {
    tintColor: Colors.white,
  },
  categoryText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size14,
    color: '#55665C',
  },
  categoryTextActive: {
    color: Colors.white,
    fontFamily: fonts.OpenSans_Bold,
  },
  listContainer: {
    paddingHorizontal: MarginHW.PaddingW20 || 20,
    paddingBottom: MarginHW.PaddingH10 || 10,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 18,
    padding: 12,
    marginBottom: 14,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#EFF2F0',
    flexDirection: 'row',
    position: 'relative',
  },
  cardImageContainer: {
    width: 90,
    height: 90,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#F5F7F6',
    marginRight: 12,
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  badge: {
    position: 'absolute',
    top: 6,
    left: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    zIndex: 2,
  },
  badgeText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 9,
    color: Colors.white,
  },
  cardContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    paddingRight: 65, // leave room for the points badge
  },
  cardTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16 || 16,
    color: '#1F2E23',
    marginRight: 4,
  },
  checkIcon: {
    width: 14,
    height: 14,
    tintColor: Colors.tint,
  },
  cardSub: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: '#809287',
    fontStyle: 'italic',
    marginTop: 1,
  },
  cardDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12 || 12,
    color: '#4B5E53',
    marginTop: 4,
    lineHeight: 16,
    paddingRight: 10,
  },
  specsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#F0F4F2',
    marginTop: 8,
    paddingTop: 8,
  },
  specItem: {
    flex: 1,
  },
  specLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: 9,
    color: '#809287',
  },
  specValue: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: 10,
    color: '#1F2E23',
    marginTop: 2,
  },
  cardPointsBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F9F4',
    borderWidth: 1,
    borderColor: '#DCF2E6',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  cardPointsIcon: {
    width: 10,
    height: 10,
  },
  cardPointsText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: 9,
    color: Colors.tint,
    marginLeft: 3,
  },
  arrowButton: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.tint,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowButtonIcon: {
    width: 12,
    height: 12,
    tintColor: Colors.white,
  },
  bottomBanner: {
    backgroundColor: Colors.bannerBg,
    borderWidth: 1,
    borderColor: Colors.bannerBg,
    borderRadius: 18,
    marginHorizontal: MarginHW.MarginW16,
    marginBottom: MarginHW.MarginH16,
    paddingHorizontal: MarginHW.PaddingW8,
    flexDirection: 'row',
    alignItems: 'center',
  },

  bannerLeftSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.2,
    flexShrink: 1,
  },

  bannerHandImage: {
    width: ImageSize.ImageW100,
    height: ImageSize.ImageH115,
  },

  bannerTextContainer: {
    flex: 1,
    flexShrink: 1,
  },

  bannerTextTitle: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size18,
    color: Colors.black,
  },

  bannerTextDesc: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size10,
    color: Colors.black,
    marginTop: MarginHW.MarginH2,
  },

  bannerRightSection: {
    flex: 1.8,
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  benefitItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: MarginHW.PaddingW8,
  },
  benefitIcon: {
    width: ImageSize.ImageW20,
    height: ImageSize.ImageH20,
    tintColor: Colors.tint,
    marginBottom: MarginHW.MarginH3,
  },

  benefitLabel: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.black,
    textAlign: 'center',
    lineHeight: 10,
  },

  benefitValue: {
    fontFamily: fonts.OpenSans_Regular,
    fontSize: FontsSize.size12,
    color: Colors.tint,
    textAlign: 'center',
    lineHeight: 10,
  },
  footerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MarginHW.PaddingW20,
    paddingBottom: MarginHW.PaddingH24,
    paddingTop: MarginHW.PaddingH10,
    backgroundColor: Colors.lightgray,

  },
  footerTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1.3,
    marginRight: MarginHW.MarginW8,
  },
  footerCheckIconContainer: {
    width: ImageSize.ImageH16,
    height: ImageSize.ImageH16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: Colors.tint,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: MarginHW.MarginW4,
  },
  footerCheckIcon: {
    width: ImageSize.ImageH20,
    height: ImageSize.ImageH20,
    tintColor: Colors.tint,
    marginRight: MarginHW.MarginW8,
  },
  footerText: {
    fontFamily: fonts.OpenSans_SemiBold,
    fontSize: FontsSize.size10,
    color: Colors.footertextgray,
    flex: 1,
  },
  continueButton: {
    flex: 1,
    backgroundColor: Colors.continue,
    height: ImageSize.ImageH40,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.btnShadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  continueText: {
    fontFamily: fonts.OpenSans_Bold,
    fontSize: FontsSize.size16,
    color: Colors.white,
    marginRight: MarginHW.MarginW6,
  },
  continueArrow: {
    width: ImageSize.ImageH14,
    height: ImageSize.ImageH14,
    tintColor: Colors.white,
  },
});
