import { Dimensions, StyleSheet } from 'react-native';
import { Colors } from '../../../comman/Colors';
import FontsSize from '../../../comman/FontsSize';
import MarginHW from '../../../comman/MarginHW';
import fonts from '../../../comman/fonts';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.containerBg || '#FAFBFB',
  },
  safeArea: {
    flex: 0,
    backgroundColor: '#FFFFFF',
  },
  // Top Section Wrapper (Gradient)
  topSectionWrapper: {
    height: 260,

  },
  // Custom Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'transparent',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerLogo: {
    width: 110,
    height: 32,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIconButton: {
    width: 34,
    height: 34,
    marginTop: 20,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    borderWidth: 1,
    borderColor: '#ECEFEF',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  headerIcon: {
    width: 16,
    height: 16,
    tintColor: '#222222',
  },
  notificationBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF3B30',
  },
  scrollViewContent: {
    paddingBottom: 24,
  },
  // Hero Section
  heroSection: {
    position: 'relative',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 16,
  },
  heroGlobe: {
    position: 'absolute',
    right: -25,
    top: -15,
    width: 220,
    height: 220,
    opacity: 0.95,
  },
  heroTextContent: {
    width: '60%',
    zIndex: 2,
  },
  heroTitle: {
    fontSize: FontsSize.size22,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0A1C14',
    lineHeight: 30,
  },
  heroTitleGreen: {
    color: '#398009',
  },
  heroDesc: {
    fontSize: 12,
    fontFamily: fonts.OpenSans_Regular,
    color: '#44554C',
    marginTop: 10,
    lineHeight: 17,
  },
  // Stats Container divided into 4 columns
  statsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: '#E7ECE8',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 3,
    marginTop: -30,
    zIndex: 10,
  },
  statItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  statIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 28 / 2,
    backgroundColor: '#EFF5F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statIcon: {
    width: 14,
    height: 14,
    tintColor: '#0D684D',
  },
  statTextContainer: {
    marginLeft: 4,
    flex: 1,
  },
  statLabel: {
    fontSize: 8,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#333333',
    lineHeight: 9,
  },
  statValue: {
    fontSize: 10.5,
    fontFamily: fonts.OpenSans_Bold,
    color: '#0D684D',
    marginTop: 0.5,
    lineHeight: 12,
  },
  statSublabel: {
    fontSize: 7.5,
    fontFamily: fonts.OpenSans_Regular,
    color: '#8E9A93',
    marginTop: 0.5,
    lineHeight: 8.5,
  },
  statDivider: {
    width: 1,
    height: 26,
    backgroundColor: '#E2ECE5',
    marginHorizontal: 2,
  },
  // Sections
  sectionHeader: {
    alignItems: 'center',
    marginVertical: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: fonts.OpenSans_Bold,
    color: '#111827',
  },
  sectionSubtitle: {
    fontSize: 11,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
    marginTop: 4,
  },
  // Category Grid
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  gridCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#EFF5F0',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 5,
    elevation: 2,
    position: 'relative',
  },
  cardInfoButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 2,
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardInfoIcon: {
    fontSize: 15,
    color: '#0D684D',
    fontFamily: fonts.OpenSans_Bold,
  },
  cardImageContainer: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  cardImage: {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,

  },
  cardTitle: {
    fontSize: 13,
    fontFamily: fonts.OpenSans_Bold,
    color: '#5f913f',
    textAlign: 'center',
  },
  cardDesc: {
    fontSize: 10,
    fontFamily: fonts.OpenSans_Regular,
    color: '#6B7A70',
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 14,
    minHeight: 42,
  },
  cardActionButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#EFF5F0',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 8,
  },
  cardActionIcon: {
    width: 11,
    height: 11,
    tintColor: '#0D684D',
  },
  // Quote Banner
  bannerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F9F4', // Light green card background
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E2EFE5',
  },
  bannerIconContainer: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  bannerIcon: {
    width: 36,
    height: 36,
  },
  bannerText: {
    fontSize: 10,
    fontFamily: fonts.OpenSans_SemiBold,
    color: '#0A1C14',
    flex: 1,
    lineHeight: 13,
  },
  bannerTreesRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bannerTreeIcon: {
    width: 150,
    height: 40,
    marginLeft: -4,
  },
  // Action Button
  assessmentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#015608',
    marginHorizontal: 16,
    height: 45,
    borderRadius: 10,
    marginBottom: 12,
    shadowColor: '#0D684D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  assessmentButtonText: {
    fontSize: 14,
    fontFamily: fonts.OpenSans_Bold,
    color: '#FFFFFF',
    marginRight: 8,
  },
  assessmentButtonArrow: {
    fontSize: 14,
    color: '#FFFFFF',
    fontFamily: fonts.OpenSans_Bold,
  },
  // Custom Bottom Navigation Bar
  bottomNav: {
    flexDirection: 'row',
    height: 60,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#ECEFEF',
    paddingBottom: 4,
    paddingTop: 8,
  },
  navItem: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navIcon: {
    width: 20,
    height: 20,
    tintColor: '#8E9A93',
  },
  navIconActive: {
    tintColor: '#0D684D',
  },
  navText: {
    fontSize: 9.5,
    fontFamily: fonts.OpenSans_Medium,
    color: '#8E9A93',
    marginTop: 4,
  },
  navTextActive: {
    color: '#0D684D',
    fontFamily: fonts.OpenSans_Bold,
  },
  navCenterButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -22,
    borderWidth: 2,
    borderColor: '#0D684D',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 5,
  },
  navCenterIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EEF5EE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navCenterIcon: {
    width: 22,
    height: 22,
    tintColor: '#0D684D',
  },
});
