import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  overlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  safeArea: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingVertical: 16,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 5,
  },
  logoImage: {
    width: 240,
    height: 80,
  },
  titleContainer: {

    paddingHorizontal: 24,
    marginTop: 20,
    marginBottom: 10,
  },
  titleDark: {
    fontSize: 52,
    fontWeight: '900',
    color: '#073B34',
    lineHeight: 56,
    letterSpacing: -1,
  },
  titleGreen: {
    fontSize: 52,
    fontWeight: '900',
    color: '#26A69A',
    lineHeight: 56,
    letterSpacing: -1,
  },
  subtitleContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  subtitleText: {
    fontSize: 18,
    color: '#4F6F69',
    lineHeight: 26,
    fontWeight: '500',
  },
  subtitleLegacy: {
    color: '#0D684D',
    fontWeight: 'bold',
  },
  cardContainer: {
    paddingHorizontal: 24,
    marginBottom: 20,
  },
  glassCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.42)',
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    paddingVertical: 14,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 8,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  iconWrapper: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255, 255, 255, 0.75)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  cardValue: {
    fontSize: 19,
    fontWeight: 'bold',
    color: '#073B34',
  },
  cardLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: '#7B8E89',
    marginTop: 2,
    letterSpacing: 1,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    marginHorizontal: 4,
  },
  spacer: {
    flex: 1,
    minHeight: 20,
  },
  button: {
    backgroundColor: '#3E8D4F',
    height: 56,
    borderRadius: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
    shadowColor: '#167156',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1.5,
    borderColor: '#4FAF6C',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  arrowContainer: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  arrowLine: {
    width: 14,
    height: 2.5,
    backgroundColor: '#FFFFFF',
    position: 'absolute',
  },
  arrowHead: {
    width: 9,
    height: 9,
    borderTopWidth: 2.5,
    borderRightWidth: 2.5,
    borderColor: '#FFFFFF',
    transform: [{ rotate: '45deg' }],
    position: 'absolute',
    right: 4,
  },
  signInContainer: {
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 24,
  },
  signInText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.15)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  signInHighlight: {
    color: '#82E272',
    textDecorationLine: 'underline',
    fontWeight: 'bold',
  },
  footerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 12,
    paddingBottom: 16,
    marginTop: 10,
  },
  footerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  footerText: {
    fontSize: 9,
    color: '#FFFFFF',
    fontWeight: '800',
    marginLeft: 6,
    lineHeight: 12,
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.15)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  footerSeparator: {
    width: 1,
    height: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
});
