import { StyleSheet } from 'react-native';
import { Colors } from '../../comman/Colors';
import FontsSize from '../../comman/FontsSize';
import MarginHW from '../../comman/MarginHW';
import ImageSize from '../../comman/ImageSize';
import HWSize from '../../comman/HWSize';

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  overlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: Colors.overlayBg,
  },
  safeArea: {
    flex: 1,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: -MarginHW.MarginH20,
    marginBottom: MarginHW.MarginH5,
  },
  logoImage: {
    width: ImageSize.ImageW180,
    height: ImageSize.ImageH80,
  },
  titleContainer: {
    paddingHorizontal: MarginHW.PaddingW30,
    marginBottom: MarginHW.MarginH10,
  },
  titleDark: {
    fontSize: FontsSize.size52,
    fontWeight: '900',
    color: Colors.darkGreen,
    lineHeight: FontsSize.size56,
    letterSpacing: -1,
  },
  titleGreen: {
    fontSize: FontsSize.size52,
    fontWeight: '900',
    color: Colors.legacyGreen,
    lineHeight: FontsSize.size56,
    letterSpacing: -1,
  },
  subtitleContainer: {
    paddingHorizontal: MarginHW.PaddingW30,
    marginBottom: MarginHW.MarginH30,
  },
  subtitleText: {
    fontSize: FontsSize.size20,
    color: Colors.labelGrey,
    lineHeight: FontsSize.size26,
    fontWeight: '500',
  },
  subtitleLegacy: {
    color: Colors.legacyGreen,
    fontWeight: 'bold',
  },
  cardContainer: {
    marginTop: MarginHW.MarginH30,
    paddingHorizontal: MarginHW.PaddingW24,
  },
  glassCard: {
    backgroundColor: Colors.glassBg,
    borderRadius: FontsSize.size24,
    borderWidth: 1.5,
    borderColor: Colors.glassBorder,
    paddingVertical: MarginHW.PaddingH14,
    paddingHorizontal: MarginHW.PaddingW20,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 8,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: MarginHW.PaddingH8,
  },
  iconWrapper: {
    width: ImageSize.ImageW42,
    height: ImageSize.ImageH42,
    borderRadius: 21,
    backgroundColor: Colors.iconWrapperBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: MarginHW.MarginW16,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  cardValue: {
    fontSize: FontsSize.size19,
    fontWeight: 'bold',
    color: Colors.darkGreen,
  },
  cardLabel: {
    fontSize: FontsSize.size12,
    fontWeight: '800',
    color: Colors.labelGrey,
    marginTop: MarginHW.MarginH2,
    letterSpacing: 1,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.whiteDivider,
    marginHorizontal: MarginHW.MarginW4,
  },
  spacer: {
    flex: 1,
    minHeight: 20,
  },
  button: {
    backgroundColor: Colors.btnBg,
    height: HWSize.H_Height50,
    borderRadius: FontsSize.size12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: MarginHW.MarginW24,
    shadowColor: Colors.btnShadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1.5,
    borderColor: Colors.btnBorder,
  },
  buttonText: {
    color: Colors.white,
    fontSize: FontsSize.size20,
    fontWeight: '700',
  },
  arrowContainer: {
    width: ImageSize.ImageW24,
    height: ImageSize.ImageH24,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: MarginHW.MarginW10,
  },
  arrowLine: {
    width: ImageSize.ImageW14,
    height: 2.5,
    backgroundColor: Colors.white,
    position: 'absolute',
  },
  arrowHead: {
    width: ImageSize.ImageW9,
    height: ImageSize.ImageH9,
    borderTopWidth: 2.5,
    borderRightWidth: 2.5,
    borderColor: Colors.white,
    transform: [{ rotate: '45deg' }],
    position: 'absolute',
    right: 4,
  },
  signInContainer: {
    alignItems: 'center',
    marginTop: MarginHW.MarginH16,
    marginBottom: MarginHW.MarginH10,
  },
  signInText: {
    fontSize: FontsSize.size14,
    color: Colors.white,
    fontWeight: '500',
    textShadowColor: Colors.textShadow,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  signInHighlight: {
    color: Colors.textHighlight,
    textDecorationLine: 'underline',
    fontWeight: 'bold',
  },
  footerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: MarginHW.PaddingW12,
    paddingBottom: MarginHW.PaddingH24,
    marginTop: MarginHW.MarginH10,
    marginBottom: MarginHW.MarginH35,
  },
  footerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  footerText: {
    fontSize: FontsSize.size9,
    color: Colors.white,
    fontWeight: '800',
    marginLeft: MarginHW.MarginW6,
    lineHeight: FontsSize.size12,
    letterSpacing: 0.5,
    textShadowColor: Colors.textShadow,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  footerSeparator: {
    width: 1,
    height: HWSize.H_Height18,
    backgroundColor: Colors.footerDivider,
  },
  cardIcon: {
    width: ImageSize.ImageW22,
    height: ImageSize.ImageH22,
    tintColor: Colors.darkGreen,
  },
  footerIcon: {
    width: ImageSize.ImageW16,
    height: ImageSize.ImageH16,
    tintColor: Colors.greenMint,
  },
});
