import { Dimensions, StyleSheet, Platform, StatusBar } from 'react-native';
import { Colors } from '../../../comman/Colors';
import FontsSize from '../../../comman/FontsSize';
import MarginHW from '../../../comman/MarginHW';
import fonts from '../../../comman/fonts';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const cardWidth = (SCREEN_WIDTH - MarginHW.MarginW10 * 2 - MarginHW.MarginW10) / 2; // Split screen with responsive 10 margins and gap

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.containerBg,
    },
    scrollViewContent: {
        paddingBottom: MarginHW.MarginH10,
    },

    // Top Hero Section
    topSectionWrapper: {
        width: '100%',
        paddingBottom: MarginHW.MarginH20,
        position: 'relative',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: MarginHW.MarginW16,
        paddingTop: MarginHW.MarginH30,
        paddingBottom: MarginHW.MarginH10,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    backButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: Colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    backIcon: {
        width: 16,
        height: 16,
        tintColor: '#222222',
    },
    heroSection: {
        paddingHorizontal: MarginHW.MarginW16,
        flexDirection: 'row',
        position: 'relative',
        zIndex: 5,
    },
    heroTextContent: {
        width: '58%',
        zIndex: 2,
    },
    heroSubtitle: {
        fontSize: FontsSize.size16,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#222222',
        lineHeight: 18,
    },
    heroTitle: {
        fontSize: FontsSize.size24,
        fontFamily: fonts.OpenSans_Bold,
        color: Colors.TextColorLightGreen,
        marginTop: MarginHW.MarginH2,
        lineHeight: 30,
    },
    heroTitleGreen: {
        color: Colors.TextColorLightGreen,
    },
    heroTitleIcon: {
        width: 18,
        height: 18,
        tintColor: '#056213',
    },
    heroDesc: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.OpenSans_Regular,
        color: '#55665C',
        marginTop: MarginHW.MarginH2,
        lineHeight: 15,
    },

    // Carbon Score & bulb graphics
    topVisualsRow: {
        flexDirection: 'row',
        paddingHorizontal: MarginHW.MarginW16,
        marginTop: MarginHW.MarginH12,
        justifyContent: 'space-between',
        alignItems: 'flex-end',
    },
    annualFootprintWrapper: {
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: MarginHW.PaddingH12,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 3,
        width: '45%',
        borderWidth: 1,
        borderColor: '#EAF1EC',
        transform: [{ translateY: -25 }, { translateX: -10 }],
    },
    annualFootprintTitle: {
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#222222',
        textAlign: 'center',
    },
    annualFootprintVal: {
        fontSize: FontsSize.size38,
        fontFamily: fonts.OpenSans_Bold,
        color: '#135928',
        textAlign: 'center',
        marginTop: MarginHW.MarginH2,
    },
    annualFootprintUnit: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#222222',
        textAlign: 'center',
        marginTop: MarginHW.MarginH2,
    },

    bulbGraphicWrapper: {
        position: 'absolute',
        right: '25%',
        bottom: 0,
        zIndex: 1,
        alignItems: 'center',
    },
    bubbleTreeImage: {
        width: 140,
        height: 200,
    },
    geotreeStoneText: {
        position: 'absolute',
        bottom: 22,
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Bold,
        color: '#222222',
        opacity: 0.7,
    },

    carbonScoreWrapper: {
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: MarginHW.PaddingH12,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 3,
        width: '45%',
        alignItems: 'center',
        zIndex: 5,
        borderWidth: 1,
        borderColor: '#EAF1EC',
        transform: [{ translateY: 15 }, { translateX: 10 }],
    },
    carbonScoreTitle: {
        fontSize: FontsSize.size12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#222222',
        marginBottom: MarginHW.MarginH4,
    },
    progressCircleOuter: {
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 4,
        borderColor: '#E2EFE5',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    progressCircleGreenSector: {
        position: 'absolute',
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 4,
        borderColor: '#056213',
        borderLeftColor: 'transparent',
        borderBottomColor: 'transparent',
        transform: [{ rotate: '45deg' }],
    },
    progressCircleValue: {
        fontSize: FontsSize.size16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    progressCircleTotal: {
        fontSize: FontsSize.size9_5,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7A70',
    },
    scoreBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EAF6EE',
        borderRadius: 12,
        paddingHorizontal: MarginHW.PaddingW8,
        paddingVertical: MarginHW.PaddingH3,
        marginTop: MarginHW.MarginH8,
    },
    scoreBadgeIcon: {
        width: 12,
        height: 12,
        tintColor: '#056213',
        marginRight: 4,
    },
    scoreBadgeText: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#056213',
    },
    scoreDesc: {
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7A70',
        textAlign: 'center',
        marginTop: MarginHW.MarginH6,
        lineHeight: 10,
    },

    // Category Breakdown Card
    categoriesContainer: {
        marginHorizontal: MarginHW.MarginW10,
        marginTop: MarginHW.MarginH6,
        backgroundColor: Colors.white,
        borderRadius: 12,
        paddingVertical: MarginHW.PaddingH16,
        paddingHorizontal: MarginHW.PaddingW10,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#EFF4EF',
    },
    catItem: {
        flex: 1,
        alignItems: 'center',
        borderRightWidth: 1,
        borderRightColor: '#F0F0F0',
        paddingHorizontal: 2,
    },
    catItemLast: {
        flex: 1.2,
        alignItems: 'center',
        paddingHorizontal: 2,
    },
    catIconBg: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: MarginHW.MarginH6,
    },
    catIcon: {
        width: 16,
        height: 16,
    },
    catLabel: {
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Regular,
        color: '#55665C',
    },
    catValue: {
        fontSize: FontsSize.size14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginTop: MarginHW.MarginH2,
    },
    catUnit: {
        fontSize: FontsSize.size7,
        fontFamily: fonts.OpenSans_Regular,
        color: '#7C8A81',
    },
    catBadge: {
        borderRadius: 10,
        paddingHorizontal: MarginHW.PaddingW8,
        paddingVertical: 2,
        marginTop: MarginHW.MarginH6,
    },
    catBadgeText: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Bold,
    },
    totalEmissionsLeafBg: {
        position: 'absolute',
        bottom: -5,
        right: 0,
        width: 36,
        height: 36,
        opacity: 0.08,
        tintColor: '#056213',
    },

    // Analytics / Charts Row
    analyticsRow: {
        flexDirection: 'row',
        paddingHorizontal: MarginHW.MarginW10,
        marginTop: MarginHW.MarginH8,
        justifyContent: 'space-between',
    },
    analyticsCard: {
        width: cardWidth,
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: MarginHW.PaddingH12,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#EFF4EF',
    },
    analyticsCardTitle: {
        fontSize: FontsSize.size11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: MarginHW.MarginH12,
    },

    // Donut Chart Styles
    donutChartWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: MarginHW.MarginH4,
    },
    donutRing: {
        width: 76,
        height: 76,
        borderRadius: 38,
        borderWidth: 12,
        borderColor: '#E2E8F0', // fallback
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    // Mock Segmented Donut Chart using nested borders / absolute rotations
    donutSegment1: {
        position: 'absolute',
        width: 76,
        height: 76,
        borderRadius: 38,
        borderWidth: 12,
        borderColor: '#9061F9',
        borderLeftColor: 'transparent',
        borderBottomColor: 'transparent',
        transform: [{ rotate: '-45deg' }],
    },
    donutSegment2: {
        position: 'absolute',
        width: 76,
        height: 76,
        borderRadius: 38,
        borderWidth: 12,
        borderColor: '#3B82F6',
        borderTopColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: 'transparent',
        transform: [{ rotate: '45deg' }],
    },
    donutSegment3: {
        position: 'absolute',
        width: 76,
        height: 76,
        borderRadius: 38,
        borderWidth: 12,
        borderColor: '#EAB308',
        borderTopColor: 'transparent',
        borderLeftColor: 'transparent',
        borderBottomColor: 'transparent',
        transform: [{ rotate: '120deg' }],
    },
    donutSegment4: {
        position: 'absolute',
        width: 76,
        height: 76,
        borderRadius: 38,
        borderWidth: 12,
        borderColor: '#10B981',
        borderTopColor: 'transparent',
        borderRightColor: 'transparent',
        borderLeftColor: 'transparent',
        transform: [{ rotate: '210deg' }],
    },
    donutHole: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: Colors.white,
        position: 'absolute',
    },
    donutCenterText: {
        position: 'absolute',
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    donutLegendList: {
        flex: 1,
        marginLeft: MarginHW.MarginW8,
    },
    legendRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: MarginHW.MarginH4,
    },
    legendLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    legendDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 4,
    },
    legendLabel: {
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Regular,
        color: '#4B5563',
    },
    legendPercent: {
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },

    // Indian Citizen Comparison styles
    comparisonWrapper: {
        marginTop: MarginHW.MarginH4,
    },
    barsRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'flex-end',
        height: 60,
        // paddingBottom: MarginHW.MarginH6,
    },
    barColumn: {
        alignItems: 'center',
    },
    barValue: {
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 2,
    },
    barValueUnit: {
        fontSize: FontsSize.size8_5,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7A70',
    },
    barAvg: {
        width: 24,
        height: 25,
        backgroundColor: '#E5E7EB',
        borderRadius: 4,
    },
    barYour: {
        width: 24,
        height: 50,
        backgroundColor: '#056213',
        borderRadius: 4,
    },
    barLabel: {
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7A70',
        marginTop: 4,
    },
    gradientTrack: {
        height: 6,
        borderRadius: 3,
        position: 'relative',
    },
    gradientTrackThumb: {
        position: 'absolute',
        top: -3,
        right: 10,
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: '#FF3B30',
        borderWidth: 2,
        borderColor: Colors.white,
    },
    sliderLabelRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 4,
    },
    sliderLabel: {
        fontSize: FontsSize.size7,
        fontFamily: fonts.OpenSans_Regular,
        color: '#9CA3AF',
    },
    comparisonHighlightBox: {
        backgroundColor: '#F3F4F6',
        borderRadius: 6,
        paddingVertical: 6,
        paddingHorizontal: 8,
        marginTop: MarginHW.MarginH8,
    },
    comparisonHighlightText: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#1F2937',
        textAlign: 'center',
        lineHeight: 12,
    },
    comparisonHighlightBold: {
        fontFamily: fonts.OpenSans_Bold,
        color: '#D11A2A',
    },

    // Offset Emissions Box
    offsetSectionContainer: {
        marginHorizontal: MarginHW.MarginW10,
        marginTop: MarginHW.MarginH8,
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: MarginHW.PaddingH12,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#EFF4EF',
    },
    offsetIntroRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    offsetIntroImage: {
        width: 90,
        height: 90,
    },
    offsetIntroTextWrapper: {
        flex: 1,
    },
    offsetIntroLabel: {
        fontSize: FontsSize.size14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    offsetIntroDesc: {
        fontSize: FontsSize.size11,
        fontFamily: fonts.OpenSans_Regular,
        color: '#55665C',
    },
    offsetIntroMainText: {
        fontSize: FontsSize.size16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#056213',
    },
    offsetIntroSub: {
        fontSize: FontsSize.size11,
        fontFamily: fonts.OpenSans_Regular,
        color: '#55665C',
    },

    // Offset cards options
    offsetCardsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: MarginHW.MarginH12,
    },
    offsetOptionCard: {
        width: '31%',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        paddingVertical: MarginHW.PaddingH10,
        alignItems: 'center',
        position: 'relative',
        backgroundColor: '#FFFFFF',
    },
    offsetOptionCardSelected: {
        borderColor: '#056213',
        borderWidth: 1.5,
        backgroundColor: '#F4FBF7',
    },
    offsetOptionTitle: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7A70',
    },
    offsetOptionImage: {
        width: 35,
        height: 35,
        marginVertical: 4,
    },
    offsetOptionCount: {
        fontSize: FontsSize.size11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    offsetOptionCountSelected: {
        color: '#056213',
    },
    offsetOptionPercent: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7A70',
    },
    offsetOptionPrice: {
        fontSize: FontsSize.size11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginTop: 2,
    },
    offsetOptionBadge: {
        position: 'absolute',
        bottom: -9,
        backgroundColor: '#056213',
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    offsetOptionBadgeText: {
        color: '#FFFFFF',
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Bold,
    },

    // AI Insight and Equivalence cards
    insightsRow: {
        flexDirection: 'row',
        paddingHorizontal: MarginHW.MarginW10,
        marginTop: MarginHW.MarginH8,
        justifyContent: 'space-between',
    },
    insightCard: {
        width: cardWidth,
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: MarginHW.PaddingH12,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#EFF4EF',
    },
    insightHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: MarginHW.MarginH8,
    },
    aiIconBg: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#EAF6EE',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 6,
    },
    aiIcon: {
        width: 14,
        height: 14,
        tintColor: '#056213',
    },
    insightCardTitle: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    insightBodyText: {
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Regular,
        color: '#1F2937',
        lineHeight: 13,
    },
    insightBodyHighlight: {
        fontFamily: fonts.OpenSans_Bold,
        color: '#D11A2A',
    },
    insightBodyDesc: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#55665C',
        marginTop: 6,
        lineHeight: 12,
    },

    equivalenceContent: {
        marginTop: MarginHW.MarginH4,
    },
    equivalenceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginVertical: 2,
    },
    equivalenceItem: {
        flex: 1,
        alignItems: 'center',
    },
    equivalenceIconBg: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#FFF8E6',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 2,
    },
    equivalenceIconBgGreen: {
        backgroundColor: '#EAF6EE',
    },
    equivalenceIcon: {
        width: 14,
        height: 14,
    },
    equivalenceLabel: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7A70',
        textAlign: 'center',
    },
    equivalenceVal: {
        fontSize: FontsSize.size9,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        textAlign: 'center',
    },
    equivalenceOr: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#9CA3AF',
        paddingHorizontal: 4,
        marginTop: -10,
    },

    // Footer actions
    footerActionsContainer: {
        marginHorizontal: MarginHW.MarginW10,
        marginTop: MarginHW.MarginH4,
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: '#EFF4EF',
        paddingTop: MarginHW.PaddingH12,
    },
    footerActionBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: MarginHW.PaddingH6,
    },
    footerActionDivider: {
        width: 1,
        height: 24,
        backgroundColor: '#E5E7EB',
        alignSelf: 'center',
    },
    footerActionIcon: {
        width: 20,
        height: 20,
        marginRight: 6,
        tintColor: '#056213',
    },
    footerActionTextContainer: {
        flex: 1,
    },
    footerActionTitle: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    footerActionDesc: {
        fontSize: FontsSize.size8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7A70',
        marginTop: 1,
    },

    // Bottom CTA Action
    ctaButtonContainer: {
        marginHorizontal: MarginHW.MarginW10,
        marginTop: MarginHW.MarginH10,
    },
    ctaButton: {
        backgroundColor: '#056213',
        borderRadius: 24,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: MarginHW.PaddingH12,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 5,
        elevation: 4,
    },
    ctaButtonIcon: {
        width: 18,
        height: 18,
        marginRight: 8,
        tintColor: Colors.white,
    },
    ctaButtonText: {
        color: Colors.white,
        fontSize: FontsSize.size14,
        fontFamily: fonts.OpenSans_Bold,
    },
    ctaButtonArrow: {
        width: 14,
        height: 14,
        marginLeft: 8,
        tintColor: Colors.white,
    },
});
