import { StyleSheet } from 'react-native';
import fonts from '../../../../comman/fonts';
import FontsSize from '../../../../comman/FontsSize';
import { Colors } from '../../../../comman/Colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F3F4F6',
    },
    heroSection: {
        width: '100%',
        height: 230,
    },
    headerRow: {
        top: 30,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,

    },
    backButton: {
        width: 30,
        height: 30,
        borderRadius: 30 / 2,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    backIcon: {
        width: 14,
        height: 14,
        tintColor: '#111827',
    },
    logoImage: {
        height: 32,
        width: 120,
    },
    secureBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    secureLockIcon: {
        width: 12,
        height: 12,
        tintColor: '#0A5F35',
        marginRight: 4,
    },
    secureBadgeText: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
    },
    successMessageContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginTop: 50,
    },
    checkCircle: {
        width: 35,
        height: 35,
        borderRadius: 35 / 2,
        backgroundColor: '#0A5F35',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    successTextContainer: {
        flex: 1,
        justifyContent: 'center',
    },
    checkIcon: {
        width: 15,
        height: 15,
        tintColor: '#FFFFFF',
    },
    successTitle: {
        fontSize: FontsSize.size18,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginBottom: 8,
        textAlign: 'left',
    },
    successSubtitle: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#111827',
        textAlign: 'left',
        lineHeight: 18,
    },
    contentContainer: {
        paddingHorizontal: 16,
        marginTop: 20
    },
    orderCard: {
        width: '70%',
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 20,
        marginHorizontal: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
        alignSelf: 'flex-start',
        paddingRight: 12,
    },
    orderInfoCol: {
    },
    orderIdText: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Regular,
        color: '#111827',
        marginBottom: 4,
    },
    orderDateText: {
        fontSize: 8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#6B7280',
    },
    paidBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F0FDF4',
        paddingHorizontal: 10,

        paddingVertical: 6,
        borderRadius: 8,
    },
    paidCheck: {
        width: 12,
        height: 12,
        tintColor: '#0A5F35',
        marginRight: 6,
    },
    paidText: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#0A5F35',
    },
    rowContainer: {
        flexDirection: 'column',
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    cardTitle: {
        fontSize: FontsSize.size14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 16,
    },
    summaryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    summaryTreeImage: {
        width: 85,
        height: 80,
        borderRadius: 8,
        marginRight: 16,
    },
    summaryTextCol: {
        flex: 1,
    },
    planLabel: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 4,
    },
    planTitle: {
        fontSize: FontsSize.size16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginBottom: 4,
    },
    planOffsetDesc: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
    },
    divider: {
        height: 1,
        backgroundColor: '#E5E7EB',
        width: '100%',
        marginVertical: 10,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 2,
    },
    detailLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    detailIcon: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
        marginRight: 8,
    },
    detailLabelText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#111827',
    },
    detailValueText: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Regular,
        color: '#111827',
    },
    alertBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.listBgLight,
        padding: 16,
        borderRadius: 10,
        marginTop: 16,
    },
    alertIcon: {
        width: 24,
        height: 24,
        tintColor: '#0A5F35',
        marginRight: 12,
    },
    alertText: {
        flex: 1,
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#0A5F35',
        lineHeight: 18,
    },
    boldAlertText: {
        fontFamily: fonts.OpenSans_Bold,
    },
    receiptRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
    },
    receiptLabel: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
    },
    receiptValue: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
    },
    grandTotalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 12,
    },
    grandTotalLabel: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
    },
    grandTotalValue: {
        fontSize: 16,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    whatsNextCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
    },
    stepsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingRight: 16,
    },
    stepItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 12,
    },
    stepIconCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#F0FDF4',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        marginRight: 12,
    },
    stepIcon: {
        width: 20,
        height: 20,
        tintColor: '#0A5F35',
    },
    verticalDivider: {
        width: 1,
        height: 40,
        backgroundColor: '#E5E7EB',
        marginRight: 12,
    },
    stepTextContainer: {
        width: 140, // Allows text wrapping beside icon
    },
    stepTitle: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginBottom: 4,
    },
    stepDesc: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Regular,
        color: '#111827',
        lineHeight: 14,
    },
    cardsStack: {
        flexDirection: 'column',
    },
    certificateCard: {

        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    certLeftCol: {
        flex: 1,
        marginRight: 12,
        justifyContent: 'center',
    },
    certRightCol: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center'
    },
    certDesc: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
        marginBottom: 10,
    },
    emailButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.listBg,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 8,
        marginBottom: 12,
    },
    emailButtonIcon: {
        width: 18,
        height: 18,
        tintColor: '#0A5F35',
        marginRight: 10,
    },
    emailButtonText: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        flexShrink: 1,
    },
    downloadButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#0A5F35',
    },
    downloadButtonIcon: {
        width: 18,
        height: 18,
        tintColor: '#0A5F35',
        marginRight: 10,
    },
    downloadButtonText: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        flexShrink: 1,
    },
    certPreviewImage: {
        width: 140,
        height: 160,
    },
    trackCard: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        paddingHorizontal: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    trackLeftCol: {
        width: '55%',
        marginRight: 12,
        justifyContent: 'center',
    },
    trackRightCol: {
        width: '45%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    trackDesc: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
        marginBottom: 12,
    },
    featureList: {
        marginBottom: 16,
    },
    featureItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    featureCheckIcon: {
        width: 14,
        height: 14,
        tintColor: '#0A5F35',
        marginRight: 8,
    },
    featureItemText: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Medium,
        color: '#111827',
    },
    primaryButton: {
        backgroundColor: '#0A5F35',
        paddingVertical: 12,
        borderRadius: 6,
        alignItems: 'center',
    },
    primaryButtonText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
    },
    dashboardPreviewImage: {
        width: 140,
        height: 260,
        resizeMode: 'contain',
    },
    communityBanner: {
        flexDirection: 'column',
        backgroundColor: '#F4F9F4',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
    },
    communityTop: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    communityImage: {
        width: 70,
        height: 70,
        marginRight: 16,
    },
    communityTextCol: {
        flex: 1,
    },
    communityTitle: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#111827',
        marginBottom: 4,
    },
    communitySubtitle: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Medium,
        color: '#4B5563',
    },
    communityHorizontalDivider: {
        width: '100%',
        height: 1,
        backgroundColor: '#D1D5DB',
        marginVertical: 16,
    },
    communityBottom: {
        alignItems: 'center',
    },
    socialTitle: {
        fontSize: 12,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginBottom: 8,
        textAlign: 'center',
    },
    socialRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    socialIconBtn: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 4,
        borderWidth: 1,
        borderColor: '#D1D5DB',
    },
    socialIcon: {
        width: 16,
        height: 16,
    },
    bottomActionsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    outlineBtn: {
        width: '32%',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        paddingHorizontal: 4,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
    },
    outlineBtnIcon: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
    },
    outlineBtnText: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#111827',
        textAlign: 'center',
    },
    shareBtn: {
        width: '32%',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        paddingHorizontal: 4,
        borderRadius: 8,
        backgroundColor: '#0A5F35',
    },
    shareBtnIcon: {
        width: 16,
        height: 16,
        tintColor: '#FFFFFF',
    },
    shareBtnText: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
        textAlign: 'center',
    },
    footerSecureText: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Medium,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 20,
    }
});
