import { StyleSheet, Dimensions } from 'react-native';
import fonts from '../../../../comman/fonts';
import FontsSize from '../../../../comman/FontsSize';
import { Colors } from '../../../../comman/Colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FAFBFB',
    },
    scrollContent: {
        paddingBottom: 32,
    },
    headerBg: {
        width: '100%',
        minHeight: 240,
    },
    headerOverlay: {
        backgroundColor: 'transparent',
        paddingBottom: 24,
        minHeight: 200,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 16,
    },
    backButton: {
        width: 28,
        height: 28,
        borderRadius: 28 / 2,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1.5 },
        shadowOpacity: 0.1,
        shadowRadius: 2.5,
        elevation: 2.5,
    },
    backIcon: {
        width: 14,
        height: 14,
        tintColor: '#000000',
    },
    headerTitleContainer: {
        flex: 1,
        marginLeft: 12,
    },
    headerTitle: {
        fontSize: FontsSize.size18,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A1C14',
    },
    headerLeafIcon: {
        width: 18,
        height: 18,
        marginLeft: 6,
        tintColor: '#0A5F35',
    },
    aboutPill: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EFF6F1',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E6F4ED',
    },
    aboutPillIconContainer: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 1.2,
        borderColor: '#0A5F35',
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 6,
    },
    aboutPillIconText: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        textAlign: 'center',
        lineHeight: 14,
    },
    aboutPillText: {
        fontSize: 9.5,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A1C14',
        lineHeight: 11.5,
    },
    headerSubtitle: {
        fontSize: FontsSize.size10,
        fontFamily: fonts.OpenSans_Regular,
        color: '#475569',

        marginTop: 1,
    },
    statsCardContainer: {
        paddingHorizontal: 16,
        marginTop: -30, // overlaps beautifully into the header
        zIndex: 5,
    },
    statsCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.listBgLight,
        borderRadius: 10,
        paddingVertical: 8,
        paddingHorizontal: 8,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 6,
        borderWidth: 1,
        borderColor: '#F1F5F9',
    },
    statItem: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        minWidth: 0,
    },
    statItem2: {
        flex: 0.8,
        flexDirection: 'row',
        alignItems: 'center',
        minWidth: 0,
    },
    statItem3: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        minWidth: 0,
    },
    statIconWrapper: {
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 5,
    },
    statIcon: {
        width: 15,
        height: 15,
    },
    statTextContainer: {
        flex: 1,
    },
    statLabel: {
        fontSize: 7.8,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#0F172A',
        lineHeight: 10,
    },
    statValue: {
        fontSize: 13,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginTop: 1.5,
    },
    statUnit: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    statSubText: {
        fontSize: 7,
        fontFamily: fonts.OpenSans_Regular,
        color: '#64748B',
        marginTop: 2,
    },
    verticalDivider: {
        width: 1,
        height: '70%',
        backgroundColor: '#E2E8F0',
        marginHorizontal: 4,
    },
    sectionContainer: {
        paddingHorizontal: 16,
        marginTop: 24,
    },
    sectionTitle: {
        fontSize: 14.5,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A1C14',
        marginBottom: 12,
    },
    breakdownRow: {
        flexDirection: 'row',
        marginTop: 20,
    },
    formulaCard: {
        flex: 1,
        backgroundColor: '#F3F9F5',
        borderWidth: 1.2,
        borderColor: '#C6E3D5',
        borderRadius: 12,
        padding: 10,
        marginRight: 10,
    },
    formulaTitle: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginBottom: 8,
    },
    formulaText: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#44554C',
        lineHeight: 14,
    },
    tableCard: {
        flex: 2.4,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#F1F5F9',
        paddingTop: 10,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 3,
        elevation: 2,
    },
    tableHeaderRow: {
        flexDirection: 'row',
        paddingHorizontal: 10,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
    },
    tableHeaderCell: {
        fontSize: 9,
        fontFamily: fonts.OpenSans_Bold,
        color: '#64748B',
    },
    tableRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 7.5,
        borderBottomWidth: 1,
        borderBottomColor: '#F8FAFC',
    },
    tableCellLabel: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    tableIcon: {
        width: 12,
        height: 12,
        marginRight: 6,
        tintColor: '#64748B',
    },
    tableLabelText: {
        fontSize: 9.5,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#334155',
    },
    tableValueText: {
        fontSize: 9.5,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#0F172A',
    },
    tableSummaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#F3F9F5',
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
    },
    tableSummaryLabel: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    tableSummaryValueContainer: {
        alignItems: 'flex-end',
    },
    tableSummaryValue: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    tableSummaryValueSub: {
        fontSize: 10,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#0A5F35',
        marginTop: 1,
    },
    chartsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginTop: 0,
    },
    donutCard: {
        width: '50%',
        flexDirection: 'row',
        alignItems: 'center',
        borderRightWidth: 1,
        paddingRight: 5,
        borderRightColor: '#E2E8F0',
    },
    donutRing: {
        width: 56,
        height: 56,
        borderRadius: 28,
        borderWidth: 6,
        borderColor: '#0A5F35',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    donutPercentage: {
        fontSize: 11,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A1C14',
    },
    donutLegend: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    legendDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#0A5F35',
        marginRight: 6,
    },
    legendText: {
        fontSize: 9.5,
        fontFamily: fonts.OpenSans_SemiBold,
        color: '#475569',
        flex: 1,
    },
    legendVal: {
        fontSize: 9.5,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0F172A',
    },
    donutDivider: {
        width: 1,
        height: '80%',
        backgroundColor: '#E2E8F0',
        marginHorizontal: 12,
    },
    howItWorksCard: {
        width: '50%',
        marginLeft: 2,
        backgroundColor: '#F8FAFC',
        borderRadius: 10,
        padding: 5,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    howItWorksIconContainer: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#EFF6F1',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    howItWorksIcon: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
    },
    howItWorksTextContainer: {
        flex: 1,
    },
    howItWorksTitle: {
        fontSize: 9.5,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0F172A',
        marginBottom: 2,
    },
    howItWorksText: {
        fontSize: 8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#475569',
        lineHeight: 11.5,
    },
    estimateBanner: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#F3F9F5',
        marginHorizontal: 16,
        marginTop: 20,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: '#E6F4ED',
    },
    estimateBannerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 8,
    },
    estimateIconCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#EBF7F0',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    estimateBannerIcon: {
        width: 14,
        height: 14,
        tintColor: '#0A5F35',
    },
    estimateTextContainer: {
        flex: 1,
    },
    estimateBannerTitle: {
        fontSize: 9.5,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    estimateBannerText: {
        fontSize: 8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#475569',
        marginTop: 1,
    },
    bannerTreeImage: {
        width: 70,
        height: 32,
    },
    accurateCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F9F5',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E6F4ED',
        marginHorizontal: 16,
        marginTop: 16,
        paddingHorizontal: 12,
        paddingVertical: 12,
    },
    accurateIconContainer: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#EFF6F1',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    accurateIcon: {
        width: 16,
        height: 16,
        tintColor: '#0A5F35',
    },
    accurateTextContainer: {
        flex: 1,
        marginRight: 8,
    },
    accurateTitle: {
        fontSize: 9.5,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0F172A',
    },
    accurateDesc: {
        fontSize: 8,
        fontFamily: fonts.OpenSans_Regular,
        color: '#64748B',
        marginTop: 2,
        lineHeight: 11.5,
    },
    connectButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#0A5F35',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#FFFFFF',
    },
    connectButtonText: {
        fontSize: 9.5,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
    },
    connectButtonIcon: {
        fontSize: 10.5,
        fontFamily: fonts.OpenSans_Bold,
        color: '#0A5F35',
        marginLeft: 4,
    },
    backCtaButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#0A5F35',
        borderRadius: 8,
        marginHorizontal: 16,
        marginTop: 24,
        paddingVertical: 12,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
    },
    backCtaText: {
        fontSize: 13,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
    },
    backCtaIcon: {
        fontSize: 14,
        fontFamily: fonts.OpenSans_Bold,
        color: '#FFFFFF',
        marginLeft: 6,
    },
});
